conda_build/convert.py

I realized the last PR added the ability to convert from architectures like arm to linux, but not the other way around. This PR adds that capability.

Check architecture in index.json for platforms other than Linux, macOS, and Windows

---

conda_build/api.py
conda_build/build.py
conda_build/metadata.py
conda_build/render.py
conda_build/variants.py
tests/test-recipes/metadata/nested_prefix/bld.bat
tests/test-recipes/metadata/nested_prefix/meta.yaml
tests/test-recipes/split-packages/script_install_files/meta.yaml
tests/test_api_build.py
tests/test_subpackages.py
tests/test_utils.py
tests/test_variants.py

This led to timestamp issues, where if a newer build had mismatching vc deps, conda-build would end up trying to create unsatisfiable envs.

fix non-finalized recipe being used for creating build env

---

conda_build/variants.py

led to TypeErrors.  Only saw this with c3i, but might be a problem elsewhere too.

fix lists getting nested during merging of configs

---

conda_build/metadata.py

host_prefix is where the target platform's libs should be, so having this act on build_prefix was actually broken.  It was OK for most builds because most builds are not cross.  This was broken on win-64 compiling for win-32.

make always_include_files act on host_prefix, not build_prefix

---

conda_build/skeletons/pypi.py

This pull request is a fix for issue #2500.  It simply adds a small function for getting the truthiness of the `SSL_NO_VERIFY` environment variable and passes that to `requests.get` to disable SSL verification.  There is an accompanying pull request for conda-docs that adds a small section describing this feature with examples of how to use it.

#2500 Adding fix for bypassing MITM proxies

---

conda_build/convert.py

fixes #2501
Replaced 'lib/site-packages' with os.path.join to join the two directories. After fixing this, I was able to successfully install a package as instructed in #2501.
Also added an indent to the dump to paths.json as I found the sometimes the file wasn't indented.
Edit: I'm starting to see some errors so let me see what else I can try.

Fix convert paths [WIP]

---

conda_build/windows.py

Partial backport of PR ( https://github.com/conda/conda-build/pull/2259 ). Related to issue ( https://github.com/conda/conda-build/issues/2257 ).
Pulls this change from commit ( https://github.com/conda/conda-build/commit/4c2ecd375cc4cf76c561d9c82553ce9dffe46841 ) in `conda-build` 3.x and brings it back to `conda-build` 2.x. Only pulls back the Windows functionality change as there doesn't appear to be an equivalent change for UNIX.

Backport "only set env vars in build scripts that actually have values"

---

conda_build/metadata.py
conda_build/variants.py
tests/test-recipes/variants/19_used_variables/conda_build_config.yaml
tests/test_variants.py

This helps limit "used" variables to those that are used, even if they're just a single value.  Previously, it was only possible to obtain a list of "used" variables that had multiple values.
Prereq for https://github.com/conda-forge/conda-smithy/pull/618

add method for getting all used vars, not just loop vars

---

conda_build/convert.py
conda_build/tarcheck.py
conda_build/utils.py
tests/test-recipes/metadata/arbitrary_file_in_info_dir/meta.yaml

fixes #2532 
It's less that the info dir was being clobbered, and more that the tarcheck code was written badly with the assumption that nothing else would ever put anything in the info dir.
This PR allows other stuff to be present in the info dir, and handles it properly.  Conflicts may still occur, but I think (hope?) they'll be very rare.

don't filter out all files in info dir when checking tar

---

conda_build/utils.py

icon.png files can be included via the app section of a recipe.
closes #2544

include icon.png in filtered info directory files

---

conda_build/utils.py
tests/test_jinja_context.py

As reported by @jjhelmus, max_pin values with more x's than the actual version ended up not correctly incrementing the upper bound:
- test  >=1.2.3,<1.2.3

fix handling of too many x.x.x.x in max_pin field for pin_* jinja2

---

conda_build/build.py

If the `test/files` section in `meta.yaml` has path to a file inside a
directory, example: `tests/hello.c`, `copy_recipe()` was copying the file
`hello.c` to `info/hello.c` instead of `info/tests/hello.c`
Fixes #2555

Make sure dst is recipe_dir/x and not just x

---

conda_build/metadata.py
tests/test-recipes/split-packages/_order/meta.yaml
tests/test-recipes/split-packages/_order_bad/meta.yaml
tests/test_subpackages.py

test_subpackage_order_bad() is marked as xfail for now, but we need
to remove this marking when this is fixed.

Add test to show that pin_subpackage does not build in correct order

---

setup.py

This is helpful for installing this package via setuptools. The conda
recipe already mentions 'jinja2' as a runtime dependency.
Fixes #2565

Specify 'jinja2' as an install dependency

---

conda_build/cli/main_build.py
conda_build/config.py
conda_build/utils.py
conda_build/variants.py
tests/test_api_render.py

This PR attempts to allow the conda-build section of the .condarc file to include environment variables in the two path entries; namely, `pypirc` and `root-dir`. The changes are straightforward, but I'm not sure how to test them.

Issue2521 condarc env vars WIP

---

conda_build/os_utils/macho.py
conda_build/post.py
conda_build/utils.py

This PR is in relation to Issue https://github.com/conda/conda-build/issues/2291
On MacOS, when building relocatable binaries the the post build "fixing linking" stage can take hours to complete on a large library (VTK, QT). I've traced the main source of the issue to a single function that is repeatedly called for every shared library that is examined. 
**I see a 21% reduction in the time spent on this last phase (on a common library I compile it went from from 628.304 sec before to 498.068 sec after) when building the ITK library**
The line profile output pasted below traces the major time suck from post build instantiation to the problem function. 
```
Total time: 606.69 s
File: /Users/rick/projects/conda-build/conda_build/post.py
Function: post_build at line 455
Line #      Hits …
```

[WIP] Speed up fixing linking phase for macos binary builds

---

conda_build/api.py
conda_build/build.py
conda_build/environ.py
conda_build/jinja_context.py
conda_build/metadata.py
conda_build/render.py
conda_build/variants.py
tests/test-recipes/variants/24_test_used_vars_in_scripts/bld.bat
tests/test-recipes/variants/24_test_used_vars_in_scripts/build.sh
tests/test-recipes/variants/24_test_used_vars_in_scripts/conda_build_config.yaml
tests/test-recipes/variants/24_test_used_vars_in_scripts/meta.yaml
tests/test-recipes/variants/24_test_used_vars_in_scripts/output_script.sh
tests/test_variants.py

The purpose here is that with conda-build 3.1, we make up the hash from what variables (and values) are "used" in a recipe.  "Used" means the value was filled into a jinja2 template, or was applied to pin something in meta.yaml.  This PR expands that "used" definition to also include variables that are used as environment variables in build scripts or in output install scripts.
CC @mingwandroid @nehaljwani

allow detection of used variables in shell scripts, not just meta.yaml

---

conda_build/metadata.py
tests/test-recipes/split-packages/script_install_files/meta.yaml

too many things were getting hashed after zip_keys was considered in judging what variables are "used".  This fixes things back to the expected behavior: only direct dependencies affect the hash.

exclude zipped keys from used vars when computing hash

---

bdist_conda.py
conda_build/build.py
conda_build/config.py
conda_build/metadata.py
tests/test-recipes/metadata/_set_env_var_activate_build/install-output.bat
tests/test_environ.py

Keeps build and host envs always separate.  Still merges them when only build section is present, unless {{ compiler() }} jinja2 is used in build.
fixes #1467

always split build and host prefixes

---

.travis.yml
appveyor.yml
ci/travis/run.sh
conda_build/metadata.py
conda_build/variants.py
tests/conftest.py
tests/test-recipes/variants/25_target_platform_looping/conda_build_config.yaml
tests/test-recipes/variants/25_target_platform_looping/meta.yaml
tests/test_api_build.py
tests/test_variants.py

3.1.4 was a dud release because it was much, much slower.  The test suite wasn't terribly affected because it is so simple.  Rendering the conda-build recipe to build the 3.1.4 release was painfully slow.
This was the main hotspot.

cache used variables

---

conda_build/variants.py

causing a list to be passed later for single string values
Fixes issue raised by @isuruf at https://github.com/conda-forge/conda-smithy/pull/625#issuecomment-352952516

fix zipped key with single entry 

---

conda_build/index.py
conda_build/variants.py

This is helpful when trying to figure out why on earth you're seeing some strange values - it at least gives you a list of places to look.
Output looks like:
```
CONDA_SUBDIR=linux-64 conda render ctng-dbg-compilers-activation-feedstock -m ctng-dbg-compilers-activation-feedstock/recipe/conda_build_config.cos6.x86_64.yaml
Adding in variants from internal_defaults
Adding in variants from /Users/msarahan/code/aggregate/conda_build_config.yaml
Adding in variants from ctng-dbg-compilers-activation-feedstock/recipe/conda_build_config.cos6.x86_64.yaml
```

add log messages when adding variant configs

---

conda_build/metadata.py
conda_build/render.py
tests/test_variants.py

leave cleanup of zip_keys for others
The issue here was that for conda-smithy, we were ending up with too many configurations due to zipped keys that were ultimately unused.  We need to deduplicate those somehow, but having the zip_keys pulled in made that much harder.
https://github.com/conda-forge/conda-smithy/pull/625#issuecomment-353518158
This is a companion PR for https://github.com/conda-forge/conda-smithy/pull/625/commits/2cfd07288855dececaff67fd9148ccbfa8375444

don't loop in all zip_keys when collecting used vars

---

conda_build/build.py
conda_build/config.py
conda_build/environ.py
conda_build/skeletons/cran.py

Let me know if you want these split (first commit as one PR then next two as another PR) but both are needed to be able to build R packages correctly.
fixes #2603

Skeleton fixes

---

conda_build/build.py
tests/test-recipes/split-packages/split_packages_hash_resolution/conda_build_config.yaml
tests/test-recipes/split-packages/split_packages_hash_resolution/meta.yaml

fixes #2606 
@nehaljwani note that I needed to add a runtime dep on nomkl for the nomkl-featured package.  Without that, you'll get unsatisfiable errors that are very confusing.  They'll tell you that the package you just built is not installable, but won't mention anything about the feature.

fix outputs not loading hash info at test time correctly

---

conda_build/api.py
conda_build/jinja_context.py
conda_build/metadata.py
tests/test_cli.py

@nehaljwani reported issues rendering a recipe for mxnet, which had a number of problems on windows:
- run_exports from other packages were not taking effect (opencv, mkl)
- exact subpackage pins weren't taking effect
With more aggressively skipping metadata and outputs, these confusions go away.

check skip status in more places, to avoid confusion

---

conda_build/os_utils/pyldd.py

This is required so that `cf.uniqueness_key()` doesn't error out with `AttributeError`:
```
patchelf: --print-rpath failed for
/opt/conda/conda-bld/cmake-binary_yyy/xxx/cmake-bin/share/cmake-3.9/Modules/CPack.OSXScriptLauncher.in
...
File "/home/nwani/conda-build/conda_build/os_utils/pyldd.py", line 986, in _inspect_linkages_this
return cf.uniqueness_key(), [], []
File "/home/nwani/conda-build/conda_build/os_utils/pyldd.py", line 504, in uniqueness_key
return self.filename
AttributeError: 'machofile' object has no attribute 'filename'
```

Always set filename, dirname for a machofile

---

conda_build/build.py
conda_build/metadata.py
conda_build/render.py

This was breaking the example from our blog post on conda-build 3, because many of the recipe package/names were identical.

cache used vars based also on recipe path, to avoid over-caching

---

conda_build/build.py

This change closes the memory map before rewriting it. This prevents problems when running on WSL and does not seem to cause problems in Windows or Linux. This is a fix for issue #2598

Update build.py to fix rewriting problem when running in WSL

---

conda_build/post.py

```python
File "<...>/conda_build/api.py", line 188, in build
need_source_download=need_source_download, config=config, variants=variants)
File "<...>/conda_build/build.py", line 1923, in build_tree
notest=notest,
File "<...>/conda_build/build.py", line 1352, in build
built_package = bundlers[output_d.get('type', 'conda')](output_d, m, env)
File "<...>/conda_build/build.py", line 809, in bundle_conda
files = post_process_files(metadata, initial_files)
File "<...>/conda_build/build.py", line 710, in post_process_files
post_build(m, new_files, build_python=python)
File "<...>/conda_build/post.py", line 592, in post_build
check_overlinking(m, files)
File "<...>/conda_build/post.py", line 528, in check_overlinking
_inspect_file_linking(m, path, files, …
```

correction

---

conda_build/metadata.py
conda_build/source.py
conda_build/variants.py
tests/test-recipes/variants/numpy_used/conda_build_config.yaml
tests/test-recipes/variants/numpy_used/meta.yaml
tests/test_variants.py

fixes #2658 
The problem here was an unhappy medium between ``numpy x.x`` and having numpy unpinned.  ``numpy x.x`` worked ok, but the equivalent pin_compatible expression wasn't being treated correctly.
There are 3 outcomes with numpy:
1. ``numpy x.x`` or ``{{ pin_compatible('numpy', max_pin='x.x') }}`` - this is what gets you the npXYY in the build string.  You can have min_pin set to anything you want.  The key is having max_pin with **two** x's.
2. usage of ``{{ pin_compatible('numpy') }}`` either without max_pin arguments at all, or with arguments other than ``'x.x'`` - this makes numpy contribute to the hash
3. No usage of pin_compatible - this makes numpy not contribute to the hash

fix hash handling of numpy pinning

---

setup.py

If git is not in PATH, get_version() returns 'unknown+0' instead of
erroring out, which affects the output for `conda-build -V`. This patch
addresses the issue by erroring out during creation of package if
version cannot be computed.

Error out if version computation fails

---

conda_build/cli/main_render.py
conda_build/config.py
conda_build/variants.py
tests/test-recipes/variants/exclusive_config_file/conda_build_config.yaml
tests/test-recipes/variants/exclusive_config_file/meta.yaml
tests/test_variants.py

This is intended to address @jakirkham comments from https://github.com/conda-forge/conda-smithy/pull/625
This provides a slightly different CLI option and API argument to specify a config file that overrides the usual search in HOME and cwd.  The thought here was to help people avoid "oops" situations where they meant to use some specific config file, but their system-wide defaults crept in.
With an exclusive config file, the hierarchy is:
1. exclusive config file
2. config file in the recipe (alongside meta.yaml)
3. any additional files specified on the CLI with --variant-config-files/-m

implement exclusive config file

---

conda_build/variants.py

Fixes problems like:
```
File "C:\MC2\Scripts\conda-build-script.py", line 11, in <module>
load_entry_point('conda-build', 'console_scripts', 'conda-build')()
File "z:\msarahan\code\conda-build\conda_build\cli\main_build.py", line 413, in main
execute(sys.argv[1:])
File "z:\msarahan\code\conda-build\conda_build\cli\main_build.py", line 383, in execute
action(recipe, config)
File "z:\msarahan\code\conda-build\conda_build\cli\main_build.py", line 323, in test_action
return api.test(recipe, move_broken=False, config=config)
File "z:\msarahan\code\conda-build\conda_build\api.py", line 213, in test
test_result = test(recipedir_or_package_or_metadata, config=config, move_broken=move_broken)
File "z:\msarahan\code\conda-build\conda_build\build.py", line 1609, …
```

fix interpretation of zip_keys when testing pkgs

---

conda_build/api.py
conda_build/config.py

addresses issues reported in https://github.com/conda-forge/conda-smithy/issues/653

allow trimming of skipped metadata in rendering to be optional

---

conda_build/conda_interface.py
tests/test_conda_interface.py

To be used by conda-forge primarily, but may be useful elsewhere.

add get_installed_version func in conda_interface to get pkg vers

---

.travis.yml
appveyor.yml
conda.recipe/meta.yaml
conda_build/api.py
conda_build/build.py
conda_build/cli/main_build.py
conda_build/config.py
conda_build/post.py
conda_build/utils.py
tests/test_api_build.py
tests/test_api_consistency.py
tests/test_build.py
tests/test_utils.py

The primary purpose of the build stats here is to feed into CI systems that have different classes of workers.  We'll be aggregating the needs of given package builds, and then we'll use that information to dispatch jobs to the smallest worker that is capable (and available).

Record build stats

---

conda_build/build.py
tests/test_subpackages.py

@mingwandroid commented that he had a hard time finding a recipe for curl, which is a split package where neither output matches the top-level name.  We were not copying the original top-level recipe into packages - only the rendered metadata.
This PR puts the top-level recipe into all output packages, in the "parent" subfolder, and maintains the previous behavior otherwise.

save parent recipe in subfolder of outputs for info/recipe

---

conda_build/utils.py

memory and cpu usage won't be tracked, but disk and overall elapsed time will be.  This will help us until we can figure out why psutil fails to import for us on linux-32 in a linux-64 docker container.

fall back gracefully when psutil is not available

---

conda_build/_load_setup_py_data.py

When doing something like
```python
load_setup_py_data(setup_file='../setup.py', from_recipe_dir=True)
```
load_setup.py data did not add the correct path to sys.path.
This fix allows this to work cleanly

Add relative path support for load_setup_py_data

---

conda_build/build.py
conda_build/windows.py
tests/test-recipes/metadata/_compiler_python_build_section/meta.yaml
tests/test-recipes/metadata/_empty_pkg_with_python_build_host/meta.yaml
tests/test_api_build.py

@mingwandroid reported problems building R recipes where he needed the compilers to be in the host section for some reason.  This PR is a WIP as we explore this idea - it might break stuff pretty badly.

reverse build/host activation order, to give build exe's higher priority

---

conda_build/build.py
conda_build/create_test.py
tests/test-recipes/split-packages/_output_test_script/meta.yaml
tests/test-recipes/split-packages/_output_test_script/run_output_2_test.py
tests/test_subpackages.py

observed this with h2o, but it seems to have been a long-standing problem.  Outputs using
```
test:
script: some_script.py
```
were not ending up picking up the test at all.  This adds a test of that test functionality.

fix test scripts from subpackage outputs not being detected

---

conda_build/config.py
conda_build/post.py

It diverged a lot from the upstream one, and the split between in_prefix and in_system is less clear-cut
now that whitelists are supported.
Should whitelists be in conda_build_config.yaml and not hardcoded at all? I am leaning that way personally.

Use my latest version of check_overlinking

---

conda_build/os_utils/pyldd.py
conda_build/post.py

When inspecting linkages, skip over files which appear to be ELF files but are incomplete.

skip incomplete ELF files

---

conda_build/build.py
conda_build/cli/main_build.py
conda_build/config.py
tests/test_api_test.py
tests/test_cli.py

Numba team splits their builds between build and test.  With recent conda-build versions, we're no longer re-rendering the test-time recipe - it's baked in.  This is to support testing when the recipe isn't included.
So, to support Numba being able to dynamically specify dependencies at test time, this is a new feature that allows extra specs at the CLI.  This argument is only respected for testing, not for building or rendering.
CC @stuartarchibald

add optional argument for providing extra dep specs at test time

---

tests/test_api_skeleton.py

Do we need this for the `conda` tests? Ref: https://circleci.com/gh/conda/conda/6995

[2.1.x test backport] change r skeleton from nmf to acs; nmf got removed

---

conda_build/index.py

catch yaml ScannerError for legacy conda packages

---

conda_build/metadata.py
tests/test-recipes/split-packages/_inherit_build_number/meta.yaml
tests/test_subpackages.py

This had been default behavior but had regressed.

make outputs inherit build number if not provided otherwise

---

conda_build/utils.py

I tried to build a package with the most recent version of conda today on my Windows machine and it failed in `conda_build.utils.directory_size`: https://github.com/conda/conda-build/blob/6b8f4b57f559b18d0b671257f7d58b571f90b45e/conda_build/utils.py#L128
It turns out the output of `dir /s` is different accross the different languages of Windows. In the german version the first letter of bytes is uppercase. I modified the regular expression to ignore the case.

Fix directory_size on german windows by ignoring case

---

conda_build/index.py

fix #2756 ignore non-rendered jinja2 in info/recipe/meta.yaml during indexing

---

conda_build/jinja_context.py
conda_build/metadata.py

Non-final output data was entering into lists of dependencies.  For exact subpackage pins, this led to solver conflicts.  This PR ignores the output metadata in favor of the original metadata obtained from the top-level, which is further along at this point.

fix exact pinning in subpackages due to non-final output data

---

.lgtm.yml

The product team has been known to use lgtm.com.  Conda and conda-build both get (well, fixed in conda now) bad scores primarily because of this one 'redundant-assignment' error.  Our use is perfectly legitimate though.  This is the config pretty much just copied over from conda (https://github.com/conda/conda/blob/master/.lgtm.yml) that wipes that one out for us.
To clarify, the redundant assignment error happens with we do
```python
from conda.exports import foo
foo = foo
```
but, because their inspection rule set is still probably young
```python
from conda.exports import foo, bar
foo, bar = foo, bar
```
doesn't trigger the error indicator.
Regardless, given how flake8 and pycharm interact, our use of the assignment here is the best technical solution.

lgtm.com config

---

conda_build/os_utils/pyldd.py
conda_build/post.py

Here I raise an error or warning if any DT_RUNPATH entries are found.
Some people (e.g. glibc developers) consider DT_RUNPATH the right thing to do. It is non-transitive and allows LD_LIBRARY_PATH to take precedence over it. It is enabled by passing --enable-new-dtags to ld, and by default when using gold where it can be disabled with --disable-new-dtags.
I believe the Anaconda Distribution never wants this however. We've wasted a lot of time tracking down non-bugs because someone has set LD_LIBRARY_PATH by mistake and I see no real use for it outside of a software developer testing their own fixes to a system library, personally.
I would welcome other people's opinions and some discussion here though: @msarahan, @nehaljwani, @jjhelmus, @kalefranz, @jakirkham, @mbargull, @ocefpaf, …

For discussion only at present.

---

conda_build/variants.py

fixes an issue reported by @mingwandroid where the qt recipe was detected as using "python" when it was not really.  Narrowed this regex to be the problem.

fix pin_* regex that was erroneously picking up wrong usages

---

conda_build/utils.py
tests/test_utils.py

Closes #2774.
@msarahan please review.

Don't filter out .gitignore and .gitmodules when packaging

---

conda_build/jinja_context.py
conda_build/metadata.py
conda_build/render.py
tests/test-recipes/metadata/_numpy_setup_py_data/meta.yaml
tests/test-recipes/metadata/_numpy_setup_py_data/setup.py
tests/test_api_build.py

for load_setup_py_data.  Because rendering is done before any environments are created, we can't fix this in conda-build.  We can't require that envs be created in order to render recipes.
fixes https://github.com/conda/conda-build/issues/2765
New error output looks like
```
conda_build.exceptions.CondaBuildException: Could not render recipe - need modules installed in root env.  Import error was "No module named 'Cython'"
```
so at least it should be less confusing.

improve error message when modules are needed to render recipe

---

conda_build/config.py

Minor correction to `config.py` `log.warn` when setting the `arch` or the `platform`.

Minor update to config log warning

---

conda_build/post.py

Works around https://github.com/conda/conda-build/issues/2674
I suspect this binary is actually broken, it was generated by
go, and go has its own really weird and buggy toolchain that
seems to have been derived from Plan-9.

Skip (but warn about) failures in pyldd

---

conda_build/skeletons/cran.py

Generating MRO packages was failing due to this simple mistake.

skeleton (cran): Fix a misnamed key

---

conda_build/build.py
conda_build/render.py
conda_build/utils.py
tests/test-recipes/metadata/_test_downstreams/downstream/meta.yaml
tests/test-recipes/metadata/_test_downstreams/upstream/meta.yaml
tests/test_api_build.py

Implements new behavior where a package may specify downstream packages from itself that should be tested when a new build of a given upstream is built.  For example,
```
package:
name: test_upstream_with_downstream_tests
version: 1.0
test:
downstreams:
- test_downstream_with_test_fail
```
```
package:
name: test_downstream_with_test_fail
version: 1.0
test:
commands:
- exit 1
```
See the test case in this PR: if you build ``test_downstream_with_test_fail`` (disabling testing, of course), then build ``test_upstream_with_downstream_tests``, the test phase after building the latter package will fail because of the forced fail in the downstream package.
This PR is kind of hairy.  It could use some rework to make the implementation simpler.  Please take a look at the general idea here, and let …

PoC: downstream testing

---

conda_build/utils.py

This PR is to address #2821, for appending to recipes (https://conda.io/docs/user-guide/tasks/build-packages/variants.html#appending-to-recipes):
> Any contents in recipe_append.yaml will add to the contents of meta.yaml. List values will be extended [...]
However, I'm not really clear on the intent of the function I'm modifying here, so I could do with some guidance. For instance, although line 1401 doesn't affect me right now, I also don't see its purpose (I would expect just line 1402).

Recipe appending: avoid losing ordering of both original and appended commands.

---

conda_build/skeletons/cran.py

Per @mingwandroid's advice, this stuff should not have been merged until https://github.com/conda-forge/r-base-feedstock/pull/43 is merged.  There is a difference in the filesystem paths on Windows after that PR, and conda-forge and defaults are out of sync.
@jdblischak please resubmit this PR after the r-base PR above gets merged.

revert #2831, Add license file for R packages from CRAN

---

conda_build/render.py
conda_build/variants.py

Supplement to #2830; key order was being lost when the dictionaries from many configs were being squished together.

try again to keep key order in squished variants

---

conda_build/cli/main_skeleton.py
conda_build/skeletons/cran.py
conda_build/variants.py

Supersedes #2833 
For Anaconda, we'll need to use -m and specify our config file.  I can also put in a condarc setting to help us avoid forgetting to pass that.

Sync default cran mran setting

---

conda_build/api.py
conda_build/metadata.py
conda_build/render.py
conda_build/utils.py
conda_build/variants.py
tests/test_utils.py

General points:
* Variant space is reduced based on knowledge of which variables are "used" in a recipe.  This dramatically cuts back the rendering time
* Regex improvements for finding out which variable is used.  Mostly this was replacing ``.*`` with more specific things, like ``[^\{]``.
* memoizing string splitting for repeat words (helps speed up splitting of zipped keys)

several speedups focused on rendering

---

conda_build/render.py
tests/test_api_build.py
tests/test_render.py
tests/test_subpackages.py

Fixes issue raised by @tkelman in https://github.com/conda-forge/conda-build-feedstock/pull/41#issuecomment-384470429
wherein he had an upper bound with <=, and it just so happened that conda-forge's only available packages were exactly that upper bound.  The old behavior of ignoring the operator and always forcing < was broken.  This fixes it and does the comparison a little more straightforwardly.
fixes #2806

fix handling of <= on upper bound constraints being forced to <

---

.gitignore
.travis.yml
conda_build/build.py
conda_build/conda_interface.py
conda_build/windows.py

Per fairly extensive discussion with @mingwandroid, we took out the default environment stacking from conda 4.4.  In conda 4.6, to get environment stacking, you now need to add a `--stack` flag to activate (from https://github.com/conda/conda/pull/7195).  This PR should maintain compatibility here.

add conda 4.6 compat with activate --stack flag

---

conda_build/conda_interface.py

Working on cleaning up `conda.exports` and `conda_build.conda_interface` in conjunction with https://github.com/conda/conda/pull/7217.

remove conda 4.2 and earlier compat

---

conda_build/create_test.py

.. this is so that you can 'call run_test.bat' without having it close your cmd.exe prompt
when you are trying to investigate why tests failed.

create_test: Use exit \b N instead of exit N

---

conda_build/build.py

to avoid confusion at test time.  The problem here is that on a local system, when this particular bit of metadata exists in a recipe, conda build uses it for determining used variables, recomputes the build id, goes stupid, and can't find packages that it just built because the build strings are different.

remove parent_recipe entry when recording meta.yaml for outputs 

---

conda_build/build.py
conda_build/license_family.py
tests/test_license_family.py

With split packages, you are warned when duplicate files are present across packages.  This check did not account for packages that have no files, and thus no checksums.

handle empty packages in check for duplicated files

---

conda_build/build.py
conda_build/environ.py
conda_build/jinja_context.py
conda_build/metadata.py
conda_build/utils.py
conda_build/windows.py
tests/test-recipes/metadata/_setup_py_data_in_env/meta.yaml
tests/test-recipes/split-packages/_entry_points/test-pkg1.py
tests/test-recipes/split-packages/_entry_points/test-pkg2.py

as opposed to the old way of seeing if the python executable was there.  This makes {{ PYTHON }} usable in rendering, where it was previously only available in the build scripts afterwards.
CC @tomashek

set PYTHON and other language path vars based on presence in reqs

---

conda_build/jinja_context.py
conda_build/metadata.py
conda_build/render.py
conda_build/utils.py
tests/test-recipes/metadata/_empty_host_avoids_merge/meta.yaml
tests/test-recipes/metadata/_no_merge_build_host/meta.yaml
tests/test-recipes/split-packages/noarch_subpackage/meta.yaml
tests/test-recipes/variants/numpy_used/meta.yaml
tests/test_api_build.py
tests/test_api_render.py

fixes #2887 
Note that this changes some behavior with run_exports.  If a strong run_exports is present in the build section, any weak run_exports in the build section will not apply, because the strong run_export creates the host section with its injection of the strong run_exports.
This also switches from the yaml BaseLoader to the default.  This interprets booleans more directly.  I have attempted to keep the version number parsing as a string, but there may be some small issues that the test suite doesn't cover.

fix merge_build_host functionality.  Empty host section splits envs.

---

conda_build/metadata.py
tests/test-recipes/metadata/float_misinterpretation/meta.yaml
tests/test-recipes/metadata/float_misinterpretation/run_test.bat
tests/test-recipes/metadata/float_misinterpretation/run_test.sh

fix yaml loading versions as floating point and losing trailing zeros

---

conda_build/jinja_context.py

When using the load_file_regex() in a jinja template, we were receiving a resource warning:
```
/miniconda3/lib/python3.6/site-packages/conda_build/jinja_context.py:187: ResourceWarning: unclosed file <_io.TextIOWrapper name='/localdisk/ipp/linux/include/ippversion.h' mode='r' encoding='ISO-8859-1'>
match = re.search(regex_pattern, open(load_file, 'r').read())
```
This patch makes sure the file is closed
fixes #2917

ensure the file handle is closed upon out-of-scope

---

conda_build/build.py

The code was raising `RuntimeError(msg, pattern)` (a tuple) instead of the intended `RuntimeError(msg % pattern)`.

Fix raise RuntimeError

---

tests/test-recipes/variants/27_requirements_host/conda_build_config.yaml
tests/test-recipes/variants/27_requirements_host/meta.yaml
tests/test_variants.py

This is intended to be a test case for the fix in #2912.
I followed the conventions in the test-recipes directory, but I am not sure how to trigger these tests.
When triggered manually with conda-build 3.10.3's conda-render, no errors are raised.
When triggered manually with 3.10.4, the error as described in #2900 is reproduced.

Add a test case for #2912

---

conda_build/jinja_context.py
tests/test-recipes/variants/28_custom_compiler/conda_build_config.yaml
tests/test-recipes/variants/28_custom_compiler/meta.yaml
tests/test_variants.py

As of 3.10.5 there is a bug where it is not possible to define
a custom compiler for a language different from the default ones.
This PR includes test case variants/28_custom_compiler to show
the error.

Support custom language in compilers

---

conda_build/utils.py

`glob2` is considerably slower than `glob` from the Python 3's standard library acc. to the measurements from gh-2936:
```
7.650 glob
3.055 parse_config_file
18.984 render
2.514 glob
3.124 parse_config_file
14.154 render
```
If I didn't miss anything else, the differences between `glob2.glob` and `glob.glob` are that `glob2.glob` offers more fine grained behavior via additional parameters, i.e., `with_matches, include_hidden, norm_paths, case_sensitive, sep`, uses `recursive=True` instead `False` on default and also calls `normcase` on each returned path.
BEWARE: I did not check whether `conda-build` uses any of the additional parameters of `glob2.glob` or if there are other possible differences/cornercases between the two implementations.
But since `glob.glob` (`glob.iglob`) from Python …

utils: replace glob2 by glob for PY3

---

conda_build/utils.py

Followup to https://github.com/conda/conda-build/pull/2937#issuecomment-393959530.
I simply misread `glob2`'s source code. The `normcase` is only used internally but does not affect the output. Hence, the `map(normcase, ...)` isn't needed and should fix the inconsistent output (and therefore the failing `tests.test_utils.test_expand_globs` on Windows + PY3).

utils.glob: remove unnecessary normcase, fix test_expand_globs

---

conda_build/skeletons/pypi.py

Rationale for this: the conda forge linter moans when encountering things
like `BSD License`
We can attempt to make the output of conda skeleton pypi play a bit nicer
with conda-forge's linter by cleaning this up.

Clean up the license field for pypi skeleton

---

conda_build/variants.py

Second and hopefully final fix after gh-2949 for issues introduced in gh-2925.

variants: fix re.escape usage for Python <3.3

---

conda_build/environ.py

If we do not catch this packages will end up untested but not moved
to broken.

get_install_actions: Handle conda UnsatisfiableError

---

conda_build/post.py

Allow empty missing_dso_whitelist in build section

---

conda_build/render.py

host_reqs is modified in-place to inject extra_run_specs_from_build
however, it was possible for host_reqs to refer to a detached list via defaults/ensure_list, preventing the `requirements/host` field from being modified
this ensures that host_reqs actually refers to the requirements/host value even if it is initially not defined or defined as null
closes #2986

ensure host_reqs modifications are made in-place

---

conda_build/skeletons/cran.py

Replicated the changes in PR #2500 into `skeleton cran` which add a small function for getting the truthiness of the SSL_NO_VERIFY environment variable and passes that to requests.session to disable SSL verification.

Adding fix for bypassing MITM proxies to skeleton cran

---

conda_build/skeletons/cran.py

Fixes #2805. 
If there are special characters in the DESCRIPTION file, then `grep -v ...` has undesirable behavior when applied to it. This tells grep to assume the file is text.

Force text interpretation of CRAN DESCRIPTION files

---

docs/source/variants.rst

These corrections are based on my testing and reading of the 'find_config_files' function in 'variants.py' in the conda-build 3 source code ( https://github.com/conda/conda-build/blob/e2a4a8fd1d29347f6c12f8464d9537486b4be983/conda_build/variants.py#L140-L170 )
'cwd' was added to the search path for conda-build 3.0.0 in commit: conda/conda-build@36c2725
The behavior where the conda_build/config_file entry overrides the default location in home dir appears to be even older.
[PR moved from conda/conda-docs#595 per request from @msarahan]

Fix documentation of search order for conda_build_config.yaml

---

conda_build/cli/main_render.py
conda_build/config.py
conda_build/variants.py
tests/test_variants.py

@msarahan in https://gitter.im/conda/conda-build?at=5b0dc3d299fa7f4c062c0217:
>> Would you accept a PR to extend either the --exclusive-config-file CLI parameter or the conda_build: config_file .condarc parameter to accept multiple paths?
The use case is Bioconda which is essentially a conda-forge downstream repository now. As such we want to use conda-forge-pinning's conda_build_config.yaml but also add our own on top of that. Using --variant-files won't work, due to the config file processing order, as soon as we would start to add per-recipe configuration files.
>
> Sure, I think that's fine. Just be really clear what the priority is. I think it would be most consistent to have later files have higher priority (this is backwards compared to channels in conda, but more consistent with …

support multiple exclusive_config_files

---

conda_build/skeletons/cran.py

Three changes:
- Add Windows-specific `sed` and `coreutils` build dependencies whenever `make` is added, because the Makefiles seem to require these. Otherwise I would get errors that `sed` and `basename` were missing.
- Remove the `automake` build dependency. We don't actually _have_ an automake package; instead, we have `automake-wrapper` (which is already included), and this in turn pulls in all the versions of `automake` that we have. I don't know why it's structured this way, but it is!
- Add `zip` as a build dependency on Windows. I've noted that the Windows build step requires `zip`. I think it's used just to build the binary package, which if I understand correctly we don't need. But seeing the error when it fails to run `zip` makes me uneasy. I'd rather either patch the Makefile …

Improvements to CRAN skeletons

---

appveyor.yml
ci/travis/run.sh
conda_build/build.py
conda_build/environ.py
conda_build/jinja_context.py
conda_build/metadata.py
conda_build/skeletons/pypi.py
conda_build/windows.py

@msarahan hopefully I did not break anything. The goal is to:
- enforce sha256;
- change the `script` section to use `pip`;
- simplify the recipe by reducing the excess of jinja variables.
I'm sure there are more places we can optimize and simplify the code but I'm not too familiar with conda-skeleton to go any further.
Also, I'd like to remove the single quotes from the name and version values in the package section, to keep a consistent style with the rest of the recipe, but I'm not sure how to do that in an `ruamel_yaml.comments.CommentedMap` object (and that is not really that important anyway.)
fixes #3000

Make recipes beautiful again

---

conda_build/skeletons/cran.py

Fixes what I broke in #3030:
```
requirements:
build:
- {{ compiler('c') }}        # [not win]
- {{ compiler('fortran') }}  # [not win]
- {{native}}toolchain        # [win]
- {{posix}}filesystem        # [win]
- {{posix}}sed               # [win]
- {{posix}}grep              # [win]
- {{posix}}autoconf
- {{posix}}automake          # [not win]
- {{posix}}automake-wrapper  # [win]
- {{posix}}pkg-config
- {{posix}}make
- {{posix}}coreutils         # [win]
- {{posix}}zip               # [win]
```

Bring back automake for CRAN on Unix

---

conda_build/build.py
conda_build/cli/main_build.py
conda_build/cli/main_metapackage.py
conda_build/config.py
docs/source/commands/conda-build.rst
docs/source/commands/conda-metapackage.rst

--label argument for anaconda upload

---

conda_build/index.py
conda_build/utils.py

fixes #3036 
Channels specified via --channel, -c on the CLI, or channel_urls (in the API) will take priority over locally built packages.  Locally built packages still take priority over anything configured in condarc.

put local channel behind user-specified channels, for remote priority

---

conda_build/build.py

c3i was skipping packages because it was finding them locally.  Not cool.

add option to omit local channel in is_package_built

---

conda_build/build.py

@msarahan https://github.com/conda/conda-build/pull/3038 does *not* resolve https://github.com/conda/conda-build/issues/3036.  I've tested this change and it has the desired behavior:
```
If a user specifies "conda build -c mychannel -c local":
conda will prioritize packages in mychannel over packages in the local conda-bld folder for the test environment
If a user specifies "conda build -c mychannel":
conda will prioritize packages in the local conda-bld folder over packages in mychannel for the test environment
If a user specifies "conda build -c local -c mychannel":
conda will prioritize packages in the local conda-bld folder over packages in mychannel for the test environment
```
Without this change, in all 3 cases conda will prioritize packages in the local conda-bld folder over …

Allow local channel to have the appropriate priority in test environments

---

conda_build/build.py
conda_build/windows.py

Fixes https://github.com/conda/conda-build/issues/2748
We never want `pip` to install dependencies in the build as we will supply them ourselves.

Configure `pip` to disable pulling in dependencies

---

conda_build/post.py

GCC is currently failing to build because of
```
ERROR (gcc_impl_linux-64,x86_64-conda_cos6-linux-gnu/sysroot/lib/librt-2.12.2.so): runpaths ['$ORIGIN/../../../lib/'] found in /opt/conda/conda-bld/compilers_linux-64_1533843820745/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_plac/x86_64-conda_cos6-linux-gnu/sysroot/lib/librt-2.12.2.so
```
@mingwandroid is very hesitant to monkey with any of this stuff, as GCC handles it own relocatability stuff.  This PR allows us to whitelist runpath stuff and avoid this error.

allow whitelisting runpath entries

---

.travis.yml
conda_build/utils.py
conda_build/variants.py
setup.cfg

This also has the important effect of capturing any ```*_compiler_version``` config stuff in the used variables, and thus in the hash.

allow looping over compiler_version matrices

---

conda_build/build.py

fix linux temp channel used during testing

---

conda_build/metadata.py
tests/test_check.py

`source` and `outputs` can contain a list of dictionaries, in which case checking would fail.
I couldn't exactly figure out where to put the regression test, so I created a new file for it.
Closes #3096.

Fix --check for optionally iterable fields

---

conda_build/post.py
conda_build/utils.py
tests/test_post.py

Move the permission fix before opening the file. Fix #2824
Fix the following traceback ( from https://circleci.com/gh/bioconda/bioconda-recipes/24304 ), which affects macOS builds of some Bioconda Perl packages:
```
File "/Users/distiller/project/miniconda/bin/conda-build", line 11, in <module>
sys.exit(main())
File "/Users/distiller/project/miniconda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 424, in main
execute(sys.argv[1:])
File "/Users/distiller/project/miniconda/lib/python3.6/site-packages/conda_build/cli/main_build.py", line 415, in execute
verify=args.verify)
File "/Users/distiller/project/miniconda/lib/python3.6/site-packages/conda_build/api.py", line 200, in build
notest=notest, need_source_download=need_source_download, …
```

Fix fix_shebang

---

conda_build/build.py
conda_build/config.py
conda_build/skeletons/pypi.py
conda_build/windows.py

Do not disable pip's cache, rather point in to a location inside the work dir

---

conda_build/build.py
conda_build/index.py
conda_build/jinja_context.py
conda_build/metadata.py
conda_build/render.py
tests/test-recipes/metadata/state_variables/meta.yaml
tests/test-recipes/metadata/state_variables/setup.py
tests/test_cli.py

fix CONDA_BUILD_STATE not being set in load_setup_py_data

---

conda_build/index.py

Not every package has all of these files.  We don't really care if it doesn't - it'll just be empty in the index.

skip over index metadata files when they're not available

---

conda_build/build.py
conda_build/conda_interface.py

fixes #3127 
@teake - please test.  Please submit a PR with a test, too, if you can.  I don't have time for more than just throwing up what @kalefranz proposed in #3127

allow channel auth when checking if package is built

---

conda_build/os_utils/pyldd.py

Do not return elf sections which are not included in the memory image of the
process. These include string tables which are only needed for debugging.
closes #3126

skip elf section not in process memory image

---

conda_build/index.py
conda_build/render.py

This tries to fix #3119
I noticed that once json.load - and the other time json.loads is called.. I thought the first is to be called with a file descriptor? .. if so, why do we get the "need str not byte" error?

decode to str before passing to json

---

conda_build/build.py

Provide feedback to the user that the license file was found and packaged.

Print the license file was packaged

---

conda_build/metadata.py
tests/test-recipes/split-packages/_inherit_build_number/conda_build_config.yaml
tests/test-recipes/split-packages/_inherit_build_number/meta.yaml

xref: https://github.com/conda-forge/cryptominisat-feedstock/pull/11#discussion_r221037068

split-packages: handle empty build section in output

---

conda_build/build.py
conda_build/variants.py

fix issues testing packages/recipes separately from build stage

---

docs/index.rst
docs/source/channels.rst

- initiated the doc from channel-specific options from "conda-build -h"
- added a section explaining what to do when channel and package name are the same
This PR is a result of communication @ https://github.com/conda/conda-build/issues/3178, summarizing and generalizing Mike's notes.

new detailed doc for conda channels

---

conda_build/build.py
conda_build/post.py
conda_build/render.py
conda_build/skeletons/rpm.py
conda_build/source.py

Since the others haven't been merged yet I'm ploughing ahead with my `conda-build` backlog, praise be to CI and timezone differences.

Master osx allow rpaths

---

conda_build/index.py
conda_build/source.py

We use os.cpu_count() directly here instead of dividing it by two.
Mostly though this prevents max_threads=None getting passed to the
low level concurrency stuff. When that happens Python assumes that
the job is not CPU bound and uses cpu_count() * 5.

Fix thread count when indexing

---

conda_build/build.py
conda_build/index.py

This is an attempt to fix https://github.com/conda/conda-build/issues/3216 (regression of https://github.com/conda/conda-build/issues/3036) without also breaking https://github.com/conda/conda-build/issues/3070.

Test environment incorrectly prioritizes local channel

---

conda_build/environ.py

@mingwandroid 
I needed this patch to conda-build for my R experiments to work (for the R environment variable to exist).

Add r-impl to R packages

---

conda_build/build.py

Wheel creation as an output was not appending the environment activation to the wheel_output script. It looks like the metadata reference for the activation config was wrong. This PR fixed it for us internally. It now matches the reference in the bundle_conda method, line 867.

bugfix: append activation to the wheel script

---

conda_build/index.py

As this exception is not defined on python 2.7.
Fixes the following error when running `conda skeleton pypi`:
```
File "/dls_sw/apps/python/anaconda/1.7.0/64/bin/conda-skeleton", line 11, in <module>
sys.exit(main())
File "/dls_sw/apps/python/anaconda/1.7.0/64/lib/python2.7/site-packages/conda_build/cli/main_skeleton.py", line 65, in main
return execute(sys.argv[1:])
File "/dls_sw/apps/python/anaconda/1.7.0/64/lib/python2.7/site-packages/conda_build/cli/main_skeleton.py", line 61, in execute
version=args.version, config=config)
File "/dls_sw/apps/python/anaconda/1.7.0/64/lib/python2.7/site-packages/conda_build/api.py", line 282, in skeletonize
recursive=recursive, config=config, **kwargs)
File "/dls_sw/apps/python/anaconda/1.7.0/64/lib/python2.7/site-pack …
```

index.py: import PermissionError from utils

---

conda_build/config.py
conda_build/environ.py
conda_build/index.py
conda_build/source.py
conda_build/utils.py

With a timeout of 90 seconds, we consistently get failures when performing multiple builds in parallel.
@msarahan I see that this setting is defined in config.py, but for the life of me I cannot figure out how to change this setting at runtime. There doesn't appear to be a corresponding condarc entry, nor a flag I can pass to conda build. Please let me know if I'm missing something. In the meantime, increasing the default timeout seems like a reasonable approach if this value cannot be easily changed at runtime.

Change default build timeout to 900

---

conda_build/cli/main_build.py
tests/test_cli.py

Forgot to add this to #3265, sorry.
The reason I'd like this to be configurable via `.condarc` is simply because I need the switch and would like to do everything via `.condarc`.
Also, I think the original action of `--long-test-prefix` was wrong and changed it to `store_true`. This might cause some headaches though for people who used the switch as a feature bug.

Make the --long-test-prefix switch configurable via .condarc

---

conda_build/render.py
conda_build/utils.py
tests/test_render.py

get_pin_from_build was discarding build string information when a given dep is in pin_run_as_build
This is coming up in attempts to ensure that packages built with a particular variant of a dependency have a runtime dependency on the same variant. It generally works, but when the dependency is in `pin_run_as_build`, the build string in requirements.run is discarded when the pinning is applied.
For example:
```yaml
pin_run_as_build:
mpi:
max_pin: x.x
requirements:
host:
- mpi * mpich
run:
- mpi * mpich
```
The result is runtime dependency on `mpi >=1.0,<2.0` without any mention of the `mpich` build string.

avoid discarding build string during pin_run_as_build and ensure_valid_spec

---

conda_build/index.py

Packages built with very old versions of conda-build might not have the
'depends' keyword with an empty list for packages with no dependencies
in the index.json inside the tarball.

conda-index: don't assume presence of key: 'depends'

---

conda_build/os_utils/liefldd.py

nm may be not available on all system where conda-build is run, when it is not
available do not fail the build, rather print a warning and continue.
fixes the linux related portions of #3287

allow call to nm to fail

---

conda_build/skeletons/cran.py
tests/test_api_skeleton.py

Now that the installation path for R is the same across all operating systems (https://github.com/conda-forge/r-base-feedstock/pull/61), I am resubmitting an updated version of my previous PR (#2831) to add the license file to recipes of R packages that use the standard licenses shipped with R base.
Here are some examples:
* [usethis](https://cran.r-project.org/web/packages/usethis/DESCRIPTION) - GPL-3 (specifically `License: GPL-3`)
* `license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'`
* [abf2](https://cran.r-project.org/web/packages/abf2/DESCRIPTION) - Artistic-2.0 (specifically `License: Artistic-2.0`)
* `license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/Artistic-2.0'`
* [corTools](https://cran.r-project.org/web/packages/corTools/DESCRIPTION) - Artistic-2.0 …

Another attempt to add license file to CRAN recipes.

---

conda_build/source.py

Introduced in https://github.com/conda/conda-build/pull/3288/files

log.warn does not accept `file=` keyword argument

---

README.rst

Without first installing anaconda-client, `py.test tests` fails because it cannot find binstar_client. I also added how to test a single file.

Expand instructions for setting up test environment.

---

conda_build/index.py

#3303 introduced except clauses looking for `json.decoder.JSONDecodeError` objects instead of relying on the Python 2/3 agnostic solution from the header of the index.py file.
This PR corrects those 2 lines to prevent crashing on Python 2.7 builds which have gone live with conda-build 3.17.3
I don't have a formal issue for this opened, would you like me to for documentation purposes or is this sufficient?

Replace JSONDecodeError with Py version agnostic solution

---

conda_build/build.py
conda_build/windows.py

The environment variable PIP_NO_BUILD_ISOLATION is set to 'False' in the
build environment.  Previously this variable was not set in the environment
due to it having a falsey value. It is now set to the string 'False' so that it
has a truethy value in Python which results in in being included in the
environment file.
closes #3318

fix pip build isolation

---

conda_build/build.py
conda_build/windows.py

Since we don't want to include this in noarch: python packages, it makes no sense to have python go through with creating pyc files when installing a package.  This cleans it up.  Might save a tiny bit of time.

don't write bytecode when building noarch: python packages

---

conda_build/index.py
tests/test_api_build.py

While `conda-build` does not have an `--offline` flag like other conda commands (see https://github.com/conda/conda-build/issues/282 and 
https://github.com/conda/conda-build/issues/695), it *does* respect the equivalent environment variable `$CONDA_OFFLINE`. This is due to the `conda.common.configuration.Configuration` class, which pulls in environment variables to the `conda.context` module.
The `asv` test suite runs a number of builds inside test cases to ensure its `conda` integration is working; those tests have been failing due to `conda-build` exiting with exit code 1 and the following message in stdout:
```
EnforceUnusedAdapter called with url https://repo.anaconda.com/pkgs/main/channeldata.json
This command is using a remote connection in offline mode.
```
The intent behind …

Respect context.offline setting

---

conda_build/convert.py

escape path separator in repl

---

conda_build/skeletons/rpm.py

Update the base URL for CentOS 7 based source RPMs for the 7.6 release.
This URL will need to be updated whenever there is a minor CentOS 7 release.

update centos7 source URL

---

conda_build/variants.py

I wanted to override one key in conda-forge global `conda_build_config.yaml` without overriding all of the other keys zipped with it. This PR allows that. If the lengths are not the same, then it will fall back to the old behaviour of filtering.

Allow overriding one key of zip_keys group if the lengths are correct

---

conda_build/index.py
conda_build/utils.py
news/ax3l-fix-tarFallback.rst

Try to re-introduce the tarball extractor from conda-build 3.15.0.
Trying to fix #3351
Shamelessly taken from https://github.com/conda/conda-build/compare/3.15.0...3.16.0
fixes #3351

Tar: Extract Fallback

---

conda_build/environ.py
conda_build/jinja_context.py

Treat the linux-aarch64 platform similar to linux-ppc64le

default to cos7 distribution on linux-aarch64

---

conda_build/environ.py

If the machine already has an existing R installation, the `R_LIBS_USER`
environment value (defaults to
%USERPROFILE%\Documents\R\win-library\{r.major}.{r.minor}) location will
exist, and commands like `R CMD INSTALL --build .` will install the
generated package into this location rather than the build environment.
This prevents conda-build from seeing the added files, and results in an
empty package. Setting the `R_USER` environment variable fixes the R
installation exclusively to that spot, and it will be prefered over the
per-user library directory.
Scenario where this was affecting the package build: A machine with an 
existing R 3.5 installation, and installed packages. When building 
`r-base` packages, it worked without issue, but building `mro-base` 
targeting packages failed as …

Set R_USER when building R packages

---

conda_build/config.py
news/shorter-testing-prefix.rst
tests/test_config.py

I've seen a couple errors caused by the prefix replacement failing when the install path is shorter than the build path. This has been caused by the null bytes that are appended on the strings and could be fixed using `has_prefix_files` to explicitly mark them as text files.
I propose reducing the length of the testing environment path by 2 characters so these cases can be noticed by `conda-build`'s testing step.

Reduce length of test environement prefix

---

conda_build/build.py
news/override-has_prefix_files.rst

The documentation seems to imply that if a file is automatically detected as `binary` adding it to `text_has_prefix_files` should force it to be treated as `text` when replacing the prefix (and vice versa)
Currently an exception is raised `Did not detect hard-coded path in %s from text_has_prefix_files`.
Perhaps there is a different way of modifying this? If not, this PR modifies the behaviour to match what I expected from the documentation.

Allow *_has_prefix_files to override the mode

---

conda_build/metadata.py

I feel a little weird proposing such a small change, but I was reading through this file and the extra line caught my eye.

Removing extra line in metadata.sanitize docstring

---

docs/source/concepts/features.rst
docs/source/concepts/recipe.rst
docs/source/resources/compiler-tools.rst
docs/source/resources/define-metadata.rst
docs/source/resources/make-relocatable.rst
docs/source/user-guide/environment-variables.rst
docs/source/user-guide/recipes/build-without-recipe.rst
docs/source/user-guide/tutorials/building-conda-packages.rst
docs/source/user-guide/tutorials/index.rst

Hi!
There are some warnings/errors when building HTML docs. This PR fixes all those errors, including:
- Broken links
- Bad indentation on doc tree
Regards!

Fix sphinx warnings

---

tests/test_api_skeleton.py

The CRAN package [Ruchardet](https://cran.r-project.org/package=Ruchardet) was archived, which broke one of the [tests of the CRAN skeleton](https://github.com/jdblischak/conda-build/blob/9e6bc448090acd118d51872bcb700a504837cd3d/tests/test_api_skeleton.py#L190). This PR replaces Ruchardet with [udpipe](https://cran.r-project.org/package=udpipe).
Thanks to @bilderbuchi for reporting this in PR #3460.

Update test of CRAN license

---

conda_build/utils.py
news/update-filter_files.rst
tests/test_utils.py

Make sure to filter out *.conda_trash files when packaging.
Closes #3455.
@msarahan please review.

Filter out *.conda_trash files when packaging

---

conda_build/jinja_context.py
conda_build/metadata.py

I hit this with conda-concourse-ci and a recipe that used pin_subpackage.  I think it's specific to how c3i does things, but the fix is here.

fix recursion error with subpackages and build_id

---

conda_build/api.py
conda_build/cli/main_build.py
conda_build/cli/main_render.py
conda_build/config.py

This patch introduces a function to reduce duplicate code and makes use
of it in conda_build.api.debug, conda_build.cli.main_render.execute and
conda_build.cli.main_build.execute.
This change makes conda-debug to also honor channels passed with the -c
argument.
Fixes #3433

Introduce conda_build.config.get_channel_urls()

---

README.rst

When I tried to run tests following the README, I encountered some missing dependencies. I found them by looking in the .travis.yml file.

Update list of additional packages required to run tests

---

conda_build/utils.py

This addresses #3475. 
Doesn't seem to cause any more tests to fail than were already failing.

Do not sort files after globbing (fixes 3475)

---

tests/test_api_debug.py

shell_cmd kept getting modified in subsequent calls, leading to test
failures on Windows.

test_api_debug: don't modify global variable

---

docs/source/user-guide/environment-variables.rst

I figured that `37` is probably supported for this environment variable, since Anaconda now ships with python 3.7

Add 37 to list of CONDA_PY

---

conda_build/build.py

The stdlib glob doesn't use recursion (`**`) by default, but utils.glob
does. Note that `**` is only supported since Python 3.5, but since
anything older is already EOL (and because we fall back on glob2 for
Python 2) this isn't a problem.
Closes #3504.

Replace stdlib glob with utils.glob

---

conda_build/index.py

When updating a file in channel with different build time and/or disk size `_calculate_update_set` incorrectly returns a zero length `update_set`.

Fix inconsistency in computation of changed files

---

conda_build/skeletons/cran.py
news/cran_skeleton_win_compilers

Update cran skeleton to use m2w64 compilers for windows instead of toolchain.
The linter is telling since long: Using toolchain directly in this manner is deprecated.
(Instead of updating the liner: https://github.com/conda-forge/conda-smithy/pull/1062)

Update cran skeleton to not use toolchain for win

---

conda_build/skeletons/rpm.py

This seems to already exist in RPMs. So by default will result in the `usr` directory being created again within `usr`, which causes problems for CDTs and anything using them. This fixes that by dropping `usr` from the path.
cc @mingwandroid

Drop `/usr` from CDT skeleton path

---

conda_build/build.py
conda_build/config.py
conda_build/render.py
conda_build/variants.py

For complex build systems that rely heavily on variant specs to produce
and update a large set of packages (such as conda-forge or c3i), it is
useful to have some means of overriding the behavior that is used by
conda render when generating package variants.
Alternatively we could just provide a config value allowing an override for `combined_spec` to be specified at the config level.
cc @msarahan

Split variant parsing function so that users can get an order preserving combined variant spec.

---

conda.recipe/meta.yaml
conda_build/conda_interface.py
setup.py

This PR adds an explicit dependency on `setuptools`, since `pkg_resources` module is a module-level import. I have not added a news entry, since this is a packaging-only change.

Added dependency on setuptools

---

conda_build/skeletons/rpm.py

Follows from the discussion in PR ( https://github.com/conda-forge/staged-recipes/pull/8560 ).
As there is only one output with CDTs, there isn't a need to use `outputs`. To simplify things a bit, this drops `outputs` and updates the CDT recipe to work without it.

Rewrites CDT template without outputs

---

conda_build/skeletons/rpm.py

Drops the vendored `rpm2cpio` script from CDTs. This is no longer needed as `libarchive` handles unpacking `rpm`s into the `SRC_DIR`.
cc @mingwandroid (please recheck in case I missed things)
Fixes https://github.com/conda/conda-build/issues/3492
Closes https://github.com/conda-forge/staged-recipes/issues/8241

Drop rpm2cpio from CDTs as libarchive handles this

---

docs/source/user-guide/environment-variables.rst

As seen [here](https://github.com/conda/conda-build/blob/32a305208ffe53502e3a2bed8e83279da2cb5a5e/conda_build/environ.py#L575), the default `MACOSX_DEPLOYMENT_TARGET` has drifted since this doc was written.

Update MACOSX_DEPLOYMENT_TARGET default value

---

conda_build/metadata.py
conda_build/post.py

LIEF is buggy, but patchelf is buggy. Which to use? You decide (or
fix the bugs).

Add build/rpaths_patcher

---

conda_build/index.py

fix caching using move instead of copy, resulting in missing .conda data

---

conda_build/index.py
conda_build/templates/subdir-index.html.j2
news/fix_html_fnames

Fix issue where filenames and links where missing from the index.html
files created by conda-index.
Adds a SHA256 column which was already being recorded for the extra files.

Fix missing package names in index.html

---

conda_build/environ.py
news/fix-conda-debug

fix conda debug output being suppressed
`config.verbose` is set to `True` if `--debug` is used in https://github.com/conda/conda-build/blob/3.18.6/conda_build/cli/main_build.py#L382. Thus the first `if` condition is `True` when the `elif` condition is `True`, ergo the latter isn't executed.

fix conda debug output being suppressed

---

conda_build/render.py

This PR adds check on `pkg_loc` as explained in the following note privately sent to @msarahan:
<hr>
<p>
In A Travis’s PR job for Pull Request by @ogrisel to daal4py fails with conda build error:
https://github.com/IntelPython/daal4py/pull/111/checks?check_run_id=159357667
Failures manifest itself on Py2 on Linux, and Py 3 on OSX, i.e. work fine on Py3/Linux and Py2/OSX.
The failure happens during rendering of the recipe being built.
The trailing backtrace:
```
File "/home/travis/miniconda/lib/python2.7/site-packages/conda_build/render.py", line 234, in _read_specs_from_package
if not specs and os.path.isfile(pkg_loc):
File "/home/travis/miniconda/lib/python2.7/genericpath.py", line 37, in isfile
st = os.stat(path)
TypeError: coercing to Unicode: need string or buffer, NoneType found
``` …

Fix in render.py::_read_specs_from_package

---

conda_build/utils.py

Merge channeldata from all urls associated with a channel. Previously
only the channeldata from the last url examined was returned.
closes #3610

merge channeldata from all urls

---

conda_build/os_utils/liefldd.py
conda_build/post.py

This pull requests fixes to two cases where warnings/error messages would be printed by the post build checks when nothing was wrong:
- The check on the difference between the results of get_rpath_raw and patchelf in post.py would always fail because a list (get_rpath_raw) was being compared to a str (output from the subproccess call to pathelf). The first one is a fix for issue #3520 
- get_linkages sometimes throws a warning because the function ```inspect_linkages_lief``` doesn't strip trailing path separators from sysroot, but ```inspect_linkages_pyldd``` does. In cases were sysroot has a trailing separator the comparison of the results fail because some of the results from ```inspect_linkages_lief``` would have double separators. This one is a fix for #3539

Fixes spurious post build errors/warning messages

---

conda_build/index.py

Fixes https://github.com/conda/conda-build/issues/3597
We could remove MAX_THREADS_DEFAULT and just use the default constructor for ProcessPoolExecutor if we were always on Python 3.7.4+, but I assume we want this to also work on older python versions :)

Limit threads to 61 on Windows

---

conda_build/cli/main_render.py
conda_build/config.py
conda_build/render.py

Add a --use-channeldata argument which determines if channeldata is used to determine run_exports when rendering (and builds) a recipe.  The default is False which will use run_export information from the packages directly.

add --use-channeldata arg which determines if channeldata is used to find run_exports

---

docs/source/user-guide/tutorials/building-conda-packages.rst
news/docs-remove-bzip2.rst

`docs/source/user-guide/tutorials/building-conda-packages.rst ` mentions `bzip2` as one of the "other tools" of the "building toolkit" but -- in contrast to patch and Git -- does not reference it later anywhere.
For consistency, `bzip2` could/should be removed in that document.
(It is also no "optional dependency" for `conda-build` like `git` and `patch` are, so no hurt in not mentioning it.)
xref: https://github.com/conda-forge/docker-images/pull/103

docs: remove bzip2 package from build toolkit description

---

conda_build/skeletons/cran.py
tests/test_api_skeleton.py

cc @bgruening, @cbrueffer, @daler, @dbast, @dpryan79, @jdblischak, @johanneskoester
For MIT, R packages list the license as `MIT + file LICENSE`. (For eg: https://cran.r-project.org/web/packages/broom/index.html). This is the recommended practice. (For eg: https://cran.r-project.org/web/licenses/MIT)
This PR uses that info.

MIT and BSD in cran skeleton

---

conda_build/index.py

Looks like 60 was the magic number in this case. Was basing it off the python change which uses 61. Not sure where the extra thread comes from. Rather than trying to get this exact though, I figure it's better to have plenty of room to spare.

Actually fix https://github.com/conda/conda-build/issues/3597

---

conda_build/skeletons/cran.py
news/cran_skeleton_match_optional_licenses
tests/test_api_skeleton.py

This is a bit tricky. Ideas welcome to improve it or do it in a different way.
Still I believe, that this gives some skeleton generated recipes a valid license file, which they
currently miss. This is not only helpful for new recipes, but also for existing ones, that get re-generated as part of an update process.
@jdblischak updated the license handling before, maybe you want to take a look.
This can be tested with e.g. r-dt or r-zoo.
Thanks

cran-skeleton: support optional licenses

---

.binstar.yml
.travis.yml
appveyor.yml
ci/travis/run.sh
setup.cfg
tests/test_api_build.py
tests/test_api_build_dll_package.py
tests/test_api_build_go_package.py
tests/test_api_convert.py
tests/test_api_debug.py
tests/test_api_inspect.py
tests/test_api_render.py
tests/test_api_skeleton.py
tests/test_api_test.py
tests/test_cli.py
tests/test_published_examples.py
tests/test_render.py
tests/test_source.py
tests/test_subpackages.py
tests/test_utils.py
tests/test_variants.py
tests/utils.py

Added slow and sanity marks to tests. Some tests are taking too much time to finish and because of that, the CI is failing due to timeout.
The goal of this PR is to separate the tests in three jobs, each job will execute one "type" of tests such as ``slow`` tests, ``sanity`` tests and another one to execute the rest of them

Split tests on CI

---

conda.recipe/meta.yaml
conda_build/cli/main_render.py
tests/test_cli.py

The following command does not behave as expected because `conda render` does not respect both `--file` and `--output` simultaneously.  (If `--output` is present, then `--file` is ignored.)
```
conda render --output --file=rendered-meta.yaml myrecipe > rendered-tarball-name.txt
```
With this PR, both options can be used at the same time.

render: Permit --file and --output to be used simultaneously

---

conda_build/skeletons/cran.py
tests/test_api_skeleton.py

conda skeleton CRAN ignores CRAN's OS_type information (CB-810)

---

conda_build/skeletons/cran.py

While working on the CRAN versioning work I discovered that the `--use-binaries-ver` option wasn't working. This fixes that. And while I was at it I ripped out the use of bs4 for parsing in place of a simple `re.findall`, which speeds things up tremendously.

Fix binary recipe building for cran

---

conda_build/build.py

Fix use of the __version__ on build.py

---

conda_build/skeletons/pypi.py
news/bug-3718-unquote-entries.rst
tests/test_pypi_skeleton.py

Related to #3718 
Quoting only ``version``, ``summary``, ``script`` and ``description`` or attributes which contains special characters.
cc: @ocefpaf

Skeleton pypi quoting only version, summary, script and description

---

conda_build/skeletons/cran.py

Adding support for version selection for `conda skeleton cran`.
To do this, we've replaced the internal index `conda_metadata` with a simpler index `conda_index`. We never used most of the information in `conda_metadata`; it really exists just to provide a lowercase-to-fullycased package map. The new `conda_index` keys are lowercase names of packages as before, and the values are `(name, version)` pairs, where `name` is the fully-cased package name, and `version` is the active version of the package. What is important is that _archived_ packages are included in this list, with `version = None`. Because the `PACKAGES` file does not include information about archived packages or older versions, this index is constructed by scraping the HTML from `/src/contrib/` and `/src/contrib/Archive`. …

Version support for CRAN skeleton

---

.travis.yml
README.rst
appveyor.yml
azure-pipelines.yml
conda.recipe/meta.yaml

It appears that python-libarchive-c was previously being pulled in as a transitive dependency during CI test runs, but is not longer being implicitly installed in the test environment. 
Adds python-libarchive-c, which is a hard requirement for conda-build, into the conda recipe run requirements, matching the existing dependency specified in setup.py.

Add python-libarchive-c to package and CI dependencies.

---

.travis.yml
README.rst
appveyor.yml
azure-pipelines.yml
conda.recipe/meta.yaml
conda_build/build.py
conda_build/utils.py
news/pkg_2_build.rst
tests/test_api_build_conda_v2.py

Fix pkg_format 2 (.conda) package builds.

---

docs/source/resources/define-metadata.rst

Add short section about requirements.run_constrained to define-metadata.rst
fixes #3739

Document run_constrained

---

conda_build/metadata.py
news/add-more-info-to-error.rst

Related to #3544 I think.
Was creating a new recipe using the `staged-recipes` template. Had already created one, so was doing it faster this time as I needed to go to a meeting.
Unfortunately whenever you are in a hurry you make simple mistakes. I copied everything similar to the other recipe, but did not notice that I had used the dependency version from the project `setup.py` without translating to what conda expects.
I used `- graphql-core >=2.0<3` while it should be `- graphql-core >=2.0,<3`. But haste never helps to spot issues like this. It exited the process with exit code `1`, and the following message:
```bash
$ conda build .
Adding in variants from internal_defaults
INFO:conda_build.variants:Adding in variants from internal_defaults
Received dictionary as spec.  Note that pip …
```

Add more information to error about pip version usage

---

conda_build/metadata.py
tests/test-recipes/split-packages/_extra_metadata/meta.yaml

Adding it here should also avoid some lint that I'm [running into]( https://github.com/conda-forge/ucx-split-feedstock/pull/14#issuecomment-533550603 ).

Add `extra` to `outputs` in `FIELDS`

---

conda_build/build.py

In [`create_info_files`](https://github.com/conda/conda-build/blob/3.18.9/conda_build/build.py#L696-L698), it normalized the file paths into backward slash on Windows. However, the `rg` still outputs the path in forward slash, and the mismatch causes the logic not able to identify the files to patch around the following code block:
https://github.com/conda/conda-build/blob/3.18.9/conda_build/build.py#L213-L217
This fixes #3348.

Fix has_prefix detection for Windows.

---

docs/source/resources/define-metadata.rst
news/doc_sub_pkg.rst

This PR corrects the documentation for subpackage test requirements. 
Closes #3777

DOC update docs for subpackage tests

---

conda_build/utils.py

fixes an issue with `tar_xf` util function where if an archive has mixed capitalization it may be missed while in the rest of the utils folder the call to .lower() resolves the issue.

fixed a missing .lower() on two tar_xf related util functions

---

docs/source/resources/variants.rst

fix missing "}}" in docs

---

conda_build/inspect_pkg.py

This PR optimises `conda_build.inspec_pkg.which_package()` by only compiling the `fnmatch` once (rather than once per file per package), which significantly speeds up link checking for packages that produce large numbers of binary files.
I'm not sure if this merits a news item, since it doesn't modify any interfaces.
Some timing info. Old:
```
(base) $ python -m timeit -s "import sys; from conda_build.inspect_pkg import which_package" "print(list(which_package('bin/python', sys.prefix)))"
[Dist(channel='conda-forge', dist_name='python-3.7.3-h0d93f26_0', name='python', fmt='.tar.bz2', version='3.7.3', build_string='h0d93f26_0', build_number=0, base_url=None, platform=None)]
[Dist(channel='conda-forge', dist_name='python-3.7.3-h0d93f26_0', name='python', fmt='.tar.bz2', version='3.7.3', …
```

Optimise use of fnmatch in which_package()

---

conda_build/build.py

Under some special conditions, for example installing miniconda in a folder that contains `.gitignore`, behavior of ripgrep can change during builds.
Adding the `--unrestricted` flag avoids this.
```
-u, --unrestricted                      
Reduce the level of "smart" searching. A single -u won't respect .gitignore
(etc.) files. Two -u flags will additionally search hidden files and
directories. Three -u flags will additionally search binary files.
'rg -uuu' is roughly equivalent to 'grep -r'.
```

Do not consider .ignore files when searching with ripgrep

---

azure-pipelines.yml
conda_build/build.py
conda_build/skeletons/cpan.py
conda_build/skeletons/cran.py
conda_build/skeletons/luarocks.py
conda_build/skeletons/rpm.py
news/skeleton_build_sh_shellcheck_clean.rst
tests/test_api_skeleton.py

This is done in context of https://github.com/conda-forge/conda-smithy/pull/1122 where the conda-forge linter is learning shellcheck, potentially activated for new recipes brought via conda-forge/staged-recipes or later also for updates of existing recipes. By reducing the findings in the existing skeletons the linter will then only have findings in custom added code.
This is all done in 4 steps:
1. Make the already applied `errexit` bash setting more explicit by 1. turning it from the short form `-e` into the long form `-o errexit` and 2. by adding it also to the build.sh files itself. The last steps may seem redundant, but is important to provide `shellcheck` the information under which settings the build.sh script is actually running (that changes the required error handling). Also the …

Make build.sh files of skeletons shellcheck clean

---

conda.recipe/meta.yaml

Looks like `requests` is listed as a dependency in `setup.py`, but not in the Conda recipe. Plus it appears to be used in the recipe skeleton code like [for PyPI generated recipes]( https://github.com/conda/conda-build/blob/0799ec813a883c274420f9b70277c74d5b25437b/conda_build/skeletons/pypi.py#L22-L23 ). So this adds the requirement to the recipe here as well.
Note: This is [implicitly a requirement from Conda]( https://github.com/conda/conda/blob/e5407fb0cd7e013db01417c32e3822bd0857e427/conda.recipe/meta.yaml#L45 ), but it's worth making it explicit.

Make the requirement of `requests` explicit

---

conda_build/inspect_pkg.py
conda_build/post.py

In #3686 `fnmatch` was used to improve the handling paths of case insensitive filesystems. I think this is buggy as files containing `*`/`?`/`[something]` will now be matched dynamically instead of literally. See https://github.com/conda/conda-build/pull/3782#discussion_r337590375 for more details.
This changes the matching to be equivalent to `normcase(a) == normcase(b)` instead. The performance is much better than `fnmatch` and completely negligible on case sensitive filesystems.

Use normpath instead of fnmatch where appropriate

---

conda_build/noarch_python.py

The noarch check for binary scripts uses the locale preferred encoding to guess if the script is binary or text based.
On some CI systems, (e.g. gitlab continuous integration using the `conda/miniconda3` docker image), the default encoding is ascii (expressed as "ANSI_X3.4-1968").
In general, in any system with an ascii default encoding conda assumes "if it is not ascii then it is binary". I argue it makes more sense to say "if it is not utf-8 then it is binary". Since ascii is a subset of UTF-8, we will reduce the false positives with this change.
Other encodings are not affected by this.

On ASCII locales, allow UTF-8 text in scripts

---

docs/source/resources/define-metadata.rst

- Is the heading of "Whitelisting shared libraries" correct? What should it be?
- What is the background/value/purpose of these two keys? 
- What are the example values that we should show in the code blocks?

Added whitelist info to build section

---

conda_build/build.py
conda_build/inspect_pkg.py
conda_build/metadata.py
conda_build/os_utils/external.py
conda_build/os_utils/macho.py
conda_build/post.py

Some trivial fixes and Xcode avoidance (preferring our tools if found, in build prefix or base env) also warn about Apple's stub exes

---

azure-pipelines.yml
ci/azurepipelines/activate_conda
ci/azurepipelines/run_conda_forge_build_setup_osx
conda_build/build.py
conda_build/os_utils/external.py
conda_build/os_utils/macho.py
conda_build/post.py

Macos azure

---

azure-pipelines.yml
tests/test_api_skeleton.py
tests/test_cli.py

Add [pytest-replay](https://github.com/ESSS/pytest-replay/) to help us to investigate when a test suddenly fails on CI, which might be related to some race condition. Thereby, we will be able to see which tests were running in parallel.
The only problem here is, the output of ``pytest-replay`` is different between version lower than ``1.0.0`` and versions greater or equal then ``1.0.0`` are available just for Python 3+. 
The release ``1.2.0`` added more information to the output, such as the time which the test started and finished, outcome and node id. Nonetheless, older versions just list the order of the tests which were executed by each worker.
https://github.com/ESSS/pytest-replay/#features

Add pytest-replay and pytest-rerunfailures

---

conda_build/skeletons/cran.py

This implements an `--allow-archived` argument for `conda skeleton cran`. When selected, it will build a recipe for the latest version of an archived package instead of failing. For instance, `conda will return the error
```
ERROR: Package graph is archived; to build, use --allow-archived or supply a --version value
```
but will succeed if `conda skeleton cran graph --allow-archived` is used.
As the error message implies, it will also work to supply an explicit version; e.g., `conda skeleton cran graph --version 1.30.0`. This is already working in master; the error message has simply been adjusted to include the `--allow-archived` option.

Fetch the latest CRAN archived version if requested

---

docs/source/resources/define-metadata.rst

This PR replaces a dead hard-coded link to "Package match specifications" with a cross-reference pointed at the desired target.

Fix dead link in docs.

---

conda_build/index.py
news/index-atomic-write.rst

Prevent non-atomic writes to repodata JSON files

---

conda_build/create_test.py

Fix for globbing test files on Windows

---

conda_build/build.py
tests/test-recipes/metadata/binary_has_prefix_files_list/bld.bat
tests/test-recipes/metadata/binary_has_prefix_files_list/build.sh
tests/test-recipes/metadata/binary_has_prefix_files_list/meta.yaml
tests/test-recipes/metadata/binary_has_prefix_files_list/run_test.sh
tests/test-recipes/metadata/binary_has_prefix_files_list/write_binary_has_prefix.py

If specified as a list, then only those files in that list are
considered eligible for binary prefix replacement.

Change behaviour of build/binary_has_prefix_files

---

conda_build/metadata.py

Keep python pinning in hashing if there's a space

---

conda_build/post.py

Use patchelf by default

---

docs/source/concepts/recipe.rst
news/clarify_rm_build_env_in_recipe_concepts.rst

I don't see anywhere in the docs where it is explained why the SOURCE_DIR, and build/host environments are deleted at the beginning of test phase (or in between build and test phase).  This commit captures that reasoning so that I can point here for new people learning about conda-build.

Clarify 'deletes the build env' in concepts/recipe

---

conda_build/post.py
news/dont-fix-macho-files-on-other-platforms.rst

As found in https://github.com/conda-forge/cmake-feedstock/pull/115#issuecomment-603472268 the Linux CMake build produces a Mach-O binary which then triggers this assertion and causes the build to fail.
This is a regression in 3.18 as this function used to never be called on other platforms: https://github.com/conda/conda-build/pull/3808/files#diff-60400bbbdb51124a0a8a06ca17ecec5cL1105
cc @jakirkham

Ignore patching Mach-O files if not running on macOS

---

conda_build/post.py
news/fix_ignore_macho.rst

Load the logger prior to calling the warn method.  Adjust indentation to match the module's style.

load log prior to calling in post.py

---

conda_build/metadata.py

This PR corrects a typo from 7fdaff4e96be98e9656786378cd4930f87226450 (#3762) by replacing `error-over{depending,linking}` with `error_over{depending,linking}`.

Fixed typos in FIELDS list

---

conda_build/skeletons/cran.py

See details in #3943. Currently, recipes generated with `conda skeleton cran` result in a linter note from `conda-forge-linter`. This PR proposes a fix to prevent the linter.

[R] add spaces in CRAN templates (fixes #3943)

---

azure-pipelines.yml
setup.py

Enable Python 3.8 on Azure Pipelines

---

azure-pipelines.yml
conda_build/api.py
conda_build/build.py
conda_build/cli/main_build.py
conda_build/config.py
conda_build/index.py
conda_build/inspect_pkg.py
conda_build/os_utils/ldd.py
conda_build/os_utils/liefldd.py
conda_build/os_utils/macho.py
conda_build/os_utils/pyldd.py
conda_build/post.py
conda_build/source.py
conda_build/utils.py
tests/test-recipes/metadata/entry_points_have_prefix_noarch_has_prefix_files/meta.yaml
tests/test-recipes/metadata/entry_points_have_prefix_noarch_has_prefix_files/run_test.bat
tests/test-recipes/metadata/entry_points_have_prefix_noarch_has_prefix_files/setup.py
tests/test-recipes/metadata/has_prefix_files/build.sh
tests/test-recipes/metadata/has_prefix_files/run_test.py
tests/test_api_skeleton.py

12 3.19.4 bits

---

conda_build/index.py
tests/index_data/.gitignore

This PR makes sure that packages in the current repo data which have features also have version without features. This change makes sure that feature minimization works.
cc @isuruf @jjhelmus

ENH make sure packages in current repo data w/ features have versions without features

---

tests/test-recipes/metadata/_binary_has_utf_non_8/bld.bat
tests/test-recipes/metadata/_binary_has_utf_non_8/build.sh
tests/test-recipes/metadata/_binary_has_utf_non_8/meta.yaml
tests/test-recipes/metadata/_binary_has_utf_non_8/run_test.py
tests/test-recipes/metadata/_binary_has_utf_non_8/write_binary_has_prefix.py
tests/test_api_build.py

Adds tests for binary files that contain many charsets, utf16 and utf32
xref: https://github.com/conda/conda/pull/9946
xref: https://github.com/conda/conda/issues/4298

Add tests for non-utf-8 charsets

---

docs/source/user-guide/tutorials/build-pkgs.rst

I recently got tripped by following the tutorial as a base for a new package, without realising local installs don't evaluate runtime dependencies of the given package. Make a note to point users to the snippet from `conda install --help` or the install reference doc.
```
conda can also be called with a list of explicit conda package filenames
(e.g. ./lxml-3.2.0-py27_0.tar.bz2). Using conda in this mode implies the
--no-deps option, and should likewise be used with great caution. Explicit
filenames and package specifications cannot be mixed in a single command.
```
This is also highlighted in the Anconda [docs](https://docs.anaconda.com/anaconda/user-guide/tasks/install-packages/#installing-packages-on-a-non-networked-air-gapped-computer) for `install`

tutorials/build-pkgs.rst: Add note for local package install deps

---

conda_build/post.py

Fix relocation when cross compiling

---

CHANGELOG.txt
conda_build/skeletons/pypi.py

Allow python=3.8 for pypi skeletons

---

conda_build/exceptions.py
news/fix-parsing-UnsatisfiableError.rst

This has been broken since
https://github.com/conda/conda/commit/1dff3526c2ca2574a56e2352d7b8de86441fbd8b#diff-1f2230f9e987e7b066381cf7e00e9d21R697

Fix parsing UnsatisfiableError from conda>=4.7.8

---

conda_build/environ.py
conda_build/metadata.py

Set build_platform for aid in cross compiling

---

conda_build/environ.py

Fix noarch get_shlib_ext for osx

---

README.rst

To use 'root' as an env is a bit confusing, given that it invokes suggestions of admin rights on Unix, and the whole point of conda is to avoid using the system libraries. 
Here making clear that 'root' is just a name.

Clarify usage

---

conda_build/source.py
news/hash-check.rst

I forgot to enter an sha256 hash in an input file, but left had the field there. I found the error uninformative (copied below), so added a check to raise a more helpful exception.
```
File "/home/conda/.ci_support/build_all.py", line 133, in <module>
build_all(args.recipes_dir, args.arch)
File "/home/conda/.ci_support/build_all.py", line 66, in build_all
build_folders(recipes_dir, new_comp_folders, arch, channel_urls)
File "/home/conda/.ci_support/build_all.py", line 123, in build_folders
conda_build.api.build([recipe], config=get_config(arch, channel_urls))
File "/opt/conda/lib/python3.7/site-packages/conda_build/api.py", line 209, in build
notest=notest, need_source_download=need_source_download, variants=variants)
File …
```

More helpful error message if an empty hash field is given

---

bdist_conda.py
docs/source/user-guide/environment-variables.rst
docs/source/user-guide/recipes/build-without-recipe.rst

Leave code intact, but no docs
Mutex metapackages are the documented preferred approach: https://docs.conda.io/projects/conda/en/latest/user-guide/concepts/packages.html#mutex-metapackages

remove docs on features from bdist_conda and env vars

---

conda_build/build.py
conda_build/utils.py

Rename ccache method from mklink to symlinks

---

conda_build/environ.py
conda_build/jinja_context.py

- Treat linux-s390x platform similar to linux-ppc64le,linux-aarch64
- Similar to PR https://github.com/conda/conda-build/pull/3357

cdt fix for linux-s390x

---

conda_build/variants.py
news/remove-default-variants-sysroot

In https://github.com/conda/conda-build/commit/8a326413e1f7fc2441a9668027977ecb2e2fdfe0#diff-593f4997b372b8d4a4fe630de1e497adR36 a hard-coded path was added as a default value for `CONDA_BUILD_SYSROOT`.
The commit message from that commit is
> Set CONDA_BUILD_SYSROOT during tests to /opt/MacOSX10.10.sdk 
. So, supposedly, this also wasn't meant to be added as a general default value, but just for tests.
If it is still needed to be set for some tests, feel free to add it to the appropriate place and commit to this branch (meaning, "Allow edits from maintainers." is enabled).

variants: remove hard-coded default path for CONDA_BUILD_SYSROOT

---

conda_build/build.py

`build.sh` is run with `-e`, but scripts in outputs are not. This commit fixes that.

Run bash with -e in outputs too

---

conda_build/os_utils/liefldd.py
conda_build/post.py

Master overlinking fixes post 3.20.0

---

conda_build/post.py
news/linking_tbd.rst

Fix post.py when SDK has install names surrounded by single qoutes

---

conda_build/api.py
conda_build/utils.py
tests/test_api_build.py
tests/test_utils.py

- Both `conda_build.api.build` and `conda_build.utils.find_recipe` perform checks for *.AppleDouble* and `os.path.isfile`, removed checks from former and rely on `IOErrors` raised in latter.
- Extracted a constant `VALID_METAS` that contains all valid conda recipe meta filenames (I went ahead and included the option to specify both `.yaml` or `.yml` extensions, I understand this doesn't make this possible to use these alternative extensions yet as `meta.yaml` is still hardcoded in a number of places).
- Updated `conda_build.utils.rec_glob` to include the option to pass in an `ignores` argument which removes directories we do not wish to traverse (this simplifies ignoring *.AppleDouble*).
- Updated `conda_build.utils.find_recipe` to better check for base level meta files and ensured that …

Refactor recipe search & conda_build.api.build

---

conda_build/metadata.py

cc @chenghlee, @jjhelmus, @msarahan, @beckermr 
Note that this will change the hash for all packages and people relying on skipping existing builds might not like this.

Include target_platform in hash

---

conda_build/source.py

Closes #4061 
cc @mingwandroid @jjhelmus

ENH raise runtimeerror instead of calling sys.exit

---

conda_build/api.py
conda_build/build.py
conda_build/cli/main_debug.py
conda_build/index.py
conda_build/render.py
conda_build/utils.py

I see that `conda` switched from using `CONDA_TARBALL_EXTENSIONS` to `CONDA_PACKAGE_EXTENSIONS` over a year ago.
This change doesn't alter anything in `conda_build` beyond renaming the old `CONDA_TARBALL_EXTENSIONS` variables and removing duplicate code.

Switch to using CONDA_PACKAGE_EXTENSIONS

---

conda_build/build.py

Refactor to make code readable and to remove duplicate logic. Also removed what appears to be debugging print statements that are no longer in use.

Refactor conda_build.build.get_all_replacements

---

conda_build/metadata.py

Looks like this was disabled in https://github.com/conda/conda-build/commit/c546a3b2a9a04cefe67afa3f4ed4ad7041ece519
because conda used to symlink itself into each conda environment. conda doesn't do this anymore, so it's
safe to disable this now.

Activate the environments even when building conda

---

conda_build/build.py
conda_build/utils.py

`seconds_to_text` belongs in `utils` following the prior precedent set by `bytes2human`. Minor cleanup of select prints to make more readable and reworked several text blocks that were preventing proper code folding.
I'm aware that the styling of multiline test blocks is highly opinionated, I picked this style as it doesn't require any additional imports (e.g. `textwrap.dedent`) and is a style already in use elsewhere in conda-build. Let me know if a different style is preferred.

seconds2human

---

conda_build/utils.py
conda_build/variants.py
tests/test_variants.py

Refactor code to eliminate overly verbose and complex code. 6-12 times faster implementation.
I sought to eliminate a number of private helper functions that did not aid in simplifying the code. I also ended up adding a new function `conda_build.utils.islist` which we may find valuable to use elsewhere.
Yes, I like using list/dictionary comprehension and when formatted properly I believe they are easier to read - I totally understand how subjective this is so let me know if you disagree and want it coded differently.
I personally wish to rename `dict_of_lists_to_lists_of_dict` to `expand_variants` (and `lists_of_dict_to_dict_of_lists` to `collapse_spec`) in order to make the functions more self documented as well as making them less of a mouthful. @mingwandroid what do you think? I have …

Refactor dict_of_lists_to_lists_of_dict

---

conda_build/api.py
conda_build/cli/main_index.py
conda_build/index.py
tests/test_index.py

This allows a user to pass a new line separated file into `conda index` using the `-f, --file` flag. This will allow a user to pass in a list of packages to be considered for index instead of looking at all of the packages on the file system.

index by file

---

conda_build/os_utils/macho.py
conda_build/post.py

Remove old rpath when loader_path is used

---

conda_build/environ.py

Fix MACOSX_DEPLOYMENT_TARGET default for osx-arm64

---

conda_build/utils.py
conda_build/variants.py

Introduce new private functions for extracting special types of keys from `spec`. Otherwise, revert to explode terminology used prior to #4075.
This is an attempt to split PR #4079 into smaller changes.

Helper functions to extract keys

---

conda_build/render.py

`requirements/host` might get deleted in the resulting package and conda-build will assume `merge_build_host==True` in that case

Don't trim empty keys

---

conda_build/metadata.py

Follow up to https://github.com/conda/conda-build/pull/4065

force target_platform as used when not noarch

---

conda_build/skeletons/pypi.py
tests/test_cli.py

.. we expand this to >=X.Y.Z,==X.Y.* as per the PEP
Test with openshift which uses 'Compatible release' specs
Add commented out code to compare with conda-build's old
handling of this which differed:
`kubernetes >=11.0.0,<11.1 vs kubernetes >=11.0.0,==11.0.*`

Respect PEP440 ~= 'Compatible release clause'

---

conda_build/metadata.py
news/gh-4124-info_index-host_platform.rst
tests/test-recipes/metadata/_cross_build_unix_windows/conda_build_config.yaml
tests/test-recipes/metadata/_cross_build_unix_windows/meta.yaml
tests/test_api_render.py

If we cross-build on different platforms and not just different architectures of the same platform, the `platform` key in `index.json` is not set to the target platform.
refs:
- https://gitter.im/conda-forge/conda-forge.github.io?at=5faa7d4b8a236947ba9813eb
> I'm having an odd upload issue at https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=237099 .
> The build went fine and uploads for `linux-64` and `osx-64` were successful. But the `win-64` one does not upload (restarted once).
> There is one peculiarity I did: The `win-64` one is built on `linux-64` -- but that shouldn't cause any issues, shouldn't it? (Given that we upload `osx-arm64` packages built from `osx-64`.)
- https://gitter.im/conda-forge/conda-forge.github.io?at=5faad739c6fe0131d4e912df
> I got it:
> …

Fix index.json:"platform" in cross-platform builds

---

conda_build/render.py
conda_build/utils.py
docs/source/resources/define-metadata.rst
news/gh-4125-run_exports-constains.rst
tests/test-recipes/metadata/_run_exports_constrains/meta.yaml
tests/test_api_build.py

@isuruf, is this what you had in mind for adding `constrains: ['__glibc >=2.17']` automatically from, e.g., `sysroot_linux-64`?

Add *_constrains run_export types

---

conda_build/os_utils/liefldd.py
conda_build/post.py
news/gh-4131-split-patchelf-rpath.rst

Reduce amount of warnings like
https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=235715&view=logs&j=656edd35-690f-5c53-9ba3-09c10d0bea97&t=e5c8ab1d-8ff9-5cae-b332-e15ae582ed2d&l=715
> WARNING :: get_rpaths_raw()=['/home/conda/feedstock_root/build_artifacts/slirp4netns_1604525000330/_build_env/lib:/home/conda/feedstock_root/build_artifacts/slirp4netns_1604525000330/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib'] and patchelf=[['/home/conda/feedstock_root/build_artifacts/slirp4netns_1604525000330/_build_env/lib', '/home/conda/feedstock_root/build_artifacts/slirp4netns_1604525000330/_h_env_placehold_placehold_placehold_placeho …

Reduce get_rpaths_raw/patchelf disagree warnings

---

README.rst

This error occurs without `flaky`:
```
==== test session starts ====
platform linux -- Python 3.8.0, pytest-6.1.2, py-1.9.0, pluggy-0.13.1
rootdir: [...]/conda-build/conda-build, configfile: setup.cfg
plugins: cov-2.10.1, mock-3.3.1
collected 558 items / 1 error / 557 selected                                                                                                                           
==== ERRORS =====
____ ERROR collecting tests/test_api_skeleton.py ____
'flaky' not found in `markers` configuration option
==== warnings summary ====
```

Add flaky to testing dependencies

---

conda_build/build.py
news/fix-auth-in-aboutjson.rst
tests/test_build.py

Closes #3991 
This uses the Channel class from conda to sanitize the channel url, instead of relying on a regular expression.
This does mean that the channel format in `about.json` now is different. E.g. see these test urls:
```
https://conda.anaconda.org/t/ms-534991f2-4123-473a-b512-42025291b927/somechannel
https://myuser:mypass@conda.anaconda.org/somechannel
```
Previously these would become
```
https://conda.anaconda.org/t/<TOKEN>/somechannel
https://myuser:mypass@conda.anaconda.org/somechannel
```
Now they are both
```
https://conda.anaconda.org/somechannel
https://conda.anaconda.org/somechannel
```
This is better, because
* it is standardized with how conda itself does things
* it should not matter how the channel is authenticated.
[Edit: removed something about clahub.com being …

Fix auth in aboutjson

---

conda_build/os_utils/liefldd.py

LIEF: Allow parsing static libs to fail

---

azure-pipelines.yml
conda_build/convert.py
conda_build/license_family.py
conda_build/metadata.py
conda_build/os_utils/liefldd.py
conda_build/post.py
conda_build/skeletons/cran.py
conda_build/skeletons/pypi.py
conda_build/skeletons/rpm.py
conda_build/utils.py
conda_build/windows.py
news/gh-4154-ci-fixes.rst
tests/test_api_build.py
tests/test_api_consistency.py
tests/test_api_skeleton.py

This updates the RPM skeleton URLs for CentOS 6 to use `http://vault.centos.org` (the previous ones aren't valid anymore due to CentOS 6(.10)'s EOL).
Also has some small test/CI fixes.

Fix skeleton URLs for CentOS 6 (EOL) and various CI fixes

---

conda_build/build.py
docs/source/resources/define-metadata.rst
news/gh-4153-license_file-dir.rst
tests/test-recipes/metadata/_about_license_file/recipes/dir-no-slash-suffix/license-dir-from-recipe/first-license.txt
tests/test-recipes/metadata/_about_license_file/recipes/dir-no-slash-suffix/license-dir-from-recipe/second-license.txt
tests/test-recipes/metadata/_about_license_file/recipes/dir-no-slash-suffix/meta.yaml
tests/test-recipes/metadata/_about_license_file/recipes/dir/license-dir-from-recipe/first-license.txt
tests/test-recipes/metadata/_about_license_file/recipes/dir/license-dir-from-recipe/second-license.txt
tests/test-recipes/metadata/_about_license_file/recipes/dir/meta.yaml
tests/test-recipes/metadata/_about_license_file/recipes/list/license-from-recipe.txt
tests/test-recipes/metadata/_about_license_file/recipes/list/meta.yaml
tests/test-recipes/metadata/_about_license_file/recipes/single/meta.yaml
tests/test-recipes/metadata/_about_license_file/source/license-dir-from-source/first-license.txt
tests/test-recipes/metadata/_about_license_file/source/license-dir-from-source/second-license.txt
tests/test-recipes/metadata/_about_license_file/source/license-from-source.txt
tests/test_api_build.py

Allow directories as license_file source

---

conda_build/source.py
news/gh-4118-bytes-like-no-str.rst

When rendering I see a stream of errors this seems to fix the problem:
```
write() argument must be str, not bytes
write() argument must be str, not bytes
write() argument must be str, not bytes
write() argument must be str, not bytes
write() argument must be str, not bytes
write() argument must be str, not bytes
write() argument must be str, not bytes
write() argument must be str, not bytes
write() argument must be str, not bytes
```
I think this fixes https://github.com/conda/conda-build/issues/4118.

Fix "write() argument must be str, not bytes" error

---

conda_build/environ.py
conda_build/metadata.py
conda_build/utils.py

In order to decrease duplicate code and to make the build_number method "smarter" we explicitly check for falsy build numbers and otherwise raise a ValueError for otherwise bad values (e.g. "abba").
Resolves #4146

Smarter build_numbers

---

conda_build/environ.py
docs/source/resources/define-metadata.rst
docs/source/user-guide/environment-variables.rst

Fixes setting values in `build/script_env` containing `=` and add docs for this feature.

Document build/script_env and support setting values containing "="

---

conda_build/cli/main_debug.py

I did not experience any bug but while checking the code I stumbled across that typo. I am pretty sure its meant to be ".bat"...

Typo in conda-debug

---

setup.py

As conda-build dropped support for Python 2.7, this PR is just to remove the classifiers from the ``setup.py``

Update setup py

---

conda_build/render.py
conda_build/utils.py

This reverts commit 264663da57afe2c7960376032460966e4d5be1f1.
Fixes #4219 as we don't know what the initial reasoning for this change was but it is breaking one of the dependencies of conda-build itself.

Revert "Consider any file containing .yaml in its name as maybe a recipe file"

---

conda_build/utils.py
docs/source/resources/variants.rst
news/gh-4272-Fix-pinning-expressions-for-prerelease-builds.rst
tests/test-recipes/metadata/_pinning_prerelease/conda_build_config.yaml
tests/test-recipes/metadata/_pinning_prerelease/meta.yaml
tests/test-recipes/metadata/_pinning_prerelease_python/conda_build_config.yaml
tests/test-recipes/metadata/_pinning_prerelease_python/meta.yaml
tests/test_api_build.py
tests/test_api_render.py

Fix pinning expressions for prerelease builds

---

conda_build/metadata.py
news/circular-deps-cross-compile.rst
tests/test-recipes/split-packages/_circular_deps_cross/conda_build_config.yaml
tests/test-recipes/split-packages/_circular_deps_cross/meta.yaml
tests/test_subpackages.py

When cross compiling, build dependencies are coming from already
built packages and cannot be subpackages from the same recipe.
This is similar to https://github.com/conda/conda-build/pull/4011

Don't check build for circular dependencies when cross compiling

---

docs/source/resources/define-metadata.rst

Small documentation fix regarding the Jinja example for `resolved_packages('host')`. The template code occurs only in the `run` section and not in the `host` section. So the `host` section should not change by the rendering.

Fix Jinja render example for resolved_packages

---

conda_build/skeletons/cran.py
news/cran-skeleton-tests.rst
tests/test-cran-skeleton/rpart/DESCRIPTION
tests/test_api_skeleton.py
tests/test_api_skeleton_cran.py
tests/test_cran_skeleton.py

I've found it difficult to work on the CRAN skeleton because its unit tests are in `tests/test_api_skeleton.py`, which for me takes about 45 minutes to run the entire file. It also has lots of errors and warnings, which make it difficult to quickly see if I've broken anything new.
This PR does 2 things:
1. It moves the existing CRAN skeleton tests in `test_api_skeleton.py` to `test_api_skeleton_cran.py`. Now `test_api_skeleton_cran.py` completes in ~90 seconds without errors
2. I created a new file `test_cran_skeleton.py` for quick unit tests. It was inspired by `test_pypi_skeleton.py`. It purposefully avoids downloading any internet resources so that it can run as quickly as possible. It completes in under a second without errors
I also confirmed that both test files pass flake8.
@dbast …

More unit tests for CRAN skeleton

---

conda_build/skeletons/cpan.py

- Fix new shellcheck [SC2292](https://github.com/koalaman/shellcheck/wiki/SC2292).

Get CI to build again

---

conda_build/config.py
news/rebuild_id_mismatch.rst
tests/test_config.py

#4167 changed the way `compute_build_id` was computed to be based on the package name. However, it also made the assumption that the old `work_dir` would be equal to `{croot}/{package name}/work` which is not true if someone manually passes in a `croot` and a `build_id` to the `Config` constructor; either manually or as a pass through on `api.render`.
The result was old work would be lost if the original `work_dir` did not match the specific string, instead of just looking where the original work_dir was. This PR fixes the bug and adds a test to make sure the work is preserved and correctly moved to the new folder.
This is a very niche edge case found when directly using the API at omnia-md/conda-dev-recipes#212

Fix keeping old work when workdir does not match package name

---

CONTRIBUTING.md
README.rst

In the interest of making information more digestible for potential contributors and also to mirror the [`conda` ](https://github.com/conda/conda)repo more closely, this PR separates out the contributor/testing-related information into a separate `.md` file.

Separate Contributor-Related Documentation Into Dedicated File

---

.pre-commit-config.yaml

pyupgrade was applied before, so adding it to pre-commit does nothing, except for newly added code to be upgraded.
Also exclude versioneer.py as it is a vendored file.

[RFC] Add pyupgrade via pre-commit

---

.github/workflows/tests.yml

Connecting issue https://github.com/conda/conda-build/issues/4386

[WIP] Migrating Windows Tests from Azure Pipeline to GitHub Actions

---

.github/workflows/tests.yml
tests/test_api_build.py
tests/test_api_render.py
tests/test_conda_interface.py
tests/test_subpackages.py

Adding Windows to Github Actions for tests.

Run Tests Against Windows in GitHub Actions

---

conda_build/skeletons/pypi.py

For the reasons pointed out in https://github.com/conda/conda-build/pull/4412#issuecomment-1098972719.
closes https://github.com/conda/conda-build/issues/4354

workaround for #4354 - patch the vendored distutils.core too

---

conda_build/metadata.py

This appears to be usable in recipes and [covered in the tests]( https://github.com/conda/conda-build/blob/3b99b2222a067e113a2282926871cd1e5406ee2b/tests/test-recipes/split-packages/_entry_points/meta.yaml#L19-L22 ). So add it to `FIELDS`.

Add `entry_points` to `outputs` in `FIELDS`

---

conda_build/_load_setup_py_data.py
tests/test_jinja_context.py

Fixes https://github.com/conda/conda-build/issues/4428
This fixes the deprecation warning raised by Setuptools when using `load_setup_py_data` in recipes. Also fixes a similar issue in the tests.
It is worth noting that Setuptools status this provisional module `setupcfg` may go away in the future. So we may need another solution for when that happens. Though it is unclear atm what that would be.

Support Setuptools 61.0.0+

---

conda_build/index.py

This should avoid one syscall per directory entry for the (modest) `channel_root` listing.

use scandir() to avoid separate is_dir() syscall

---

ci/github/run_conda_forge_build_setup_osx
conda_build/post.py
news/rpaths.rst
tests/test-recipes/metadata/_clean_rpaths/meta.yaml
tests/test_api_build.py

And also remove any rpaths in PREFIX/../ that doesn't start with PREFIX.
This remove rpaths in BUILD_PREFIX, SRC_DIR, etc

Remove rpaths that occur multiple times

---

tests/test_api_build.py

SDK tools in MacOS runners are now set up properly, which means we can remove some `xfail` markers!

Remove `xfail` Markers from MacOS CI Tests

---

conda_build/index.py

speeds conda index when the number of unchanged packages is large

use set for membership queries

---

.github/workflows/tests.yml

This follows the practice we've used in conda that auto-cancels builds on repeated pushes to the repo, which is even more important for conda-build given its runtime.

Add concurrency rules for GitHub Actions.

---

.github/workflows/tests.yml
CONTRIBUTING.md
tests/conftest.py

pytest dropped the dot as in `py.test` already a couple of years ago.

Fix spelling of pytest

---

conda_build/build.py
conda_build/cli/main_build.py
conda_build/config.py
news/compression_tuple.rst

I keep finding myself needing to build an extremely large package (many gigabytes) which causes zstandard to use an excessive amount of memory when used in combination with `level=22`. Even when it works I've seen `level=22` an hour when `level=1` takes ~10 seconds which is worthwhile when debugging and not deploying the packages. (I actually wonder if a lower level by default would be more appropriate to make installations faster but that's a separate question.)
As this is configurable behind the scenes I think it would be good to expose the option to the CLI.
Any thoughts?

Add CLI option for changing the compression settings

---

conda.recipe/meta.yaml
conda_build/exceptions.py
conda_build/source.py
news/4495-patch-hard-dependency
tests/test_patch.py

While doing the recent conda-build 3.21.9 release (#4483) we noticed that the [`test_ensure_unix_line_endings_with_nonutf8_characters` test would fail](https://github.com/conda/conda-build/runs/6667921343?check_suite_focus=true#step:11:1160) during cleanup of it's temporary files. No good reason for why this occurred as the test would usually pass. 🤷🏻‍♂️ 
In trying to rework the test to be more robust we learned a couple of things:
1. The tests defined in `tests/test_patch.py` weren't actually testing what they claimed to test. They claimed to be able to successfully apply a mismatched line endings patch (e.g. an LF patch could be applied to a CRLF source and vice-versa). The tests were instead consistently testing matching line endings.
3. In trying to correct the test to actually test …

Add `patch`/`m2-patch` as a hard dependency

---

conda_build/utils.py
news/fix-sp_dir.rst
tests/test-recipes/metadata/python_build/build.sh

This way, variables like `STDLIB_DIR` and `SP_DIR` will point to the `python3.10` directory, not the symlink `python3.1`.
Fixes #4477
Related threads:
- https://github.com/conda/conda/issues/10969
- https://github.com/conda/conda/issues/11423
- https://github.com/conda/conda/pull/10478
- https://github.com/conda/conda/pull/10970
- https://github.com/conda-forge/python-feedstock/pull/511
- https://github.com/AnacondaRecipes/python-feedstock/pull/47

get_stdlib_dir(): Don't select python3.1 symlink; select python3.10

---

news/4516-replace-cortools-badger
tests/test_api_skeleton_cran.py

CRAN R archived `cortools` on 2022-06-20 so this test fails.
Found a different "Artistic-2.0" licensed package (`badger`) to use instead.

Replace `r-cortools` with `r-badger` for "Artistic-2.0" license testing

---

conda_build/utils.py
news/reduce-urllib3-verbosity

Notably, `urllib3.connectionpool` was missing from the list. This caused debug messages like the following to be added to the output, even though `--verbose` was not given and the log level of the other loggers was set to `INFO`:
```
DEBUG:urllib3.connectionpool:Starting new HTTPS connection (1): conda.anaconda.org:443
DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /conda-forge/linux-64/repodata.json HTTP/1.1" 200 None
DEBUG:urllib3.connectionpool:https://conda.anaconda.org:443 "GET /conda-forge/noarch/repodata.json HTTP/1.1" 200 None
```
Also, `conda_build.noarch_python` was missing.

Make default logger list more complete

---

.github/workflows/docs.yml
.github/workflows/tests.yml
README.rst
asv.conf.json
tests/test-recipes/variants/conda-build-demo.ipynb

Performing necessary changes to rename master branch to main.
Ref: https://github.com/conda/conda-build/issues/4494

Rename master to main

---

conda_build/post.py
news/4529-fix-sysroot-dso-identify

This PR addresses a corner-case bug in identifying needed DSOs when cross-compiling packages that have multiple compiled objects.
The issue was caused by this code:
https://github.com/conda/conda-build/blob/7be9ba75b6bf0cda07ba2ab48e92b454ad398179/conda_build/post.py#L736-L749
where the `sysroot` variable is first declared as the list of `SYSROOT` base paths:
https://github.com/conda/conda-build/blob/7be9ba75b6bf0cda07ba2ab48e92b454ad398179/conda_build/post.py#L738
but then redeclared inside a nested loop while iterating over multiple SYSROOTs:
https://github.com/conda/conda-build/blob/7be9ba75b6bf0cda07ba2ab48e92b454ad398179/conda_build/post.py#L749
This resulted in all but the first file in `files` only seeing the _last_ sysroot in the original `sysroot_files.keys()` list. In turn this …

Rename 'sysroot' variable to avoid overwriting inside nested loop

---

conda_build/environ.py

Instead of using a custom `os.devnull` file handler use the stdlib `subprocess.DEVNULL` constant.

Use `subprocess.DEVNULL` instead of `os.devnull`

---

conda_build/cli/main_convert.py
conda_build/convert.py
conda_build/utils.py
conda_build/windows.py
news/4579-add-win-arm64

Add `win-64` to the list of known platforms (subdirs) as a step to addressing conda/conda#11472.
This is the conda-build counterpart to conda/conda#11778.

Add `win-arm64` as a recognized platform

---

conda_build/config.py
conda_build/metadata.py
conda_build/post.py
docs/source/resources/define-metadata.rst
news/add-overlinking-ignore-patterns
tests/test-recipes/metadata/_overlinking_detection_ignore_patterns/build_scripts/default.bat
tests/test-recipes/metadata/_overlinking_detection_ignore_patterns/build_scripts/default.sh
tests/test-recipes/metadata/_overlinking_detection_ignore_patterns/build_scripts/no_as_needed.sh
tests/test-recipes/metadata/_overlinking_detection_ignore_patterns/build_scripts/with_bzip2.bat
tests/test-recipes/metadata/_overlinking_detection_ignore_patterns/conda_build_config.yaml
tests/test-recipes/metadata/_overlinking_detection_ignore_patterns/meta.yaml
tests/test_api_build.py

Adds a new `build.overlinking_ignore_patterns` key to ignore file patterns for the overlinking and overdepending checks. This is sometimes useful to speed up builds that have many files (large repackage jobs) or builds where you know only a small fraction of the files should be checked.

add overlinking_ignore_patterns build parameter

---

conda_build/api.py
conda_build/bdist_conda.py
conda_build/build.py
conda_build/cli/main_convert.py
conda_build/conda_interface.py
conda_build/develop.py
conda_build/environ.py
conda_build/features.py
conda_build/inspect_pkg.py
conda_build/jinja_context.py
conda_build/metadata.py
conda_build/post.py
conda_build/render.py
conda_build/skeletons/cran.py
conda_build/skeletons/pypi.py
conda_build/skeletons/rpm.py
conda_build/utils.py
conda_build/variants.py
news/4603-remove-use-of-six-from-conda
tests/test_api_build.py
tests/test_api_consistency.py
tests/test_index.py
tests/utils.py

Following https://github.com/conda/conda/pull/11979, I thought it was worthwhile to remove the transient dependency on conda's vendored six.py.

Remove transient dependency on conda vendored six.py, and py2 code.

---

.github/workflows/tests.yml

Oops, the main label is the same as unlabeled, the following mean the same thing:
```
conda install -c conda-canary/label/main conda-build
conda install -c conda-canary conda-build
```
So we switch back to using dev for canary builds on the main branch. Feature branches will still use their branch name as the label.
Xref https://github.com/conda/conda/pull/12048

Switch main canary label back to dev

---

conda_build/build.py
news/4604-run-conda-in-isolated-mode

`conda build` generates some shell scripts wrappers to run `build.sh` and `bld.bat`. This includes setting a number of environment variables and activating the host and build environments in a stacked way. To do this, it employs `python -m conda shell.posix hook`. 
However, the `-m` semantics implies that the current working directories (`SRC_DIR` for conda-build!) and other user installation paths are considered as part of `sys.path`. This is usually ok, but there can be corner cases:
* If we are packaging `conda` and the version being packaged on `SRC_DIR` happens to change how `shell.posix hook` works, it might produce different code than what the released conda-build expects. 
* Not sure, but if we are packaging a dependency needed during the `hook` generation steps, it might also …

Run Python in isolated mode unless in dev mode

---

docs/source/concepts/generating-index.rst

Addresses issue #4601.
As documented in issue #4601 I had issues following the 'build a channel index' example in the docs.  This PR adds support for Windows and the new Apple Silicon to the list.  Also adds a section about how to get `wget` if you don't already have it.

Updated the "Generated an index" example to include more platforms.

---

.github/workflows/tests.yml

We're moving the token from being per-project to org-wide and it'd be best to be overly specific about the name to prevent overlap.

Changed token name to be specific to canary channel.

---

conda_build/environ.py
conda_build/inspect_pkg.py
conda_build/metadata.py
conda_build/os_utils/ldd.py
conda_build/render.py
conda_build/skeletons/cpan.py
conda_build/utils.py
conda_build/variants.py
news/4615-pendingdeprecation

This fixes the failing tests introduced by #4593.
1. Replaces `lru_cache(None)` with `lru_cache(maxsize=None)`
2. Deprecates `conda_build.environ.system_vars` in favor of `conda_build.environ.os_vars`
3. Create shim for `conda_build.os_utils.ldd.get_linkages` to circumvent hashing issue

Fix `lru_cache` issues

---

conda_build/build.py
conda_build/conda_interface.py

Deprecating per https://github.com/conda/conda/pull/12101.

Remove deprecated `context.conda_private`

---

conda_build/build.py
news/4604-run-conda-in-isolated-mode

After discussing #4604 in the community calls, we have come to the conclusion that the changes there contained might disrupt packaging workflows in conda-forge and other communities. Some reasons:
* Isolated mode prevents `PYTHON*` variables from being used and we are unsure this behavior is propagated to subprocesses (like the ones running `build.sh` and `bld.bat`).
* `conda-forge-ci-setup` sets `PYTHONUNBUFFERED`
* Python-based activation scripts might rely on PYTHON* variables as well.
* Since we are not sure and cannot test all the edge cases in time for the release, we are proposing a safer solution that better respects the default behavior in previous releases.
* Since the affected recipes are only `conda` and its dependencies (a very small % of the whole packaging ecosystem), it …

Run `conda` in isolated mode only if opted in

---

conda_build/cli/main_build.py
news/gh-4650-fix-cli-zstd-level-override-gh-4649.md
tests/test_cli.py

fixes gh-4649:
> The `conda-build` command defines a default value for `--zstd-compression-level` (`conda_build.config.zstd_compression_level_default=22`) without querying the Conda config for the `conda_build.zstd_compression_level` key. Since parameters given by the CLI take precedence over those from `.condarc`, a `zstd_compression_level` set in the latter is always overridden by the default value when `conda-build ...` is invoked.

fix: conda-build CLI overrode condarc's zstd_compression_level with the default value

---

conda_build/cli/main_build.py
conda_build/config.py
news/zstd_def_19

This uses less memory and takes less time while still providing a good level compression. Also lines up with how this was changed in conda-package-handling and conda-forge.
xref: https://github.com/conda/conda-package-handling/pull/169
xref: https://github.com/conda/conda-package-handling/issues/168
xref: https://github.com/conda-forge/conda-forge-ci-setup-feedstock/pull/217

Change Zstd compression default to 19

---

conda_build/build.py
conda_build/environ.py
conda_build/metadata.py
conda_build/utils.py
conda_build/windows.py
news/4665-fix-activation-path
tests/test_api_build.py

In https://github.com/conda-forge/conda-feedstock/pull/181#issuecomment-1334110585 we encountered unexpected failures for PyPy variants of the builds with
```cmd
D:/bld/conda_1669913819035/_h_env/python.exe: error while loading shared libraries: libpypy3.9-c.dll: cannot open shared object file: No such file or directory
```
It turned out, this happened because the build environments were not activated at all.
The correct Python interpreter was launched because the build script used `$PYTHON`.
The CPython variants built fine "by chance" only since our CPython builds carry library lookup patches to also function without an activated environment and other programs needed for the build were already on `PATH` from outside the build environment.
This happened due to a regression caused by …

Fix: Build environments not activated

---

.pre-commit-config.yaml

The recent 22.12.0 version of black breaks darker. Pinning black to 22.10.0 for now.
Xref https://github.com/conda/conda-build/issues/4673

Pin black for darker

---

.github/workflows/tests.yml

https://github.com/conda/conda-build/pull/4621 added allure reports and adds a `tar` command:
https://github.com/conda/conda-build/blob/9951c3ee0e208cf9c7e3c42a0b88b44560f04989/.github/workflows/tests.yml#L281-L282
Unfortunately, this `tar` command occurs within the same step as `pytest` resulting in the `pytest` exitcode being shadowed by the `tar` exitcode. The fix is to move the `tar` process into a separate step.
See this test that reports the test step as having passed despite there being failures: https://github.com/conda/conda-build/actions/runs/3709733101/jobs/6288635122#step:11:3184

Move tar-ing into separate step to avoid shadowing test results

---

conda_build/build.py
conda_build/conda_interface.py
conda_build/render.py
conda_build/utils.py
news/4677-remove-pre-conda413-code
tests/test_api_build.py
tests/test_index.py

Since conda-build's minimum compatible conda is 4.13 we can remove all older conda logic.

Remove logic branching for `conda_43`/`conda_44`/`conda_45`/`conda_46`/`conda_47`

---

tests/test_api_inspect.py

Removes a duplicate `thisdir` variable (also defined in `utils.py`) and removed no-op/unused tests.
Xref: https://github.com/conda/conda-build/issues/4590

Remove unused `test_api_inspect.py` tests & global variable

---

tests/test_os_utils_external.py

Rewrote `tests/test_os_utils_external.py::test_find_executable` more compactly and added missing Windows support (see original PR https://github.com/conda/conda-build/pull/1899).

Minimize `test_os_utils_external.py::test_find_executable` test and add Windows support

---

tests/conftest.py

Provide meaningful labels for the `variants_conda_build_sysroot` parameters. So instead of:
```
tests/test_api_build.py::test_overlinking_detection[variants_conda_build_sysroot0]
tests/test_api_build.py::test_overlinking_detection[variants_conda_build_sysroot1]
```
We instead get:
```
tests/test_api_build.py::test_overlinking_detection[default MACOSX_DEPLOYMENT_TARGET]
tests/test_api_build.py::test_overlinking_detection[override MACOSX_DEPLOYMENT_TARGET]
tests/test_api_build.py::test_overlinking_detection[no MACOSX_DEPLOYMENT_TARGET]
```
Xref: https://github.com/conda/conda-build/pull/4648

Label `variants_conda_build_sysroot` fixture

---

tests/test_api_build_dll_package.py
tests/utils.py

Inline a fixture that is only used once.
Xref: https://github.com/conda/conda-build/issues/4590

Inline `test_api_build_dll_package.py` recipe fixture

---

conda_build/_link.py
conda_build/build.py
conda_build/conda_interface.py
news/4728-deprecate-CrossPlatformStLink
tests/test_misc.py

Combined `pyc_f` tests into a parameterized test and deprecated `CrossPlatformStLink` in favor of `os.stat().st_nlink`.

Refactor `test_misc.py` and deprecate `CrossPlatformStLink`

---

tests/test_pypi_skeleton.py

Tests were previously written without using parameterize. Was also still using `OrderedDict` when `dict` is sufficient.
Xref: https://github.com/conda/conda-build/issues/4590

Refactor `test_pypi_skeleton.py` to use parametrize and convert `OrderedDict` to `dict`

---

tests/test_api_build_conda_v2.py
tests/test_api_build_dll_package.py
tests/test_api_build_go_package.py
tests/test_api_convert.py
tests/test_api_render.py
tests/test_api_skeleton.py
tests/test_api_test.py
tests/test_build.py
tests/test_cli.py
tests/test_develop.py
tests/test_inspect.py
tests/test_metadata.py
tests/test_post.py
tests/test_published_examples.py
tests/test_utils.py
tests/test_variants.py

Related to current test pruning/update efforts per the following epic:
https://github.com/conda/conda-build/issues/4590
There are many instances of unused fixtures in several test files (e.g., some instances of `testing_workdir`); removing them in order to simplify/streamline the test code.

Remove unused test fixtures

---

tests/test_api_skeleton_cran.py

Inline parameterized logic. Switches from `os.path` to `pathlib`. Replace select CRAN packages in favor of smaller packages (with identical licenses) for faster testing:
| Old CRAN | Old Runs | New CRAN | New Runs |
|---|---|---|---|
| `r-badger` | 190.31s | `r-fastdigest` | 24.27s |
| `r-udpipe` | 28.82s | `r-tokenizers.bpe` | 23.67s |
| `r-zoo` | 24.65s | `r-base64enc` | 7.71s |
Xref https://github.com/conda/conda-build/issues/4549 https://github.com/conda/conda-build/issues/4590

`test_api_skeleton_cran.py`: Inline parametrize, use pathlib, update CRAN packages

---

tests/test_api_render.py

Removed `pytest.mark.skipif` conditions for Python 3+ codes.
Removed test (`test_run_exports_from_repo_without_channeldata`) marked as `pytest.mark.xfail` and never had its recipe files (`tests/test-recipes/metadata/_run_export_no_channeldata`) committed when originally added in 2019 (see https://github.com/conda/conda-build/pull/3596). Furthermore, the test was designed to only run on Linux + Python 2 (`pytest.mark.skipif(sys.platform != "linux2")`), which is no longer supported.

`test_api_render.py`: remove unused `skipif` and converted `unittest.mock` to pytest-mocker

---

tests/test_build.py

Removed `skipif` markers checking for Python 2.7. Converted `os.path` to `pathlib`.

`test_build.py`: removed unnecessary `skipif` markers and converted `os.path` to `pathlib`

---

tests/test_jinja_context.py

Since conda-build depends on `conda>=4.13`, which in turn depends on `setuptools>=31.0.1`, we can drop the `pytest.mark.skipif` fence checking for `setuptools<30.3.0`.
Also converted pytest `tmpdir` to `tmp_path`.

`test_jinja_context.py`: remove unnecessary `skipif` clause and convert `tmpdir` to `tmp_path`

---

tests/requirements.txt
tests/test_api_skeleton.py

Grouped fixtures at the top of the file. Remove pre-Python 2.7 condition. Require `ruamel.yaml` to avoid try-except.

`test_api_skeleton.py`: Reorg fixtures, remove pre-Python 2.7 condition, require `ruamel.yaml`

---

conda_build/render.py

Xref https://github.com/conda/conda-build/issues/4750

Install downstream packages in correct `subdir`

---

.github/workflows/tests.yml
news/4767-reenable-coverage-reporting

Allows so see the current test coverage (or untested / potential dead code).
The action `codecov/codecov-action@v3` requries no secrete for public repos.
The repo already contains a .codecov.yml that disables PR comments and the README already contains a codecov badge, so no further steps required to get this enabled again.
Coverage is >77%, see https://app.codecov.io/gh/conda/conda-build/pull/4767 or https://app.codecov.io/gh/conda/conda-build/tree/codecov

Re-enable coverage reporting to codecov

---

docs/source/resources/define-metadata.rst

Added documentation for `build.force_[use|ignore]_keys`, which are useful for influencing the build string.
I've found these useful for multi-output repos that include e.g. a library and its Python bindings. Often conda-build's default hashes do not produce the correct output without  including `python` in the hash inputs of `libfoo`. Adding `python` to `build.force_use_keys` is an easy fix for that.

Document build.force_use_keys and build.force_ignore_keys

---

conda_build/render.py
news/4763-subdir
tests/test_render.py

Adds missing tests for #4750, #4763.
This adds tests for the 5 different use cases for `conda_build.render.find_pkg_dir_or_file_in_pkgs_dirs`:
1. package not found
1. package tarball found
1. pacakge directory found
1. package directory found, generate on demand tarball
1. package directory found, generate on demand tarball, place in different subdir from host
Took the opportunity to also refactor `conda_build.render.find_pkg_dir_or_file_in_pkgs_dirs` to use `pathlib`.

Add tests for #4763

---

conda_build/cli/main_develop.py
conda_build/cli/main_inspect.py
conda_build/conda_interface.py

`conda.base.context.get_prefix` has been marked for deprecation so we should stop using it.
Xref https://github.com/conda/conda/issues/12385
Resolves https://github.com/conda/conda/issues/12515

Stop using pending deprecation `get_prefix`

---

tests/test_api_skeleton.py
tests/test_api_skeleton_cran.py

These tests fail daily. Skip them now that we have an alternative in https://github.com/conda/grayskull
See also #4460

skip troubled skeleton tests; grayskull is available

---

conda_build/config.py
conda_build/index.py
news/4843-config-cleanup

Deprecate Python 2 silliness and use `os.makedirs(exists_ok=True)`

---

conda_build/metadata.py
news/4817-require-source-when-load-file-data-used
tests/test-recipes/metadata/jinja_load_toml_from_source/meta.yaml
tests/test-recipes/metadata/jinja_load_toml_from_source/src/pyproject.toml

Require the source to be downloaded and available if the `load_file_data` Jinja2 function is used in the recipe's meta.yaml.
closes #4807

Require the source when rendering if load_file_data is used

---

tests/test-recipes/metadata/_macos_tbd_handling/meta.yaml

Noticed this field had a typo in it. This fixes that typo.

Fix typo in `error_overdepending` field

---

news/4845-enable-xattr-test-macos
tests/conftest.py
tests/test_api_build.py

Xattr test previously only ran on Linux (if `setfattr` is present), made necessary changes to allow the test to also run on macOS.
Updated `testing_homedir` fixture to use a simpler `tempfile.TemporaryDirectory` implementation.

Enable `xattr` test for macOS

---

conda_build/build.py
news/4862-multi-output-subdir-variable

This PR fixes #4855 by renaming the usage of `subdir` as a loop variable when rebuilding the index after building an output in a multi-output build.

Use a unique subdir variable name when rebuilding the index for multi-output builds

---

.github/workflows/tests.yml

Changes canary builds to always occur, irrespective of "success".
Resolves #4892

Always build canary when pushed to main/feature/release

---

tests/requirements.txt

We can remove `pytest-xdist`'s `py` dependency since `pytest-*` packages have been hotfixed to explicitly depend on `py` (instead of indirectly via `pytest`).
Xref https://github.com/ContinuumIO/anaconda-issues/issues/13198

Revert `py` dependency

---

.github/workflows/tests.yml

Adding a Schedule cron job for `conda-build`

Adding the schedule cron job for conda-build

---

conda_build/build.py
news/4901-log-extra-meta-data
tests/test_api_build.py

This an improvement to #4303, which enabled to burn-in extra meta data into packages. The feature is used to e.g. burn-in CI_RUN_IDs, GIT_URL, GIT_SHA1 into packages to be able to trace them back to specific build runs and commits in the recipe feedstock.
Its currently pretty cumbersome to check if a build run embeds the right extra meta data or not (requires inspecting the resulting package). 
This PR:
* makes it much easier by logging the extra-meta data that is burn-in into the build log.
* makes it much easier to co-relate a package and its build log as both contain the same extra meta data
This particularly helps to test https://github.com/conda-forge/conda-smithy/pull/1577 and also constantly check via future build logs that the right meta data is in place.
pinging also @jaimergp :)

Log the extra-meta data we burn into the package for better testability

---

news/4912-fix-resolved_packages-test-failure
tests/test-recipes/metadata/_resolved_packages_host_build/meta.yaml

The recent release of OpenSSL 3.0.8 caused the `resolve_packages` test to start failing with incompatible OpenSSLs being installed in the `build` and `host` environments.
Resolves https://github.com/conda/conda-build/issues/4911

Ensure `build` and `host` install the same OpenSSL

---

conda_build/source.py
news/4914-fix-test_relative_git_url_submodule_clone
tests/test_api_build.py

Includes `-c protocol.file.allow=always` when calling `git submodule update --init --recursive` to allow cloning of local paths.
Resolves #4895

Add `protocol.file.allow=always` to `git submodule update`

---

conda_build/utils.py
news/4903-duplicate-logging

conda-build produces duplicated logging for a while now. This makes logs unnecessarily long and confusing.
The reason is that another application in the import tree must be calling `logging.basicConfig()` blindly, so the root logger gets the default stderr handler. 
We can prevent this by adding `propagate = False` to the `conda_build` top-level logger. 
I don't understand why the `get_logger` function checks every time for handlers (should be enough with the one at the top-level?) but well, I won't go down that rabbit hole now. This fixes it :)
Before:
```
No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.22
WARNING:conda_build.metadata:No numpy version specified in conda_build_config.yaml.  Falling back to default numpy value of 1.22
Adding …
```

avoid duplicate logging by preventing propagation from the conda_build logger to the root logger

---

recipe/meta.yaml

Updating conda-build's recipe file to have the most up-to-date version requirements, per comparison to [Anaconda's feedstock](https://github.com/AnacondaRecipes/conda-build-feedstock/blob/master/recipe/meta.yaml).
- [`conda-verify`](https://github.com/AnacondaRecipes/conda-build-feedstock/blob/master/recipe/meta.yaml#L67)

Update conda-build recipe file

---

conda_build/__init__.py
conda_build/plugin.py
news/4956-improve-command-plugin

Fix #4949 (avoid conda-build side effects when not using conda-build subcommands). Should improve conda start time when conda-build is installed.
Untested.

delay imports in command plugin

---

docs/source/resources/define-metadata.rst

The current link is dead, fixed to the correct source. Looked at the original link in the wayback machine and this matches the same content previously provided.

Fix the broken link to the jinja2 template page

---

docs/source/install-conda-build.rst
news/4995-run-conda-build-in-base-env

Documentation solution to problem discussed here: https://github.com/conda/conda-build/issues/4995

Update docs regarding base env use

---

docs/source/resources/define-metadata.rst
news/4942-docs-prefix-activation

Docs were wrong / out of date for this one. Comes from https://github.com/conda-forge/conda-forge.github.io/issues/1841#issuecomment-1650227240
cc @jakirkham 
Proof:
https://github.com/conda/conda-build/blob/835820623dae74308ae12b8e06571720add3dcca/conda_build/build.py#L2195-L2238

Clarify which environment gets activated first

---

.github/workflows/tests.yml

Sometimes we need to cancel workflows and we expect them to quickly finish so we can restart them. Currently this is not possible as several jobs will `always()` run even when prior jobs have been canceled.
Xref https://github.com/conda/conda/pull/13157

Only continue tests.yml workflow if not canceled

---

.pre-commit-config.yaml
tests/requirements-linux.txt
tests/requirements-macos.txt
tests/requirements-windows.txt
tests/requirements.txt

Removes comments from requirement files and enables pre-commit sorting.
This is an easier improvement extracted from  #5019.

Add sort check for requirements.txt files

---

conda_build/inspect_pkg.py
news/5021-get_hash_input

This PR fixes #5020 by patching `conda_build.inspect_pkg.get_hash_input` to use the package file basename as the hash key, rather than attempting to strip off the extension (which it currently gets wrong for `.conda` packages).

Print package file name in get_hash_input

---

conda_build/conda_interface.py

Xref https://github.com/conda/conda/issues/13192

Deprecate `conda.models.dist.IndexRecord`

---

conda_build/build.py
conda_build/environ.py
news/5031-post-conda-5708-cleanup

Attempting to remove code marked as unnecessary once https://github.com/conda/conda/issues/5708 was merged.
This is part of a larger effort to remove usage of `conda.models.dist.Dist` and related backports present in `conda` exclusively for `conda_build`.
Xref https://github.com/conda/conda/issues/13192

conda#5708 cleanup

---

tests/test_utils.py

Well look at that, the [unit tests I wrote 3 years ago](https://github.com/conda/conda-build/pull/4045) didn't withstand the test of time...the code itself is fine, the tests just need some love.
This refactors the custom `_generate_tmp_tree` helper context to use pytest's `tmp_path` fixture and brings the various path creations inline.
This was discovered while working on https://github.com/conda/conda-build/pull/5024

Replace `_generate_tmp_tree` with `tmp_path` and inline logic

---

conda_build/metadata.py
tests/test_metadata.py

Adding test to confirm we aren't loosing any selectors with the proposed change in #5009.
Corrects `py3k` selector to correctly evaluated to True for all Python 3 versions. While the `py*` selectors are deprecated (see https://github.com/conda/conda-build/issues/4032, https://github.com/conda/conda-build/issues/4297, and https://github.com/conda/conda-build/issues/4324) in favor of the `py` selector there's no reason for the deprecated selectors to be incorrect.

Add test for `conda_build.metadata.get_selectors`

---

conda_build/metadata.py
conda_build/utils.py
docs/source/resources/define-metadata.rst
news/5009-use-conda-known-subdirs
tests/test_metadata.py

Refactor `conda_build.metadata.get_selectors` to use `conda.base.constants.KNOWN_SUBDIRS` instead of duplicating this list in `conda_build`. Furthermore, abstract the selector generation so theres less effort to add new OS/Archs in the future.

Use conda.base.constants.KNOWN_SUBDIRS for setting up selectors

---

conda_build/render.py
news/5037-conda-libmamba-solver-pins

Closes #4991 
After quite some effort debugging this issue, this is what we've found:
* The channel configuration must either redefine `default_channels` or `channel_alias`, or both.
* The package cache must be clean (e.g. after `conda clean -pt`)
In this situation, the `get_upstream_pins` calculation is forced to download the package on the spot to extract it and retrieve its `run_exports` metadata. 
The problem is caused by a small divergence in the indices (parsed repodatas) as loaded by libmamba and conda, respectively. With customized `default_channels` and `channel_alias` values, the `channel` attribute of each `PackageRecord` in the `conda-build` index is set differently than in `libmamba`.
For example, with this configuration:
```yaml
channels:
- defaults
default_channels:
- …
```

Fallback to solved record filename to find the downloaded tarball in `get_upstream_pins`

---

conda_build/jinja_context.py
docs/source/resources/compiler-tools.rst
tests/test-recipes/metadata/_stdlib_jinja2/conda_build_config.yaml
tests/test-recipes/metadata/_stdlib_jinja2/meta.yaml
tests/test_metadata.py

Fixes https://github.com/conda/conda-build/issues/4981
Continuation of #4996, as requested.
cc @chenghlee, @mbargull, @beckermr

support stdlib() jinja function 

---

conda_build/build.py
news/5050-missing-anaconda-client-bugfix

Fixes: #5049
This makes the check for a missing `anaconda-client` a little more broad. This value can be an empty list.

Fix bug regarding missing `anaconda` executable

---

docs/source/_static/css/custom.css
docs/source/resources/package-spec.rst

Resolves https://github.com/conda/conda-build/issues/3713
**Before**
**After**

Allow non-first-child table cells to wrap

---

conda_build/api.py
conda_build/build.py
conda_build/create_test.py
conda_build/environ.py
conda_build/metadata.py
conda_build/post.py
conda_build/render.py
conda_build/skeletons/cran.py
tests/test-recipes/metadata/_empty_host_avoids_merge/meta.yaml
tests/test-recipes/metadata/_no_merge_build_host/meta.yaml
tests/test-recipes/split-packages/_order/meta.yaml
tests/test-recipes/variants/27_requirements_host/meta.yaml

The MetaData object contains lots of fancy helper methods/properties (e.g. `get_value` and `build_id`). Let's attempt to more consistently use these features instead of reaching into the MetaData's internals.

Use `conda_build.metadata.MetaData`'s `get_section` & `get_value`

---

.github/workflows/tests.yml
tests/test_deprecations.py
tests/test_metadata.py

Currently we have little insight into whether our conda lower bound is valid. Changes lower Python supported to test with the lowest conda supported (instead of the latest stable release).

Test minimum conda supported

---

conda_build/cli/main_build.py
conda_build/config.py
tests/cli/test_main_metapackage.py
tests/cli/test_main_render.py
tests/conftest.py

The default_testing_config monkeypatching fixture was added in gh-4653 but did not consider "from .config import get_or_merge_config" cases in which get_or_merge_config is already bound and thus not patched.
I noticed flaky tests again in gh-5066.
This is essentially a follow-up to gh-4653 (... about a year later....).

Fix testing config monkeypatch for concurrent test flakiness

---

news/5059-ci-conda-libmamba-solver
tests/cli/test_main_build.py
tests/conftest.py
tests/test_api_build.py

conda 23.10.0 requires conda-libmamba-solver and has `solver=libmamba` as default, so conda-build's CI is going to be using it now.

CI adjustments for conda-libmamba-solver as default

---

conda_build/index.py
news/5066-fix-conda_index-log-spam

Log messages from `conda_index.index` get put out with high verbosity.
As an example, I built https://github.com/conda-forge/zlib-feedstock/tree/main
which yielded a build log with 936 lines -- 260 of those lines (about 28%) were `INFO`/`DEBUG` messages from `conda_index.index` like these:
<details>
```
DEBUG:conda_index.index:found subdirs {'linux-64', 'noarch'}
DEBUG:conda_index.index.sqlitecache:CondaIndexCache channel_root=/opt/conda/conda-bld, subdir=linux-64 db_filename=/opt/conda/conda-bld/linux-64/.cache/cache.db cache_is_brand_new=False
DEBUG:conda_index.index.sqlitecache:linux-64 listdir
DEBUG:conda_index.index.sqlitecache:linux-64 save fs state
DEBUG:conda_index.index:linux-64 find packages to extract
DEBUG:conda_index.index:linux-64 extract 1 packages …
```

Fix conda_index.index verbose DEBUG/INFO logging

---

.pre-commit-config.yaml
conda_build/_load_setup_py_data.py
conda_build/api.py
conda_build/build.py
conda_build/cli/main_build.py
conda_build/cli/main_develop.py
conda_build/cli/main_render.py
conda_build/config.py
conda_build/exceptions.py
conda_build/index.py
conda_build/inspect_pkg.py
conda_build/jinja_context.py
conda_build/metadata.py
conda_build/noarch_python.py
conda_build/os_utils/liefldd.py
conda_build/os_utils/pyldd.py
conda_build/plugin.py
conda_build/post.py
conda_build/skeletons/cran.py
conda_build/skeletons/rpm.py
conda_build/tarcheck.py
conda_build/utils.py
conda_build/variants.py
news/5052-ruff-format
pyproject.toml
tests/conftest.py
tests/test_api_build.py
tests/test_api_render.py
tests/test_utils.py

`ruff format` is now a thing (see https://github.com/astral-sh/ruff/releases/tag/v0.1.2 and https://github.com/astral-sh/ruff/releases/tag/v0.1.3).
Removing the need for `black`.
Trimmed line-length down from 180 to 120 (removing this line-length deviation will result in 753 E501 lints, too much to do in one go).
Xref https://github.com/conda/conda/pull/13272

Replace `black` with `ruff-format`

---

docs/source/user-guide/environment-variables.rst

Saying `<build prefix>` now implies `BUILD_PREFIX`, which isn't the case. AFAIK these have always been constructed based on `PREFIX`, which is the host environment. Guessing this is just leftover verbiage that needs a refresh.
Also make the same change for `LD_RUN_PATH`, which has the same issue.
Plus some other lines describing behavior in the prose.
<hr>

[DOC] Clarify `PREFIX` usage in environment variables

---

tests/cli/test_main_build.py
tests/conftest.py
tests/test-recipes/metadata/entry_points/meta.yaml
tests/test_api_build.py
tests/test_api_build_conda_v2.py
tests/test_api_convert.py

`cli.main_build.execute` (et al.) call the function with `**args.__dict__` with args having default values (e.g., `croot=None`) via `parse_args`.
Follow-up to gh-5068.
See https://github.com/conda/conda-build/pull/5066#issuecomment-1817033741

Tests: Fix get_or_merge_testing_config for cli tests

---

conda_build/config.py
conda_build/inspect_pkg.py
conda_build/utils.py
tests/test_config.py

Stumbled over while working on https://github.com/conda/conda-build/pull/5080
Updates `test_keep_old_work` to use pytest's `tmp_path` fixture and adds some type hints on the way.

Update flaky Windows permissions test

---

conda_build/metadata.py
news/5096-relax-metadata-version-checks
tests/test-recipes/split-packages/_empty_outputs_requires_package_version/meta.yaml
tests/test-recipes/split-packages/_multi_outputs_without_package_version/meta.yaml
tests/test-recipes/split-packages/_order/meta.yaml
tests/test_api_build.py
tests/test_subpackages.py

Correcting conda-build issues identified for multi-outputs where the version is undefined (https://github.com/conda-forge/admin-requests/pull/890).
Leaving in the version checks in simple recipes but relaxes the requirements for recipes with multi-outputs.
Xref https://github.com/conda/conda-build/pull/5055
Resolves #5097

Relax `package/version` check for multi `outputs`

---

pyproject.toml
recipe/meta.yaml

lief was added to the pip-style dependencies, causing pip check to fail since py-lief's conda package has no `dist-info` (pip metadata)
Xref https://github.com/conda/conda-build/issues/5101

add pip check to recipe tests

---

conda_build/post.py
news/5116-menuinst-importerror

If `menuinst` v1 is present in the `base` environment, `ModuleNotFoundError` won't be raised. Instead the more general `ImportError` is thrown. Catch that one instead.

catch the more general `ImportError` if menuinst cannot be imported

---

conda_build/inspect_pkg.py
conda_build/post.py
news/5108-fix-which_package
tests/conftest.py
tests/test_inspect_pkg.py

The refactor of `which_package` accidentally resulted in the same package record being returned multiple times (once for each _file_ collision). This results in misleading build warnings.
Instead we only want to return a unique set of package records.
Resolves https://github.com/conda/conda-build/issues/5106

`which_package` to yield unique collection of package records

---

conda_build/build.py
conda_build/metadata.py
conda_build/render.py
conda_build/source.py
news/5112-fix-multiple-sources
tests/test-recipes/metadata/source_multiple/meta.yaml
tests/test_metadata.py

The recipe format supports 9 fields, all of which are expected to be `dict` except "source" and "outputs" which can be either a single `dict` or a `list` of `dict`.
Previously this distinction had to be uniquely handled throughout out the code, e.g.:
https://github.com/conda/conda-build/blob/061063f10c51162707c7c5253daa39b2752fcfcc/conda_build/build.py#L1567-L1569
It instead makes more sense for the `MetaData.get_section` to auto handle this sanitization for us and to always return a `list` of `dict` for "source" and "outputs".
Resolves #5111

Fix `MetaData.get_section` handling for "source" & "outputs"

---

.github/workflows/tests.yml
tests/test_api_build.py

See https://github.com/conda/conda/pull/13357

Add tests to ensure that context is properly reset

---

conda_build/os_utils/liefldd.py
news/5124-fix-ensure_binary-None-handling

Fix `conda_build.os_utils.liefldd.ensure_binary` to handle `None`

---

conda_build/build.py
conda_build/environ.py
news/5105-script-env-warn
tests/test-recipes/split-packages/_build_script_missing_var/meta.yaml
tests/test_subpackages.py

The behavior of `script_env` was inconsistent between top-level and outputs. This PR makes outputs be less strict (warning, not failing) if a referenced variable is not set.

reduce unset script_env variable to warning

---

conda_build/inspect_pkg.py
conda_build/utils.py
news/5126-samefile-regression
pyproject.toml
tests/test_config.py
tests/test_inspect_pkg.py

The `which_package` refactor https://github.com/conda/conda-build/pull/5041 switched from using `os.path.normcase` to compare paths to calling `Path.samefile` which calls `os.stat`. This became especially expensive for certain builds so we need to ~revert~ revisit this change.
The proposal here is to implement a cached mapping of files to packages making `which_package` into `O(n)` for the first lookup and `O(1)` for all subsequent lookups.
We add a benchmark/battery test to better compare implementations. Here are the results of running the benchmark test with a few different versions/ideas:
| Version/Idea | Time |
|---|---|
| `3.27.0` | ~9s |
| `3.28.2` | ~16m48s |
| `normpath` | ~1m6s |
| `normcase` | ~35s |
| mapping | ~2s |
Resolves https://github.com/conda/conda-build/issues/5126

Deprecate `conda_build.utils.samefile` in favor of path to package mapping

---

conda_build/inspect_pkg.py
news/5141-fix-which_package
tests/conftest.py
tests/test_inspect_pkg.py

Fix linking check regressions by restoring pre-`3.28` behavior for `which_package`.
Fixes gh-5136.

Restore pre-`3.28` behavior for `which_package`

---

.github/workflows/tests.yml

The test workflow isn't ready to run the tests and canary builds based on CalVer two-digit Git tags. This fixes it.
Xrefs #4857 and https://github.com/conda/conda/pull/12622

Trigger test runs on CalVer release branches.

---

tests/test_api_skeleton.py

`tests/test_api_skeleton.py::test_get_package_metadata` has suddenly become very flaky on Windows (not sure why, it almost looks like a caching issue or some other Windows specific issue where its unable to properly delete old files), see recent failures [here](https://github.com/conda/conda-build/actions/runs/7658085399/job/20889482027?pr=5150) and [here](https://github.com/conda/conda-build/actions/runs/7668341190/job/20902706818?pr=5151).
This is a dumb attempt to fix the issue by simply updating the `pylint` version (from 2.3.1 to 2.7.4, the last `pylint` to use `setup.py` without `setup.cfg`) the test fetches from PyPI. As a bonus this change also allows the test to succeed on `osx-arm64`.

Update `pylint` from 2.3.1 to 2.7.4

---

docs/requirements.txt

A new version of [conda-sphinx-theme](https://github.com/conda-incubator/conda-sphinx-theme) was recently release which updates the link to the Miniconda documentation. This pull request moves the conda-build docs to that version.

Bump conda-sphinx-theme version to 0.2.1

---

conda_build/cli/main_build.py
conda_build/cli/main_convert.py
conda_build/cli/main_debug.py
conda_build/cli/main_develop.py
conda_build/cli/main_inspect.py
conda_build/cli/main_metapackage.py
conda_build/cli/main_render.py
conda_build/cli/main_skeleton.py
conda_build/plugin.py
conda_build/utils.py
news/5169-fix-nonzero-exitcode
tests/cli/test_main_build.py

Fix nonzero exit for conda-build entrypoint

---

conda_build/os_utils/liefldd.py

openmpi builds on conda-forge are failing at https://github.com/conda-forge/openmpi-feedstock/pull/142
The source of the issue (still unclear) is an invalid utf-8 path, but the intended error handling doesn't safely catch errors.
The problem is in the _logs_ of the failure to parse then raise because the warning itself fails to be formatted:
```
File "/opt/conda/lib/python3.10/site-packages/conda_build/os_utils/liefldd.py", line 54, in ensure_binary
return lief.parse(str(file))
TypeError: '/home/conda/feedstock_root/build_artifacts/openmpi-mpi_1707395567538/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold/lib/\x01\udce4 …
```

Avoid encoding error when warning about error in ensure_binary

---

conda_build/build.py
conda_build/environ.py
news/5184-fix-multi-output-package-corruption
tests/test-recipes/metadata/outputs_overwrite_base_file/install.bat
tests/test-recipes/metadata/outputs_overwrite_base_file/install.sh
tests/test-recipes/metadata/outputs_overwrite_base_file/meta.yaml

Fix corrupted package cache for outputs in subpackage tests
This re-introduces conda_build.environ.clean_pkg_cache with slight
changes to not use conda.models.dist.Dist and handle multiple pkgs_dirs
better.
Addresses https://github.com/conda/conda-build/issues/5179#issuecomment-1942172592
- ~~[ ] Add / update outdated documentation?~~

 Fix corrupted package cache for outputs in subpackage tests

---

pyproject.toml

We wish to dismiss messages like the following from PRs:
Xref https://github.com/conda/conda/pull/13597

Ignore `TYPE_CHECKING` imports in coverage reports

---

pyproject.toml
recipe/meta.yaml

Since the `conda index` subcommand/entrypoint was deprecated and removed (see https://github.com/conda/conda-build/pull/5151) from `conda-build` we need to explicitly depend on the `conda-index>=0.4.0` package for the `conda index` subcommand.
Other relevant discussions:
- https://github.com/conda/conda-build/pull/5158#discussion_r1471435596
- https://github.com/AnacondaRecipes/conda-build-feedstock/pull/41#discussion_r1491516034

Correct `conda-index` dependency

---

conda_build/bdist_conda.py
news/5196-deprecate-bdist-conda

Resolves https://github.com/conda/conda-build/issues/4985

Deprecate `bdist_conda` module

---

conda_build/build.py
news/5199-deprecate-have_prefix_files

Mark for deprecation and remove old commented out code.

Deprecate unused `conda_build.build.have_prefix_files`

---

conda_build/variants.py
news/5195-fix-stdlib-variant
tests/test_metadata.py

Fix stdlib being recognized in variant hash inputs

---

conda_build/conda_interface.py
conda_build/environ.py
news/5221-deprecate-get_version_from_git_tag

We were still using a minor helper function from the deprecated `conda.auxlib.packaging`. This wasn't caught until the conda canaries were rebuilt after the removal.

Port deprecated `conda.auxlib.packaging.get_version_from_git_tag` to `conda_build`

---

conda_build/conda_interface.py
conda_build/index.py
news/5203-remove-deprecations

- gh-5203 (I suppose unintentionally) removed `.index._apply_instructions` which is slated for deprecation in `24.5` at the earliest.
- I'd like to re-add `.conda_interface.get_index` for another release cycle since I didn't get to update downstream (conda-forge scripts, etc.) for this change, yet.

Defer `.index._apply_instructions` and `.conda_interface.get_index` deprecations

---

conda_build/os_utils/liefldd.py
news/5228-lief-0.14-compat
tests/requirements.txt

Add compatibility for LIEF=0.14
Fixes gh-5227.

Add compatibility for LIEF=0.14

---

.github/workflows/tests.yml
news/5233-enable-codspeed
tests/test_inspect_pkg.py
tests/test_metadata.py

Enables CodSpeed benchmarks and adds a new `test_select_lines_battery` test.

Enable CodSpeed and add select lines benchmark

---

tests/test-recipes/metadata/_pin_subpackage_benchmark/meta.yaml
tests/test_api_render.py

This is a performance regression benchmark for gh-5224.
- ~~[ ] Add / update outdated documentation?~~

Add benchmark for high `pin_subpackage` count recipe

---

conda_build/build.py
tests/test_build.py

While working on https://github.com/conda/conda-build/pull/5255 found that `conda_build.build.guess_interpreter` actually guesses incorrectly for certain extensions (e.g., `.sh_what`, `.bat_what`, `.ps1_what`, `.py_what`).

Add `test_guess_interpreter`

---

conda_build/__init__.py

Porting development version error handling improvement from conda (see https://github.com/conda/conda/pull/13539).
Xref https://github.com/conda/conda/pull/13764
Extends https://github.com/conda/conda-build/pull/5262

Catch `LookupError` when getting development version

---

conda_build/deprecations.py
tests/test_deprecations.py

Ports recent improvements from `conda.deprecations` to `conda_build.deprecations`:
- https://github.com/conda/conda/pull/13716
- https://github.com/conda/conda/pull/13765

Sync with `conda.deprecations`

---

conda_build/metadata.py

Looking to see just how much of a speedup we get by removing this redundant line.
Extracted from:
- https://github.com/conda/conda-build/pull/5237

Remove duplicate `extract_package_and_build_text` call

---

conda_build/jinja_context.py
conda_build/metadata.py
conda_build/utils.py
news/5284-deprecate-HashableDict
pyproject.toml
recipe/meta.yaml
tests/requirements.txt
tests/test_jinja_context.py

Instead of using a customized `HashableDict` implementation we can just use the `frozendict` library (which `conda` already depends on). Using `frozendict` also means we can avoid calling `deepcopy` (`frozendict` takes care of this for us).

Deprecate `HashableDict` in favor of `frozendict`

---

.github/dependabot.yml
.github/workflows/builds-review.yaml
.github/workflows/docs.yml
.github/workflows/tests.yml
.pre-commit-config.yaml

- Update `.github/dependabot.yml` file
- Switch GitHub Actions to use commit hashes instead of commit tags (dependabot will update tags to tags and hashes to hashes)
- Add `check-dependabot` hook to pre-commit

Update pre-commit & dependabot config

---

conda_build/metadata.py

Reorders if-clause to run cheaper (faster) calculation first and more expensive calculation second so we can benefit from short-circuiting.
Split from: 
- https://github.com/conda/conda-build/pull/5253

Short-circuit `get_output_dicts_from_metadata`'s if clause for faster evaluation

---

conda_build/metadata.py

Memoizes `conda_build.metadata._filter_recipe_text` to avoid expensive re-parsing.
Split from: 
- https://github.com/conda/conda-build/pull/5253

Memoize `conda_build.metadata._filter_recipe_text`

---

conda_build/variants.py

Properly `re.escape` variant variable in `find_used_variables_*`

---

conda_build/variants.py
tests/test_variants.py

This refactor adds a `variant in text` check before calling the more expensive `re.search(PATTERN % variant, text)`. And while working on this went ahead and added a unittest!
Extracted from:
Extends https://github.com/conda/conda-build/pull/5283

Minor refactor of `find_used_variables_*` functions

---

conda_build/config.py
conda_build/render.py
tests/conftest.py

Deprecate `noarch_python_build_age`

---

.github/workflows/tests.yml

See https://github.com/conda-incubator/setup-miniconda/issues/344 for context.

Be explicit about macOS runner choices in GHA workflows

---

conda_build/config.py
news/5271-context

The `Config.override_channels` property was set to fetch an invalid value from the context.
To test:
```bash
python -Wd -c "from conda_build.config import Config; print(Config().override_channels)"
python -Wd <<HEREDOC
from conda_build.config import Config
from conda.base.context import context
from argparse import Namespace
context.__init__(argparse_args=Namespace(override_channels=True))
print(Config().override_channels)
HEREDOC
```

Fix `Config.override_channels` property

---

.github/workflows/upload.yml

Port conda's `upload.yml` workflow that has been successfully used for three releases now to produce release tarballs with static sha256 hashes.
This will prevent the sha256 race condition that occurs when using GitHub's auto-generated release tarballs (see https://github.com/AnacondaRecipes/conda-build-feedstock/pull/44 and https://github.com/conda-forge/conda-build-feedstock/pull/226).
Fixes https://github.com/conda/conda-build/issues/5340

Add `upload.yml` workflow

---

conda_build/os_utils/liefldd.py
news/5348-fix-excessive-memory-use-in-inspect_linkages_lief

introduced in gh-5228 which replaced `binary.name` with `str(file)`.
The former returns the path to the binary whereas the latter returns the
contents of the parsed binary, naturally causing high memory usage.
That semantic change was unintended (misread upstream changes).
Since binary's path is no longer part of the object, pass it separately.
Fixes gh-5267

Fix excessive memory use in `inspect_linkages_lief`

---

conda_build/metadata.py
news/5345-fix-frozendict
tests/test-recipes/metadata/gh-5342/meta.yaml

A very specific use case results in the code trying to modify a `frozendict` version of the output dict.
Fix #5342

Fix `frozendict` usage

---

conda_build/metadata.py
news/5359-validate-run-constrained
tests/test-recipes/metadata/_run_constrained_error/meta.yaml
tests/test_api_build.py

Closes #5047
conda-build allows to include `run_constrained` items in the recipe content. These are sometimes not checked because they only affect the solver if the constrained name happens to be present in the test environment. As a result, faulty lines might get sneak all the way into the final repodata.json. 
When the rules finally kick in, you get a solver error. One current example comes in the [`willow` recipe, which constrains `pillow-heif`](https://github.com/conda-forge/willow-feedstock/blob/67d9ac1c5232295ccaac41b131e3982a335b365b/recipe/meta.yaml#L29).
That line is not a valid `MatchSpec`:
```
>>> from conda.models.match_spec import MatchSpec
>>> MatchSpec("pillow-heif >=0.10.0,<1.0.0<py312|>=0.13.0,<1.0.0>=py312")
File …
```

Validate `run_constrained` specs

---

conda_build/exceptions.py

For `sys.exit` removal work (see #4209).

Add `CondaBuildUserError` exception

---

conda_build/build.py
tests/test_build.py

Replacing `sys.exit` call in `copy_readme` with the new `CondaBuildUserError` exception for better downstream error handling. Add missing unit test.
Depends on #5353
Xref #4209

Replace `sys.exit` in `copy_readme`

---

conda_build/build.py
conda_build/inspect_pkg.py
conda_build/metadata.py
conda_build/utils.py

In #5364 I missed a few calls to `.warn` because they were chained with our own `get_logger` function.
This PR takes care of those.
Still nothing here applies.

Fix a few more logger.warn calls

---

conda_build/build.py
tests/test_build.py

Replacing `sys.exit` call in `bundle_conda` with the new `CondaBuildUserError` exception for better downstream error handling. Add missing unit test.
Xref https://github.com/conda/conda-build/issues/4209

Replace `sys.exit` in `conda_build.build.bundle_conda`

---

conda_build/build.py
tests/test_build.py

Replacing `sys.exit` call in `handle_anaconda_upload` with the new `CondaBuildUserError` exception for better error handling, along with a corresponding unit test. 
This work has been separated out from #5255
Xref #4209

Replace `sys.exit` in `conda_build.build.handle_anaconda_upload`

---

conda_build/build.py
tests/cli/test_main_build.py
tests/test_api_build.py
tests/test_api_test.py
tests/test_build.py
tests/test_subpackages.py

Replacing `sys.exit` call in `tests_failed()` in `build.py` with the new `CondaBuildUserError` exception for better error handling, along with a corresponding unit test. 
This work has been separated out from #5255
Xref #4209

Replace `sys.exit` call in `conda_build.build.tests_failed`

---

conda_build/build.py
news/5368-pip-outputs
tests/test-recipes/split-packages/script_install_files/subpackage1.py

Set PIP_* env vars for outputs/script

---

conda_build/utils.py
news/5384-test-log-level

This PR tries to address #5382 by only calling `setLevel` if needed. I am trying it instead of #5383 since it is less intrusive and I am seeing odd test failures in that PR.
closes #5383 
closes #5382

perf: only set level if needed

---

conda_build/metadata.py
tests/test_api_build.py
tests/test_metadata.py

Replacing `sys.exit` call in a few functions in `conda_build/metadata.py` with the new `CondaBuildUserError` exception for better error handling, along with corresponding unit tests. 
The changes in this PR are separated out from work previously done by @kenodegard in #5255
Xref #4209

Replace `sys.exit` calls in `conda_build/metadata.py`

---

conda_build/inspect_pkg.py
tests/cli/test_main_inspect.py
tests/test_inspect.py
tests/test_inspect_pkg.py
tests/test_post.py

Replacing `sys.exit` call in a few functions in `conda_build/inspect_pkgs.py` with the new `CondaBuildUserError` exception for better error handling, along with corresponding unit tests. 
The changes in this PR are separated out from work previously done by @kenodegard in #5255
Xref #4209

Replace `sys.exit` calls in `conda_build/inspect_pkg.py`

---

conda_build/build.py
conda_build/deprecations.py
news/3192-deprecate-testing-recipes
tests/test_build.py

`conda build --test recipe/` has been marked for deprecation since `conda-build 3.16.0`.
Might as well get it on the deprecation train.

Update `conda build --test recipe/` deprecation

---

conda_build/post.py
news/5404-sysroot-prefer
tests/test-recipes/metadata/_sysroot_detection/build.sh
tests/test-recipes/metadata/_sysroot_detection/conda_build_config.yaml
tests/test-recipes/metadata/_sysroot_detection/main.c
tests/test-recipes/metadata/_sysroot_detection/meta.yaml
tests/test_api_build.py

Improves sysroot selection.
Fixes https://github.com/conda/conda-build/issues/5403

Prefer sysroot matching subdir when there are multiple

---

tests/test_api_build.py

`conda-libmamba-solver 24.7.0` reuses the `.solv` cache by default. This means toggling the `add_pip_as_python_dependency` value doesn't have an impact until the cache is cleared.
Here we use a temporary directory for the cache to avoid the issue.
Xref https://github.com/conda/conda-build/pull/5426
Resolves https://github.com/conda/conda-libmamba-solver/issues/506
Xref https://github.com/conda/conda-libmamba-solver/issues/393
Xref https://github.com/conda/conda-libmamba-solver/pull/481
Xref https://github.com/conda/conda-libmamba-solver/pull/482

Clear libmamba `.solv` cache

---

conda_build/build.py
news/5434-check-for-WSL
tests/test_api_build.py

Fixes for `24.7.1` patch release:
Cherrypick #5428
Resolves #5433
Since this cherrypicks a commit from `main` we probably shouldn't squash merge this?

Check whether WSL is installed

---

conda_build/noarch_python.py
conda_build/utils.py
tests/test_noarch_python.py

While working on https://github.com/conda/conda-build/pull/5255 found an opportunity to add unittests and do a small refactor to `conda_build.noarch_python.rewrite_script`.

Remove `sys.exit` from `noarch_python` and add unittests

---

conda_build/build.py
conda_build/deprecations.py
conda_build/metadata.py
news/5441-24.9-removals
tests/test_build.py

Removing all deprecations slated for removal in `24.9.x`.

24.9 Removals

---

conda_build/variants.py
news/5447-jinja2-for-set-vars
tests/test-recipes/variants/jinja2_used_variables/conda_build_config.yaml
tests/test-recipes/variants/jinja2_used_variables/meta.yaml
tests/test_variants.py

This PR adds two regexes to catch variables used in single-line jinja2 `for` and `set` statements. These have been missed for a long time and appear to be the cause of at least one bug. I have not gone through the bug tracker, but I have a hunch this PR might fix other bugs related to similar situations I've seen in the past.
closes #5445

fix: make sure to catch jinja2 vars used in single-line `for` and `set` statements

---

conda_build/develop.py
tests/test_develop.py

Replacing `sys.exit` calls in `conda_build/develop.py` with the new `CondaBuildUserError` exception for better error handling + unit tests. 
The changes in this PR are separated out from work previously done by @kenodegard in #5255
Xref #4209

Remove `sys.exit` from `develop.py`

---

conda_build/convert.py
tests/test_api_convert.py

Replacing `sys.exit` calls in `conda_build/convert.py` with the new `CondaBuildUserError` exception for better error handling + updating corresponding unit tests.
The changes in this PR are separated out from work previously done by @kenodegard in #5255
Xref #4209

Remove `sys.exit` calls from `convert.py`

---

conda_build/post.py
pyproject.toml
tests/requirements-ci.txt
tests/test-recipes/metadata/_sysroot_detection/meta.yaml

Found that while we were passing `--xdoctest-modules` we haven't actually been running any docstring example codes anyhow since `pytest` only crawls the `tests` directory by default.
Correcting this (and/or switching to use `doctests` instead) is out of scope and relegated to a future effort.
Also ignoring over depending checks for `libgcc` on linux as was previously done for `libgcc-ng` since conda-forge recently renamed `libgcc-ng` to `libgcc`.
Closes #5470 
Closes #5469 
Closes #5468 
Closes #5475 
Closes #5476

Remove `xdoctest` & ignore `libgcc` for overlinking/overdepending checks

---

conda_build/metadata.py
news/5458-avoid-undefined-jinja-in-skipped
tests/test_metadata.py

A few NVIDIA feedstocks on conda-forge have been failing to re-render lately. See https://github.com/conda-forge/cuda-nvdisasm-feedstock/issues/12. The expected behavior was that undefined jinja variables shouldn't error out when the metadata is skipped.
I tracked it back to https://github.com/conda/conda-build/pull/5371, which I think is a good code improvement. In order to avoid these irrelevant errors for skipped recipes, we just abort after the first parsing pass.

Avoid undefined jinja errors for skipped recipes

---

conda_build/build.py
news/5478-24.9-removals
tests/cli/test_main_build.py
tests/test_api_test.py
tests/test_build.py

This removal was missed in https://github.com/conda/conda-build/pull/5441.

Remove deprecated "test from recipe" function

---

tests/test-recipes/metadata/_render_recipe/conda_build_config.yaml
tests/test-recipes/metadata/_render_recipe/meta.yaml
tests/test_render.py

Adds `render_recipe` test for https://github.com/conda/conda-build/pull/5392. This is added separately so we can see the benchmark speedups in the other PR via CodSpeed.

Add benchmark test for `render_recipe`

---

tests/requirements-ci.txt

Short-term fix for #5493. This is to get the test unblocked allowing us to merge #5491.

Require `setuptools <71.1.0`

---

.github/condarc
.github/workflows/tests.yml

Since https://github.com/conda/conda/pull/14227 has been merged we're now getting deprecation warnings here. Editing our condarc to silence the warning message.

Set default channel to avoid deprecation warning

---

.github/workflows/tests.yml
conda_build/build.py
conda_build/environ.py
conda_build/index.py
conda_build/render.py
news/5508-deprecate-get_build_index-locking-timeout
pyproject.toml
tests/test_api_build.py
tests/test_index.py

Adds a benchmark test so we can see the speed improvements with the new lazy index from `conda 24.9.0`.
A few things are done here:
1. We deprecate two unused arguments (`locking` and `timeout`) from `conda_buil.index.get_build_index`
2. We force the benchmark CI job to use `conda=24.7` so we can get an accurate before measurement (we will revert this change in #5488)
3. Add benchmark test in `tests/test_index.py::test_get_build_index`
4. Ignore `filterwarings` in pyproject.toml to avoid deprecation errors (we will revert this change in #5488)
Xref #5488

Add index benchmark

---

conda_build/skeletons/pypi.py
news/5517-fix-skeleton-patch.rst
tests/test_api_skeleton.py

This PR moves the ruamel.yaml calls to the new APIs.
Fixes #5515

fix: update ruamel.yaml usage to use supported APIs

---

conda_build/variants.py
news/5514-better-jinja2-regex.rst
tests/requirements-ci.txt

This PR uses a more specific regex for jinja2 set statements per the comment from @isuruf.

fix: use a more specific regex for jinja2 set/for statements

---

.github/workflows/tests.yml

Minor update following #5082, since https://github.com/conda-incubator/setup-miniconda/pull/342 added a new feature to setup-miniconda to also define the installation directory.
- ~[ ] Add a file to the `news` directory ([using the template](https://github.com/conda/conda-build/blob/main/news/TEMPLATE)) for the next release's release notes?~

Also install on D: on GHA Windows runners for improved performance

---

.github/workflows/tests.yml
recipe/meta.yaml

The first canary build created after cutting a release branch produces a misleading version/build string. Instead of deriving the version/build string from the upcoming release, it uses the version from the most recent release on `main`. This leads to a race condition with packages produced by the canary build workflow from the `main` branch.
The race condition occurs because both `main` and the release branch end up generating packages with the same version/build string. Even though we upload them to anaconda.org with different labels, only one package would "win." As a result, we occasionally see the package first appear under one label, only to disappear and reappear under the other label when the other canary build workflow finishes and uploads it's packages.
The proposed fix is to …

Conditionally override version after cutting a release branch

---

conda_build/variants.py
news/5535-fix-variant-finding.rst
tests/test_variants.py

Currently, conda-build will say the variant variable `python` is used for a statement like
```yaml
requirements:
host:
- python {{ python_min }}
```
This is incorrect and only `python_min` is used in this case AFAIK.
It also says this statement does NOT use `python` when it does
```yaml
requirements:
run:
- {{ pin_compatible('python') }}
```
This bug was introduced in https://github.com/conda/conda-build/pull/2838.
The issue appears to be a buggy regex for searching for variants. 
This PR proposes a new regex and adds unit tests that assert the correct behavior.

fix: ensure variable finding works properly and add unit tests for variable finding

---

.github/workflows/tests.yml

A follow-up PR related to https://github.com/conda/conda-build/pull/5483
Builds are failing (see example [here](https://github.com/conda/conda-build/actions/runs/11842587199/job/33001566121#step:4:44)) due to [`check_output()`](https://docs.python.org/3/library/subprocess.html#subprocess.check_output) returning a bytes object instead of a string; per discussion with @kenodegard , I've added `text=True` so that a `str` will be returned, and also a `.strip()` to avoid any potential extra whitespace.

Update `check_output()` call in `tests.yml` workflow

---

conda_build/metadata.py
conda_build/render.py
news/5538-sysexit-vs-cdusererror
tests/test_api_render.py

This PR catches `CondaBuildUserError` with `SystemExit` in internal routines in the code. What is going on is that as we've slowly been moving `sys.exit` calls to raising a `CondaBuildUserError`, we've inadvertently started raising exceptions in places where we should not be.

fix: catch `CondaBuildUserError` w/ `SystemExit`

---

conda_build/cli/main_build.py
news/5550-fix-TypeError-no-arguments

Correct deprecation message when no arguments are passed

---

conda_build/metadata.py
news/5555-skip-bad-specs-while-still-parsing.rst
tests/test_api_build.py
tests/test_metadata.py

This PR allows incomplete specs if they do not parse by skipping them for intermediate parsing stages. This behavior has been in the code for a while if a spec was completely specified by eg jinja2 (eg a list element `- {{ mpi }}`). The PR extends this behavior to any soec that does not parse during intermediate stages. For the final parsing stage, specs that do not parse will raise.

fix: allow incomplete specs during intermediate parsing stages

---

conda_build/build.py
news/5560-fix-pkg-type-key-error

When trying to run `conda-build` on a simple perl package I wrote, I came across the error 
```
File "/mnt/nfs01/home/y_pradat/mambaforge/bin/conda-build", line 11, in <module>
sys.exit(execute())
File "/mnt/nfs01/home/y_pradat/mambaforge/lib/python3.10/site-packages/conda_build/cli/main_build.py", line 648, in execute
api.build(
File "/mnt/nfs01/home/y_pradat/mambaforge/lib/python3.10/site-packages/conda_build/api.py", line 211, in build
return build_tree(
File "/mnt/nfs01/home/y_pradat/mambaforge/lib/python3.10/site-packages/conda_build/build.py", line 3653, in build_tree
packages_from_this = build(
File "/mnt/nfs01/home/y_pradat/mambaforge/lib/python3.10/site-packages/conda_build/build.py", line 2764, in build
newly_built_packages = …
```

Fix: change definition of pkg_type variable in build function to solve KeyError: 'conda'

---

tests/test_api_build.py
tests/test_published_examples.py

As seen in other CI runs, `click` removed `setup.py` in 8.1.8, so let's use an older version because this file is expected by the test.

Fix failing test: `test_skeleton_pypi`

---

conda_build/os_utils/liefldd.py
news/5565-lief-0.15-compat
tests/test-recipes/metadata/_rpath/meta.yaml
tests/test-recipes/metadata/_rpath_symlink/meta.yaml

ref https://lief.re/doc/stable/changelog.html#july-21th-2024
should fix https://github.com/conda/conda-build/issues/5564

adapt for api changes in py-lief 0.15

---

conda_build/build.py
conda_build/render.py
news/5603-transitive-subpackage.rst
tests/test-recipes/metadata/transitive_subpackage/conda_build_config.yaml
tests/test-recipes/metadata/transitive_subpackage/meta.yaml
tests/test_api_render.py

Fixes https://github.com/conda/conda-build/issues/3308

Fix transitive subpackage dependency resolution

---

conda_build/metadata.py
news/5601-warn-mismatches
tests/test-recipes/metadata/_jinja_outputs/meta.yaml
tests/test_metadata.py

See https://github.com/conda/conda-build/issues/5571#issuecomment-2613973480

Warn if parsed and raw outputs mismatch

---

news/5607-patchelf-0.18
recipe/meta.yaml

Copy `patchelf<0.18` from conda-forge.
Xref https://github.com/conda-forge/conda-build-feedstock/pull/243
Xref https://github.com/conda/conda-build/issues/4881

Set `patchelf<0.18`

---

conda_build/render.py
news/gh5654.rst
tests/test-recipes/metadata/_python_version_independent/meta.yaml

We were doing
```
ignore_run_exports_from:
- python
```
but we should have been doing both
```
ignore_run_exports_from:
- python
ignore_run_exports:
- python
```

python_version_independent: ignore python from other packages too

---

docs/source/resources/define-metadata.rst

A YAML code-block was not rendered because of a missing empty line.
I'm not sure if it is big enough for the news file.

define-metadata.rst: unskip yaml block

---

docs/source/resources/define-metadata.rst
news/5676-add-note-about-build-string

Add recommendation about changing build string value.  When conda is building it's change report it can classify a changed package as an upgrade, downgrade, revised or superseded. For example:
* Change in version: update or downgrade, accordingly.
* Same version, but change in build number: upgrade or downgrade, accordingly.
* Same version and build number, but different build string: changed/adjusted/revised.
* Different channel: superseded.
ref: https://github.com/conda/conda/pull/14727

Add note about build string value
