conda/conda-build

conda_build/build.py
conda_build/metadata.py
conda_build/noarch.py
conda_build/tarcheck.py

Adds support for building no-arch packages.

Add no-arch support to build

---

conda_build/build.py
conda_build/environ.py

Just a merge of master against #268 that fixes #266.

Merged master into ddale's PR

---

conda_build/build.py
conda_build/metadata.py

Fixes #318.
@srossross take a look

Add support for adding a README

---

conda_build/build.py
conda_build/main_build.py

This does change -c from --check to --channels.

Add -c and --override-channels flags to conda-build

---

conda_build/windows.py

Fixes #313.
I haven't tested this yet.
@rsignell-usgs

Look for vcvarsall.bat from the Microsoft Visual C++ Compiler for Python 2.7

---

conda_build/main_pipbuild.py

I still can't get this to work right with via `conda pipbuild invoke --release 0.10.1`, but at least now I'm not seeing SyntaxErrors.

Fix some pipbuild Python 3 compatibility issues.

---

bdist_conda.py

Without this change summary contains `0` for me.

Change source of summary description to metadata

---

conda_build/create_test.py

> 1 test command doesn't work on windows

---

conda_build/convert.py

Change the subdirectory to be that of the final platform

---

conda_build/pypi.py

Fix infinite loop in conda-skeleton

---

CHANGELOG.txt
conda_build/pypi.py

fixes #402
Signed-off-by: Harsh Gupta <gupta.harsh96@gmail.com>

Resolve circular dependencies in conda-skeleton

---

conda_build/build.py
conda_build/config.py

build: Place noarch packages in noarch directory

---

conda_build/main_pipbuild.py

Add noarch option to pipbuild

---

conda_build/main_pipbuild.py

pipbuild: don't check if package already exists

---

bin/conda-sign
conda_build/index.py
conda_build/main_sign.py

This PR allows creating signed conda packages to work in conjunction with https://github.com/conda/conda/pull/1343

Signed packages

---

conda_build/source.py

Attempt to fix issues when git commits have non-ASCII characters in Python 2

---

conda_build/index.py

Catch tarfile.ReadError in conda index

---

conda_build/build.py
conda_build/main_build.py

Fix behaviour with --output for noarch packages

---

conda_build/main_sign.py

See also https://github.com/conda/conda/pull/1399

use Crypto.Signature.PKCS1_PSS module

---

conda_build/build.py
conda_build/cran.py

Otherwise, if the version installed as a build dependency has the same files
as the version being build, a package will be built that don't include those
files.
One can attempt to work around this in the build script by installing some
build dependencies manually, but this is messy will result in a package that
includes its dependencies if not done correctly.

Automatically remove a package of the recipe itself if it is installed as a build dependency

---

conda_build/build.py
tests/test-recipes/metadata/always_include_files_regex/meta.yaml
tests/test-recipes/metadata/always_include_files_regex/run_test.py

add regex to always included files

---

conda_build/cran.py
conda_build/main_build.py
conda_build/main_skeleton.py
conda_build/pypi.py

This requires https://github.com/conda/conda/pull/1443 for tab completion to work with conda-build (although not to work at all, it should just no-op without that pull request).

Some custom tab completers

---

conda_build/main_pipbuild.py

Parenthesise print()

---

conda_build/noarch_python.py

The way that python noarch packages work is completely different from standard packages.  AFAIK, the source is the only documentation of this, so I thought it should have comments and docstrings.

Improvement of noarch_python.py docs

---

conda_build/build.py
conda_build/main_build.py
tests/test-recipes/metadata/jinja2/meta.yaml

@asmeurer, this also fixes the issue in #520. I watched the .trash folder, and it does get removed.

Use trash on windows when deleting environments

---

conda_build/windows.py

Quote set calls in the bld.bat

---

conda_build/build.py
conda_build/main_build.py

Add conda build --no-include-recipe

---

conda_build/main_build.py
tests/test-recipes/build_recipes.sh
tests/test-recipes/fail/recursive-build/meta.yaml
tests/test-recipes/fail/recursive-build2/meta.yaml

Don't recursively build recipes more than once

---

conda_build/environ.py

.git can be a file

---

conda_build/config.py

That way it gets updated properly when CONDA_PY gets updated.
Fixes #565.

Make config.PY3K a property

---

conda_build/windows.py

Fix conda build with newer versions of psutil on Windows

---

conda_build/config.py
conda_build/main_build.py
conda_build/source.py
conda_build/windows.py

This also includes a fix to normalize line endings to UNIX style when Gnuwin patch.exe is used.

Setup for Python 3.5; --force32 option

---

conda_build/config.py
conda_build/main_build.py

Remove --force32 command option

---

conda_build/post.py

Correctly remove egg directories on Windows

---

CHANGELOG.txt
conda_build/metadata.py
conda_build/windows.py

This allows a recipe to force which version of MSVC it builds with.

Force MSVC version

---

conda_build/main_inspect.py

This is a port of scripts/test_installable.py from the anaconda repository.

Add conda inspect channels --test-installable

---

conda_build/post.py

See #45.
I haven't tested this yet.

Add support for absolute rpaths

---

conda_build/main_build.py
conda_build/metadata.py
tests/test_metadata.py

Allow the system to handle versions with have more than a single digit in the minor version.

Numpy 1.10

---

conda_build/metadata.py

Automatically add package features to build string

Auto add build features to build string

---

conda_build.recipe/meta.yaml

This bites me every single time I set up a new computer

BLD: add jinja2 to the run requires

---

conda_build/cran.py
conda_build/environ.py
conda_build/macho.py
conda_build/main_pipbuild.py
conda_build/post.py
conda_build/source.py
conda_build/utils.py

Hello,
This pull requests tries to remove some redundant blocks of code related to the `subprocess.Popen`.
I hope it will be useful. 
Thanks,
Alex

Add a method to shell out and execute a command through subprocess

---

conda_build/build.py

This is a followup PR on https://github.com/conda/conda-build/pull/705

use /bin/sh on openbsd

---

conda_build/main_pipbuild.py

Merges #474 with a simplification to platform detection.
Closes #474 
Closes #331

Fix Win references to PipBuild scripts

---

conda_build/metadata.py
conda_build/source.py

Using a git shallow clone can save a lot of bandwidth in some cases when cloning large repositories.

[WIP] Git shallow clones

---

conda_build/environ.py

Fixes an issue introduced via #758.  If `git_url` points to a local directory instead of a remote url, the `GIT_` variables remained undefined.

Fix GIT_ variables when the repo is local

---

conda_build/main_build.py

Fix printing of NumPy 1.10 in help message

---

conda_build/build.py
conda_build/config.py
conda_build/main_build.py

Fix for using noarch on fresh env (#797)

---

conda_build/cran.py

Python 3 compatibility with cran.py

---

conda_build/environ.py

This PR breaks up the giant `get_dict` function in `environ.py` into logical components.  It's only a refactor, and shouldn't change any of the `get_dict` behavior.

clean up environ.py

---

conda_build/cran.py

@groutr, @ilanschnell, @kalefranz please review. I've left the larger Windows/Unix unification change out until these are dealt with.

Cran updates

---

conda_build/build.py
conda_build/main_build.py

consolidate recipe rendering; ensure source presence before -t

---

conda_build/main_build.py

Fixes an issue where outer lock of build would conflict with inner lock of metadata rendering.  The scope of that lock was far too large, anyway.  Now the lock is applied for each build process, and for each test process, but not in between.
cc @jakirkham

limit scope of locks in main_build

---

conda_build/build.py
conda_build/main_build.py
conda_build/main_render.py
tests/test_build_recipes.py

Merge of #927 with test added.  Also moves locking out of main_build, into build.py (in test and build functions).
Closes #927 (includes it here)
This PR includes a rather sloppy rebase - I got carried away making changes while merging @johanneskoester's conflicts.  Sorry.  @johanneskoester, if that is an issue, I can try to back them out.  Otherwise, more credit for you. =)

reintroduce skip existing

---

conda_build/main_build.py

closes #936 
Please confirm appropriate behavior, @stuarteberg

restore anaconda upload message

---

conda_build/post.py

add deprecation notices to post-build customization methods

---

conda_build/source.py

fixes https://github.com/conda/conda-build/issues/968

Handle -p1 patch level

---

conda_build/external.py
conda_build/scripts.py

Please review @masarahan.
This mirrors what we do in conda when we activate enivornments.

MSYS2: Add build paths

---

tests/test-recipes/metadata/_source_git_jinja2_relative_git_url/meta.yaml
tests/test-recipes/metadata/_source_git_jinja2_relative_path/meta.yaml
tests/test-recipes/metadata/source_git_jinja2/meta.yaml
tests/test_build_recipes.py

refine tests for default values for environ.get in jinja2

---

appveyor.yml
conda_build/environ.py
conda_build/main_build.py
conda_build/render.py
conda_build/source.py
tests/test-recipes/metadata/_pyyaml_find_header/meta.yaml
tests/test-recipes/metadata/always_include_files_glob/meta.yaml
tests/test-recipes/metadata/jinja2_build_str_template_only/meta.yaml
tests/test-recipes/metadata/source_git/meta.yaml
tests/test-recipes/metadata/source_git_jinja2/meta.yaml
tests/test_build_recipes.py
tests/test_render.py

intended to get to root of #993.  This test passes on my system, but my system has VS2010 proper, and does not use the Win 7 SDK.  Appveyor is really the definitive test here.
Fixes #993  (or rather, will, once this PR is done)
CC @jakirkham

[skip ci] Test/fix header finding with Python 3.4/vs2010

---

conda_build/post.py

set empty build section if none exists

---

conda_build/source.py
tests/test_build_recipes.py

@msarahan, another one for you.

patch: Automatically determine patch strip level

---

conda_build/main_inspect.py
tests/test-recipes/metadata/build_string/run_test.sh
tests/test-recipes/metadata/nested_recipe/build_number/run_test.sh
tests/test_build_recipes.py

move check_install over from conda 4.0.8

---

conda_build/main_build.py
tests/test_build_recipes.py

add test for disabling anaconda upload; fix behavior

---

conda_build/windows.py

Fixes #1048 - but needs testing.

handle exception when VS2008 is not installed

---

conda_build/windows.py

Reg.get_value apparently throws when it doesn't find a key, rather than the more pythonic approach of returning None.  This wraps that section with a try statement, and falls back to only looking for VS 2010.  Failing to find VS 2010 is totally OK - you'll see some error message in the build log about it, but it won't kill builds.
Fixes #1048 (for Python 3.3/3.4)

Fix msvc for Python 3.3/3.4 builds when no MS SDK present

---

conda_build/build.py

thanks to @mingwandroid for suggestion.
Closes #1070

be more graceful when finding vcs executable fails

---

conda_build/utils.py
tests/test_utils.py

fix PEP420 namespace packages

---

conda_build/source.py

This wraps calls to different vcs systems with a try block.  It returns basic file modified times instead of revision information in case of failure, and logs a debug message.
Closes #1018

warn users if getting origin data fails, rather than crash

---

conda_build/build.py
tests/test_build_recipes.py

make python tests drop out on win on failure

---

conda_build/build.py
conda_build/tarcheck.py

Fixes https://github.com/Anaconda-Platform/anaconda-server/issues/2565#issuecomment-234570243 - thanks to @mcg1969 for his assistance.

add dist split for channel names

---

conda_build/build.py
conda_build/exceptions.py
conda_build/jinja_context.py
conda_build/main_build.py
conda_build/main_render.py
conda_build/metadata.py
conda_build/render.py
conda_build/source.py
conda_build/utils.py
tests/test_build_recipes.py

Fixes #1138 
I think this also fixes #1133, but need to confirm.

provide fallback when rendering fails to try again in build env

---

tests/test-recipes/metadata/_requirements_txt_run_reqs/meta.yaml
tests/test-recipes/metadata/_requirements_txt_run_reqs/requirements.txt
tests/test-recipes/metadata/_requirements_txt_run_reqs/run_test.py
tests/test-skeleton/test_skeleton.py
tests/test_build_recipes.py

Intended to explore https://github.com/Anaconda-Platform/anaconda-server/issues/2565 - I was hoping that this would show the error from that issue, but it does not seem to.  More commentary at that issue.

add test of requirements.txt parsing

---

conda_build/pypi.py
tests/test-skeleton/test_skeleton.py

Fixes #1139 - version sorting anyway.

sort package versions from PyPI.  Add test.

---

conda_build/metadata.py
tests/test-recipes/metadata/_source_setuptools_env_var/meta.yaml
tests/test-recipes/test-package/setup.py
tests/test_build_recipes.py

Ping @janssen for comment.  This is meant to be my implementation of our discussion in https://github.com/conda/conda-build/issues/1023#issuecomment-236064273

add CONDA_BUILD_RENDERING env var that is set while rendering

---

conda_build/build.py

Hi @msarahan, I ran into this just now.

Re-evaluate prefix when need to use 80 char version

---

conda_build/metadata.py

do not force download if vcs is used as source

---

conda_build/build.py
conda_build/utils.py

make env vars be byte strings on win

---

conda_build/config.py

These should help with builds having unsatisfiable dependencies.

update perl (5.20.3) and R (3.3.1) default versions

---

conda_build/cran.py
conda_build/pypi.py
conda_build/source.py
conda_build/utils.py
tests/test_build_recipes.py

Hey @masrahan, see what you think about these for the release.
closes #1126 
closes #1190

relatively pathed git submodules; git am for patching; guess license family

---

conda_build/conda_interface.py
conda_build/cran.py
conda_build/main_convert.py
conda_build/source.py
tests/test-skeleton/sympy-0.7.5-url/meta.yaml
tests/test-skeleton/sympy-0.7.5/meta.yaml

Pypi license family

---

conda_build/convert.py

when package has no hard py-version dependency.
Conda convert only worked correctly when python dependency in the recipe was given as:
python X.X*
Any other specification (python >=X.X) or no version specification would prevent convert convert from translating the file structure "lib/pythonX:X/..." to "Lib/.." on windows.
We don't really need the version number when converting from linux to windows. The python version number is not part of the file structure on windows. It is only really needed if we convert the other way, because we need to know if the files should go into lib/python2.7/... or lib/python3.4/...

Fix error in conda convert (linux to win package) 

---

conda_build/convert.py
conda_build/environ.py
conda_build/source.py
tests/test-recipes/metadata/source_hg_jinja2/bld.bat
tests/test-recipes/metadata/source_hg_jinja2/build.sh
tests/test-recipes/metadata/source_hg_jinja2/meta.yaml

Add HG vars to jinja2

---

conda_build/build.py

create environment before looking for VCS in it.  Recreate as necessary

---

.travis.yml
appveyor.yml
conda_build/cli/main_build.py
conda_build/environ.py
conda_build/jinja_context.py
conda_build/render.py
conda_build/utils.py
tests/test-recipes/metadata/_numpy_setup_py_data/meta.yaml
tests/test_api_build.py

Fixes #1241.  Exposed a few bugs - the example project is untagged, and the git stuff barfed all over it.  Good opportunity to fix that.
cc @bladwig1

add numpy setup.py data reader.  Fix bugs that this exposed.

---

.travis.yml
appveyor.yml
conda.recipe/meta.yaml
conda_build/api.py
conda_build/build.py
conda_build/cli/main_build.py
conda_build/cli/main_inspect.py
conda_build/config.py
conda_build/tarcheck.py
conda_build/utils.py
tests/test_build.py

Fix deadlock in create env

---

bin/conda-pipbuild
conda.recipe/meta.yaml
setup.py

remove remnants of pipbuild

---

tests/test_api_build.py

re-add test of submodule checkout from b6090af75923

---

conda_build/utils.py

Add Scripts to the prepended paths

---

conda_build/metadata.py
tests/test-recipes/fail/pip_reqs_fail_informatively/meta.yaml
tests/test_api_build.py

fixes #1170 
Please comment on the message here @mcg1969 @postelrich @Godley - is it clear enough, or would some other way of saying it be better?

add more informative message about pip reqs not allowed in meta.yaml

---

conda_build/create_test.py
conda_build/metadata.py
tests/test-recipes/fail/backslash_in_include_files/meta.yaml
tests/test-recipes/metadata/_backslash_in_include_files/meta.yaml
tests/test-recipes/metadata/always_include_files_glob/meta.yaml
tests/test_api_build.py

fixes #1194 
CC @janschulz @jakirkham

disallow backslashes in always_include_files pattern matching

---

conda_build/build.py
conda_build/source.py
conda_build/utils.py
conda_build/windows.py
tests/test_api_build.py

Hi @masarhan, please review this.

Build environment used during tooling and testing.

---

conda_build/cli/main_inspect.py
tests/test_cli.py

restore prefix-lengths inspect command

---

conda_build/post.py

update post-build versioning deprecation warning; update link

---

conda_build/build.py

create pkgs folder to lock if not exist

---

conda_build/build.py
conda_build/index.py
tests/test_build.py

rework warning for old conda-build; add test

---

conda_build/build.py
conda_build/convert.py
conda_build/environ.py
conda_build/metadata.py
conda_build/tarcheck.py
conda_build/utils.py
tests/test_cli.py

fix convert not updating subdir in index.json

---

conda_build/post.py
tests/test_api_build.py
tests/test_post.py
tests/utils.py

remove pycache removal

---

conda_build/build.py
conda_build/conda_interface.py

Hey @msarahan, this bit me again today .. no more!

conda_interface: Handle conda >=4.2 too-short-prefix

---

conda_build/convert.py
tests/test_api_convert.py

Fixes #1324 
Write_info was a completely extraneous function.  It was breaking things that were already done in the path mapping function
CC @talumbau

add test for convert that checks file contents.  Fix problems.

---

conda_build/source.py

Fixes #1320 
@wulmer, please suggest a test, if you can.  I'm not sure how I can test this, short of setting up a git server somewhere (perhaps a temporary localhost server would suffice).

replace all colons with _ to avoid Windows path errors

---

.travis.yml
bdist_conda.py
conda_build/api.py
conda_build/build.py
conda_build/conda_interface.py
conda_build/convert.py
conda_build/index.py
tests/bdist-recipe/setup.py
tests/test-recipes/dummy_dependency/meta.yaml
tests/test-recipes/metadata/_condarc_channel/meta.yaml
tests/test-recipes/metadata/_recipe_requiring_external_channel/meta.yaml
tests/test_api_build.py
tests/test_api_render.py
tests/test_api_test.py
tests/test_build.py
tests/utils.py

These files sometimes stick around, leading frustratingly to cached packages showing up in tests.  Very confusing.  Hopefully this helps.

remove existing package with rm_rf instead of conda.

---

conda_build/cli/main_build.py
conda_build/config.py
conda_build/utils.py
tests/test_cli.py

CC @pitrou - I think this is what you were looking for.

add purge-all command to clean up built packages

---

conda_build/post.py
conda_build/utils.py

Placates `anaconda-verify` and saves some junk from getting into our packages.
I slipped the `LGPL` thing in too as it's so minor. If that's a problem I can revisit.

More pyo pyc

---

conda_build/inspect.py

fix erroneous file argument to logging call

---

conda_build/config.py

This fixes a bug where CONDA_NPY was not set when using the CONDA_NPY environment variable only.

Fix availability of CONDA_NPY when rendering recipe.

---

conda_build/cli/main_build.py
conda_build/config.py
conda_build/post.py
tests/test_cli.py

PR aimed at fixing some of the CI issues that are bothering us.

add --croot build arg; contain cli test more

---

conda_build/build.py
conda_build/config.py
conda_build/render.py
tests/test_cli.py

fix --no-build-id argument to build (actually respect it)

---

conda_build/build.py
conda_build/config.py
tests/test_cli.py

fix trailing slash hiding package folder name in build id

---

conda_build/build.py
conda_build/conda_interface.py

handle LinkError from Conda 4.2 appropriately

---

conda_build/build.py
conda_build/index.py

As we know it is not a mirror.
@msarahan, @dsludwig, @ilanschnell, @quasiben please check that this looks reasonable.

Do not fatal on index if _license package in ${CONDA_PREFIX}/pkgs

---

tests/test_api_build.py

We have intermittent CI failures without this.  This should address some of them - at least the ones that this test causes.
Story: If you have multiple CI workers all trying to create, read, or verify non-existence of one package on anaconda.org at once, you're going to have an unpredictable time.

add uuid to token upload test to avoid race conditions

---

conda_build/render.py
tests/test_render.py

fix noarch in output path for noarch packages

---

conda_build/build.py
conda_build/cli/main_build.py
conda_build/config.py
conda_build/create_test.py
conda_build/environ.py
conda_build/jinja_context.py
conda_build/post.py
conda_build/source.py
conda_build/windows.py
tests/test-recipes/published_code/building_jinja2_direct_env_vars/meta.yaml
tests/test-recipes/published_code/building_jinja2_environ/meta.yaml
tests/test-recipes/published_code/building_jinja2_setup_py_data/meta.yaml
tests/test_api_build.py
tests/test_published_examples.py

roll source_dir into config.work_dir; add tests for published jinja2

---

conda_build/build.py
conda_build/post.py

Curious if this is an answer to https://github.com/conda/conda-build/pull/869#pullrequestreview-1424290
@asmeurer is having trouble with just stat here - possibly with a broken symlink?

try lstat and stat before memmapping

---

conda_build/utils.py

This was having problems on Windows only.  Passes tests locally, now.

simplify and fix locking in copy/merge

---

conda_build/utils.py

This was just plain wrong.  It was causing problems with some code paths in packaging files.

fix path walking in get_ext_files

---

conda_build/config.py
tests/test_config.py

Thought here is that it's better to present people with the api to change platform and bits independently, rather than setting subdir as the combination of the two.

make subdir a derived property.  test.

---

conda_build/skeletons/pypi.py
tests/test_api_skeleton.py

fix regression in pypi skel for recipes with entry points.  test.

---

conda_build/utils.py

Fixes #1426 
I have not been able to reproduce the problem, but based on discussion in that issue, this is probably the fix.  @janssen, if you can test this, I'd be grateful.

fall back to copying fewer attributes if copy fails with OSError

---

conda_build/cli/main_build.py
conda_build/render.py
conda_build/source.py
conda_build/utils.py
tests/test_api_test.py

fix source re-copy (leading to IOError) with test as separate ste

---

conda_build/build.py
conda_build/windows.py

quote paths in activation of envs

---

conda_build/build.py
conda_build/cli/main_build.py
tests/test_build.py
tests/test_cli.py
tests/utils.py

prepend conda's PATH, in case it isn't on PATH already

---

conda_build/api.py
tests/test_api_skeleton.py

Fixes #1442 
Issue basically was that we were unhappily merging (or not) the arguments from the CLI into the API.

fix version argument to skel pypi not working

---

conda_build/build.py
conda_build/conda_interface.py
conda_build/utils.py

fix infinite recursion when missing dependency is R or python

---

.travis.yml
conda_build/build.py
conda_build/conda_interface.py

This also adds a test build on travis for 4.1.
Fixes #1459

fix compatibility with conda 4.1.x

---

conda_build/metapackage.py

fix metapackage not going through api build

---

conda_build/utils.py
tests/test-recipes/metadata/empty_patch_section/meta.yaml

fix lists of empty strings created by ensure_list

---

conda_build/metadata.py
tests/test_metadata.py

Fixes #1497 #1488 
Adds tests for hopefully not seeing this again.

fix overly broad regex for hg in uses_vcs_in_build

---

conda_build/build.py
conda_build/config.py
conda_build/environ.py
conda_build/index.py
conda_build/utils.py
tests/test_config.py

Fix arch, simplify locks

---

conda_build/metadata.py
conda_build/render.py

for external usage (conda-concourse-ci)

break build string construction out into standalone function

---

conda_build/skeletons/cpan.py

fix perl version comparison sometimes being str-int uncomparable

---

conda_build/utils.py

ignore broken symlinks in copying files

---

conda_build/build.py

it was not always being found...

specify conda exe more specifically for Windows

---

conda_build/build.py
conda_build/conda_interface.py
conda_build/config.py

make conda verify config use condarc and be more back compat

---

conda_build/build.py
tests/test_api_build.py
tests/test_build.py

as per request of @ilanschnell

Rename short_path to path in files.json

---

conda_build/build.py

Don't compute sha256 for folders

---

conda_build/utils.py

fix merge check for dst starting with src

---

conda_build/post.py

use normpath when comparing utils.relative

---

conda_build/metadata.py

allow source_files in recipe check

---

.travis.yml
appveyor.yml
setup.cfg
tests/test_api_build.py
tests/test_cli.py
tests/utils.py

Hopefully fix recurrent CI failures due to race conditions

make purge test run serially

---

.travis.yml
appveyor.yml
conda_build/api.py
conda_build/build.py
conda_build/metadata.py
conda_build/utils.py
tests/test_api_build.py
tests/test_cli.py
tests/test_metadata.py
tests/test_utils.py

allow wildcard expressions for inputs to api.build

---

conda_build/build.py

Fixes https://github.com/conda/conda-build/issues/1588. Any ideas how a test for this would be structured?

Fix bug corrupting rendered meta.yaml from conda build

---

conda_build/metadata.py
tests/test_metadata.py

disallow leading period in version

---

conda_build/api.py
conda_build/render.py
tests/test_api_render.py

fix undefined reference to need_source_download

---

conda_build/skeletons/cran.py

Further:
* change URLs to https
* download source and calculate sha256 (when using CRAN and not github)
This PR is part of the effort to port the R channel to conda-forge (see issue conda-forge/staged-recipes#2009).

Change CRAN-skeleton to follow conda-forge style. 

---

conda_build/metadata.py
tests/test_metadata.py

disallow - character in features

---

conda_build/cli/main_render.py

remove help text about passing multiple options

---

conda_build/build.py
tests/test_cli.py

fix index when output-folder is specified

---

conda_build/config.py
conda_build/utils.py

This is causing an incompatibility with conda 4.3.

fix/simplify usage of python_d.exe on win if it exists

---

.travis.yml

@msarahan I think this is a better alternative to https://github.com/conda/conda-build/pull/1627

test against any conda tag

---

conda_build/skeletons/cpan.py

fix version comparison in cpan skeleton

---

conda_build/utils.py

fix undefined ref to locks in copy_into

---

conda_build/build.py
tests/test_build.py

filter .git directories, but not x.git ones

---

conda_build/cli/main_build.py
tests/test_cli.py

fix --source option to conda build to download source; test

---

conda_build/build.py
tests/test-recipes/metadata/ds_store_ignored/meta.yaml

ignore .DS_Store files when packaging.  Thanks, Apple.

---

.travis.yml
conda_build/api.py
conda_build/build.py
conda_build/conda_interface.py
conda_build/metadata.py
conda_build/skeletons/cpan.py
conda_build/utils.py
tests/test-recipes/metadata/_preferred_env/bld.bat
tests/test-recipes/metadata/_preferred_env/build.sh
tests/test-recipes/metadata/_preferred_env/meta.yaml
tests/test_api_build.py
tests/test_api_sign.py
tests/test_api_skeleton.py
tests/test_build.py
tests/test_cli.py

fixes #1650 
fixes #1652
fixes #1654

Conda 4.3 compatibility - fix

---

conda_build/skeletons/cpan.py

Thank goodness the web is pretty standard about utf-8.

read cpan json file as utf-8 to fix windows

---

conda_build/build.py

depends on https://github.com/conda/conda/pull/4388

add retry for conda version error that happens if info/files missing

---

conda_build/metadata.py
conda_build/skeletons/cran.py
tests/test_api_skeleton.py

Cran GitHub

---

conda_build/skeletons/pypi.py
tests/test_api_skeleton.py

Proposed solution to Issue #1697.
- the documentation / guides may need changes.
- we may be able to change the current numpy heuristics to the default value of --extra-specs.

WIP: --extra-specs for conda-skeleton.

---

conda_build/index.py

fix unbound local error due to undefined 'locks' in update_index

---

conda_build/utils.py

fix glob acting on strangely named files that matched glob patterns

---

conda_build/config.py

Solution: make any path absolute

Problem: Croot path cannot be relative

---

conda_build/build.py
conda_build/conda_interface.py
conda_build/environ.py
tests/test_api_build.py

Fixes #1726 
CC @dsludwig @kalefranz 
Kale, I'm doing a not-very-nice import from conda here.  I want to talk with you about how to best use the Dist class - should it be one of the exports?

fix and test pin_depends with conda 4.3

---

.travis.yml
conda_build/conda_interface.py
conda_build/convert.py
conda_build/license_family.py
conda_build/metadata.py
conda_build/render.py
conda_build/skeletons/pypi.py
conda_build/utils.py
setup.cfg
tests/test_license_family.py

unify allowed license families with anaconda-verify

---

.travis.yml
conda_build/utils.py

Test by disallowing write to central lock folder on travis.
Fixes #1745 #1601

provide lock directory fallback path in user home.  

---

conda_build/skeletons/cpan.py
conda_build/skeletons/pypi.py

fixes #1722 #1741 
but you still need to specify --recursive in order to output each recipe.

fix pypi recipe recursion

---

conda_build/build.py
conda_build/metadata.py
conda_build/render.py
tests/test-recipes/metadata/_source_git_jinja2_relative_git_url/meta.yaml
tests/test-recipes/metadata/extra_freeform_metadata/run_test.py
tests/test_metadata.py

fix leading period error on non-final renderings with default values

---

conda.recipe/meta.yaml
tests/test_api_build.py

Build fixup

---

conda_build/build.py
conda_build/post.py
conda_build/utils.py
tests/test-recipes/metadata/symlinks/build.sh
tests/test-recipes/metadata/symlinks/meta.yaml
tests/test-recipes/metadata/symlinks/run_test.sh

fix symlinked folders not getting picked up in packaging. test.

---

conda_build/build.py
conda_build/post.py
tests/test_api_build.py

fixes #1302
@jakirkham please test

try mmap, fall back to just plain file handle

---

conda_build/api.py
conda_build/build.py
conda_build/cli/main_build.py
conda_build/cli/main_render.py
conda_build/inspect.py
conda_build/jinja_context.py
conda_build/metadata.py
conda_build/render.py
tests/test-recipes/metadata/_pin_compatible/meta.yaml
tests/test-recipes/split-packages/script_install_files/meta.yaml
tests/test_api_build.py
tests/test_metadata.py
tests/test_subpackages.py

Discovered some necessary changes when testing new compiler packages with dakota recipe.

simplify compiler jinja2 (no host)

---

appveyor.yml
conda_build/build.py
conda_build/render.py
tests/test-recipes/metadata/symlinks/build.sh
tests/test-recipes/metadata/symlinks/run_test.sh

Note: for conda 4.3, this requires the fix at https://github.com/conda/conda/pull/4759
This works as-is for conda 4.2.
Fixes #1769

fix symlinks to folders in packaging

---

conda_build/variants.py
tests/test_variants.py

Some dimensions are not actually independent.  For example, most of the time, we want python version and vc to be coupled.  This PR implements a mechanism to describe that coupling.
Rather than 4 variants for the following:
```
python:
- 2.7
- 3.5
vc:
- 9
- 14
zip_keys:
- python
- vc
```
this PR produces only 2 - python 2.7 is associated with vc 9 and python 3.5 is associated with vc 14.

implement zip_keys to pair variant dimensions (e.g. python/vc)

---

conda_build/source.py

Clarify git root env

---

conda_build/source.py

don't die when unicode found in patches

---

conda_build/build.py

fix attribute error in exception handling for dep

---

conda_build/config.py

make test prefix also use placeholder

---

conda_build/_link.py
conda_build/build.py
conda_build/config.py
conda_build/create_test.py
conda_build/environ.py
conda_build/metadata.py
conda_build/noarch_python.py
conda_build/render.py
conda_build/utils.py
tests/test_api_build.py

Fix test env vars

---

conda_build/inspect.py

convert depmap keys from Dist objects in conda 4.3

---

conda_build/conda_interface.py

This is what I'd recommend, given how we also neutered the same function in the conda code via https://github.com/conda/conda/pull/4867.

fix #1825 monkey patch ensure_use_local

---

conda_build/inspect.py

properly initialize empty list for system linkages

---

conda_build/convert.py

catch csv dialect sniffing error.  Fall back to excel_tab.

---

conda_build/metadata.py
tests/test-recipes/split-packages/_intradependencies/install-py1-intradependencies.sh
tests/test-recipes/split-packages/_intradependencies/install-py2-intradependencies.sh
tests/test-recipes/split-packages/_intradependencies/install-r1-intradependencies.sh
tests/test-recipes/split-packages/_intradependencies/install-r2-intradependencies.sh

Mostly the removal of 'intradependencies' is important here.

Hash stuff

---

conda_build/environ.py

Theano needs this at test-time.

Add another Windows environment var (NUMBER_OF_PROCESSORS)

---

conda_build/utils.py
tests/test_utils.py

Set permissions when extracting from a zipfile

---

conda_build/environ.py

even if tags are not
fixes #1846 
CC @ betranjacob

reduce scope of git try/except block so GIT_FULL_HASH is available

---

conda_build/license_family.py
tests/test_license_family.py

fix license family comparison, especially for public-domain

---

conda_build/create_test.py

remove header in create_test - let users do what they want.

---

conda_build/skeletons/cran.py

Calculate checksum and simplify cran skeleton.

---

conda_build/build.py
conda_build/environ.py
conda_build/render.py

4 fixes I'm happy with, sorry it's not a commit per topic!

Upstreaming

---

.travis.yml
conda_build/create_test.py
tests/test_api_skeleton.py
tests/test_cli.py
tests/test_create_test.py

CC @jjhelmus - this backports your fix to 2.1.x and adds tests.

Add create test tests

---

conda_build/post.py
tests/test-recipes/metadata/post_build_versioning/bld.bat
tests/test-recipes/metadata/post_build_versioning/build.sh
tests/test-recipes/metadata/post_build_versioning/meta.yaml
tests/test_post.py

CC @dsludwig - this will go into the 3.0.0 release.  I'll ping you again when that is imminent.  Let me know if you need help adapting any of your projects.
I might do some more work here to raise errors if someone tries to use post-build versioning.

remove post-build versioning

---

conda_build/build.py
tests/test_api_build.py

fix cleanup happening even when build fails

---

conda_build/build.py
conda_build/metadata.py

fix bin/conda getting included in conda-build packages

---

conda_build/build.py

backport bin/conda exclusion from master

---

conda_build/build.py
tests/test_published_examples.py
tests/utils.py

Fix conda bin being included in packages starting with "conda-"

---

conda_build/build.py
conda_build/config.py
conda_build/metadata.py
tests/test-recipes/split-packages/_entry_points/install-pkg1.sh
tests/test-recipes/split-packages/_entry_points/install-pkg2.sh
tests/test-recipes/split-packages/_entry_points/meta.yaml
tests/test-recipes/split-packages/_entry_points/test-pkg1.py
tests/test-recipes/split-packages/_entry_points/test-pkg2.py
tests/test_api_build.py
tests/test_subpackages.py
tests/test_utils.py

fix entry points, test commands, test imports not being separated

---

conda_build/build.py
conda_build/environ.py
conda_build/post.py
conda_build/utils.py
tests/test-recipes/metadata/_lua_env_defined/meta.yaml
tests/test-recipes/metadata/_lua_env_defined/run_test.py
tests/test-recipes/metadata/_perl_env_defined/meta.yaml
tests/test-recipes/metadata/_perl_env_defined/run_test.py
tests/test-recipes/metadata/_r_env_defined/meta.yaml
tests/test-recipes/metadata/_r_env_defined/run_test.py
tests/test-recipes/metadata/python_env_defined/meta.yaml
tests/test-recipes/metadata/python_env_defined/run_test.py
tests/test_api_build.py

Language version vars 3

---

conda_build/metadata.py

I ran into this problem building spyder 3.1.4

Do not add python.app to run_reqs multiple times

---

conda_build/utils.py

try to pipe stdin for better ctrl-c handling with conda

---

conda_build/conda_interface.py
conda_build/metadata.py
tests/test-recipes/split-packages/_about_metadata/meta.yaml
tests/test_subpackages.py

allow about section for each output

---

conda_build/api.py
conda_build/build.py
conda_build/conda_interface.py
conda_build/config.py
conda_build/environ.py
conda_build/index.py
conda_build/jinja_context.py
conda_build/metadata.py
conda_build/render.py
tests/test-recipes/metadata/_keep_work_dir/conda_build_config.yaml
tests/test-recipes/metadata/_keep_work_dir/meta.yaml
tests/test-recipes/variants/11_variant_output_names/conda_build_config.yaml
tests/test-recipes/variants/11_variant_output_names/meta.yaml
tests/test_api_build.py
tests/test_api_consistency.py
tests/test_cli.py
tests/test_config.py
tests/test_metadata.py
tests/test_variants.py

We discovered a number of issues with the cross-compiling support recently.  This PR is still failing with several git-jinja2 related failures.  These have to do with work_dir not matching up and source code not being present.
I'm going to come back to this late Sunday or first thing Monday.

WIP: Fix cross compiling

---

conda_build/build.py
conda_build/config.py
tests/test_api_build.py

Fixes #1883 
Needs backport to 2.1.x
@davidslac @joelhullcio if you have time, I'd appreciate any testing you can do here.

ensure that lock files are removed to avoid permission errors

---

conda_build/build.py
conda_build/config.py
conda_build/utils.py
tests/test_api_build.py

backport #2002 to 2.1.x
fixes #1883

backport lock cleanup from master

---

appveyor.yml
conda_build/build.py
conda_build/create_test.py
conda_build/post.py
conda_build/render.py
conda_build/utils.py
tests/test-recipes/metadata/preserve_egg_dir/meta.yaml
tests/test-recipes/test-package/setup.py

fix missing arg to get_site_packages; test

---

conda_build/build.py
conda_build/cli/main_render.py
conda_build/config.py
conda_build/metadata.py
tests/test_api_build.py
tests/test_cli.py

closes #1919 
Please review @ilanschnell

implement --old-build-string option (no hash in filename)

---

conda_build/jinja_context.py
conda_build/metadata.py
conda_build/render.py
tests/test-recipes/split-packages/_intradependencies_circular/meta.yaml
tests/test_subpackages.py

test and fix handling of cyclical intradependencies

---

conda_build/utils.py
tests/test_cli.py
tests/test_variants.py

memoize package_has_file to speed up pin_compatible

---

conda_build/source.py
tests/test_api_build.py
tests/test_patch.py

fall back to converting to unix line endings.
Continuation of #2035
CC @rolando - I think this should fix things.

on win, try to patch without changing line endings

---

conda_build/config.py
conda_build/jinja_context.py
conda_build/variants.py

Thanks to @kalefranz and @mandeep for helping to find this.

fix handling of platforms containing - characters

---

conda_build/build.py
conda_build/cli/main_build.py
conda_build/config.py
tests/test_api_build.py
tests/test_cli.py

add CLI flag and condarc setting to disable --force for anaconda-upload

---

conda_build/environ.py

add Windows env vars passthrough related to CPU info

---

conda_build/build.py
conda_build/environ.py

reduce verbosity of git info messages

---

conda_build/inspect.py

fix inspect commands not working with plain string input

---

conda_build/api.py
conda_build/cli/main_inspect.py
conda_build/inspect.py
conda_build/os_utils/ldd.py
conda_build/os_utils/pyldd.py
conda_build/post.py
tests/test_api_consistency.py

For now, both ldd/otool and pyldd are used and disparities are warned about.

Add pyldd and use it when ldd/otool fails

---

conda_build/build.py
conda_build/metadata.py
setup.cfg

fix wheel not matching configured python version, fix wheel output

---

.travis.yml
appveyor.yml
conda_build/api.py
conda_build/build.py
conda_build/config.py
conda_build/environ.py
conda_build/index.py
conda_build/jinja_context.py
conda_build/metadata.py
conda_build/render.py
conda_build/skeletons/pypi.py
conda_build/utils.py
tests/conftest.py
tests/test-recipes/fail/recursive-build/meta.yaml
tests/test-recipes/metadata/_checkout_tool_as_dependency/meta.yaml
tests/test-recipes/split-packages/_hash_inputs/build.sh
tests/test-recipes/split-packages/_hash_inputs/install-script.sh
tests/test-recipes/split-packages/_hash_inputs/meta.yaml
tests/test-recipes/split-packages/_hash_inputs/run_test.py
tests/test-recipes/split-packages/_hash_inputs/test-script.sh
tests/test_api_build.py
tests/test_api_render.py
tests/test_build.py
tests/test_cli.py
tests/test_environ.py
tests/test_jinja_context.py
tests/test_metadata.py
tests/test_subpackages.py
tests/test_variants.py

Narrow hash file scope

---

conda_build/skeletons/cran.py

Please review @msarahan, @johanneskoester

skeleton: Fix some problems with cran

---

conda_build/convert.py
tests/test_api_convert.py

fixes #2085
It looks like dependencies weren't being passed to the get_pure_py_file_map function from the conda_convert function. I added logic in conda_convert to deal with dependencies and added an argument to get_pure_py_file_map to accept these dependencies. This fix includes a test that converts a package with two dependencies and checks that these dependencies are listed in index.json.

Fixed issue in conda_convert where dependencies weren't being added

---

conda_build/convert.py
tests/test_api_convert.py

Backported conda convert dependency fix from conda-build 3.0.0

---

conda_build/cli/main_convert.py
conda_build/convert.py
tests/test_api_convert.py

There are still some tests that I would like to add to this branch; however, I believe everything in convert.py is ready.

Convert rewrite [WIP]

---

conda_build/build.py
conda_build/convert.py
tests/test-recipes/metadata/_disable_pip/bld.bat
tests/test-recipes/metadata/_disable_pip/build.sh
tests/test-recipes/metadata/_disable_pip/build_script.py
tests/test-recipes/metadata/_disable_pip/meta.yaml
tests/test_api_build.py

fix disable_pip removing packages even when they are explicit deps

---

conda_build/_load_setup_py_data.py

drop setup.py data that is unserializable

---

conda_build/environ.py

Clarify suggestion to use annotated tags

Improve error message when git describe fails

---

conda_build/render.py

This exhibited terrible behavior for packages using both python and numpy - or anything that used two packages for which variant values existed.  Only one variant value would "take".

fix variant pinning that would only affect one package

---

conda_build/cli/main_build.py
conda_build/cli/main_render.py
tests/test_cli.py

fix logging output in --output output.  Fix tests.

---

conda_build/config.py
tests/test_cli.py

fix CONDA_* variables without .

---

conda_build/source.py

pass croot to extraction

---

conda_build/build.py

fix incorrect unpacking of metadata tuples

---

conda_build/_load_setup_py_data.py
conda_build/jinja_context.py
tests/test_jinja_context.py

fixes #2164 - thanks @mbargull

fix priority of setup.cfg over setup.py

---

conda_build/build.py
conda_build/environ.py
conda_build/skeletons/rpm.py

.. as determined by the contents of `always_include_files`

HACK: Do not SYMLINK_CONDA when building conda

---

conda_build/build.py
conda_build/config.py
tests/test_api_build.py
tests/test_cli.py

test and fix --skip-existing

---

conda_build/environ.py
conda_build/metadata.py
conda_build/render.py
tests/test-recipes/metadata/_numpy_xx/meta.yaml
tests/test-recipes/metadata/_numpy_xx/run_test.bat
tests/test-recipes/metadata/_numpy_xx/run_test.py
tests/test-recipes/metadata/_numpy_xx/run_test.sh
tests/test-recipes/metadata/_numpy_xx_host/meta.yaml
tests/test-recipes/metadata/_numpy_xx_host/run_test.bat
tests/test-recipes/metadata/_numpy_xx_host/run_test.py
tests/test-recipes/metadata/_numpy_xx_host/run_test.sh
tests/test-recipes/metadata/_pin_compatible/meta.yaml
tests/test_api_build.py
tests/test_api_render.py

test and fix numpy x.x

---

conda_build/build.py
tests/test_cli.py

include 'local' alias that conda is being overly helpful with

---

conda_build/environ.py
conda_build/render.py
tests/test-recipes/metadata/_python_xx/meta.yaml
tests/test-recipes/metadata/_python_xx/run_test.bat
tests/test-recipes/metadata/_python_xx/run_test.py
tests/test-recipes/metadata/_python_xx/run_test.sh
tests/test_api_build.py

fix and test python x.x

---

conda_build/render.py
tests/test_api_build.py

fix default variant introducing version conflicts in indirect deps

---

conda_build/environ.py
conda_build/metadata.py
conda_build/render.py
conda_build/utils.py
tests/test_environ.py
tests/test_render.py
tests/test_utils.py

properly insert variant versions for x.x in outputs

---

conda_build/utils.py
conda_build/variants.py
tests/test-recipes/metadata/_numpy_xx/meta.yaml

relax default perl, lua, and r_base versions to avoid unsatisfiability

---

conda_build/api.py
conda_build/build.py
conda_build/config.py
conda_build/noarch_python.py
conda_build/render.py
tests/conftest.py
tests/test-recipes/metadata/_preferred_env/bld.bat
tests/test_api_render.py
tests/test_metadata.py
tests/test_variants.py

This is primarily a concern for c3i, but will come up for other people at some point, probably.

fix skipping finalization; fix looping for implicit variants

---

conda_build/build.py
conda_build/render.py
tests/test-recipes/metadata/empty_sections/meta.yaml
tests/test_cli.py

try to avoid downloading until it's truly necessary

---

conda_build/build.py

@mingwandroid - this should fix you, but I'd also appreciate if you could help me understand exactly what you were doing, so I can write a test.

fix test python not using correct metadata config object

---

conda_build/_load_setup_py_data.py

This is causing our tests to fail unless we ignore warnings ;(

Fix "ResourceWarning: unclosed file"

---

conda_build/environ.py
conda_build/metadata.py
tests/test-recipes/metadata/_activate_scripts_not_included/meta.yaml
tests/test_cli.py

fix win activate scripts appearing in packages; test

---

conda_build/build.py
tests/test_api_test.py

fix testing with recipe arguments

---

conda_build/cli/main_render.py
tests/test_cli.py

This aims to fix the problem that `conda-render` ignored channel settings provided on the command line (#2266) by copying over the respective code snippet from `conda_build/cli/main_build.py`.
The PR includes a test for success and failure depending on whether the channel is provided as command line flag or not. The check for success is currently whether the rendered `meta.yaml` contains the correct version number for the required package or not. @msarahan I'm not sure whether that's too much of an assumption that the version number is present. If you have better criteria in mind, I'm happy to change that.

Consider channels specified via CLI in conda-render

---

conda_build/render.py

.. otherwise --override-channels does nothing.

Pass omit_defaults=m.config.override_channels to get_build_index

---

conda_build/cli/main_build.py
conda_build/config.py

respect conda_build/cache_dir setting in condarc for source cache dir

---

conda_build/source.py
tests/test_source.py

fix hoisting when folder names are the same

---

conda_build/post.py

Allow binary_relocation to specify a list of files

---

conda_build/environ.py

This is hard-coded, sorry.
I also re-arranged the imports to keep flake8 happ{y,ier}

Set BUILD env. var

---

conda_build/environ.py

Default MACOSX_DEPLOYMENT_TARGET to 10.9

---

conda_build/environ.py

read MACOSX_DEPLOYMENT_TARGET from variant

---

conda_build/build.py
conda_build/environ.py
conda_build/metadata.py
conda_build/render.py
tests/test-recipes/metadata/_pin_depends_record/meta.yaml
tests/test-recipes/metadata/_pin_depends_strict/meta.yaml
tests/test_api_build.py
tests/test_api_render.py

@ilanschnell I believe this maintains your original behavior.  I'd appreciate it if you have time to review this and make sure.
cc @mingwandroid

modernize pin_depends for availability in render phase

---

conda_build/build.py

update index before testing .tar.bz2 and after moving failed

---

conda_build/render.py

fix --output to respect --output-folder arg

---

conda_build/environ.py

The key change here is that all of these variables can now have entries in conda_build_config.yaml.  The environment variable has the highest priority, followed by the variant, and finally the default (most of these have no default, and fall back to '')

allow variant to set CFLAGS, CXXFLAGS, LDFLAGS, LD_RUN_FLAGS

---

conda_build/environ.py

avoid setting empty compiler variables

---

conda_build/environ.py
conda_build/render.py
conda_build/utils.py

Sorry about the lack of tests for the run_exports one, time is against me.

config.arch is a string, run_exports are processed as dicts of lists.

---

conda_build/source.py

https://github.com/conda/conda-build/issues/2327

fix hash regex for downloaded files in src_cache

---

conda_build/environ.py

add LD_RUN_PATH back into linux variables for now

---

conda_build/skeletons/rpm.py
conda_build/source.py
tests/test-recipes/metadata/wheel_source/meta.yaml

fixes #2324 
fixes #2342 
fixes #2339

copy wheel and unknown file ext files into workdir without hash

---

conda_build/source.py

remove downloaded files if they failed at any download step

---

conda_build/build.py

Closes https://github.com/conda/conda-build/issues/2347
Backports @jjhelmus' PR ( https://github.com/conda/conda-build/pull/1894 ).

Backport PR 1894

---

conda_build/source.py

BUG: verify source hash

---

conda_build/environ.py
conda_build/utils.py

incorporates and supersedes #2364

fix several arch -> host_arch instances

---

conda_build/_version.py
versioneer.py

Workaround for https://github.com/warner/python-versioneer/issues/122

fix versioneer coming out with unknown version on win

---

conda_build/build.py
conda_build/tarcheck.py

This fixes https://github.com/conda/conda-build/issues/2377

Write out info/files in the noarch case. Always sanity check info/files.

---

conda_build/utils.py

reduce logging output from filelock

---

conda_build/build.py

Make [ba]sh -x trace depend on --debug

---

conda_build/build.py
conda_build/cli/main_build.py
conda_build/config.py
conda_build/metadata.py
conda_build/render.py

also fix some fields related to conda-verify tests

make conda-verify opt-in, not opt-out.  

---

conda_build/metadata.py
tests/test-recipes/metadata/_requires_provides_features/meta.yaml
tests/test_api_build.py

This is for conda 4.4's new key-value pair support
CC @kalefranz

implement requires_features and provides_features

---

conda_build/windows.py

Thanks @nehaljwani for figuring this out.  I'll come back in a bit to add tests.

Fix bits wrong win cross compile

---

conda_build/cli/main_metapackage.py

allow channels to be specified to metapackage command

---

conda_build/build.py
conda_build/create_test.py
conda_build/skeletons/cpan.py
conda_build/skeletons/cran.py
conda_build/windows.py

change windows errorlevel comparisons to NEQ 0

---

conda_build/post.py

revert os.rename to copy_into for cross-volume compatibility

---

conda_build/cli/main_convert.py
conda_build/convert.py

@msarahan sorry for this. cb tests don't behave well locally for me so I missed this on the initial pass.

Fix typo in convert platforms list

---

conda_build/environ.py

fixes #2499 
fixes #2498 
Doesn't actually fix them, just warns about the behavior.
CC @stuartarchibald

warn when user builds recipe with script_env

---

conda_build/metadata.py

as opposed to variant value
fixes #2495

base build string py/np/whatever on actual build-time versions

---

conda_build/source.py
tests/test_source.py

fix source hoisting issues

---

conda_build/jinja_context.py

Bring time modules to jinja2 context

---

conda_build/inspect.py
conda_build/skeletons/pypi.py
tests/test_published_examples.py

This is in 2 commits incase memoizing isn't something we want to do with filelists in dists. AFAICT it should be OK.

which_package speedup

---

conda_build/create_test.py
tests/test_api_build.py

fix source_files not working correctly with using test files in pkgs

---

conda_build/render.py
conda_build/variants.py

to account for - in pkg, _ in variant

fix package matching regexes with variants 

---

conda_build/variants.py
tests/test-recipes/variants/21_conditional_sections/conda_build_config.yaml
tests/test-recipes/variants/21_conditional_sections/meta.yaml
tests/test_variants.py

fix detection of variables used in jinja2 condtionals

---

conda_build/metadata.py
conda_build/render.py
tests/test-recipes/split-packages/outputs_using_vars_defined_in_meta/meta.yaml
tests/test_subpackages.py

fix output extraction regexes so that top-level var setting always done

---

conda_build/render.py
tests/test-recipes/variants/22_run_exports_rerendered_for_other_variants/conda_build_config.yaml
tests/test-recipes/variants/22_run_exports_rerendered_for_other_variants/meta.yaml
tests/test_variants.py

fix build run_exports not applying to host early enough

---

conda_build/build.py
conda_build/environ.py
tests/test-recipes/split-packages/_build_script/meta.yaml
tests/test_subpackages.py

fixes #2512 
CC @anton-malakhov @tomashek

support build/script and build/script_env in outputs

---

conda_build/build.py
conda_build/create_test.py
conda_build/environ.py
conda_build/jinja_context.py
conda_build/metadata.py
conda_build/render.py
conda_build/skeletons/pypi.py
conda_build/utils.py
tests/test_api_skeleton.py

Fix pyc build prefix

---

conda_build/os_utils/external.py
tests/test_os_utils_external.py

raise recipe error when required executable (git) isn't available

---

.travis.yml
appveyor.yml
ci/travis/run.sh
conda_build/build.py

Remove unnecessary looped rm rf

---

conda_build/build.py
conda_build/jinja_context.py
conda_build/metadata.py
conda_build/render.py
conda_build/skeletons/cran.py
conda_build/utils.py
tests/test-recipes/metadata/_self_reference_run_exports/meta.yaml
tests/test-recipes/split-packages/_strong_run_exports_applies_from_build_to_host/build.sh
tests/test-recipes/split-packages/_strong_run_exports_applies_from_build_to_host/meta.yaml
tests/test_api_render.py
tests/test_cli.py
tests/test_subpackages.py

fix run_exports not applying to build-time requirements at top level

---

appveyor.yml
conda_build/api.py
conda_build/build.py
conda_build/jinja_context.py
conda_build/metadata.py
conda_build/render.py
conda_build/utils.py
tests/test-recipes/split-packages/_line_up_python_compiled_libs/conda_build_config.yaml
tests/test-recipes/split-packages/_line_up_python_compiled_libs/meta.yaml
tests/test-recipes/split-packages/_line_up_python_compiled_libs_top_level_same_name_output/conda_build_config.yaml
tests/test-recipes/split-packages/_line_up_python_compiled_libs_top_level_same_name_output/meta.yaml
tests/test_api_build.py
tests/test_api_render.py
tests/test_subpackages.py

Tests on the way.  Putting this up for testing with @jjhelmus and @nehaljwani

fix matching of partial variants when lining up subpackages

---

conda_build/build.py
conda_build/post.py

post (macOS): Fix linking compiler runtimes from build to host prefix

---

conda_build/cli/main_build.py
conda_build/config.py
conda_build/jinja_context.py
conda_build/metadata.py

Most of this comes from #2618 which will be merged soon, and this PR will get much simpler.  It depends on work done in that PR, so it's necessary to be here.

Optional build host merge

---

conda_build/build.py
conda_build/jinja_context.py
conda_build/metadata.py
conda_build/render.py
tests/test-recipes/metadata/_run_exports_in_outputs/conda_build_config.yaml
tests/test-recipes/metadata/_run_exports_in_outputs/meta.yaml
tests/test-recipes/split-packages/_entry_points/install-pkg1.sh
tests/test-recipes/split-packages/_entry_points/install-pkg2.sh
tests/test-recipes/split-packages/_merge_build_host/meta.yaml
tests/test_api_render.py
tests/test_jinja_context.py
tests/test_subpackages.py

.. side question, is m.is_cross not redundant now?

Actually merge the top-level specs when build_is_host is set

---

conda_build/utils.py

fix conda's download output when using LoggingContext

---

conda_build/skeletons/pypi.py

allow pypi_url to be reflected in final output from skeleton

---

conda_build/metadata.py

fix overly broad 'None' in string check

---

conda_build/tarcheck.py

ignore tarcheck errors for info files not in info/files

---

conda_build/skeletons/pypi.py

remove host prefix in between skeletons with pypi (fix recursive)

---

conda_build/metadata.py

addresses issues reported in https://github.com/conda-forge/conda-smithy/issues/650

use lookaheads in extraction regexes to avoid capturing unwanted text

---

conda_build/build.py
tests/test-recipes/split-packages/_output_activation/install_activated.sh
tests/test-recipes/split-packages/_output_activation/install_not_activated.sh
tests/test-recipes/split-packages/_output_activation/meta.yaml
tests/test_api_build.py
tests/test_api_convert.py
tests/test_api_render.py
tests/test_api_skeleton.py
tests/test_cli.py
tests/test_published_examples.py
tests/test_source.py
tests/test_subpackages.py
tests/test_variants.py

Move build prefix before test

---

conda_build/convert.py
conda_build/environ.py
conda_build/utils.py
tests/test_api_build.py

use scandir's walk on py27; use walk instead of scandir for dir size

---

.travis.yml
conda_build/jinja_context.py
conda_build/metadata.py
conda_build/render.py
conda_build/skeletons/cran.py
tests/test-recipes/split-packages/_hash_inputs/meta.yaml
tests/test-recipes/split-packages/_hash_inputs/test-script.bat
tests/test_cli.py
tests/test_subpackages.py

Fix cran all list; fix win test_subpackage_hash_inputs

---

conda_build/metadata.py
tests/test-recipes/variants/24_test_used_vars_in_scripts/conda_build_config.yaml
tests/test-recipes/variants/24_test_used_vars_in_scripts/meta.yaml
tests/test_api_skeleton.py
tests/test_variants.py

fixes issue raised in https://github.com/conda-forge/vtk-feedstock/pull/50 - variables used in selectors were not showing up as "used" and thus were not being looped over.

fix boolean type conversion in variants; fix selectors not being 'used'

---

conda_build/convert.py
tests/test_api_convert.py

Add filesize calculation to converted script files

---

conda_build/build.py

expand bundle_wheel so it can use activated environments

---

conda_build/variants.py

fixes a bug where variables were being considered "used" inappropriately because of regex matches extending across multiple lines.
CC @jjhelmus - you mentioned seeing something like this, I believe.

add end-of-line anchor for selector regex

---

conda_build/variants.py

handle empty config.yaml variant input files without barfing

---

conda_build/post.py
conda_build/skeletons/cran.py

This fixes https://github.com/conda/conda-build/issues/2750#issuecomment-372142662

skeleton cran: Fix cli / argparse bug

---

conda_build/skeletons/cran.py

remove argparse suppress from cran arguments 

---

conda_build/utils.py

Fix decoding errors in directory_size and add flexibility for Windows localization: [2754](https://github.com/conda/conda-build/issues/2754)

Fix directory_size issue 2754

---

conda_build/utils.py

fix dir size operation on non-english Windows

---

conda_build/build.py
conda_build/config.py

fix R/Rscript mixup that broke R env var

---

conda_build/environ.py
conda_build/metadata.py

fixes https://github.com/conda/conda-build/issues/2769

fix FEATURE_NOMKL putting invalid specs into solver

---

conda_build/jinja_context.py
tests/test-recipes/metadata/_resolved_packages_host_build/meta.yaml
tests/test_api_render.py
tests/test_jinja_context.py

Adds a new jinja function: resolved_packages

---

conda_build/build.py

allow license_file to be in either source root or recipe root

---

conda_build/post.py

fixes https://github.com/conda/conda-build/issues/2761

fix shebang fixer so that it only touches python[w]? shebangs

---

conda_build/render.py

Remove unused function call

---

conda_build/metadata.py

Closes https://github.com/conda-forge/conda-smithy/issues/756
cc @isuruf

Include `folder` as a field in `source`

---

conda_build/render.py
conda_build/variants.py

remove conversion of dash to underscore in pin_run_as_build

---

conda_build/build.py
conda_build/environ.py
tests/test-recipes/metadata/_overlapping_files_warning/a/meta.yaml
tests/test-recipes/metadata/_overlapping_files_warning/b/meta.yaml
tests/test_api_build.py

Per discussion.  Probably not done yet.  Figured I'd get something started and in the queue though.

warn for path conflicts during environment building for test phase

---

conda_build/utils.py

I was bumping up against this assertion error, and I had no clue what it meant until I put it break points.  I think this additional information would have made the message a lot of more obvious.

add information to merge/copy source into subdirectory AssertionError

---

conda_build/skeletons/cran.py

These things both lead to a lot of unnecessary differences which makes the batch update
job more difficult than it needs to be.
We also remove the # patch comment lines, they're pointless.

Fix over-rendering and needless indentation change

---

conda_build/metadata.py
conda_build/skeletons/cran.py
conda_build/variants.py
conda_build/windows.py
tests/test_cli.py

add deprecation notice for msvc_compiler.  set default cran_mirror

---

conda_build/build.py
conda_build/convert.py

fix win-style slashes appearing in files converted from win packages

---

conda_build/build.py

fix multiple duplicate import tests

---

conda_build/build.py
tests/test-recipes/metadata/empty_run_section/meta.yaml

fix handling of empty run & test reqs

---

conda_build/build.py
conda_build/environ.py
tests/test-recipes/metadata/python_build/build.sh
tests/test-recipes/metadata/python_env_defined/meta.yaml
tests/test-recipes/metadata/python_env_defined/run_test.py

fix regression in SP_DIR pointing at host env during test phase

---

conda_build/metadata.py

fixes https://github.com/conda/conda-build/issues/2902
fixes https://github.com/conda/conda-build/issues/2900

fix None values from empty keys overriding default values for those keys

---

conda_build/environ.py
conda_build/utils.py
tests/test-recipes/metadata/_test_test_source_files/conda-recipe/meta.yaml
tests/test-recipes/metadata/python_env_defined/run_test.py

Fix prefix in os vars

---

conda_build/build.py
conda_build/config.py
conda_build/create_test.py
conda_build/environ.py
conda_build/metadata.py
tests/test-recipes/split-packages/test_files_copying/meta.yaml
tests/test_api_build.py

fix test file creation not working for outputs

---

conda_build/build.py
conda_build/create_test.py
tests/test-recipes/metadata/_test_test_source_files/conda-recipe/meta.yaml
tests/test-recipes/metadata/_test_test_source_files/test/text.txt
tests/test-recipes/split-packages/test_files_copying/meta.yaml
tests/test_api_build.py

fix folder copying in test files, improve tests

---

conda_build/metadata.py

Fixes https://github.com/conda/conda-build/issues/2956
Fixes https://github.com/conda-forge/conda-smithy/issues/791
cc @sodre

Keep zip_keys intact

---

conda_build/build.py
conda_build/environ.py
conda_build/os_utils/macho.py

Sorry @msarahan, this was also missing.

Actually move the broken (test env unsat) packages

---

conda_build/metadata.py

Add missing_dso_whitelist to FIELDS

---

conda_build/post.py

Don't skip logic in pyldd based on CB verbosity

---

conda_build/build.py
conda_build/create_test.py
tests/test-recipes/metadata/_test_test_deps_when_not_include_test_files/conda-recipe/meta.yaml
tests/test-recipes/metadata/_test_test_source_files/conda-recipe/meta.yaml
tests/test_api_build.py

addresses https://github.com/vmtk/vmtk/pull/313#issuecomment-406146264
CC @jcfr

fix test/requires being ignored when --no-copy-test-source-files

---

conda_build/build.py

Fix is_no_link() logic to honor patterns

---

conda_build/metadata.py

Fix apply selectors

---

conda_build/build.py

https://github.com/conda/conda-build/issues/3046
@msarahan

Include "extra" field of meta.yaml in about.json

---

appveyor.yml
conda_build/build.py
tests/test-recipes/split-packages/test_files_in_parent/meta.yaml

CC @oleksandr-pavlyk
I still haven't been able to reproduce your original issue.  I certainly see how it *could* happen, but I can't force it to happen again.  Maybe it is an older package that you are running tests on, and the new code doesn't handle the older package correctly?
At any rate, I think the changes here will fix it, but I'd appreciate your confirmation.

test recipe for parent source_files, try to handle parent recipe folders

---

conda_build/build.py
conda_build/post.py
conda_build/skeletons/cran.py

Eh, the cran change isn't that small thinking about it, the other one should catch the problem (or similar ones) that we had with setuptools_scm.

Master small fixes

---

conda_build/build.py
conda_build/post.py
conda_build/skeletons/cran.py

Reverts conda/conda-build#3068
introduced a few errors that @mingwandroid will spend more time on when he finds time.

Revert "Master small fixes"

---

conda_build/metadata.py

Memoize read_meta_file

---

.travis.yml
appveyor.yml
ci/travis/run.sh
conda.recipe/meta.yaml
conda_build/api.py
conda_build/build.py
conda_build/cli/main_index.py
conda_build/conda_interface.py
conda_build/environ.py
conda_build/index.py
conda_build/metadata.py
conda_build/render.py
conda_build/templates/channeldata-index.html.j2
conda_build/templates/rss.xml.j2
conda_build/templates/subdir-index.html.j2
conda_build/utils.py
setup.py
tests/conftest.py
tests/test-recipes/metadata/_index_hotfix_pkgs/meta.yaml
tests/test_api_build.py
tests/test_api_consistency.py
tests/test_api_update_index.py
tests/test_cli.py
tests/test_index.py

Most of this is adapted from https://github.com/ContinuumIO/conda-channel-clone/ (private project, sorry for curious outsiders)

Indexing rewrite

---

.travis.yml
conda_build/api.py
conda_build/build.py
conda_build/cli/main_render.py
conda_build/index.py
conda_build/jinja_context.py
conda_build/metadata.py
conda_build/noarch_python.py
conda_build/os_utils/pyldd.py
conda_build/utils.py
conda_build/variants.py
tests/test_jinja_context.py

fix usage of config in load_setup_py_data

---

conda_build/cli/main_index.py

fix channel_name arg for conda index

---

conda_build/index.py

fix indexing of noarch folder as done by conda-forge

---

conda_build/index.py
tests/test_index.py

This allows conda-build to directly use a .tar.bz2 file with potentially multiple patch instruction files (each in their own subdir folder).  It will facilitate application of conda-forge and other external parties hotfixes.

add support for tarballs with patch instructions

---

conda_build/skeletons/pypi.py

Resolves https://github.com/conda/conda-build/issues/3137

Avoid duplicate "pip" requirement

---

conda_build/source.py

In some cases, the a repo in the local `git_cache` can become corrupted in a way that prevents the user from building a recipe.  With this PR, conda-build will simply delete the locally cached repo if updating fails for any reason.  (If the error was due to corruption, maybe the recipe will build successfully on the next try.)
As a little motivating example, consider this (broken) recipe:
```yaml
package:
name: foo
version: 0.1
source:
git_url: https://github.com/stuarteberg/helloworld/helloworld
```
This will create a new directory `/minconda3/conda-bld/git_cache/github.com/stuarteberg/helloworld`, but then (of course) fail to populate it with a repo due to the incorrect `git_url`:
```
Cloning into bare repository '/minconda3/conda-bld/git_cache/github.com/stuarteberg/helloworld/helloworl …
```

source: If the local git cache can't be updated, delete it.

---

conda_build/build.py
conda_build/index.py
conda_build/utils.py
conda_build/variants.py
tests/test-recipes/metadata/always_include_files_glob/meta.yaml
tests/test-recipes/metadata/always_include_files_glob/run_test.py
tests/test_api_build.py
tests/test_index.py
tests/test_variants.py
tests/utils.py

fix loss of 'removed' section on second loop of indexing

---

conda_build/build.py
conda_build/convert.py
conda_build/index.py
conda_build/os_utils/pyldd.py
conda_build/render.py
conda_build/skeletons/pypi.py
conda_build/source.py
tests/test-recipes/metadata/_numpy_xx/run_test.bat
tests/test-recipes/metadata/_numpy_xx/run_test.py
tests/test-recipes/metadata/_numpy_xx/run_test.sh
tests/test-recipes/metadata/_numpy_xx_host/run_test.bat
tests/test-recipes/metadata/_numpy_xx_host/run_test.py
tests/test-recipes/metadata/_numpy_xx_host/run_test.sh
tests/test_api_build.py
tests/test_api_skeleton.py

fix private channels

---

conda_build/index.py
tests/test_index.py

This also handles corrupt package files a little better.

sort removed fns in index; fix deps being merged instead of clobbered

---

conda_build/index.py

This should fix #3167 (it works when I test it locally).

Fix #3167, update cache to exclude removed files.

---

conda_build/index.py

Just kidding, we all :heart: the brand new conda-index in conda-build!

conda-index: don't forget clean up after copying

---

conda_build/build.py
tests/test-recipes/metadata/_cmake_generator/meta.yaml
tests/test-recipes/split-packages/_xgboost_example/conda_build_config.yaml
tests/test-recipes/split-packages/_xgboost_example/meta.yaml
tests/test_subpackages.py
tests/test_variants.py

fix removal of outputs from earlier loops

---

conda_build/skeletons/pypi.py

fix pypi skeleton when constraint has no operator

---

conda_build/build.py
conda_build/post.py
conda_build/render.py
conda_build/skeletons/rpm.py
conda_build/source.py

This includes the commits from the previous PR, so only merge one or the other @msarahan! Though actually one then the other would probably be fine anyway git'll just go "yeah, I know".

Various minor fixes and tweaks.

---

conda_build/noarch_python.py

Remove noarch binary file check

---

conda_build/build.py
conda_build/config.py
conda_build/create_test.py
conda_build/index.py
conda_build/noarch_python.py
conda_build/utils.py
tests/test_api_build.py
tests/test_subpackages.py

fix test of noarch files. generate .sh and .bat for new noarch pkgs

---

conda_build/index.py

might be some stuff associated with errors being more stringent in conda 4.6.0.

WIP: make index error handling a bit more robust (skip errors; warn)

---

conda_build/build.py

Fix tests are not run on windows

---

conda_build/build.py

Fixes https://github.com/conda/conda-build/issues/3254

Fix PIP_NO_DEPENDENCIES

---

conda_build/utils.py

handle unicode decode fails in output rewriting

---

conda.recipe/meta.yaml
conda_build/build.py
conda_build/metadata.py
conda_build/post.py
conda_build/source.py
conda_build/windows.py
setup.py
tests/test-recipes/split-packages/_output_activation/meta.yaml

omit LIEF on win for now; fix behavior with no bld.bat on win

---

conda_build/create_test.py

Fixes https://github.com/conda/conda-build/issues/3339

Fix testing in outputs

---

docs/source/define-metadata.rst

document that py27 selectors are discouraged

---

docs/source/user-guide/index.rst
news/user-guide-index.rst

User guide index

---

docs/source/user-guide/index.rst

[skip ci] user-guide index

---

docs/index.rst
docs/source/define-metadata.rst
docs/source/package-spec.rst
docs/source/user-guide/Tutorials/index.rst

Meta yaml example

---

docs/index.rst
docs/source/concepts/index.rst
docs/source/install-conda-build.rst
news/clearing-doc-refs.rst

Deleted references to recently deleted docs.
@msarahan  - Can you please check if I'm doing the News component correctly?

[skip ci] Deleted outdated doc references

---

docs/conf.py
news/argparse-fix.rst

Argparse fix

---

conda_build/build.py

@msarahan - I came across this duplicated code. The expression remove is a copy of the one above.

Removed duplicated code

---

docs/source/resources/compiler-tools.rst
docs/source/resources/define-metadata.rst
docs/source/user-guide/tutorials/building-conda-packages.rst
docs/source/user-guide/tutorials/index.rst

Rrigdon reworking tutorial

---

docs/source/compiler-tools.rst
docs/source/define-metadata.rst
docs/source/user-guide/tutorials/building-conda-packages.rst
docs/source/user-guide/tutorials/index.rst

[skip ci] Reworked SEP and GDAL tutorial

---

requirements-doc

Using this to update the Sphinx version.

Create requirements doc

---

conda_build/environ.py

Always show display actions

---

docs/index.rst
docs/source/resources/compiler-tools.rst
docs/source/resources/define-metadata.rst
docs/source/resources/make-relocatable.rst
docs/source/resources/package-spec.rst
docs/source/user-guide/tutorials/add-win-start-menu-items.rst
docs/source/user-guide/tutorials/building-conda-packages.rst
docs/source/user-guide/tutorials/index.rst
news/Admonitions.rst

Admonitions

---

docs/source/user-guide/tutorials/building-conda-packages.rst

AFAIK, there is no where command in unix. There is a whereis command and a which command. I think which is the "command to see which version comes first on PATH".

Replace where command with which command

---

conda_build/cli/main_build.py

update cli documentation on --test argument

---

docs/_static/css/custom.css

Hover fixes

---

docs/source/conf.py

Changed page title from conda-build to conda build

---

docs/click/meta.yaml
docs/source/user-guide/tutorials/build-pkgs-skeleton.rst
docs/source/user-guide/tutorials/build-pkgs.rst
docs/source/user-guide/tutorials/index.rst
docs/source/user-guide/tutorials/meta.yaml
news/tutorials-news

Added revised tutorials to conda-build (they originally lived here: https://github.com/conda/conda-docs/pull/514).

Skeleton and conda from scratch tutorials

---

docs/source/resources/compiler-tools.rst
docs/source/resources/define-metadata.rst
news/fix-doc-macos-sdk.rst

Fix doc macos sdk

---

docs/source/user-guide/tutorials/build-pkgs.rst

Fixed typo in url

---

conda_build/build.py
conda_build/cli/main_build.py
conda_build/metadata.py
docs/source/user-guide/recipes/debugging.rst
news/fix-purge-docs

Fixes some of the suggestions in #2592.
Fixes #3158.

Document purge-all

---

conda_build/os_utils/liefldd.py

Fixes https://github.com/conda/conda-build/issues/3445

Fix inspecting linkages when lief is not installed

---

conda_build/metadata.py
conda_build/variants.py

Use noarch packages for r (Jira 1025)

---

docs/source/user-guide/tutorials/build-pkgs-skeleton.rst
docs/source/user-guide/tutorials/build-r-pkgs.rst
docs/source/user-guide/tutorials/building-conda-packages.rst
docs/source/user-guide/tutorials/index.rst
news/News-skeleton-cran.rst

Added the building a package with skeleton CRAN tutorial, made minor edits to other tutorials, added to index.

Skeleton cran tutorial

---

docs/source/user-guide/tutorials/build-r-pkgs.rst

Minor formatting change

---

conda_build/skeletons/cpan.py
conda_build/windows.py
tests/test_api_debug.py

Ignore registry autorun for all cmd.exe invocations

---

.travis.yml
appveyor.yml
conda_build/metadata.py
tests/test_api_build.py

Bump python version in CI from 3.6 -> 3.7

---

conda_build/post.py

Allow empty missing_dso_whitelist in build section

---

conda_build/config.py

Fixed noarch R package testing on Windows

---

docs/source/concepts/recipe.rst
docs/source/user-guide/tutorials/building-conda-packages.rst

Updates to the recipe concepts page

---

news/R_USER-for-R-pkgs.rst
news/add-37-CONDA_PY.rst
news/allow-empty-missing_dso_whitelist.rst
news/cdt-defaults-aarch64.rst
news/ci-bump-py-version.rst
news/ci-for-docs.rst
news/conda-debug-honor-channels.rst
news/conda-pkgv2-support.rst
news/conditional-lief-inspection.rst
news/current_repodata
news/display-actions-always.rst
news/docs-clarify-where-which.rst
news/docs-rpath-anaconda-compilers.rst
news/fix-lief-integration.rst
news/fix-user-guide-index.rst
news/ignore-registry-autorun.rst
news/meta-yaml-example.rst
news/pypi-skeleton-handle-special-chars.rst
news/r-pkgs-use-noarch.rst
news/recipe-build-order.rst
news/renoarmalize-eol.rst
news/repodata_from_packages.rst
news/run_test-script-name.rst
news/specify-installer-distinfo.rst
news/subpackages-build_id-recursion-problem.rst
news/test-api-debug-avoid-mutating-globals.rst
news/update-CRAN-license-testcase.rst
news/update-links.rst
news/utils-glob-over-stdlib-glob.rst

Update news items for v3.18.x

---

ci/travis/run.sh
conda_build/build.py

Activate for test

---

conda_build/inspect_pkg.py
conda_build/os_utils/liefldd.py
conda_build/post.py
setup.cfg

Speed up fix post

---

docs/source/release-notes.rst

Release notes for 3.18.0, 3.18.1, and 3.18.2

Release notes - 3.18.2

---

docs/source/index.rst
docs/source/resources/variants.rst
docs/source/user-guide/getting-started.rst
docs/source/user-guide/index.rst
docs/source/user-guide/recipes/index.rst
docs/source/user-guide/tutorials/build-pkgs-skeleton.rst
docs/source/user-guide/tutorials/build-pkgs.rst
docs/source/user-guide/tutorials/build-r-pkgs.rst
docs/source/user-guide/tutorials/building-conda-packages.rst
docs/source/user-guide/tutorials/index.rst

Basic content changes to help guide users through the content more effectively.

Reworked user guide to have more info and links between content

---

conda_build/build.py
conda_build/index.py
conda_build/os_utils/liefldd.py
conda_build/os_utils/pyldd.py
conda_build/post.py
conda_build/utils.py
conda_build/windows.py
tests/test-recipes/split-packages/_xgboost_example/meta.yaml

Binary repackaging fixes and some speed ups.

---

conda_build/skeletons/rpm.py

Fixes some lint the [conda-forge linter caught]( https://github.com/conda-forge/staged-recipes/pull/8560#issuecomment-502198888 ).

Adds an explicit build number to CDTs

---

docs/source/resources/index.rst
docs/source/resources/style-guide.rst
docs/source/resources/tutorial-template.rst
docs/source/user-guide/getting-started.rst
docs/source/user-guide/tutorials/build-pkgs-skeleton.rst
docs/source/user-guide/tutorials/build-pkgs.rst
docs/source/user-guide/tutorials/build-r-pkgs.rst
docs/source/user-guide/tutorials/building-conda-packages.rst

This includes the new tutorial template for user submissions, a style guide, and corrected tutorials to follow the new template.

Tutorial template

---

docs/source/resources/tutorial-template.rst

Formatting fix

---

news/3_18_3_news

News for 3.18.3 release

---

conda_build/index.py
news/timestamp_keyerror

fix one more timestamp key error

---

docs/source/resources/commands/index.rst
docs/source/resources/index.rst

Added basic context on CLI and resources pages

---

docs/source/release-notes.rst

Release notes for 3.18.3 - 3.18.5

---

docs/source/concepts/recipe.rst
docs/source/resources/define-metadata.rst

Also added anchors in Defining Metadata.

Added info about how conda build uses a recipe to create a pkg

---

docs/source/release-notes.rst
docs/source/user-guide/tutorials/building-conda-packages.rst

Minor language and formatting changes

---

docs/source/user-guide/index.rst

Cleaned up language

---

docs/source/release-notes.rst

Release notes for 3.18.6

---

conda_build/render.py
news/pkg_loc

Should address https://github.com/conda-forge/staged-recipes/pull/8715#issuecomment-508060435

potential fix for pkg_loc

---

conda.recipe/meta.yaml

Bump conda-package-handling to 1.3+

---

conda_build/build.py
conda_build/render.py
tests/test_api_build.py
tests/test_api_render.py
tests/test_post.py
tests/test_render.py
tests/test_utils.py

add in fallback for run_exports when channeldata not available

---

docs/source/release-notes.rst

@msarahan - this needs careful review since I adapted it from the log

Release notes for 3.18.7

---

conda_build/build.py
conda_build/utils.py
docs/source/resources/define-metadata.rst
news/MultipleLicense.rst
tests/test-recipes/metadata/multiple_sources/meta.yaml

Fixes https://github.com/conda/conda-build/issues/1247

Allow multiple license files

---

conda_build/index.py
news/index_json

fix conditions for loading existing index.json

---

docs/source/release-notes.rst

Release notes - 3.18.8

---

CHANGELOG.txt

Added 3.18.7 content

---

AUTHORS.txt
conda_build/api.py
conda_build/skeletons/pypi.py
news/skeleton-dependencies.rst
tests/test_api_skeleton.py

Refactoring of the get_package_metadata. Extract the part responsible to deal with the entry points.
The idea is to do a bigger refactoring on this part. But I particularly prefer to open merge request in small chunks so in that way would be easy and better to review the modifications and to spot new improvements.

Extracted the part responsible to deal with entry points in get_package_metadata

---

conda_build/metadata.py

Fixes https://github.com/conda-forge/conda-smithy/issues/1114

Add `disable_pip` to `FIELDS`

---

news/for_release.rst

add more news items in preparation for release

---

docs/source/release-notes.rst

Release notes - 3.18.9

---

docs/source/resources/variants.rst

Minor changes to variants.rst

---

docs/source/user-guide/tutorials/building-conda-packages.rst

Minor grammatical/typographical edits

---

conda_build/build.py

Rename license relative file paths starting with .. or .

---

bdist_conda.py
conda_build/skeletons/pypi.py
news/replace-readfp.rst
versioneer.py

Workaround for future deprecations (SafeConfigParser)

---

conda_build/skeletons/pypi.py
news/refactoring-package-metadata.rst
tests/conftest.py
tests/test_api_skeleton.py

Refactored the skeletons/pypi.py get_package_metadata to be more modular
Added unit tests as well

Refactoring package metadata

---

conda_build/skeletons/pypi.py
news/refactoring-package-metadata.rst
tests/conftest.py
tests/test_api_skeleton.py

Related to #3601 
But it needs PR #3633 to be merged first

#3601 scape quotes

---

conda_build/metadata.py

Add outputs: run_exports to FIELDS

---

conda.recipe/meta.yaml

require conda 4.5+ in dev recipe

---

docs/source/concepts/package-naming-conv.rst

This is related to this issue: https://github.com/conda/conda/issues/9005

More info on package naming conventions and .conda format

---

conda_build/skeletons/cran.py

Added detection for Fortran 95 and 2003

---

news/fb-3680-migrate-unit-to-pytest.rst
tests/test_misc.py
tests/test_os_utils_external.py
tests/test_utils.py

Migrate Unittests to PyTest
It closes #3680

Migrate unittest to pytest

---

conda_build/skeletons/pypi.py
news/fb-3716-update-skeleton-pypi-cmd.rst

Update script command on conda skeleton pypi to use `{{ PYTHON }} -m pip install . -vv`

Update script command on conda skeleton pypi

---

conda_build/skeletons/rpm.py

Use hostmachine so that RPMs are in the right place (HOST dir)

---

conda_build/index.py
conda_build/utils.py
tests/index_data/corrupt/noarch/bad_package.tar.bz2
tests/test_index.py

fixes https://github.com/conda/conda-build/issues/3685
Note that the exception imported from conda-package-handling is a reasonably new addition to CPH.  We may need to bump up the lower bound of CPH in the conda-build requirements.

improve error handling around invalid archives in indexing

---

docs/source/resources/define-metadata.rst

From this PR: https://github.com/conda/conda-docs/pull/565

Added information on git_depth

---

azure-pipelines.yml

Update to use pytest-azurepipelines from main pkgs

---

conda_build/index.py
conda_build/skeletons/pypi.py

Fix flake8 problems

---

docs/source/resources/define-metadata.rst

Related to this PR: https://github.com/conda/conda-docs/pull/474

Added pin runtime dependencies section

---

docs/source/resources/package-spec.rst

Fixed broken link

---

docs/source/resources/define-metadata.rst

Added info about hashes being in build strings

---

docs/source/resources/compiler-tools.rst
docs/source/user-guide/tutorials/build-r-pkgs.rst

Added link to SDK info

---

docs/source/resources/activate-scripts.rst
docs/source/resources/index.rst
docs/source/user-guide/tutorials/build-pkgs-skeleton.rst
docs/source/user-guide/tutorials/build-r-pkgs.rst

Added activate info, cleaned up some tutorials

---

conda_build/utils.py
news/fb-3746-recipe-path-warning.rst
tests/test_utils.py

Add a warning when a received a file on RECIPE_PATH

---

tests/test-recipes/metadata/source_setup_py_data_subdir/bld.bat
tests/test-recipes/metadata/source_setup_py_data_subdir/build.sh
tests/test-recipes/metadata/source_setup_py_data_subdir/meta.yaml
tests/test_api_build.py

Adds a test case like the one in issue ( https://github.com/conda/conda-build/issues/3754 ).
cc @marcelotrevisani

Test with `setup.py` in a subdirectory

---

conda_build/post.py

@msarahan please review, (@isuruf, you may like this too!)

Expunge the need for Xcode in post

---

docs/source/release-notes.rst

Release notes for 3.18.10

---

conda_build/cli/main_build.py
conda_build/utils.py
tests/test_cli.py
tests/test_utils.py

Fix UserWarnings regarding recipe path

---

docs/source/concepts/recipe.rst
docs/source/index.rst
docs/source/install-conda-build.rst
docs/source/resources/activate-scripts.rst
docs/source/resources/add-win-start-menu-items.rst
docs/source/resources/commands/conda-build.rst
docs/source/resources/commands/conda-convert.rst
docs/source/resources/commands/conda-develop.rst
docs/source/resources/commands/conda-index.rst
docs/source/resources/commands/conda-inspect-channels.rst
docs/source/resources/commands/conda-inspect-linkages.rst
docs/source/resources/commands/conda-inspect-objects.rst
docs/source/resources/commands/conda-inspect.rst
docs/source/resources/commands/conda-metapackage.rst
docs/source/resources/commands/conda-render.rst
docs/source/resources/commands/conda-skeleton-cpan.rst
docs/source/resources/commands/conda-skeleton-cran.rst
docs/source/resources/commands/conda-skeleton-pypi.rst
docs/source/resources/commands/conda-skeleton.rst
docs/source/resources/define-metadata.rst
docs/source/resources/make-relocatable.rst
docs/source/resources/style-guide.rst
docs/source/resources/tutorial-template.rst
docs/source/resources/use-shared-libraries.rst
docs/source/resources/variants.rst
docs/source/user-guide/environment-variables.rst
docs/source/user-guide/index.rst

Changed conda build to conda-build

---

docs/source/conf.py

Standardized project name to conda-build

---

conda_build/build.py
conda_build/cli/main_build.py
conda_build/config.py
conda_build/metadata.py
conda_build/post.py
conda_build/variants.py
tests/conftest.py
tests/test-recipes/variants/31_variant_subkeys/conda_build_config.yaml
tests/test-recipes/variants/31_variant_subkeys/meta.yaml
tests/test_variants.py

Master variant values as dicts

---

docs/source/release-notes.rst

Release notes 3.18.11

---

conda_build/skeletons/cran.py

Format string lacked argument

---

docs/source/resources/define-metadata.rst

Removed features, updated track_features

---

docs/source/user-guide/tutorials/build-pkgs-skeleton.rst

Added note about using Docker

---

conda_build/build.py

BUG warn on dangling symlinks

---

docs/source/user-guide/tutorials/building-conda-packages.rst

* Fix duplicated line
* Place `conda_build_config.yaml` in backticks

Small doc fix

---

conda_build/skeletons/rpm.py

Otherwise the sources are not found

Update sbase_url for centos7

---

conda_build/environ.py

Add GIT_DESCRIBE_TAG_PEP440

---

azure-pipelines.yml
conda_build/environ.py

Support VAR=VAL in build/script_env

---

conda_build/post.py

Less os.path in post.py

---

conda_build/build.py

05 ci a few minor improvements

---

.authors.yml
CHANGELOG.txt
news/PREP3190.rst
rever.xsh

Add news items and clean up prior to the 3.19.0 release.

Prepare for 3.19.0 release

---

azure-pipelines.yml

Change CI trigger

---

azure-pipelines.yml
conda_build/build.py

 Fix issue 3899

---

CHANGELOG.txt
news/revert_3893.rst

Preparing for a 3.19.2 release

---

conda_build/cli/main_index.py

Update the help information of the conda-index command to reflect the
current uses of the --patch-generator and --hotfix-source-repo options.

update cli help information for conda index

---

conda_build/environ.py

Use host_platform instead of sys.platform

---

docs/source/resources/define-metadata.rst

add aarch64 selector to docs

---

conda_build/metadata.py

Allow package to depend on itself if cross compiling

---

conda_build/post.py

More osx-arm64 fixes

---

conda_build/environ.py

Set the correct SHLIB_EXT when cross-compiling

---

conda_build/environ.py
tests/test_api_build.py
tests/test_api_skeleton.py

planemo package requires Python>=3.5

get tests passing again

---

docs/source/resources/define-metadata.rst
docs/source/user-guide/environment-variables.rst

Add docs on build_platform and arm64

---

conda_build/os_utils/liefldd.py

inspect linkages with pyldd when not DLL/EXE file

---

docs/source/resources/define-metadata.rst

Clarify multiple OS selection.

---

docs/source/concepts/generating-index.rst

extend docs on generating index

---

docs/source/resources/define-metadata.rst

add some detail to run_constrained doc

---

azure-pipelines.yml
ci/azurepipelines/install_conda_build_test_deps
conda_build/os_utils/liefldd.py
tests/test-recipes/metadata/has_prefix_files/run_test.py
tests/test_api_build.py
tests/test_api_skeleton.py

Get CI tests passing

---

conda_build/metadata.py

Add target to recognized fields in `outputs`

---

conda_build/build.py
conda_build/post.py
conda_build/utils.py

Master (github was acting weird, not updating the old PR)

---

conda_build/build.py
conda_build/utils.py

Add and use shutil_move_more_retrying

---

conda_build/build.py

Instead of clobbering `config` passed into `conda_build.build.build_tree` use a per iteration `cfg` variable.

Do not clobber config argument in conda_build.build.build_tree

---

conda_build/source.py
news/dry-run-patch
tests/test_api_build.py

Master.dry run patch

---

conda_build/source.py

Fix comment and function name to try_apply_patch

---

news/Use-CONDA_PACKAGE_EXTENSIONS
news/do-not-clobber-config
news/dry-run-patch
news/include_target_platform
news/linking_tbd.rst
news/raise-runtime-error

Add and update news entries

---

conda_build/metadata.py

override conda-build option with meta value if it exists

---

news/0001-stats-seconds2human.rst
news/0002-Prefer-meta-yaml-error-overlinking.rst
news/0003-Clean-up-variant-processing.rst
news/0004-Add-file-option-to-indexing.rst
news/0005-Remove-old-rpath-when-loader_path.rst
news/0006-Fix-MACOSX_DEPLOYMENT_TARGET-default-for-osx-arm64.rst
news/0007-Rewrite-apply_patch.rst

Add news entries

---

conda_build/environ.py

Fix BUILD when cross compiling

---

conda_build/post.py

Fix deleting rpath

---

conda_build/variants.py

Simplify the call and add additional documentation.
This is an attempt to split PR #4079 into smaller changes.

Simplify find_config_files call

---

conda_build/environ.py
conda_build/metadata.py
tests/test_metadata.py
tests/test_variants.py

.. I do not think I want this fix finally

Test fix for testsuite ..

---

conda_build/metadata.py
conda_build/render.py
docs/source/resources/define-metadata.rst
news/ignore_run_exports_from.rst
tests/test_api_build.py

Add ignore_run_exports_from

---

news/0001-ignore_run_exports_from.rst
news/0002-Respect-PEP440-Compatibe-release-clause.rst
news/0003-A-few-bits.rst
news/0004-Fix-indexing-by-file.rst

Add news entries in preparation for 3.20.5

---

ci/azurepipelines/install_conda_build_test_deps
conda_build/build.py
conda_build/cli/main_build.py
conda_build/config.py
conda_build/index.py
conda_build/metadata.py
conda_build/render.py
conda_build/skeletons/pypi.py
conda_build/utils.py
conda_build/variants.py
docs/source/resources/compiler-tools.rst
tests/conftest.py
tests/test-recipes/metadata/_macos_tbd_handling/conda_build_config.yaml
tests/test-recipes/metadata/_overdepending_detection/conda_build_config.yaml
tests/test-recipes/metadata/_overlinking_detection/conda_build_config.yaml
tests/test_cli.py
tests/test_post.py

First round of changes for 3.20.6

---

conda_build/skeletons/cran.py

Fix typo in cran skeleton

---

conda_build/os_utils/liefldd.py

Oops again

---

azure-pipelines.yml
conda_build/skeletons/cran.py

Use extra R_ARGS

---

conda_build/api.py

See https://github.com/conda/conda-build/issues/4133

Don't sort recipes

---

setup.cfg

Master.us marker fixes

---

conda_build/build.py
conda_build/metadata.py

Eliminate duplicate lists of accepted fields, fewer places to make future updates.
Regarding the "news entry" that is mentioned in this PR template, I've been ignoring this and so far I haven't been reprimanded, is this something that I should look into and understand or should I continue to ignore that?

Combine default_structs with FIELDS

---

conda_build/build.py
conda_build/cli/main_build.py
conda_build/config.py
conda_build/metapackage.py
conda_build/os_utils/macho.py
conda_build/post.py
conda_build/render.py

Jschueller.rpath

---

conda_build/build.py
conda_build/config.py
conda_build/index.py
conda_build/os_utils/macho.py
conda_build/post.py

Make post-link run_export/library_nature determination less gross

---

conda_build/skeletons/cran.py

Add cross-r-base for cross compiling

---

news/activate-in-scripts-defaults-to-true.rst
news/add-conda-verify-to-install_conda_build_test_deps.rst
news/add-flaky-to-testing-dependencies.rst
news/add-setting-and-build-noarch_python_build_age.rst
news/allow-directories-as-license_file-source.rst
news/avoid-writing-to-the-package-cache-in-package_has_file.rst
news/change-package_has_file-to-refresh-if-out-of-date.rst
news/consider-any-file-containing-yaml-as-maybe-a-recipe.rst
news/ensure-condarc-does-not-leak-into-testing_config.rst
news/fix-applying-patches-to-read-only-files.rst
news/fix-skeleton-URLs-for-CentOS-6.rst
news/fix-typo-in-cran-skeleton.rst
news/force-channel_targets-to-be-considered-used.rst
news/issue-a-single-command-for-the-upload-command.rst
news/lief-allow-parsing-static-libs-to-fail.rst
news/pass-cache_dir-to-api.build.rst
news/print-hash_inputs-after-upload-info.rst
news/the-rest.rst
news/use-MacOSX10.10.sdk-not-MacOS10.9.sdk-in-tests.rst
news/warn-when-files-have-been-removed-from-the-prefix.rst

new entries

---

conda_build/build.py
conda_build/render.py
news/gh4174-fix-nonarch-version-from-version-age-determination.rst

Fix https://github.com/conda/conda-build/issues/4173

---

conda_build/build.py
news/gh4177-fix-stupid-error-in-prefix-replacement.rst

Fix stupid error in prefix replacement

---

conda_build/build.py
news/symlinks.rst
tests/test_build.py

This PR closes #4178 by recusively parsing symlinks.

ENH handle symlinks in symlinks

---

conda_build/skeletons/rpm.py
news/rpm_s390x.rst

Add IBM's s390x centos clone variant

---

conda_build/utils.py

This is intended to address #4185.
Unfortunately, I still have not been able to replicate the issue on a local machine so we'll have to see how Azure does.

Fix glob ambiguity

---

docs/source/resources/define-metadata.rst

Reword note on OS skips containing typos

---

conda_build/variants.py

Make error message more informative

---

README.rst
tests/requirements.txt

README is missing some dependencies needed to run the test suite.

Update README with testing dependencies

---

.github/workflows/stale.yml

Copied from conda/conda with minor modifications.

Workflow to marking issues as stale

---

.pre-commit-config.yaml
conda_build/launcher_sources/cpython-launcher-c-mods-for-setuptools.3.6.patch
conda_build/launcher_sources/cpython-launcher-c-mods-for-setuptools.3.7.patch

Revert changes to `.patch` and prevent auto formatting in the future.
https://github.com/conda/conda-build/pull/4327#discussion_r755266340

Do not auto format .patch/.diff

---

conda_build/conda_interface.py
conda_build/environ.py
news/conda-411-auxlib.rst

Fix import for auxlib.

---

.github/workflows/docs.yml
.github/workflows/tests.yml

Resolves https://github.com/conda/conda/issues/11085

Only run GHAs on non-forks

---

CONTRIBUTING.md
Makefile

**Added:**
* Make tasks for testing
* Make targets for required conda_build_test_recipe git repo
**Changed:**
* Updates docs to point to conda-build environment name rather than dev

Making tests easier to run

---

conda_build/utils.py
news/4482-bugfix-legacy-python-removal

Fix for conda 4.13.0 Python 2.7 removal

---

conda_build/_version.py

Fix pre-commit.

---

conda_build/_version.py

Another fix to appease pre-commit.

---

.github/workflows/tests.yml

CI is running tests using the `conda-canary` channel but this isn't the bleeding edge package generated on every merge to conda's main branch. Update canary CI tests to use `conda-canary/label/dev`.

Use `conda-canary/label/dev`'s `conda` package for CI tests

---

conda_build/index.py
conda_build/inspect_pkg.py
conda_build/utils.py
news/4556-drop-cytoolz

Removing minor cytoolz usage in favor of argument unpacking and `itertools.groupby`.
xref: https://github.com/conda/conda/issues/11333 https://github.com/conda/conda/issues/11698

Drop cytoolz usage

---

docs/requirements.txt
docs/source/conf.py
docs/source/robots.txt

Refs https://github.com/conda/conda-docs/issues/810.

Add sphinx-sitemap to docs.

---

tests/test_api_skeleton.py

Sympy was recently modified to only support Python 3.8+ (see [sympy source](https://github.com/sympy/sympy/blob/cc25558518b7f5b15261f6d888d50cc53568812d/setup.py#L72-L75)).

sympy is only Python 3.8+

---

tests/test_api_build.py

The GitHub Windows runner no longer offers MSVC++ 9.0. Removes the associated test.

Drop MSVC++ 9.0 test

---

conda_build/convert.py

`test_convert` in `tests/test_cli.py` has become particularly flaky on Windows recently (updates to the Windows runners perhaps?). This is an attempt to adjust the code to avoid this flakiness.

Update path logic to avoid Windows path sensitivity

---

docs/source/index.rst
news/4632-packaging-tutorial-over-setuptools

Point to packaging.python.org instead of setuptools

---

recipe/meta.yaml

Updating conda dependency to specify the correct lower bound.
Xref https://github.com/conda/conda-build/issues/4634
Xref https://github.com/AnacondaRecipes/conda-build-feedstock/pull/20
Xref https://github.com/conda-forge/conda-build-feedstock/pull/187

Update conda dependency

---

conda_build/build.py
conda_build/develop.py
news/4636-cast-noarch-type

Fixing a regression introduced in #4603. Fixes #4636.

Cast metadata values to string

---

.authors.yml
CHANGELOG.md
news/gh-4650-fix-cli-zstd-level-override-gh-4649.md

✂️ snip snip ✂️ the making of a new release.
Xref https://github.com/conda/conda-build/issues/4617

Release 3.23.2

---

.github/workflows/tests-skip.yml

Fix skip workflow

---

.github/workflows/docs.yml
.github/workflows/tests.yml

Bumped versions for the following actions:
- actions/checkout
- actions/upload-artifacts
Opted not to bump the version for `actions/setup-python` since we intend to replace it with `conda-incubator/setup-miniconda` shortly.

Update action versions to avoid Node.js 12 deprecation notices

---

tests/test_license_family.py

Several tests were duplicated. Refactored into a pytest parameterized implementation.

`test_license_family.py`: combine tests into parameterized test

---

tests/test_api_build.py

Mark flaky test as serial & flaky to avoid macOS SDK race condition

---

tests/test_api_update_index.py

Minor cleanup of tests.
Xref: https://github.com/conda/conda-build/issues/4590

Refactor `test_api_update_index.py` to use `pathlib.Path`

---

tests/test_render.py

Combining duplicate tests with pytest parameterized and minor formatting refactor.

Combine `test_render.py` duplicate tests with pytest parametrize

---

tests/test_api_build_go_package.py
tests/utils.py

Inline a fixture that is only used once.

Inline `test_api_build_go_package.py` fixture

---

.github/workflows/tests.yml

`actions/cache@v2` is already outdated and raises deprecation warnings. Bump to `v3` instead.

Bump actions/cache version

---

docs/source/index.rst
docs/source/user-guide/tutorials/building-conda-packages.rst
news/4719-anaconda-cloud-needs-changed-to-anacondaorg-in-conda-build-docs

Closes https://github.com/conda/conda-build/issues/4706. Replaced two instances of "Anaconda Cloud" with "anaconda.org", to be a bit more up to date with what Anaconda is calling things.

Replaced instances of Anaconda Cloud with anaconda.org.

---

tests/test_variants.py

Related to:
- https://github.com/conda/conda-build/issues/4590
While updating `conda-build/tests/test_variants.py`, the following issues were discovered and filed:
- https://github.com/conda/conda-build/issues/4717
- https://github.com/conda/conda-build/issues/4718

Prune/update `test_variant.py` file

---

tests/test_utils.py

Related to:
- https://github.com/conda/conda-build/issues/4590

Updating `test_utils.py` file

---

tests/test_source.py

Related to:
- https://github.com/conda/conda-build/issues/4590

Update `test_source.py` file

---

tests/test_create_test.py

Convert all `test_create_test.py` tests into parametrized tests. Identified inconsistencies between the language implementations that don't make sense and should be investigated.

`test_create_test.py`: Convert tests into parametrized test

---

tests/test_metadata.py

Combined native compiler metadata tests as parametrized test.

`test_metadata.py`: Combine native compiler metadata tests

---

conda_build/source.py
tests/test_patch.py

Expanded patch strip level test to cover more cases and added `pathlib.Path` support.

`test_patch.py`: Expand patch strip level test to cover more cases

---

tests/test_api_build.py
tests/test_api_debug.py
tests/test_published_examples.py
tests/test_subpackages.py
tests/utils.py

Inlined fixtures that are only used once. Removed `skipif` condition that will always evaluate to false. Removed unused helper functions.

Remove unnecessary fixtures

---

tests/test_api_build.py
tests/test_index.py
tests/test_metadata.py

Noticed some more unused test fixtures; let's remove them! 🧹

Remove More Unused Test Fixtures

---

conda_build/jinja_context.py
news/tomllib-tomli
recipe/meta.yaml
setup.py
tests/requirements.txt

Python 3.11 includes its own toml implementation, which is based on tomllib. Use that.
(Unlike the older PR, doesn't try to touch the YAML implementation.)

Use tomli or Python 3.11 tomllib

---

docs/source/resources/commands/conda-build.rst

Add documentation for missing args

Update conda-build.rst with missing args

---

.github/workflows/tests.yml
conda_build/cli/main_render.py
conda_build/skeletons/pypi.py
news/4797-drop-python37-support
setup.py
tests/test_index.py

Drop Python 3.7 support.

---

conda_build/index.py
conda_build/metapackage.py
conda_build/os_utils/elf.py

In my review of the code base, I found a few things that could be cleaned up.

Some minor code cleanup

---

conda_build/build.py

Found another conditional check for an unsupported version of conda.

Drop `conda < 4.3.2` check

---

tests/test_utils.py

Discovered while working on https://github.com/conda/conda-build/pull/4843.
Removes a helper function since `pathlib.Path.touch()` does the same thing.
Since this helper function is in tests we remove it outright instead of deprecating.

Replace `makefile` with `Path.touch`

---

.github/workflows/tests.yml

To offer better release candidate testing we need to build canaries for release branches.
Xref https://github.com/conda/conda/pull/12622

Enable canary builds for release branches

---

conda_build/api.py
conda_build/build.py
conda_build/cli/main_index.py
conda_build/index.py
conda_build/render.py
conda_build/utils.py
news/4645-use-conda-index

Some changes from the other attempt. May need to adjust where/whether warnings are printed.

Conda index helpful changes from other PR

---

tests/requirements.txt

This showed up in https://github.com/conda/conda-build/actions/runs/4994273560/jobs/8945705341?pr=4886 for example.

Add py as a dependency to work around a packaging issue.

---

.github/workflows/tests.yml
tests/requirements.txt

`allure-pytest` is now available from conda-forge so lets use that instead of installing via pip/PyPI.
Depends on https://github.com/conda-forge/feedstock-outputs/pull/48

Install `allure-pytest` from `conda-forge`

---

.github/workflows/tests.yml

Updating test workflow to match the one in [conda/conda](https://github.com/conda/conda/blob/main/.github/workflows/tests.yml), see [PR #12867](https://github.com/conda/conda/pull/12867/files) for reference.

Update `tests.yml` to match workflow in conda/conda

---

.readthedocs.yml

[3.25.x] Build ePub, PDF and zipped HTML docs as well.

---

.readthedocs.yml

[3.26.x] Build ePub, PDF and zipped HTML docs as well.

---

.readthedocs.yml

We did something similar for conda recently in https://github.com/conda/conda/issues/12886

Build ePub, PDF and zipped HTML docs as well.

---

.github/labels.yml

For keeping track of noarch-related issues and pull requests

Add a `tag::noarch` label

---

.github/dependabot.yml
.readthedocs.yml
docs/requirements.txt

More details: https://blog.readthedocs.com/use-build-os-config/
Also add dependabot config for docs.

Migrate to new version of readthedocs config.

---

README.md

It seems as if the canary set up builds the same artifacts as the main branch for the first commit of a release branch and then overwrites the files on anaconda.org without adding the canary label. To work around this, this adds one commit more to the release branch to properly build the canary.
- ~[ ] Add a file to the `news` directory ([using the template](../blob/main/news/TEMPLATE)) for the next release's release notes?
~

Trigger build.

---

.pre-commit-config.yaml
conda_build/conda_interface.py
conda_build/metadata.py
conda_build/utils.py
pyproject.toml

The recent addition of ruff (https://github.com/conda/conda-build/pull/5015) accidentally disabled pre-commit entirely (due to a trailing `|`).
This fixes the issue and removes lints we are not prepared to address ATM.

Fix pre-commit exlusions

---

docs/source/user-guide/tutorials/build-pkgs-skeleton.rst

Adding a little admonition to let users know about Grayskull for building PyPI packages.

Update conda skeleton documentation to add link to Grayskull

---

.github/labels.yml
.github/workflows/builds-review.yaml
pyproject.toml
recipe/meta.yaml
tests/requirements-linux.txt
tests/requirements-macos.txt
tests/requirements.txt

Resolving canary build issues.
Needed to relax `menuinst` requirement for the solve to succeed, can add back `>=2.0` bound later.
Xref https://github.com/conda/conda/pull/13379

Correct & sync dependencies

---

.github/workflows/tests.yml
news/allure-removal
tests/requirements.txt

Remove unused Allure test collection from suite. This work is no longer scheduled.
There were some pretty neat GHA integrations https://github.com/dholth/conda-build-allure/blob/main/.github/workflows/build-report.yml and https://github.com/conda/actions/blob/main/allure-multi/action.py but it would be a big effort to make it perfect.

Allure removal

---

.github/workflows/tests.yml
pyproject.toml
recipe/meta.yaml
tests/requirements.txt

Closes https://github.com/conda/conda/issues/13371

Clean up after menuinst v2 compatible releases

---

conda_build/deprecations.py

Xref https://github.com/conda/conda/pull/13408

Correct typing in `conda_build.deprecations`

---

docs/source/resources/define-metadata.rst

Document load file regex

---

.github/CODEOWNERS

Sets `conda/builds-tools` as the code owner of conda-build for reviews.

Define `CODEOWNERS`

---

.github/workflows/tests.yml
tests/conftest.py

Asserts pytest is using the conda-build source code found alongside the test suite. Also includes conda-build's path in pytest's header for reference.
Xref https://github.com/conda/conda/pull/13698

Ensure we are testing development conda-build

---

conda_build/build.py
conda_build/conda_interface.py
conda_build/config.py
conda_build/deprecations.py
conda_build/environ.py
conda_build/os_utils/external.py
conda_build/utils.py
news/5222-deprecating-conda_interface
pyproject.toml
tests/test_environ.py

We need to do a better job of catching deprecations occurring upstream.
Xref https://github.com/conda/conda/pull/12771

Treat deprecation warnings as errors

---

conda_build/api.py
conda_build/bdist_conda.py
conda_build/build.py
conda_build/cli/main_skeleton.py
conda_build/conda_interface.py
conda_build/environ.py
conda_build/index.py
conda_build/os_utils/pyldd.py
conda_build/render.py
conda_build/skeletons/cpan.py
conda_build/skeletons/pypi.py
conda_build/source.py
conda_build/utils.py
news/5222-deprecating-conda_interface
news/5251-deprecating-conda_interface
tests/test_api_build.py

Deprecate all imports except those coming from `conda.exports`.

More `conda_build.conda_interface` deprecations

---

.github/workflows/builds-review.yaml

The review builds fail if `macos-latest` resolves to `macos-14` (`osx-amr64`).
See https://github.com/conda/conda/actions/runs/8809949546/job/24181531935?pr=13837
Xref https://github.com/conda/conda/pull/13845

Add arm64 review builds

---

conda_build/index.py
news/5205-repodata-json-only
pyproject.toml
recipe/meta.yaml
tests/requirements.txt

Skip compressed repodata for internal index

---

README.md

Added/updated the following badges:
- build/CI/tests badge to reflect the status of daily scheduled test
- add logo to codecov badge
- add codspeed badge
- add logo to release badge
- add Anaconda package badge
- add conda-forge package badge
Xref https://github.com/conda/conda/pull/14194

Update `README.md` badges

---

pyproject.toml

Something that came up in https://github.com/conda/conda-build/pull/5532 via https://github.com/conda/conda-build/actions/runs/11794011480/job/32850759508?pr=5532#step:10:6209
- ~[ ] Add a file to the `news` directory ([using the template](https://github.com/conda/conda-build/blob/main/news/TEMPLATE)) for the next release's release notes?~

Ignore some warnings for conda-libmamba-solver.

---

tests/test_api_build.py

The upstream issue is not fixed yet so let's unblock the CI for now.

Bump time-based skip for `tests/test_api_build.py::test_croot_with_spaces`

---

conda_build/utils.py
news/5637-use-correct-conda_exe

Extracted from https://github.com/conda/conda-build/pull/5633
Resolves failures seen in:
- https://github.com/conda/conda-build/actions/runs/13683225738/job/38260557871
- https://github.com/conda/conda-build/actions/runs/13660703493/job/38191136143

Use correct `CONDA_EXE`

---

conda_build/render.py
news/gh5654.rst
tests/test-recipes/metadata/_python_version_independent/meta.yaml
tests/test_api_build.py

[25.3.x] python_version_independent: ignore python from other packages too
