- conda_build/post.py
Within `post.py` there is a function called `check_symlinks()`. This function makes sure any symlinks to files within the build are relative. If it thinks they are not relative, it unlinks the symlink and replaces it with a new relative version. I believe the change introduced in https://github.com/conda/conda-build/commit/37a0d8ab2bca4b3b4cec72cb34099e5b1c6ec68c contains an error. To illustrate the problem consider a symlink to another file in the same directory:
```
bob@localhost ~/tmp/linkfun/a/b/c $ ll
total 8
drwxr-xr-x  4 bob  users   136B 24 Dec 13:57 ./
drwxr-xr-x  3 bob  users   102B 24 Dec 13:30 ../
-rw-r--r--  1 bob  users     0B 24 Dec 11:02 file.dat
lrwxr-xr-x  1 bob  users    49B 24 Dec 11:04 filelink@ -> /Users/bob/tmp/linkfun/a/b/c/file.dat
```
The code uses …
> Fix relative symlink creation

- .binstar.yml
- conda.recipe/bld.bat
- conda.recipe/build.sh
- conda.recipe/meta.yaml
- conda.recipe/run_test.py
Looking to automate this process to build conda-build on binstar so internal users can subscribe to a dev channel and work with early releases before actual releases occur.
> Add recipe for building conda-build with conda-build

- conda_build/build.py
- conda_build/metadata.py
This removes files from the list list of initial files so they are included.  It's required for building things like conda that are going to replace the `$PREFIX/bin/conda` file inside the build environment with their current version.
See also: https://github.com/conda/conda/pull/1086
> Allow specifying files to always include

- conda_build/main_build.py
[Here](https://github.com/omnia-md/conda-recipes/issues/82), we observed that when building a large collection of packages, some of the packages did not build correctly. In the log file, I see things like
```
BUILD START: mixtape-0.2.2-np18py27_1
Fetching package metadata: ...
Solving package specifications: 
Error: Could not find some dependencies for mdtraj: scripttest
```
The issue is that "mixtape" has a build-time dependency on "mdtraj", and "mdtraj" has a _runtime_ dependency on "scripttest", but _not_ a build time dependency on "scripttest". If the "scriptest" package does not exist yet, then This results in [conda/resolve.py](https://github.com/conda/conda/blob/master/conda/resolve.py#L311-L313) throwing the observed `Error: Could not find some dependencies for mdtraj: …
> Fix for building dependencies

- conda_build/build.py
Before if detect_binary_files_with_prefix was used all binary files
would be shown as being detected as text files.  This is more
accurate and shows better what conda will be doing to the files.
> Distinguish a binary file detected with a prefix

- conda_build/post.py
Related to #287 and should fix test failures on #286.
> Ignore check_symlinks() whenever readlink() is unavailable

- conda_build/build.py
See #322. The templating of the meta.yaml might pull in false information from
previous work directories.
Note that I left the removal in the provide() function because it
can be called from elsewhere.
> Remove the work directory earlier in the build

- conda_build/exceptions.py
- conda_build/main_build.py
- conda_build/metadata.py
This fixes the issue described in both #247 and #137 by detecting parse errors related to "{{" inside a YAML file.  The major reason for those to be there is when doing template work.
> Halt build on YAML error without jinja2

- .travis.yml
I'm not sure if we need sudo, but if we don't, this should make the builds use
docker, so they will start faster.
> Try setting sudo: false in the .travis.yml

- conda_build/source.py
This allows specifying a source as a git repository for projects using git submodules, as IPython does.
I'm not entirely convinced this is the right approach, but it made it work correctly for me.
> Clone git sources with --recursive option

- conda_build/index.py
- conda_build/main_index.py
It used to rely on exact `mtime` matches, which was problematic for distributed file systems like GlusterFS.
I considered switching just converting the times to ints to get around precision issues, but since we already calculate `MD5`, I thought that might be less controversial.
> Switch to using MD5 for comparison in conda index

- conda_build/post.py
The logic that was intended to skip egg dirs that were not part of the package
was incorrect and ended up skipping all egg dirs.
> Correctly fix egg dirs that are part of the package

- conda_build/environ.py
10.5 can cause build problems, as the SDK is rarely present.
> update MACOSX_DEPLOYMENT_TARGET to 10.6

- conda_build/post.py
See #111 for discussion. Without the flag, patchelf modifies RUNPATH rather
than RPATH.
> Use the --force-rpath flag to patchelf

- conda_build/build.py
This is a fix for issue #178 
Reordered building of package list for test environment. While adding package to list, if python is included, then ignore adding python to list for packages that test for valid python module/package imports.
I've manually tested this using miniconda3 for a build of a package that requires python 2.
> fix for issue #178

- CHANGELOG.txt
- conda_build/build.py
Starting in version 1.12.0, this switched from including files if present to requiring those files to be present.  This breaks the conda-env build and any other build that used the original design.
Given that it is a backwards in-compatible change, this a break without bumping to version 2.0.0.  Reverting this change and changing to a simple error message.
Original Commit: f708dd0225b5292b644133afd190800e24e5e047
> Fix regression in always_include_files introduced in 1.12.0

- conda_build/build.py
This is to help avoid typos. If there are files that aren't always there, you
can filter them out with selectors.
See the discussion at
https://github.com/conda/conda-build/commit/f708dd0225b5292b644133afd190800e24e5e047
> always_include_files should error on files that aren't there

- conda_build/main_skeleton.py
- conda_build/pypi.py
Currently, when conda-skeleton has more than one sources to choose from, it asks
the users for the decision. The patch changes this behaviour to download from
the source with the least source size. This is because this former choice can
only add to the confusion of a _normal_ user. An informed user can override the
behaviour with the newly added `--manual-url` command line argument.
Signed-off-by: Harsh Gupta <gupta.harsh96@gmail.com>
> skeleton pypi: add --manual-url argument

- conda_build/index.py
This issue is also described here:
https://groups.google.com/a/continuum.io/forum/#!topic/conda/UXX9E7LkVMA
If necessary, this could also issue warnings about old style packages, or only fix them when an option is given.
> Fix issue where 'conda index' with old packages would create bad metadata

- conda_build/pypi.py
conda-skeleton implicitly assumes that package name is same module name and adds an import test for that, it is not necessarily the case. For example the package dnspython installs a module named dns and the package factory_boy installs the package factory. The earier behavior was causing build failures for such packages.
> fix import_tests: module name != package name

- conda_build/main_skeleton.py
- conda_build/pypi.py
This PR aims to make comparison of version of locally available recipe with version on PyPI simpler.
fixes #397
> [ENH] Add --version-compare argument to conda-skeleton

- conda_build/build.py
Currently, conda-build depends on finding a conda-build package in the index. 
I think this was introduced in https://github.com/conda/conda/commit/f231ad67c1f18e84f9f70cc68ffb352096f63617.
> Removed conda-build's circluar dependency.

- conda_build/source.py
This is a remnant from the Anaconda build system. It does not belong in
conda-build.
> Remove special logic if the username on Windows is "builder"

- conda_build/main_skeleton.py
- conda_build/pypi.py
The `--no-download` option of `conda-skeleton pypi` is non-functional. Presently conda-skeleton derives important metadata from the packages setup.py file with this setup there is no way to create any recipe  without the downloading the package source.
> skeleton: remove --no-download option

- conda_build/pypi.py
Most of the heavy lifting of `conda-skeleton pypi` is done by the `get_package_metadata` function, this monolithic block of code is huge (~250 lines) which makes it hard to debug this code and reuse its parts in other. This PR factors out a few blocks into their own functions.
> Refactor conda-skeleton pypi

- conda_build/pypi.py
> skeleton: fix noarch_python option when build_comment is "#"

- conda_build/windows.py
The echo-ing of the environment when building windows distributions is exceedingly noisy, and often it is hard to see the wood from the trees. This change moves the echo on to be after the re-iteration of the build environment variables.
> Moved the windows build echo command to after the environment variables.

- conda_build/metadata.py
- tests/test-recipes/metadata/extra_freeform_metadata/meta.yaml
- tests/test-recipes/metadata/extra_freeform_metadata/run_test.py
Allow the meta.yml to have arbitrary metadata in the recipe.
This is useful for all the things that conda doesn't/shouldn't really care about.
> Supported freeform content in the meta.yaml.

- conda_build/main_develop.py
- conda_build/post.py
added --post-link option for develop command
- looks in package directory for *.so and ensures they link against
libraries in conda environment
- build_prefix points to current conda environment
- 'path' of executable (*.so) is not in build_prefix
> Added conda develop --post-link

- appveyor.yml
- conda_build/build.py
- conda_build/config.py
- conda_build/metadata.py
- conda_build/source.py
- tests/test-recipes/metadata/always_include_files_glob/meta.yaml
- tests/test-recipes/metadata/always_include_files_glob/run_test.py
- tests/test-recipes/metadata/always_include_files_regex/meta.yaml
- tests/test-recipes/metadata/always_include_files_regex/run_test.py
- tests/test-recipes/metadata/numpy_build/meta.yaml
- tests/test-recipes/metadata/numpy_build/run_test.bat
- tests/test-recipes/metadata/numpy_build/run_test.sh
- tests/test-recipes/metadata/numpy_build_run/meta.yaml
- tests/test-recipes/metadata/numpy_build_run/run_test.bat
- tests/test-recipes/metadata/numpy_build_run/run_test.sh
- tests/test-recipes/metadata/numpy_run/meta.yaml
- tests/test-recipes/metadata/numpy_run/run_test.bat
- tests/test-recipes/metadata/numpy_run/run_test.sh
- tests/test-recipes/metadata/python_build/meta.yaml
- tests/test-recipes/metadata/python_build/run_test.bat
- tests/test-recipes/metadata/python_build/run_test.sh
- tests/test-recipes/metadata/python_build_run/meta.yaml
- tests/test-recipes/metadata/python_build_run/run_test.bat
- tests/test-recipes/metadata/python_build_run/run_test.sh
- tests/test-recipes/metadata/python_run/meta.yaml
- tests/test-recipes/metadata/python_run/run_test.bat
- tests/test-recipes/metadata/python_run/run_test.sh
- tests/test-recipes/metadata/source_git/bld.bat
- tests/test-recipes/metadata/source_git/build.sh
It will still be included if CONDA_NPY or --numpy is specified, but by
default, numpy is now treated just as any other package.
> Don't include the numpy version in dependencies by default

- conda_build/post.py
This PR fixes an issue where absolute symlinks in the built binaries are not recognized as such and made relative if conda's build environment path contains a symlink.
This is because the path to which the tested symlink is pointing to is resolved with `os.path.realpath()` (which expands _all_ symlinks that are in it), but `config.build_prefix` isn't. I've encountered this bug on a system where `/home` is a symlink to `/nsf/home` (and I've had conda installed in my home directory).
> bugfix: symlinks not made relative if build_prefix contains a symlink

- bdist_conda.py
- tests/test-recipes/test-package/bin/test-script-setup.py
- tests/test-recipes/test-package/conda_build_test/manual_entry.py
Just included everything passed to `scripts` in the `--help` tests. This will help improve testing for Python packages not leveraging the keyword arguments added by `bdist_conda`. Also, it applies a reasonable on all other Python packages (namely having basic help for command line tools).
As this is something `argparse` pretty much handles (or the deprecated `optparse`), this seems like a reasonable constraint.
> Test binaries passed to `setup` via `scripts` keyword argument using `--help`

- .travis.yml
- appveyor.yml
It would be nice to catch issues with `conda build --help` in advance of a release. This is an easy way to do so.
Ultimately, something like this would be good, as well ( https://github.com/conda/conda-build/pull/400 ). Though it may need more work.
> Test help on CIs

- README.rst
- appveyor.yml
- bdist_conda.py
- conda_build/build.py
- conda_build/main_build.py
- conda_build/main_metapackage.py
- conda_build/main_pipbuild.py
- tests/test-recipes/build_recipes.sh
This PR is similar to https://github.com/conda/conda/pull/1458.  Also, only externally visible changes are made, in particular the option `--no-binstar-upload` is renamed to `--no-anaconda-upload` (where the first is also being accepted for now.
> Rename binstar -> anaconda

- conda_build/metadata.py
This small change allows sections in `meta.yaml` to be empty.  This makes it easier when having selectors.  For example:
```
build:
number: 1    [win]
```
On Linux this will get preprocessed to:
```
build:
```
Which this PR now allows.
> set field to {} when None

- conda_build/build.py
- conda_build/metadata.py
Using (in `meta.yaml`) the field `about/license_file`, allows adding a license file to conda package under `info/license.txt`.  Possible values are:
* `True`: will search the root of the source tree for the following files (in that order): `LICENSE`, `LICENSE.txt`, `license`, 'license.txt`
* `<filename>`: you can specify the filename of the license file explicitly.
* `Flase`: meaning no license file will be included under `info/license.txt`, which is the default.
For example, if the source tree has `LICENSE` in its root,
```
build:
license_file: True
```
will add this file under `info/license.txt` in in the conda package.
> Add ability to add license file in info/license.txt

- bdist_conda.py
- conda_build/convert.py
- conda_build/index.py
- conda_build/main_pipbuild.py
- conda_build/pypi.py
Fixes conda/conda#1425.
Also, grabbed a few more while I was at it.
> Use `splitlines` to break up multiple lines

- conda_build/main_develop.py
1. Added options to conda develop to build extensions
`conda develop --build_ext pkg_path`
Looks for setup.py in pkg_path, then invokes python setup.py build_ext --inplace
No exception handling here, so if this fails then user should be alerted since their setup.py is broken. If setup.py not found, then simply exit.
2. Added option to clean and build extensions
`conda develop --clean_build_ext pkg_path`
This will invoke python setup.py clean && python setup.py build_ext --inplace
3. Both options above will fix the linkages in extensions after building so they first search in current conda environment's lib/. for dependencies.
4. Also updated write_to_conda_pth() so a path is only appended to conda.pth if the path does not already exist in the file.
> develop options --build_ext, --clean_build_ext

- conda_build/build.py
- conda_build/metadata.py
- tests/test-recipes/metadata/build_skip/meta.yaml
- tests/test-recipes/metadata/build_skip/run_test.py
Implements #399 slightly differently (but I used that as a template). (ping @rmcgibbo)
This will be really useful for tools such as ObviousCI which look at a collection of recipes and figure out which ones to build (and the appropriate build matrix of py and npy versions).
If would be useful to know if this is a go-er or not, if not, my backup is to use something like:
```
package:
name: conda-build-skip
...
extra:
skip: True  # [not py2k]
```
Or even:
```
package:
name: conda-build-skip
...
extra:
skip_if: python > 2
```
> Added a build/skip entry to MetaData.

- conda_build/post.py
- tests/test-recipes/metadata/post_build_versioning/build.sh
- tests/test-recipes/metadata/post_build_versioning/meta.yaml
- tests/test-recipes/metadata/post_build_versioning/run_test.sh
Previously, search for `__conda_*__.txt` files fails when the source directory is at one directory down of WORK_DIR.  This is typically the case for a directory decompressed from zip or tar file.  This patch fixes the problem by replacing all occurrence of source.WORK_DIR in get_build_metadata() with source.get_dir().
> Post build versioning

- conda_build/metadata.py
Adding (optionally)
```
about:
license_family: MIT
```
will add the `license_family` in the `info/index.json` file of the conda package.
> add license_family to index.json

- conda_build/main_build.py
The following command crashes if `$CONDA_ROOT/conda-bld/$PLATFORM` does not exist.
```
$ conda build --skip-existing conda.recipe
```
> Fixed crash when using `--skip-existing` while conda-bld is empty

- conda_build/metadata.py
- tests/test-recipes/metadata/numpy_build_run/run_test.bat
- tests/test-recipes/metadata/numpy_build_run/run_test.py
- tests/test-recipes/metadata/numpy_build_run/run_test.sh
- tests/test-recipes/metadata/numpy_run/run_test.bat
- tests/test-recipes/metadata/numpy_run/run_test.py
- tests/test-recipes/metadata/numpy_run/run_test.sh
- tests/test_metadata.py
Currently, it is only possible to create a conda package, that just depends on `numpy`, by unsetting `CONDA_NPY` (and not using the `--numpy` option).  One can build two different packages depending on this setting (outside the recipe), which is undesirable.
This PR makes the numpy version being included in dependency specs in metadata much more explicit.  Listing just `numpy` as the runtime dependency, will *always* result in just that (setting `CONDA_NPY` won't change that.  In order to make a recipe independent of the numpy version actually set, one lists `numpy x.x` as a dependency, which will *require* using `CONDA_NPY` or `--numpy`.
Also, we add a new function, `handle_config_version()` to handle the confusing logic, as well as tests for this new function.
> Be more explicit when numpy version is included in dependency specs in metadata

- conda_build/main_develop.py
- tests/test_main_develop.py
Include option to uninstall a package path that was previously added via
conda develop. If path is not found in conda.pth, it prints a message
to inform that package was not installed via conda develop.
Added a test module for unit testing some functions of develop command
> Add uninstall option for develop with unit tests

- conda_build/build.py
When auto-adding python spec to execute `run_test.py`, don't require a specific version.  Otherwise, `environ.get_py_ver()` can conflict with the recipe's own python requirements.  (If the recipe's `run_test.py` really needs a particular version of python, it can still be specified in the `test:requires:` section of `meta.yaml`, as usual.)
Fixes #587
> When auto-adding python spec to execute run_test.py, don't require a specific version

- conda_build/source.py
The fix is easy: when writing to `sys.stdout`, strings should be encoded with `sys.stdout.encoding`.
> Fix: 'conda build' crashes when git output contains non-printable characters

- conda_build/source.py
Turns out `sys.stdout.encoding` can be `None`, as well. This normally happens when `stdout` is redirected. This fixes that bug and simplifies the logic around that region to hopefully avoid its recurrence.
For the curious ones, here's a bit more on why this happens ( http://www.macfreek.nl/memory/Encoding_of_Python_stdout ).
This encoding problem can be reproduced by a trivial docker container. Building this container will print `None`.
FROM python:2
RUN python -c "from sys import stdout as so; print(so.encoding)"
> Fix `None` encoding bug

- conda_build/cran.py
- conda_build/metadata.py
- conda_build/pypi.py
This is a much safer way to load yaml (comparable to yaml.safe_load).  This removes the ability of yaml to construct arbitrary python objects.  We now do not use yaml's type conversions, doing our own conversions as needed.  This is better because the vast majority of our options are string options anyway.
We use yaml's C library if it is available.  This *significantly* speeds up yaml parsing.  It falls back to the python parser if the C library is not available.
> [WIP] Improve yaml loading

- conda_build/pypi.py
The check here has no effect. It is probably a typo, though I do not
know the code base well enough to be sure.
> This is probably a typo.

- conda_build/environ.py
- conda_build/metadata.py
Fixes a tiny bug in `environ.py`.  The `NPY_VER` environment variable was incorrect for numpy versions >= 1.10 (`NPY_VER`was evaluating to `1.1.0` instead of `1.10`).
> environ: Fix NPY_VER for versions >= 1.10 (Should be '1.10', not '1.1.0')

- conda_build/metadata.py
For conda recipes, I think it is safer/desirable to use `jinja2` in "strict" mode, which raises an error if the template attempts to use a variable that isn't defined.
For instance, this recipe contains a typo in the `run` requirement:
```
requirements:
build:
- python {{PY_VER}}*
run
- python {{PY_VEER}}*
```
Without strict mode, the typo is ignored, and the template simply evaluates to nothing. (Not good.)
Here's another example:
```
requirements:
build:
- numpy {{NPY_VER}}*
```
No typos there, but if the user forgets to provide the `--numpy=` setting to `conda build`, then `NPY_VER` will be undefined.  Ideally, an error should be emitted in this case, but you won't see any error without strict mode.
This PR has the potential to break existing recipes, if they somehow rely template …
> metadata: Create jinja2 environment with 'strict' mode for undefined values

- conda_build/cran.py
Conda skeleton would choke if there were unicode characters in cran metadata.
> normalize unicode so it can be encoded as ascii

- conda_build/main_build.py
To build with a specific python version, the user can try two things:
1. The `CONDA_PY` environment variable, e.g. `CONDA_PY=27 conda build my-package`
OR
2. The `--python` option on the command-line, e.g. `conda build --python=2.7 my-package`
Internally, both mechanisms set `CONDA_PY` within `conda_build.config`.  Additionally, `os.environ["CONDA_PY"]` can also be used, but **only** if the user used the first mechanism.  It would be nice if that also worked in the second case.  (For example, that would make the value consistently available to `jinja2` templates within `meta.yaml`, as well as the `build.sh` environment.)
This little PR just copies `config.CONDA_PY` (and `config.CONDA_NPY`, etc.) into `os.environ`, so the two modules are in sync for these variables.
It allows `meta.yaml` …
> main: If user supplies --python, auto-set CONDA_PY environment variable.

- conda_build/main_build.py
Unlike the conventions for `config.CONDA_PY` and `config.CONDA_NPY`, which have values like `27` and `19`, respectively, the convention for  `CONDA_PERL` and `CONDA_R` [says][1] to keep the `.` characters in these variables, e.g. `CONDA_PERL=5.22.0`.
Fixes #696
[1]: https://github.com/conda/conda-build/blob/03c75c0597370c5ef1b0356c16f3beab1f417413/CHANGELOG.txt#L469-L472
> Fix handling of --perl and --R

- conda_build/environ.py
- conda_build/jinja_context.py
- conda_build/metadata.py
- tests/test-recipes/build_recipes.sh
- tests/test-recipes/metadata/jinja_vars/build.sh
- tests/test-recipes/metadata/jinja_vars/meta.yaml
**Note:** The "Files changed" tab here on github makes this PR seem bigger than it really is.  If you review these commits individually, you'll see that each one is small.
---
conda-build defines a number of [environment variables][1] that can be used within `build.sh`.  Using jinja templates, you can also use *most* these variables within `meta.yaml`.  I say *most* because some of those variables come from `meta.yaml` itself, such as `PKG_BUILDNUM`.
For instance, this recipe attempts to include the build number as part of the build string, but it won't work:
```
build:
number: 99
string: special_build_n{{PKG_BUILDNUM}}
```
We can fix this.  Since conda-build parses `meta.yaml` in *two passes*, there's no reason we can't make those variables available in the second pass.  That way, there …
> Provide parsed metadata from first pass as context to second pass

- conda_build/source.py
This copies symbolic links as links. This should be more efficient, and I have
one pathological example of a SVN repository that contains a symlink to '.'
that results in a endlessly recursive copy that eventually throws an exception
from the path getting too long.
> conda_build/source.py: give symlinks=True to copytree()

- conda_build/scripts.py
More details are available in #251.
NOTE: I've changed `PY_TMPL` from a dumb order-dependent-argument templating to a keyword-oriented templating to improve readability and to prevent possible errors in future.
> fix #251: support entry points with dots

- conda_build/main_pipbuild.py
Conda pipbuild should be removed in a future release.  This PR simply informs any potential users of its inevitable removal.
> Deprecate conda pipbuild in favor of conda skeleton.

- conda_build/utils.py
This PR changes `uncompress` to `gunzip`.
`uncompress` is an alias for `gunzip` and that alias is not always defined in old Linux systems (like CentOS 6).  (See the failures [here](https://circleci.com/gh/ioos/conda-recipes/929) for an example.)
For more information see the discussion in https://github.com/conda/conda-build/issues/362#issuecomment-101066000.
> Find uncompress in old Linux

- conda_build/main_build.py
Currently, a recipe that skips a certain configuration would still cause --output to print a file path. This is misleading, because if that configuration is skipped in the meta.yaml, no file path should be provided. This PR fixes the issue by moving the code for skipping a configuration above the handling of --output.
A quick merge and bugfix release of conda build would be much appreciated.
Thanks!
The Bioconda team.
> Moved m.skip() above the code for --output, such that --output does not provide misleading information.

- conda_build/jinja_context.py
- conda_build/metadata.py
- tests/test-recipes/metadata/jinja_load_setuptools/build.sh
- tests/test-recipes/metadata/jinja_load_setuptools/meta.yaml
- tests/test-recipes/metadata/jinja_load_setuptools/setup.py
Our setup.py relies on `__file__`, so I've added that, as well as `__name__` and `__doc__`, to the namespace used when exec'ing the file.
> Enhancements for module exec in load_setuptools

- conda_build/source.py
- conda_build/utils.py
Trying to fix issue #349.
With this patch, I can successfully build on Windows using Python3 (it's broken otherwise). I tested the helper function using python2 but not a whole build.
> "replace" unicode errors in git_info (hopefully fixing #349)

- conda_build/build.py
- conda_build/main_build.py
Packages should be left wherever they were loaded from when running with conda build --test. 
#678
> Do not move packages to broken directory when running tests only

- conda_build/build.py
get_build_metadata reads a custom version file which is necessary
for finding and installing a package when testing a package build.
#676
> Read build metadata when testing package build

- conda_build/metadata.py
An API change was made to MetaData.parse_again in #694. This change simply makes the API change softer by providing a suitable default.
> Avoided chaning the API for MetaData.parse_again.

- conda_build/main_build.py
There is a bug in conda-build that makes it impossible to build for multiple python versions in one line on Windows (e.g., `--py 35 --py 34 --py 27`), because of this assertion: https://github.com/conda/conda-build/blob/237e8fd2643863b6c1df6a4fd413dba8c24119b5/conda_build/main_build.py#L275 
Obviously that check will fail on any build after the first. The *real* solution for the issue that assert is trying to fix, would be to *not* delete the trash under such conditions, and to warn the user with a message that actually makes sense. This PR does so and restores the functionality.
> Bugfix to restore functionality: building for multiple python versions on Windows

- conda_build/environ.py
This simple PR fixes https://github.com/conda/conda-build/issues/647
> fix building when git is not installed

- conda_build/environ.py
Before the package source is downloaded, variables like `GIT_DESCRIBE_TAG` can be given incorrect values if a previous build left a git repo in the source directory.  It's not a huge problem, but it does produce incorrect status messages until the source is finally downloaded.
This PR fixes it by leaving those `GIT_` variables undefined if the `work` directory doesn't correspond to the package being built.
> Don't define GIT_ environment variables if the work directory is out-of-sync

- conda_build/main_build.py
~~Do not merge yet.  This PR depends on #758, so review that first.~~
This PR builds on #750, but avoids downloading the source when it's not necessary.  Simply put, the `--output` flag doesn't produce the right answer if the `build_id` depends on downloading the source (so the git tag can be checked).  This PR downloads the source first, but only if necessary.
> Fix --output command by downloading the source first if necessary

- CHANGELOG.txt
- conda_build/environ.py
- tests/test-recipes/metadata/build_env/meta.yaml
- tests/test-recipes/metadata/build_env/run_test.py
Fixes https://github.com/conda/conda-build/issues/612
In a recipe, a user can specify variables that can be defined externally to influence the recipe. The previous practice was to leave these undefined. However, a commit was added that began setting them to `<UNDEFINED>`. If a user intentionally left these variables undefined, they must now go back and unset them afterwards. The intent of this was likely to smoke out errors. This could initially be easily worked around in bash or batch. However, 2 pass jinja templating has forced us to handle this inside the `meta.yaml`, which is more challenging and unnecessarily ugly. Instead of continuing this trend of setting intentionally undefined variables, this breaks from that change and simply warns the user when they have an undefined …
> Stop setting values for undefined environment variables

- conda_build/pypi.py
The code was checking equality rather than assigning.
I guess no-one actually used this option?
> Fix unmasking build section for noarch_python

- conda_build/metadata.py
- tests/test-recipes/metadata/source_git_jinja2/meta.yaml
(This is an update to 03c75c0597370c5ef1b0356c16f3beab1f417413.  See also: #694.)
The `meta.yaml` file is parsed twice.  During the first parse, we permit undefined jinja variables without raising errors (but the final parse is strict).
So, this is allowed:
```yaml
build:
string: {{ GIT_FULL_HASH }} # Not defined yet during the first pass, but that's okay.
```
We also avoid choking even if the undefined variable is used in an **expression** involving various operators:
```yaml
build:
string: {{ GIT_FULL_HASH[:7] + "_hello" }}
```
But I forgot one operator: attribute access (`.`).  So, this will choke the jinja parser on the first pass:
```yaml
package:
name: pandas
version: {{ GIT_DESCRIBE_TAG.replace('.dev', 'dev') }}
```
This PR fixes that problem.
Update: I also made a few tiny …
> metadata: Permit attribute access on undefined jinja values

- conda_build/environ.py
Inside of `conda_build.environ.get_dict()`:
The initial value of `m` is `None`. An erroneous call to `m.get_value('source/git_url')` without first checking the status of `m` raises a `NoneType` exception if `get_dict()` is referenced outside of a real build environment.
See also, #751
> Fix parsing git metadata while metadata is None

- example_packages/noarch_python/README.txt
- example_packages/noarch_python/build.sh
- example_packages/noarch_python/foo.py
- example_packages/noarch_python/meta.yaml
- example_packages/noarch_python/run_test.py
- example_packages/noarch_python/setup.py
Previously `bokeh` was the noarch example package, which is actually not a good example because it is quite large and has many dependencies.  The new example is simple, *really simple*.
> make no-arch exmaple really simple

- conda_build/environ.py
Most distributions provide a multilib gcc option.  These provide the capability to compile 32-bit code with a 64-bit GCC.  Our experimental compiler docker image ( https://github.com/ContinuumIO/docker-images/pull/20 & https://hub.docker.com/r/msarahan/conda_builder_linux/ ) uses this.  Moreover, there is no 32-bit only CentOS docker image, so this is our only real option with Docker/CentOS.
Ping @groutr @ilanschnell @kalefranz 
@stuarteberg @jakirkham @ukoethe - if any of you are familiar with this stuff, I'd appreciate your input, too.
> Add -m32 to CFLAGS and CXXFLAGS for multilib gcc

- conda_build/environ.py
If the drive is on D: (for example), the CYGWIN_PREFIX environment variable will be wrong, which may cause it to miss paths to be replaced in text files.
> Fix CYGWIN_PREFIX for other drive letters other than C:

- conda_build/build.py
- conda_build/metadata.py
- conda_build/noarch_python.py
- conda_build/windows.py
- tests/test-recipes/metadata/noarch/meta.yaml
- tests/test-recipes/metadata/noarch/noarch_test_package/README
- tests/test-recipes/metadata/noarch/noarch_test_package/noarch_test_package.py
- tests/test-recipes/metadata/noarch/noarch_test_package/setup.py
- tests/test-recipes/metadata/noarch/run_test.py
* Fixes that the `build/script` entry was ignored on Windows
* Fixes that setting `noarch_python` to `False` still builds it as a noarch package (#787)
* Enables making noarch packages on Windows (fixes #796)
> Building noarch packages on Windows

- .travis.yml
- tests/test-recipes/build_recipes.sh
Fixes https://github.com/conda/conda-build/issues/810
Includes https://github.com/conda/conda-build/pull/811
Includes https://github.com/conda/conda-build/pull/809
As of conda 4.0, Python 3.3 is not supported. However, testing continues to happen here for Python 3.3. We have added a workaround to handle installing a version of conda 3.x here for Python 3.3. Also, an error message changes in conda 4.0 so we have included a different check for that warning message. However, if conda 3.x is installed for the Python 3.3 case the old error message check is used instead.
> Fix Travis CI for Python 3.3 and conda 4.x

- conda_build/environ.py
- conda_build/macho.py
- conda_build/main_develop.py
- conda_build/post.py
- conda_build/utils.py
The first commit is about making otool more useful / informative, then removing a hack and a bit of refactoring.
The 2nd commit builds on it and is important. Any package that depends on DYLD_FALLBACK_LIBRARY_PATH on OS X can't be built currently on 10.11 and this change addresses that. My approach is to add an -rpath to LDFLAGS during the build and then remove it from the executables at the end.
I went down a different path for fixing this initially (modifying the LC_ID_DYLIB load command names in the dylib files in the build environment) but backed it out when I realized it would've required copying instead of hard-linking when installing packages into the build environment. Also doing it as-per this PR involves less code (but it does rely on people not overriding LDFLAGS in build.sh) …
> Work-around System Integrity Protection on El Capitan.

- conda_build/environ.py
- conda_build/source.py
This PR addresses an issue that can occur when building a conda recipe from a local git repository. For example:
```yaml
source:
git_url: ../
```
If the user *switches branches* and attempts to build a recipe, conda-build's `git_cache` will still point to the old `HEAD`, meaning that the user is not building the branch she thinks she's building.
For example:
```bash
cd my-git-repo
git checkout master
conda build my-conda-recipe
git checkout develop
conda build my-conda-recipe 
```
It's surprising that this hasn't been noticed before, but maybe most people use `source/path` instead of `source/git_url` for local repositories, so this problem doesn't affect them.
Aside from that issue, I'm fixing a few other git-related problems.  See the commit history for details.
> Fix git with local branches

- conda_build/environ.py
The master branch of conda-build now introduces a large volume of git errors into [conda-build-all] (https://github.com/SciTools/conda-build-all).  Issue discussing this can be found at SciTools/conda-build-all#23.  The tl;dr is that these next two lines are printed roughly 200 times *for each package* that is being built with `conda-build-all`
```
fatal: ambiguous argument 'v0.4.0rc2': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions
```
This PR silences those git errors by redirecting stderr to stdout.  Note that eefb08e closes SciTools/conda-build-all#23.  e2f584c is dealing with some PEP8 in `environ.py`, but I am happy to get rid of that commit if you would rather leave files "as is".
Thanks!
cc @stuarteberg @pelson @janshulz
> Silence git errors in `get_git_build_info()`

- conda_build/macho.py
Fixes a bug I introduced in 38f333 where
install_name_tool -change was being called
on the last LC_LOAD_DYLIB instead of the
one that was meant to be changed.
> macho.py: Change the right dylib name

- .travis.yml
This reverts commit ( https://github.com/conda/conda-build/commit/f85dcdb1b511ffd059992133d1ad2adb35a9375a ).
As it appears Python 3.3 CI has been dropped, there is no longer a need for this check.
> Revert "travis: Fix testing on Python 3.3."

- conda_build/environ.py
~~Awaiting feedback in #820.~~  Now tested and ready for merge.
environ.get_git_build_info(): All entries in env dict must be str, not unicode.
Fixes #820
> Fix Windows crash in environ.get_git_build_info()

- conda_build/metadata.py
In this PR, we add the following new (optional) keys to the `about` section in `meta.yaml`: `description`, `dev_url`, `doc_url` and `license_url`.  Here is an example of how they might be used:
```
about:
license: Apache
summary: N-D labeled arrays and datasets in Python
description: |
xarray (formerly xray) is an open source project and Python package that
aims to bring the labeled data power of pandas to the physical sciences,
by providing N-dimensional variants of the core pandas data structures.
dev_url: https://github.com/pydata/xarray
doc_url: http://xarray.pydata.org
```
> allow additional keys in "about" section

- conda_build/environ.py
- conda_build/post.py
@ilanschnell, @msharan, @kalefranz, @pelson, @groutr, @jakirkham, @stuarteberg 
It seems install_name_tool from OS X 10.7 is buggy regarding -delete_rpath. Another way forward will have to be found.
The proper fix (and even detection of the problem - I couldn't get a 10.7 VirtualBox image to work) is going to take a bit of time, I can't look at it for a while and there's no way I can leave things broken for that long. Unfortunately OS X 10.11 users of conda-build will face a minor regression, but that's less important.
I would appreciate it if everyone who's built binaries that have then failed to load could run:
strings $(install_name_tool 2>&1 | cut -d' ' -f2) | grep cctools
or:
strings $(which install_name_tool) | grep cctools
and also give me the md5sum of the real install_name_tool …
> OS X: Revert SIP fix for now

- conda_build/build.py
I already proposed this PR last fall, but Aaron wanted to implement a better fix. Now, as Aaron has left and the problem still exists, I'm trying again. 
The problem is that Windows removes the test dir asynchronously and can't recreate it before removal is finished, resulting in occasional test failures. I just avoid the problem pragmatically by waiting for a second between the two operations.
> fixed race condition between removal and creation of tmp_dir on win

- conda_build/environ.py
This assertion in `environ.py` isn't correct because the conda-build root directory might not be `conda-bld` (it might be customized in `.condarc`).  The assertion didn't provide much value anyway, so I'm just removing it.
Fixes the error in conda-forge/nn-feedstock#3.
> environ: Removed invalid assertion.

- conda_build/metadata.py
If `yamlize()` fails to parse `meta.yaml`, we'd like to show a nice error message.  But at the moment, `conda-build` only detects `yaml.parser.ParserError`.  Other errors from `yaml`, such as `ScannerError`, just trigger a normal traceback.
This one-line PR checks for `yaml.error.YAMLError` instead, which is the base class for all `yaml` errors.
Closes #860.
> Display a nice error message for all yaml parsing errors, not just ParserError

- conda_build/environ.py
**Update:** In addition to defining `CONDA_PY` and `CONDA_NPY`, this PR now fixes a bug (introduced via c43325f).  Please merge...
----
(This PR is tiny.)
Most of the [environment variables](http://conda.pydata.org/docs/building/environment-vars.html) listed in the conda build docs are available for use in `build.sh`, but `CONDA_PY` and `CONDA_NPY`are missing.  This PR adds them.
These variables can be useful when setting the build string from within `build.sh`, via [`__conda_buildstr__.txt`][1]
[1]: http://conda.pydata.org/docs/building/meta-yaml.html#package-version
> environ: Make CONDA_PY and CONDA_NPY available in build.sh

- conda_build/build.py
- conda_build/noarch_python.py
- conda_build/post.py
currently conda-build uses `data = fi.read()` on an entire file. It then uses `data = data.replace(a, b)`
even if `a` is never found in the file. The replace means that two copies of the entire data file are in memory at that point.
This uses a memory-map instead of fi.read() and only incurs the memory cost of the `.replace()` if the `a` is found in the file.
> use memory map rather than read() to reduce memory usage.

- tests/test-recipes/metadata/_checkout_tool_as_dependency/meta.yaml
On Windows, SVN was unhappy that we were feeding it urls like
file://c:\path\to\recipe
it wants
file:///c:/path/to/recipe
ping @mjuric
> fix svn url on Windows in checkout tool test

- conda_build/build.py
- conda_build/post.py
This adds an empty file to one of the recipes. Without this fix, the error reported in #868 manifests in tests/test_build_recipes.py
Any suggestions on how to test better? How/where to check if `empty.py` appears in the .bz2
> handle empty files. closes #868

- conda_build/windows.py
- tests/test_win_vs_activate.py
Both VS9 and VS10 do not work out of the box for 64-bit builds.
This should try and remedy that. For VS9 it prefers the
Microsoft Visual C++ Compiler for Python 2.7 and when
falling back VS9 will call the correct bat file manually, rather
than relying on the broken logic in vcvarsall.bat.
For VS10, it will correctly call the Windows SDK rather than
relying on the also potentially incorrect vcvarsall.bat.
This was pretty difficult to test in my VM because I broke
it trying to test the different combinations. I need to create
a clean image and try each of the scenarios. 
What would be the best way to test this? I guess builds
need to be kicked off on Appveyor?
> Attempting to improve the logic for VS on Win

- conda_build/build.py
downstream utilities like the binstar/anaconda client access the info/ stuff in a tar.bz2. If those occur after a large binary or data file then extra work is done to decompress. This mitigates that by sorting files before they so that smaller ones are added to the tar ball first.
> add files in order of increasing size to improve access times to tar

- conda_build/environ.py
- conda_build/windows.py
- tests/test_win_vs_activate.py
Following up from my work in #861, this does two things:
1. Refactor the path logic so that the paths are defined once at the top of the `windows.py` file. This should reduce the risk of the tests going out of sync with the file.
2. Add a new ENV variable `VS_VERSION` that supplies the visual studio version (9.0, 10.0, 12.0, 14.0 etc). This should remove the need for the 'black magic' from the Wiki as the user is supplied with whatever VS version command was run.
If everyone is happy with this then I will also add it to the documentation.
> VS_YEAR, VS_VERSION, VS_MAJOR and CMAKE_GENERATOR Env Variables

- conda_build/noarch_python.py
- conda_build/post.py
any advice on how to trigger this with the tests?
> fix for #889

- conda_build/external.py
This can cause crashes with some programs, e.g. git.  We should not do this - we should only put our own environment on PATH.  If anyone wants cygwin, they can add it themselves.
Closes https://github.com/conda/conda-build/issues/902
> Remove cygwin from conda build's search path

- conda_build/build.py
The command that creates the test environment does not explicitly request the packages listed in the `requirements/run` of the `meta.yaml` file in the environment creation. 
Of course, because they are included in the newly-built package's metadata, you would think this doesn't matter---they're going to get picked up due to that package's dependencies.
The problem is that conda priorities maximizing the versions of the packages that are explicitly requested *first*, and then maximizes the versions of any packages included by dependency *second*. During the *build* stage, then, the build dependencies are given high version-maximation priority; and during the *test* stage, they were given lower version-maximization priority.
This sometimes caused `conda` to select different version of the …
> Include the run specs in the test environment

- conda_build/main_skeleton.py
- tests/test-skeleton/sympy-0.7.5-url/meta.yaml
- tests/test-skeleton/sympy-0.7.5/meta.yaml
- tests/test-skeleton/test_skeleton.py
PyPI changed its URLs and broke tons of stuff.  Their fix is to go back to the old way on the new service: https://github.com/conda/conda-build/pull/900/files/2da794ddf79edceda68a6b33129628f2afb5a94a#r61319835
> change pypi urls to pypi.io

- conda_build/cpan.py
Since the conda skeleton was written `source` and `test` are now required to be dicts if present instead of allowing empty strings.  This fix comments `source` and `test` out if they would have been empty.
> Fix issue with cpan skeleton generating invalid recipes for core modules.

- conda_build/windows.py
The fallbacks for different versions variations of Visual C++ is great.  However, for Visual C++ 9.0, it was only possible to use VC for Python 2.7 or VS Express.  Conda-build would break if you had a full VS2008 install.
VS Express has vcvars64.bat in the VC\bin folder.  VS 2008 locates vcvars64.bat in VC\bin\amd64.  Checking to see if the file exists in VC\bin can distinguish between VS Express and VS 2008.
> Make VS 2008 possible again

- conda_build/environ.py
Allows to override MAKEFLAGS from shell for ci builds.
See https://github.com/conda-forge/staged-recipes/pull/531#discussion_r62131583
> Whitelist MAKEFLAGS env var

- bin/conda-render
- conda_build/completers.py
- conda_build/main_build.py
- conda_build/main_render.py
- conda_build/metadata.py
- conda_build/utils.py
- tests/test-recipes/metadata/nested_recipe/build_number/meta.yaml
- tests/test-recipes/metadata/nested_recipe/build_number/run_test.bat
- tests/test-recipes/metadata/nested_recipe/build_number/run_test.sh
Closes #887 
This is the start of splitting off recipe rendering from building.  I am trying to avoid duplicating code, so I'm splitting the existing code off into other modules.
Right now, it only prints the processed metadata, not a yaml file.  That's easy enough to write as an addon option later - I'm expecting that the raw dictionary will be the most useful thing to people, rather than going back to some file on disk.  My idea is that the build module will just call functions from this file to render each recipe's meta.yaml.
This works right now, with a trivial test of a recipe from conda-forge (zlib).  Original recipe at https://github.com/conda-forge/zlib-feedstock, which I have cloned as a submodule into the packages/zlib folder:
```
$ conda render packages/zlib
{u'about': …
```
> split off recipe render from build; recurse to find meta.yaml

- conda_build/build.py
- conda_build/main_build.py
The point is to allow engineers to debug issues with callstacks spanning
multiple conda packages without having to hack conda-build or mess around
with multiple miniconda environments.
The contents of the old work directory are moved into a temporary dir
before the build commences and moved back after it has completed. It was
done this way because the source unpacking logic is fairly hostile to
this kind of change.
> Add new option --keep-old-work

- conda_build/metadata.py
- tests/test-recipes/metadata/selectors_in_imported_templates/build.sh
- tests/test-recipes/metadata/selectors_in_imported_templates/meta.yaml
- tests/test-recipes/metadata/selectors_in_imported_templates/variables.jinja
As tangentially mentioned in #728, it would be nice if selectors (e.g. `# [not win]`) were respected in not just `meta.yaml` itself, but also in any jinja templates that it happens to import.  This PR implements support for just that, with a simple test.
> metadata: Allow selectors in imported jinja templates

- conda_build/config.py
- conda_build/scripts.py
This fixes a problem when the `debug` feature is enabled (via `debug` metapackage): the interpreter that runs scripts should be `python_d`, otherwise it won't find compiled dependencies.
> Add #!python_d to scripts when package is debug

- conda_build/metadata.py
- tests/test-recipes/metadata/empty_sections/meta.yaml
This is something that I inadvertently broke in #801.  This restores the old behavior until #874 is finished.
> Restore old conda-build behavior for empty sections

- conda_build/environ.py
```
cc1: error: unrecognized command line option "-m"
```
> fix invalid option to gcc

- conda_build/main_build.py
- conda_build/main_render.py
This makes the --output argument of conda render respect the --no-source argument.  It also tries to fix some logic regarding anaconda.org uploading that looked broken.
> remove upload always true, fix some args in download functions

- conda_build/main_build.py
- conda_build/main_render.py
- conda_build/metadata.py
- conda_build/utils.py
This PR fixes a bug in the skip-existing code: if a custom build string was used, it could happen that e.g. `PKG_BUILDNUM` was not initialized. Hence, skip-existing was assuming a wrong package name and errorneously assumed the package was either already present or vice versa. 
Thanks!
Johannes Köster
EDIT: The PR also includes a small improvement to an error message and a fix for a regression introduced in 1.20.1 (see the comments in the diff).
> Fix skip-existing with custom build string.

- conda_build/main_build.py
- conda_build/windows.py
- tests/test-recipes/metadata/_cmake_generator/CMakeLists.txt
- tests/test-recipes/metadata/_cmake_generator/bld.bat
- tests/test-recipes/metadata/_cmake_generator/build.sh
- tests/test-recipes/metadata/_cmake_generator/hello.c
- tests/test-recipes/metadata/_cmake_generator/meta.yaml
- tests/test_build_recipes.py
- tests/test_win_vs_activate.py
This might work - needs testing.  If it doesn't, I think we might need to remove the /Release flag (but this really should work: https://msdn.microsoft.com/en-us/library/ff660764(v=vs.100).aspx)
ping @patricksnape @jakirkham - is there a good way for us to test this with conda-forge?
> Add MSYS2 path translation exclusion for CL with MSVC builds

- conda_build/windows.py
This also rolls back to an earlier behavior of writing the build env vars to the bld.bat script, rather than passing the env to the subprocess call.  This is simpler for debugging, but also (partially) fixes an issue observed in https://github.com/conda-forge/apptools-feedstock/pull/3 - there, with a Python 3.5 root install, the VS 2010 py 3.4 configuration was seeing the root environment rather than the build environment.  This PR changes that so at least the correct Python is on PATH - but the package is still broken somehow.
It should be said that this PR might actually somewhat mask some other issue - the issue being that the _build environment is not always being used, as it should be.
> write env vars to bld.bat

- conda_build/cran.py
- conda_build/metadata.py
- conda_build/source.py
Unify Windows and Unix R dependencies:
* Dependencies on packages in r-recommended are now explicitly listed
on Windows just the same as for the other systems.
* Add m2-base and m2w64-toolchain dependencies.
* Use r-base as the build-string identifying dependency, as well as r
(r is kept for legacy installations)
> cran: Use MSYS2

- conda_build/ldd.py
- conda_build/main_inspect.py
Fixes crashes in `conda inspect`, in part by avoiding any reliance on the filenames or dist names for package info. Instead uses the `conda-meta` content for that info.
> inspect: use conda.install for dist names and metadata

- conda_build/build.py
- conda_build/main_build.py
- conda_build/main_render.py
- conda_build/render.py
- conda_build/scripts.py
- conda_build/source.py
ping @stefanseefeld - please try this.
> download source before testing with -t

- .travis.yml
- appveyor.yml
- conda_build/build.py
- conda_build/main_build.py
- conda_build/metadata.py
- tests/test_build_recipes.py
Closes https://github.com/conda/conda-build/issues/755
Note: anaconda upload has no --token argument.  Might need a separate call to anaconda, then anaconda upload?
> WIP: add command line options to pass tokens and user through to anaconda upload

- conda_build/main_build.py
- tests/test-recipes/metadata/build_number/run_test.sh
Now, local packages have a 'local::' prefix so we must add
that when checking for a package in the index.
> Fix --skip-existing since channel prefixes

- conda_build/metadata.py
- tests/test-recipes/metadata/jinja_vars/meta.yaml
- tests/test_metadata.py
The fix here is to replace `(.+)` with `([^\[\]]+)`:
```diff
-sel_pat = re.compile(r'(.+?)\s*(#.*)?\[(.+)\](?(2).*)$')
+sel_pat = re.compile(r'(.+?)\s*(#.*)?\[([^\[\]]+)\](?(2).*)$')
```
That is, selectors don't contain "any character", they contain "any non-bracket character".
Fixes #955
> metadata: Fixed selector regex to avoid confusion with jinja templates

- conda_build/cran.py
Please review @msarahan, nothing major here.
> cran: License guess fix and use 'posix' package

- bdist_conda.py
- conda_build/build.py
- conda_build/main_build.py
- conda_build/main_render.py
- conda_build/post.py
- conda_build/render.py
- conda_build/source.py
- tests/test_build_recipes.py
- tests/test_render.py
conda build --output was outputting other stuff, when external tools required strictly the package output path.  This fixes it, and adds tests for the behavior.
Closes #949 (sorry everyone)
> fix extraneous output when outputting build path

- conda_build/main_build.py
- conda_build/source.py
- tests/test_build_recipes.py
Extra output was showing up with git sources that the test was not catching.  We need tests for svn and hg, as well as file copying.  Filing issues for those separately.
cc @stefanseefeld
> fix more source checkout outputs showing up without --verbose

- conda_build/jinja_context.py
- conda_build/metadata.py
- conda_build/render.py
- tests/test-recipes/metadata/jinja2_build_str_template_only/bld.bat
- tests/test-recipes/metadata/jinja2_build_str_template_only/build.sh
- tests/test-recipes/metadata/jinja2_build_str_template_only/meta.yaml
**Background:**
Some of the functions that decide whether or not to download the source before jinja rendering changed recently.  (For example, 1a7ebcac287de48493fdb58e0f981f40d85f0ef3 / cc6a3f92999854a58130a7eadea6242be552fcbd)
The function `parse_or_try_download()` decides whether the source is needed before the final parse.  Previously, the decision was made based on the contents of the `package/version` field.  As it turns out, this is not a sufficient condition, because it fails for a recipe like this:
```yaml
package:
name: foo
version: 1.0
source:
git_url: http://github.com/foo/foo
build:
string: g{{ GIT_FULL_HASH[:7] }}
```
```
$ conda build foo
Error: Failed to render jinja template in foo/meta.yaml:
'GIT_FULL_HASH' is undefined
```
**Solution:**
During the first parse, we permit …
> Metadata: Track undefined jinja names and decide whether to download source

- conda_build/environ.py
- conda_build/jinja_context.py
These commits were meant to be tacked on to #964, but I didn't push them in time before it was merged.  Sorry about that.
The `jinja_context` commit is pretty minor, but will hopefully it will help avoid potential surprises in the future.
The `environ` change here is important if you build a recipe with a `git_url` and then accidentally change the capitalization in the URL.
For example, if your recipe says:
```yaml
source:
git_url: https://github.com/Foo/bar
```
and later you accidentally change it to:
```yaml
source:
git_url: https://github.com/Foo/Bar
```
... then you'll encounter a weird error. `verify_git_repo()` will think that the git cache is out-of-sync, so `GIT_*` variables won't work.  Oops.  This PR just makes the comparison case-insensitive.
cc @msarahan -- Sorry again for the …
> Two tiny fixes

- conda_build/render.py
Otherwise we end up stringifying None as 'None' and the
version parsing code falls over later (if you call conda
from a build script for example).
Specifically, for me, the rendered batch file contained:
"set CONDA_NPY=None"
> Only set os.environ for non-None config vars

- conda_build/build.py
- conda_build/environ.py
- conda_build/main_build.py
- conda_build/render.py
- conda_build/source.py
- tests/test-recipes/metadata/_dirty_skip_section/bld.bat
- tests/test-recipes/metadata/_dirty_skip_section/build.sh
- tests/test-recipes/metadata/_dirty_skip_section/meta.yaml
- tests/test_build_recipes.py
I've been working on Qt5 builds.  Extracting the source takes 5-10 *minutes*.  This PR avoids it.  This is a gun pointed at your foot - use it to iterate quickly on recipes, but keep in mind that it may bite you if you forget to capture any source code changes as patches or changes to your recipe.
> add --dirty flag to skip download/extraction step

- conda_build/config.py
Recently hit this 80 character placeholder limit and was hoping to at least increase it to 128.  From this discussion, it sounds like >128 is not deemed useful on Linux systems.
https://groups.google.com/a/continuum.io/forum/#!topic/anaconda/fgDBJ2YwETI
> Update config.py to increase placeholder limit to 128

- conda_build/build.py
- conda_build/environ.py
- conda_build/features.py
- conda_build/metadata.py
In this PR, I want to make it easier to create recipes with support features.  By setting `FEATURE_*` environment variables, the user can select whatever feature they need for building a recipe with and without that feature enabled.
For example, having `FEATURE_DEBUG=0` will add the `debug` variable (set to `False`) to the selector namespace, and set `DEBUG=0` in the environment of the build script.
It is also important to see that during building and testing, the feature is enabled (when set to `1`).
> FEATURE_ environment variables

- conda_build/build.py
Windows paths have a shorter max length than *nix.  The long prefix stuff is for the sake of binary path embedding, which is not relevant to Windows.  This avoids issues where users set the binary prefix to True, and then the recipe breaks on Windows.  Nicer than requiring everyone to have selectors for unix on these things, IMHO.
> don't use long prefix on windows

- conda_build/metadata.py
In this PR, we add new selectors for `x86` and `x86_64` for Intel platforms.  Note that `x86` is `True` on either 32 or 64-bit.  This is consistent with the selectors currently in use in constructor.
> add  selectors for Intel platforms

- conda_build/build.py
Without this, conda-build fails on a certain Windows package as follows:
```
An unexpected error has occurred, please consider sending the
following traceback to the conda GitHub issue tracker at:
https://github.com/conda/conda-build/issues
Include the output of the command 'conda info' in your report.
File "c:\slave32\miniconda\Scripts\conda-build-script.py", line 4, in <module>
sys.exit(main())
File "c:\slave32\miniconda\lib\site-packages\conda_build\main_build.py", line 192, in main
args_func(args, p)
File "c:\slave32\miniconda\lib\site-packages\conda_build\main_build.py", line 486, in args_func
args.func(args, p)
File "c:\slave32\miniconda\lib\site-packages\conda_build\main_build.py", line 409, in execute
include_recipe=args.include_recipe)
File …
```
> Add forgotten encoding argument to open()

- conda_build/build.py
- tests/test_build.py
Intended to address https://github.com/conda-forge/ipykernel-feedstock/issues/6
> search for double backslashes in prefix replacement

- conda_build/metadata.py
- tests/test_metadata.py
Rolls back a little of #573 so that recipes are a little more friendly to write.
Currently one must effectively specify ``numpy x.x`` as both run and build dependencies in order to build a recipe which has a numpy ABI dependency against anything other than the latest numpy. With this change that is reduced to just specifying that as a runtime dependency.
> Lightened up the requirement on recipes to define numpy x.x as runtime

- conda_build/pypi.py
This should hopefully address the intermittent failures we see with conda skeleton.
Closes #988
> search pkg subset with pypi rather than list all

- conda_build/environ.py
- conda_build/main_build.py
- conda_build/metadata.py
- conda_build/render.py
- conda_build/source.py
- tests/test_build_recipes.py
This adds a test that currently fails on Windows, because Conda's move_to_trash isn't working correctly.
> fix missing dirty args.  Cleanup.

- conda_build/pypi.py
This ensures that proxies from the environment are used even if they are not defined in the `.condarc`.
Fixes #550.
> Always use the RequestsTransport to access pypi

- conda_build/build.py
> keep meta.yaml; move meta.yaml.rendered into recipe folder

- conda_build/build.py
- conda_build/metadata.py
- tests/test-recipes/metadata/ignore_prefix_files/meta.yaml
- tests/test-recipes/metadata/ignore_prefix_files/run_test.py
- tests/test-recipes/metadata/ignore_some_prefix_files/meta.yaml
- tests/test-recipes/metadata/ignore_some_prefix_files/run_test.py
Closes #997 
Ping @ilanschnell - please comment whether this is what you had in mind, and if it can be improved.
> add ignore_prefix_files to allowed build flags

- conda_build/source.py
As often you'll get a source file with .old appended
and the target file is the only one that exists.
Without this, you get a warning and a patch strip level
of 0 will be used in some common cases.
Also, I overthought the common prefix stuff and it
is just wrong.
> patch: strip-level guess includes target files

- conda_build/source.py
The problem with `git clone --recursive` is that git submodules (if any) are cloned according to whatever the repo `HEAD` wants them to be.  Then weird conflicts can occur when we actually `checkout` the commit specified by the `git_rev` field.
Instead of `git clone --recursive`, we can avoid this issue by using just `git clone`, followed by `git submodule --init --recursive`, *after* we've called `checkout` to select the correct commit.
(@svenpeter42 discovered this problem and proposed the fix.)
> source: Don't clone git submodules until after checkout

- appveyor.yml
- conda_build/environ.py
- conda_build/utils.py
Earlier versions of git for windows do not include cygpath (current ones do, I think.)  Cygpath is probably always going to be more reliable than the regexes I cooked up, so we should try it first.  If we don't have it, Conda's regexes might be adequate, especially for git for windows, where we don't prefix our paths with /cygdrive/.
CC @jreback
> look for cygpath, but fall back to conda's regex path conversion

- conda_build/build.py
- conda_build/environ.py
- conda_build/windows.py
- tests/test-recipes/metadata/empty_sections/meta.yaml
The gist of this is that trying to have Python record the environment variable changes from activation was prone to all sorts of variable corruption.  Rather than deal with that, we just call the activation scripts in the build scripts (by prepending this activation bit into a copy of the build script)
Fixes #1040 #1042 
cc @havocp
> Activate in build scripts, rather than trying to have Python manage env

- .travis.yml
- appveyor.yml
- conda_build/build.py
- conda_build/main_build.py
- conda_build/metadata.py
- conda_build/render.py
- conda_build/windows.py
- tests/test-recipes/metadata/_conda-build-test-environment-vars-in-build-env/bld.bat
- tests/test-recipes/metadata/_dirty_skip_section/bld.bat
- tests/test-recipes/metadata/has_prefix_files/run_test.py
- tests/test-recipes/metadata/set_env_var_activate_build/bld.bat
This addresses several small testing tweaks, especially on Windows.  It adds better support for knowing when conda needs to install some VCS in order to build a recipe (since activation may take other VCS off PATH).
This reverts MSVC activation to running the vcvarsall.bat scripts, and incorporates @patricksnape's updates to use distutils/setuptools to locate the scripts (originally #958)
> Revert MSVC to use vcvarsall; improve detection of needed VCS install

- conda_build/build.py
- conda_build/metadata.py
- tests/test-recipes/metadata/_no_include_recipe/meta.yaml
- tests/test_build_recipes.py
Fixes #1080 
It looks like include_recipe was never actually implemented in meta.yaml.  You could use --no-include-recipes on the command line, but we do document include-recipe as a key in meta.yaml: http://conda.pydata.org/docs/building/meta-yaml.html#include-build-recipe
This adds tests for both the command line flag and the meta.yaml option.
> add missing support for include_recipe in meta.yaml

- conda_build/completers.py
NumPy 1.11 was released on the 27th of March: https://github.com/numpy/numpy/releases
> Add NumPy 1.11 to all_versions dict.

- conda_build/metadata.py
- tests/test-recipes/metadata/_git_describe_number_branch/meta.yaml
- tests/test_build_recipes.py
Fixes #1087 
Thanks @elehcim for pointing this out and helping with the test case.
> fix error where an intermediate None value was breaking jinja2 for git

- conda_build/pypi.py
Fixes #1091 #1089 #974
The version ordering is pretty fragile still - assumes that data coming back from PyPI is sorted, with newest version last.  I think this assumption is what broke things in the first place: PyPI's behavior changed.  Will fix this better later.
> take last element of pypi output; fix unicode skeleton encoding

- conda_build/utils.py
- tests/test_utils.py
> fix PEP420 namespace packages 

- conda_build/build.py
It's hard to bootstrap a package, because always_include_files expects files to already be present.  This presents a warning, for the sake of catching recipe errors, but proceeds rather than exits.
> reduce always_include_files glob fail exit to a warning

- conda_build/build.py
- tests/test-recipes/metadata/_test_early_abort/meta.yaml
- tests/test-recipes/metadata/_test_early_abort/run_test.py
- tests/test_build_recipes.py
bug observed in https://ci.appveyor.com/project/JonathanHelmus/conda-build-test-bug/build/1.0.3 - reported by @jjhelmus 
```
activate _test
```
can exit early without running tests - and probably with exit code 0, leading you to believe that tests succeeded.
This changes the call to:
```
call activate _test
```
and adds a test for the early exit behavior.
> fix lack of call in bat script exiting early

- conda_build/build.py
- conda_build/index.py
- conda_build/main_build.py
- tests/test_build_recipes.py
> allow skip-existing to examine any url in condarc

- conda_build/metadata.py
- tests/test_metadata.py
This fixes an edge case in preprocessing selectors (#629), where quoted lines contain imbalanced quotes after removing the selector part. Generated yaml files will typically enclose in single quotes all entries containing ``#`` characters, so this PR adds support for generated recipes.
> Handle quotes when matching selectors 

- conda.recipe/meta.yaml
- conda_build/windows.py
msbuild hangs around a little while after a build to reduce startup time of subsequent builds.  Unless we see problems with this, we should not be forcefully killing it.  Removing this allows us to not depend on psutil.
> remove killing msbuild at end of win build.  No psutil req anymore.

- conda_build/build.py
- conda_build/windows.py
Seems to be an issue where in some cases the bash scripts are being called in windows:
https://github.com/conda-forge/ca-certificates-feedstock/pull/4#issuecomment-231399300
This makes the file extension explicit, and should clear up confusion.
CC @jakirkham
> make activate script file extensions explicit

- conda_build/jinja_context.py
- tests/test-recipes/metadata/source_setuptools/bld.bat
- tests/test-recipes/metadata/source_setuptools/build.sh
- tests/test-recipes/metadata/source_setuptools/meta.yaml
There were a couple of strange problems happening here.  The context was not in the same directory as the work directory, so any setup.py present was the wrong one (conda-build's, in the case of running the test suite!)  Next, we were not setting sys.path, so any versioneer (or equivalent) along the path would get picked up and be very confused.
Might help with #1061 - haven't tested yet.  This certainly shouldn't hurt anything.
CC @janschulz
> fix load_setuptools in jinja2 context

- conda_build/build.py
This is a pretty terrible workaround for the fact that for post-link scripts, we may not have the actual environment being created on PATH yet.  This means things like runtime libraries may not actually be locatable yet.  This PR adds those to PATH before creation of the env, so that they are found.
> try prepending path before creating env for test

- conda_build/build.py
Same as #1115 but moves PATH manipulation so that it applies during any environment creation (build or test) in conda-build.
> move PATH manipulation for env creation up

- conda_build/main_skeleton.py
- conda_build/pypi.py
- tests/test-skeleton/test_skeleton.py
This adds a few new options to `conda skeleton pypi`:
+ `--skeleton-setup-options` to allow options to be passed to `python setup.py` when it is called to determine dependencies (motivation/use case below).
+ `--recipe-setup-options` to allow options to be added to `python setup.py install` in `build.sh` and `bld.bat` in the recipe generated by skeleton (motivation/use case below).
+ `--pin-numpy` to add the proper build/run requirements to ensure the version of numpy gets pinned when the recipe is built. Without this there is no way, currently, to use skeleton to generate a recipe that pins the numpy version without manually editing the recipe afterwards.
Use case/motivation for the first two options: I maintain builds for several astropy affiliated packages, most of which use a helpers …
> Add a few options to skeleton pypi

- conda_build/build.py
Possibly related to errors like https://github.com/conda-forge/staged-recipes/pull/1065#issuecomment-233194005 - but just a good idea in general.  We should be activating absolute paths to leave less room for confusion.
> use full path of test prefix for activation

- conda_build/metadata.py
- tests/test-recipes/metadata/_no_include_recipe/meta.yaml
Fixes https://github.com/conda/conda-build/issues/1080#issuecomment-233193327 - all meta.yaml parameters presently take underscores, not hyphens.  The newly added include-recipe option was inconsistent with that.
> make hyphenation/underscore consistent in include_recipe

- conda_build/post.py
dylibs can end up with path names such as:
'/Users/ray/qt5-x64-2.7/envs/_build/gcc/../lib/libstdc++.6.dylib'
.. and, after removing the build prefix we are left with:
'gcc/../lib/libstdc++.6.dylib'
find_lib will fail to find that in a list that contains:
'lib/libstdc++.6.dylib' because it compares strings, so we
must normalize the path first.
Rebuilding GCC 4.8.5 on OS X ran afoul of this.
> post: Use os.path.normpath() in find_lib()

- conda_build/build.py
> remove path prepending in test (use consolidated create_env instead)

- conda_build/windows.py
Per http://stevedower.id.au/blog/building-for-python-3-5-part-two/, if PY_VCRUNTIME_REDIST is not set, then things will use the static vcruntime.  This might have something to do with #1111.
Thanks @pitrou for the suggestion.
> set PY_VCRUNTIME_REDIST for VS 2015+

- conda_build/main_build.py
Reported by @fschlimb - if --source was passed, but source had already been downloaded in rendering, then the --source section would be bypassed, and the recipe would be built, rather than exiting after download.
> fix --source arg to build to only download source

- conda_build/build.py
If the source workdir was created, but was empty, the code would try to create it again, raising an exception.  This removes the check for files in the folder, and only checks for its existence.
> fix create workdir logic in build

- conda_build/post.py
Packages may include sources that are only valid and used on certain Python versions, in which case compileall will fail, but installation should still succeed.
> Don't exit on compileall failure

- conda_build/render.py
This is a quick fix to an issue where 
`conda build <recipe> --dirty`
would raise:
```
File "/conda-build/conda_build/render.py", line 113, in parse_or_try_download
return metadata, need_source_download, need_reparse_in_env
UnboundLocalError: local variable 'need_source_download' referenced before assignment
```
> ensure need_source_download exists

- tests/test-recipes/metadata/_condarc_channel/meta.yaml
- tests/test_build_recipes.py
This is an explicit test for https://github.com/conda/conda-build/issues/1120#issuecomment-234803420
All appears to be well for me, but it's good to have this test anyway.
> explicitly test that condarc channels are available in build

- conda_build/build.py
- conda_build/main_build.py
- tests/test_build_recipes.py
After creation of a root handler in conda-build 1.21.8, conda's debug log was showing up.  This silences it by default, but makes it available by passing the --debug flag to conda build.
> add debug option that shows conda log output

- conda_build/main_skeleton.py
- conda_build/render.py
Reported by @mingwandroid - if conda-build is run on a totally fresh install, the conda-bld folder may not have been created yet, and locking it will fail.  This PR ensures that the folder is created before locking.
> create croot folder if missing before locking

- conda_build/main_metapackage.py
- tests/test_build_recipes.py
This is a test that verifies functionality of conda metapackage.  It is meant as a regression test of #1158
> add test for metapackage; add token and user args

- conda_build/post.py
Otherwise files like h5copy get found and the build will fail
> Compile files ending in `.py` not those ending in `py`

- conda_build/__init__.py
- conda_build/main_build.py
- conda_build/main_convert.py
- conda_build/main_develop.py
- conda_build/main_inspect.py
- conda_build/main_pipbuild.py
- conda_build/main_render.py
- conda_build/main_sign.py
- conda_build/main_skeleton.py
The real issue was that conda installs outside of conda build were picking up conda build's root logger.  This moves the root logger to the build entry points to avoid that.
CC @kalefranz
> move logging setup to entry points

- .travis.yml
- appveyor.yml
- setup.py
Something was going wrong with the conda-based entry points in the conda-build conda-forge feedstock: https://github.com/conda-forge/pyferret-feedstock/pull/8
As near as I can tell, these entry points were manually created, and then the legacy build system did the right thing with the contents of the scripts entry.  This apparently is not working with conda-build.
This PR uses setuptools entry points instead.  It introduces the constraint that pip be used to install during the build process - otherwise, egg-based entry points are created.  With pip, we get entry points similar to the ones that were manually created.
> Use setuptools entry points

- conda_build/config.py
- conda_build/windows.py
- tests/test_build.py
We've had problems with the build prefix losing its state in different parts of the build process:
https://github.com/conda-forge/staged-recipes/pull/678#issuecomment-237053396
https://github.com/conda-forge/staged-recipes/pull/582#issuecomment-236981508
The root of this is that the builds were done with the long prefix, but later parts (post-processing, like compiling pyc) was not.  We should just use the long prefix and not worry about it.  This is how it is done in #953 (conda-build 2.0) anyway.
> always use long prefix

- conda_build/build.py
Apologies if this is me being dumb, but it looks like the logic holds up to make use of the `src_dir` variable defined above.
If this PR isn't an easy merge, please close it. No need for it to hang around 👍
> Attempt to use the src_dir, rather than the WORK_DIR, for determining directory creation.

- conda_build/build.py
Looks to me that we are only deferring the version if we need to get the source, or we need the environment created. I fully confess though - I'm on pretty shaky ground with my understanding of this bit of the code at present though.
> Corrected logic for printout of meta.dist determination.

- conda_build/config.py
- conda_build/windows.py
Seeing errors with LIB paths being set without quotes.  Not sure why this would have changed.  Try to improve variable quoting in bld.bat variable setting.
Also, Windows has a path limit of 260 characters.  To minimize trouble that users encounter, keep to a short build prefix on windows.  This should not interfere with the pip-create entry point exes in Windows (https://github.com/conda/conda/pull/3224) because they re-create the binary, rather than editing the content.
> win fixes: set LIB and INCLUDE better; use short prefix

- conda_build/main_skeleton.py
- conda_build/pypi.py
- tests/test-skeleton/sympy-0.7.5-url/meta.yaml
- tests/test-skeleton/sympy-0.7.5/meta.yaml
- tests/test-skeleton/test_skeleton.py
Closes #1179 #1177 
This is a workaround for https://github.com/pypa/warehouse/issues/1417 - pypa seems to have broken the xmlrpc search function right now.  This workaround is undesirable - it is much slower, and much more data is transferred.  I don't know what the load implications are on their side.
> revert to list all packages for pypi skeleton

- conda_build/build.py
- tests/test-recipes/metadata/_binary_has_prefix_files/run_test.py
- tests/test_build_recipes.py
I've seen prefixes that are all lowercase embedded in pip-created entry point exe's.  This PR should catch those as well as ordinary ones.
> allow case insensitive matches of prefix path in binaries

- conda_build/build.py
- conda_build/config.py
The problem with long prefixes is that they have to be rebuilt all the way back down the dependency chain.  The fundamental snag is that you can't install a package with a short prefix into a long prefix build environment.  This workaround makes it so that conda-build will not die on encountering this condition, but will fall back to building with an 80-character build prefix, after vomiting a healthy amount of text trying to explain the situation.
CC @pelson - would appreciate your feedback on this approach.
> provide fallback path for builds where dep still has 80 char prefix

- conda_build/windows.py
Prefer the 'full' VS and fallback to Python tools after. At the moment, conda-build will never seek the Python tools which is a regression in behaviour. I understand why VS9 'full' is preferred (CMake) but we should still fallback to looking for the tools if available. @msarahan
> Re-add logic for activating C++ Compiler for Python 2.7

- conda_build/build.py
Follow-up to #1183, which had issues with Python 3 and the exception message string.
CC @pelson @jakirkham
> fix python 3 exception string handling with prefix too long errors

- conda_build/windows.py
Really fix #560. 
Allow ``build_vcvarsall_vs_path(v)`` to be invoked with VS version strings in ``Major.Minor`` format. Currently this function assumes that its argument is in ``MajorMinor`` format, which is not always the case. This causes VS installation path detection to fail.
> fix: detect VS installation directory 

- CHANGELOG.txt
- conda_build/environ.py
Fixes https://github.com/conda/conda-build/issues/1117
In some situations, users find the processor information to be reported incorrectly by the infrastructure they may be running a build on. For instance, a user may be running a build on a node where the node supports more cores than the user is actually provided. As a result, the detection of the number of cores will be too high and cause issues completing the build.
Previously it was thought `MAKEFLAGS` would be an acceptable way to accomplish this. Please see PR ( https://github.com/conda/conda-build/pull/917 ). In fact, that strategy does work. Most of the cases where a parallel build is desired are using `make` and thus can easily leverage this. Though it doesn't really catch all cases and so something else still needs to be done …
> Automatically pass through `CPU_COUNT`

- README.rst
Part of breaking up #953 - this adds documentation on how to run our tests.  It also updates our appveyor badge to point at the ContinuumAnalyticsFOSS account.
> document how to run tests better in readme

- conda_build/main_inspect.py
- conda_build/tarcheck.py
With the extended length prefixes coming soon, it is helpful to know which packages in an ecosystem need to be rebuilt.  This PR introduces a function for identifying packages with short prefixes.  It can be used as a Python function (see tarcheck.py, check_prefix_lengths(folder, min_prefix_length=255)), returning a dictionary of filenames and prefix lengths, or as a command-line tool:
```
conda inspect prefix-lengths
```
This command takes one mandatory argument: the folder to inspect; and one optional argument - a prefix length threshold, by default set to the value of the default prefix length in our config.  Only packages with prefix lengths shorter than this value will be show.
This functionality is perhaps best employed on a package host, because otherwise we have to download …
> add simple function for finding packages with short binary prefixes

- conda_build/post.py
- conda_build/utils.py
- tests/test_post.py
hardlinks break installation of some packages.  This copies linked files, and should make things work. More importantly, this makes anaconda-verify happy again.
CC @mingwandroid @ilanschnell
> break hardlinks in post

- conda_build/build.py
- conda_build/conda_interface.py
- conda_build/render.py
- conda_build/utils.py
- conda_build/windows.py
Windows variables are touchy - you should never change the type of the key, or else it is no longer the same key.  This steps back a bit on #1216.  It also makes the trash function local, for wrapping permission setting (https://github.com/conda/conda/pull/3280), though in practice, I could not get permission setting to work here.
> fix breakage related to Windows env vars being strings

- conda_build/build.py
After we've discovered we need to use a smaller prefix, that variable
is re-used, but it still contains the bigger value.
> Set prefix to config.build_prefix

- conda_build/post.py
Discussed with @ilanschnell.  Should fix any issues with compilation, which was finding python files to compile, but then this removal was moving them out from under it before compilation.
CC @quasiben
> remove egg removal.  Simplifies and fixes issue with pyc compilation

- .codecov.yml
The purpose here is to turn off the commenting feature of codecov.io, but keep the status updates, for easier examination of how much a given PR changes coverage.
cc @jakirkham
> add codecov.yml to disable commenting on PRs

- conda_build/build.py
- conda_build/metadata.py
- conda_build/windows.py
- tests/test-recipes/metadata/state_variables/meta.yaml
- tests/test-recipes/test-package/setup.py
- tests/test_api_build.py
This is in response to a suggestion by @janssen: https://github.com/conda/conda-build/pull/1154#issuecomment-236718919
The idea here is that you might have scripts behave differently base on whether they are being run in rendering, building, or test phases.  Rather than define a variable per phase, this has one variable with string values for the phases.  This replaces the earlier CONDA_BUILD_RENDERING variable and breaks anyone using that code.
> define CONDA_BUILD_STATE env var during RENDER, BUILD, TEST phases

- conda_build/create_test.py
- conda_build/metadata.py
- tests/test-recipes/metadata/test_source_files/meta.yaml
A frequent source of confusion is that test files are copied from the recipe directory, and there is no clear way to copy files from the source directory into the test folder.  This PR adds a new entry to the test section of meta.yaml, ```source_files``` that copies files from the source folder into the test folder.  It should also download the source if necessary (for example, if a package is being tested separately from a build).
> add source_files test arg that copies source files into test folder

- conda.recipe/meta.yaml
- conda_build/build.py
- conda_build/cli/main_build.py
- conda_build/conda_interface.py
- tests/test_api_build.py
This fixes the error message output when a build fails because some dependency is unsatisfiable AND no recipe exists in the folder with the current recipe.
Also adds some dependency stuff in the recipe.
Thanks @mingwandroid for pointing this out.
> fix error message due to missing recipe dep being covered up

- conda_build/skeletons/pypi.py
- tests/test_api_skeleton.py
should now properly handle versions with more than one digit.
closes #1214 
cc @mingwandroid
> fix pypi skeleton version sorting

- conda_build/config.py
- tests/test_config.py
Without the underscore, conda can't be installed.  Thus, conda-build cannot build itself.  Sad day.
> prefix build and test envs with _ so conda can be installed

- conda.recipe/meta.yaml
- conda.recipe/run_test.bat
- conda.recipe/run_test.sh
Entry points are not what I thought they were.  pip install does not seem to create entry points that do not depend on pkg_resources.  This reinstates conda's entry points, which should fix the entry points' dependence on pkg_resources and pth files.
> add entry points to recipe; kill test runs at build time

- .travis.yml
4.2.4 is broken.  Fix submitted at https://github.com/conda/conda/pull/3335
Until that is released, conda-build's test suite will always fail.  Fix that here.
> comment canary build for now

- .travis.yml
- appveyor.yml
Travis is having a hard time with pytest-timeout: https://travis-ci.org/conda/conda-build/jobs/154635762#L686
Try to install from pip to see if we fare any better.
> install pytest-timeouts from pip instead of defaults

- conda_build/config.py
- conda_build/source.py
fixes #1249 
This is easier than the equivalent fix on the conda side.
CC @ericdill
> export default config locations for conda clean

- conda_build/build.py
- conda_build/utils.py
- conda_build/windows.py
Virtualenv's activate scripts sometimes get found instead of conda's.  Whoops.  This makes sure to find conda's, unless someone clobbers those with virtualenv's in the root environment.
https://github.com/Anaconda-Platform/anaconda-server/pull/2782
CC @dsludwig
> specify full path to activate scripts

- conda_build/cli/main_build.py
This catch-all to direct people to the issues page is nice, but it frustratingly hides exceptions and makes debugging much harder.  Developers using conda-build will almost certainly know how to find the issue tracker.
> remove catch-all in main_build.  Showing tracebacks is more helpful

- conda_build/post.py
This mostly breaks repackaging scripts.  Example: https://github.com/conda-forge/inkscape-feedstock/issues/4
> only compile pyc files if python is in the build prefix

- conda_build/build.py
- conda_build/create_test.py
- conda_build/post.py
- conda_build/source.py
- conda_build/utils.py
- tests/test_api_build.py
- tests/test_post.py
- tests/test_utils.py
Bumped into errors with Docker image, where exception was about an invalid link operation across file systems.  Copying files helps here.
Fixes #1275
> copy files when breaking hardlinks, not rename

- conda_build/create_test.py
- conda_build/utils.py
Encountered this while testing conda-build: https://ci.appveyor.com/project/ContinuumAnalyticsFOSS/conda-build/build/1.0.485/job/1fkl51cd969173yg#L1594
> remove pyc files from test directory to avoid __file__ errors

- conda_build/environ.py
tiny fix for #1269 - more of a band-aid.  The correct fix will be to make user settings override hard-coded defaults like this.
Long-term, this default should not exist in conda-build, but should be defined on a build system basis.  Target for that is the next major release of conda-build.
> update MACOSX_DEPLOYMENT_TARGET to 10.7 for more modern compat

- bdist_conda.py
- conda_build/api.py
- conda_build/build.py
- conda_build/index.py
- conda_build/jinja_context.py
- conda_build/metadata.py
- tests/test_api_build.py
This is convenient for testing, to be able to write metadata without some separate file.  It is also used by conda-build-all, and this PR helps with compatibility there.
> allow MetaData objects passed to build and get_output_path

- conda_build/environ.py
> Prevent GIT_* env. vars containing newlines

- conda_build/metadata.py
- conda_build/render.py
- tests/test_api_build.py
This is needed for many nodejs projects that generate OS independent
.js and .css files.
> Add `build/noarch` to recipe metadata.

- conda_build/skeletons/pypi.py
This is being done for the 'javabridge' package, but I imagine it will be useful elsewhere, too.
> add numpy to pypi env creation if it is imported in setup.py

- conda_build/windows.py
In playing with Vagrant, I've discovered a flaw with our handling of VC9: it only works if setuptools is imported before distutils, because setuptools monkeypatches distutils.  See https://bugs.python.org/issue23246
CC @patricksnape
> add setuptools import to monkeypatch distutils

- bdist_conda.py
Fixes https://github.com/conda/conda-build/issues/1305
This seems to work locally for me based on testing with a simple package using `bdist_conda`.
However, it does raise some questions as this appears to be partially reverting PR ( https://github.com/conda/conda-build/pull/1281 ). Maybe I'm missing something. 😕
> Fix metadata retrieval in bdist_conda

- conda_build/build.py
- conda_build/conda_interface.py
Employ's conda's VersionOrder, and also filters out conda-build packages that have text join with their bugfix release number.
Fixes #1291
> fix warn_on_old_conda_build to ignore testing versions

- conda_build/build.py
- conda_build/environ.py
- conda_build/metadata.py
- conda_build/utils.py
- tests/test_build.py
Fixes #1306 
by recognizing the output of OpenSSL's custom prefix replacement program.
> catch prefix length errors with openssl's custom replacement

- conda_build/create_test.py
- conda_build/noarch_python.py
- conda_build/post.py
Seems they are considered harmful:
https://www.python.org/dev/peps/pep-0488/
(anaconda-verify complains about them too)
> Delete .pyo files before compiling .pyc files

- conda_build/metadata.py
Closes https://github.com/conda/conda-build/issues/1300
As stated, adds `GPL` as a license family. This seems more appropriate as the `license` itself should have license version; whereas the license family should merely note the style of license. It is also more consistent as no other license family listed requires version in this way.
Note: Would like to drop `GPL2` and `GPL3` from the list, but have kept them as that feels like a breaking change.
> Add `GPL` as a license family

- conda_build/convert.py
This fix tries to avoid catching packages with a name that starts with `python` as if they represent additional python dependencies, which leads to a "Found more than one Python dependency in package" runtime error.
See also: https://github.com/conda/conda-build/pull/481#issuecomment-246673428
> Fix pyver_re to avoid catching python-* packages

- conda_build/post.py
There are some programs (gcc, bazel) that contain prefixes, but which break when we change these prefixes.  These programs are written somehow to adjust the prefix themselves, and we break them when we put in our rpath stuff.  This provides a way to tell conda-build to leave them alone.
> skip fixing rpath for files specified in ignore_prefix_files

- conda_build/convert.py
- tests/test-recipes/metadata/noarch/meta.yaml
- tests/test_api_convert.py
The problem logic here was in convert.py.  The file_map was being updated on the first non-matching pattern, so later patterns were not being evaluated.  The unix script to win pattern was the last of 3, so its files were missing.
fixes #1346
> fix convert unix->win not creating entry point py scripts

- .travis.yml
- appveyor.yml
- conda.recipe/meta.yaml
- tests/test_build.py
We have periodic errors that look like 
```
INTERNALERROR>   File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/main.py", line 94, in wrap_session
INTERNALERROR>     session.exitstatus = doit(config, session) or 0
INTERNALERROR>   File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/main.py", line 125, in _main
INTERNALERROR>     config.hook.pytest_runtestloop(session=session)
INTERNALERROR>   File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 724, in __call__
INTERNALERROR>     return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
INTERNALERROR>   File "/home/travis/miniconda/lib/python2.7/site-packages/_pytest/vendored_packages/pluggy.py", line 338, in _hookexec
INTERNALERROR>     return …
```
> remove pytest timeout.  It is incompatible with xdist.

- conda_build/conda_interface.py
- conda_build/utils.py
This was breaking bokeh's build with conda 4.2.6 somehow.  Conda now calls the windows move to trash stuff in its rm_rf function.  There is no need to duplicate that here.
CC @brittainhard
> use conda's rm_rf, rather than move_to_trash

- .travis.yml
- appveyor.yml
- conda.recipe/meta.yaml
- conda_build/build.py
- conda_build/config.py
- conda_build/metadata.py
- conda_build/post.py
- conda_build/skeletons/pypi.py
- conda_build/utils.py
- tests/test_api_build.py
- tests/test_api_convert.py
- tests/test_cli.py
- tests/utils.py
fixes #1352 
Some packages do not contain the pkginfo.yaml file.  Instead, they only have PKG-INFO.  That is an incomplete collection of information - it is potentially missing multiple fields.  If it's all we have, then we go with it, and provide empty values where appropriate.
> fallback path for PKG-INFO for pkgs without pkginfo.yaml

- conda_build/build.py
Cause: intendation of return false is wrong
> Problem: When using conda-build --skip-existing, packages won't get built if they are not available

- conda_build/build.py
- setup.py
This PR fixes a bug when using the --skip-existing flag: any package, regardless of whether it exists or not, was not being built, because the `return False` appeared at the wrong indentation level.
Further, this adds a dependency to requests, which was previously used but not mentioned in the setup.py.
> Fix building when --skip-existing flag is set

- conda_build/build.py
Fixes #1339 
(maybe)
It seems like indexing the pkgs folder when it has never been indexed before takes quite a long time.  Since this was not done before, and because the index creation is not incremental - this can simply fail all builds because it never succeeds a first time (after which it would be fast).
CC @patricksnape
> don't index pkgs folder

- conda_build/api.py
Passing recipe folder as ./ or similar would end up with build_id being ._(timestamp) - this fixes it so that it is the folder name.
> fix build id when simple relative paths passed (./)

- .travis.yml
Conda-forge channel was overriding defaults in the perl install, causing our local conda to always be conda-forge's.
> use conda from defaults, not conda-forge

- conda_build/environ.py
#1378 boils down to `environ.meta_vars` calling `MetaData.name` which `sys.exit`s because the package's name is not set during rendering. `MetaData.name` gets called due to the following call stack:
```python
render.parse_or_try_download
metadata.MetaData.parse_again
metadata.MetaData._get_contents
jinja_context.context_processor
environ.get_dict
environ.meta_vars
metadata.MetaData.name
```
I did **not** check the implications of replacing `meta.name()` by `meta.get_value('package/name')` for other code paths. If the patch is thus not applicable, other potential solutions are:
- either guard the `meta.name()` call inside `meta_vars` by some optional Boolean argument which has to be handed down all the way from `parse_again` down to `meta_vars`,
- or simply artificially fulfil …
> Fix #1378 and #1379

- conda_build/api.py
- conda_build/cli/main_skeleton.py
- conda_build/skeletons/cpan.py
- tests/test_api_consistency.py
- tests/test_api_skeleton.py
Currently invoking conda skeleton with:
```bash
conda skeleton pypi --version 2.9.2 pytest
```
ignores the version flag due to the way skeletonize is called by main_skeleton.py. main_skeleton.py rolls all command line arguments into the config object which is passed into skeletonize. This caused version, recursive and output_dir to take on the default values in skeletonize (None, False, and ".", respectively).
This PR fixes that bug.
> [Bug-fix] Patch skeletonize to not ignore flags

- conda_build/skeletons/pypi.py
- tests/test_cli.py
This will close #1382. The first commit simply adds a test for the missing options. 
Assuming those test fail, as expected, I will push the fix.
> Add missing command line options and tests for them

- conda_build/api.py
- tests/test_cli.py
@mwcraig @sooneecheah between your two PRs, things were working fine, aside from one glitch already fixed with photutils and py3.  I added a comment explaining how the translation to/from function arguments works.  It's a little bit tricky to understand just by looking at it, but simple enough once you know what you're looking at.
> Fix pypi skeleton args

- conda_build/build.py
There was an issue with timeouts with locks on windows only.  This acquires the lock in a different order, because these things are apparently not reentrant.
> move lock acquisition after index creation for win issues

- conda_build/utils.py
Fixes py3.5 corresponding tests on appveyor
> normalize slashes to forward slashes for path checks in tarfiles

- conda_build/api.py
- conda_build/cli/main_skeleton.py
- tests/test_api_consistency.py
- tests/test_api_skeleton.py
This partially reverts #1384 to keep the skeletonize api consistent, and fixes passing of arguments through the CLI accordingly.
CC @mwcraig @sooneecheah
> Rework skeletonize api to be consistent

- conda_build/source.py
- conda_build/utils.py
fixes #1412 
confirmed by building freexl for py27 and py35 on win.
> convert popen args to bytestrings if unicode

- conda_build/skeletons/cpan.py
Fixes errors as shown in https://ci.appveyor.com/project/ContinuumAnalyticsFOSS/conda-build/build/1.0.783/job/pcj1jjhfkqce8xxl#L996 : 
```
_______________________ test_repo[perl-cpan-Shell-Cmd-] _______________________
[gw0] win32 -- Python 3.5.2 C:\Miniconda35-x64\python.exe
File "C:\projects\conda-build\tests\test_api_skeleton.py", line 21, in test_repo
api.skeletonize(package, repo, version=version, output_dir=testing_workdir, config=test_config)
File "C:\projects\conda-build\conda_build\api.py", line 192, in skeletonize
recursive=recursive, config=config, **kwargs)
File "C:\projects\conda-build\conda_build\skeletons\cpan.py", line 215, in skeletonize
package = dist_for_module(meta_cpan_url, package, perl_version, config=config)
File …
```
> fix perl file access error on win skeleton cpan

- conda_build/build.py
- conda_build/metadata.py
- conda_build/post.py
- tests/test-recipes/metadata/skip_compile_pyc/README
- tests/test-recipes/metadata/skip_compile_pyc/compile_pyc.py
- tests/test-recipes/metadata/skip_compile_pyc/meta.yaml
- tests/test-recipes/metadata/skip_compile_pyc/skip_compile_pyc.py
- tests/test-recipes/metadata/skip_compile_pyc/sub/compile_pyc.py
- tests/test-recipes/metadata/skip_compile_pyc/sub/skip_compile_pyc.py
- tests/test_api_build.py
@msarahan: It's strangely coincedental that I'm making changes in the same area of compiling `.pyc` files two days in a row, as other than the location, this is not related to yesterday's fix.
Some packages ship .py files that should not be compiled because either they
cannot be compiled (for example they contain templates) or should not be
compiled yet because the Python interpreter that will be used cannot be known
at build-time.
An example of such a package is `qtcreator` which uses GDB's embedded Python
interpreter to give a richer debugging experience. This package falls foul of
both scenarios given above.
Closes #686
> Add build/skip_compile_pyc option

- conda_build/_link.py
- conda_build/build.py
- conda_build/post.py
- conda_build/utils.py
- tests/test-recipes/metadata/fix_permissions/README
- tests/test-recipes/metadata/fix_permissions/meta.yaml
- tests/test-recipes/metadata/fix_permissions/sub/lacks_grp_other_read_perms
- tests/test_api_build.py
We had a bug report https://github.com/ContinuumIO/anaconda-recipes/issues/52
where for some unknown reason qt.conf has no read permissions for
other, and our testing procedure did not spot this.
Our fix_permissions() function wasn't forcing read access. I took
the opportunity to change it in other ways too. Now, in total, it:
1. Directories are all set to 0o755.
2. Ensures the user can write to files.
3. Broadcasts user execute to group and other for files.
4. Ensures that user, group and other can read files.
> post: Fixes and a test for fix_permissions

- conda_build/develop.py
- conda_build/environ.py
- conda_build/post.py
- conda_build/utils.py
- tests/test_develop.py
- tests/test_utils.py
This should address https://github.com/conda/conda-build/issues/1055#issuecomment-250961576 in which the site-packages folder being computed didn't actually match the site-packages folder in a given environment.  That was caused by the root environment determining the python version, which was incorrect for develop installations into non-root prefixes.
cc @jorisvandenbossche
> consolidate get_site_packages defines throughout

- README.rst
- conda_build/jinja_context.py
- conda_build/metadata.py
- conda_build/render.py
- tests/test-recipes/metadata/source_regex/bld.bat
- tests/test-recipes/metadata/source_regex/build.sh
- tests/test-recipes/metadata/source_regex/meta.yaml
- tests/test-recipes/metadata/source_regex_from_recipe_dir/bld.bat
- tests/test-recipes/metadata/source_regex_from_recipe_dir/build.sh
- tests/test-recipes/metadata/source_regex_from_recipe_dir/meta.yaml
This PR adds a preprocessor function in the same vein as `load_setup_py_data` for the meta.yaml file. It takes a file and regex string as arguments, and returns the `match` object from a `search` of the given file. This is related to #1316 
The use case for this is to grab version and other information that is specified in files other than `setup.py`. This may be common, for instance, for packages that have multiple language interfaces and want to specify the version number in a Makefile or its equivalent so that the same version is used for all the interfaces during a build.
The only issue that I had in implementing this was that Jinja2 doesn't like Python raw strings, so the backslashes in the regex string have to be escaped by doubling where they're specified in the meta.yaml file. The …
> Add regex Jinja preprocessor

- tests/test_cli.py
Should fix sporadic failures we're seeing on Travis.
> change metadata test output filenames to avoid race conditions

- conda_build/build.py
- conda_build/render.py
This fixes an issue where if one has a config object passed in, like so:
api.build('some_recipe_path', config=config)
then the noarch value in meta.yaml does not affect the config.noarch value, leading to inaccurate output folders.
> fix noarch value propagation from meta.yaml to config

- conda_build/windows.py
- tests/test-recipes/metadata/_script_win_creates_exe/meta.yaml
- tests/test-recipes/metadata/_script_win_creates_exe/setup.py
- tests/test-recipes/metadata/_script_win_creates_exe/test-script
- tests/test_api_build.py
This was removed sometime in the 2.0 transition.  There's no reason for that - it is helpful.  Restore it and test it.
Fixes #1468
> restore script exe creation on windows

- conda_build/environ.py
Often seen in feedstocks as DYN_EXT, SO_EXT, DYNAMIC_EXT, EXT, SONAME, LIBEXT, etc
> Add SHLIB_EXT environment variable to the build

- conda_build/os_utils/macho.py
otool -h output starts with "Mach header" not the file path
Xcode 8, macOS 10.12
Also expanded the error message to show the output that didn't match, rather than just the path that it didn't match.
> otool -h header changed

- .travis.yml
- appveyor.yml
- conda.recipe/meta.yaml
- conda_build/build.py
- conda_build/index.py
- conda_build/render.py
- conda_build/utils.py
- tests/test-recipes/fail/source_git_jinja2_oops/meta.yaml
- tests/test_api_build.py
This is meant to address #1494.  The idea is that lockfile only keeps track of one SoftFileLock instance, but is reentrant for that instance.  However, we had cases where more than one instance for a single file in a single process could be created.  This implements a central collection of SoftFileLock instances within each process, keyed on file location.  Any re-use of a location should get the in-process instance, and be reentrant.  This also uses context managers because the reentrancy should make file removal more robust.
> centralize locks for sharing within a process

- conda_build/post.py
This is meant to address #1463 
I don't consider this a proper fix, but it is the best I can do right now.  Conda-build really should not be left to decide which is the correct file to overwrite - this must be a user choice.  The best we can do is try to be clear about what is happening, and how to work around it.
CC @janssen @jreback
> clarify error message when extracting egg fails due to existing files

- conda_build/utils.py
Resolves #1510 .
If `copy_into` is now used and you want to copy a file in a (nested) folder the intermediate folders for the destination are created. In case you were copying folders this was already the default. This enables the same for single file copies.
> Add creation of intermediate folders for `utils.copy_into`

- conda_build/api.py
fix for test_cli.py::test_skeleton_pypi_arguments_work test failure
> Use version info from config if exists

- conda_build/post.py
@mingwandroid is this a reasonable approach to https://github.com/conda/conda/issues/3308 ?
I'm not sure that this will work as-is - if we copy the binary around, then the RPATH stuff will be wrong, correct?  Can we just shuffle this function to be called earlier and use the RPATH replacement stuff without modification?
> break symlink and copy file if symlink points to executable

- conda.recipe/meta.yaml
- conda_build/build.py
- tests/test_api_build.py
- tests/test_build.py
- tests/utils.py
ref: https://github.com/conda/conda-build/issues/1486
> Files json

- conda_build/metadata.py
It is used to represent 'epoch'.
> Allow `!` in package version

- .travis.yml
- appveyor.yml
- conda_build/api.py
- conda_build/build.py
- conda_build/cli/main_build.py
- conda_build/cli/main_render.py
- conda_build/config.py
- conda_build/environ.py
- conda_build/render.py
- conda_build/utils.py
- tests/test_api_build.py
This fixes ```conda build --test``` so that the actual package provided is the one that gets installed for the test.  It no longer tries to go download it from somewhere, based on metadata provided by rendering the recipe in the package.
This hard-codes important information in the rendered meta.yaml file:
* exact pins for build dependencies (even those not explicitly listed - it is whatever is present in the build env)
* absolute path substituted for relative source/path or source/git_url entries (necessary for testing)
* the build string, so that no further rendering is necessary to come up with a similar package spec.
Finally, this adds one option to conda build, ```--output-folder```, which dumps the output package to some folder.  This is useful for CI (particularly concourse CI), …
> fix directly testing packages; freeze more meta.yaml data

- conda_build/conda_interface.py
fixes #1507, but only with conda 4.2.  I couldn't figure out how to monkeypatch conda 4.1 properly. =(
> disallow softlinks for conda in conda-build

- conda_build/metadata.py
- tests/test_metadata.py
> support globs in prefix file functions

- conda_build/metadata.py
- conda_build/post.py
also makes binary_relocation accept list of files/globs to improve granularity
> decouple ignore_prefix_files from binary_relocation

- conda_build/environ.py
Closes https://github.com/conda/conda-build/issues/1269 (though I suppose PR https://github.com/conda/conda-build/pull/1278 should have already)
As promised, whitelist the environment variable `MACOSX_DEPLOYMENT_TARGET` so that people can override it with an external environment variable easily.
cc @msarahan
> Whitelist MACOSX_DEPLOYMENT_TARGET

- conda_build/build.py
- conda_build/conda_interface.py
Hi @msarahan, this needs to be copied over to ensure that PATH is manipulated correctly (i.e. that the root env gets removed from it). Conda 4.3 will necessitate changing this again.
> Copy CONDA_PATH_BACKUP into build/test env.

- conda_build/metadata.py
Without this, when that environment variable is missing, recipes using nomkl feature will fail to render.
> define nomkl selector when FEATURE_NOMKL env var not set

- conda_build/api.py
There's a problem with tests if they are run by passing a package file.  The extracted recipe folder is deleted after creating metadata from it.  If the test needs files from that recipe, then they're gone.  This moves the cleanup of the extracted recipe, so that they should still be there.
> move test removal of recipe until after test completes

- conda.recipe/meta.yaml
- conda_build/api.py
- conda_build/cli/main_build.py
For example, if you have a local folder ``packages`` that has the standard directory structure:
```
packages
osx-64
noarch
```
This PR will allow you to pass ```-c packages``` to conda build, and it will flesh out the full absolute path on whatever machine you're on.
This PR is critical for operation of the Concourse CI system.
> allow relative local channels

- .travis.yml
- conda_build/build.py
- conda_build/conda_interface.py
- tests/test_api_build.py
- tests/test_build.py
- tests/test_misc.py
Creating a new pr to address the code review from https://github.com/conda/conda-build/pull/1501#pullrequestreview-8498841
~~This is dependent on https://github.com/conda/conda/pull/3887 being merged~~
> finalizing paths.json spec

- conda_build/post.py
Because otherwise conda fails to install and gives up the ghost:
```
conda.exceptions.CondaOSError: OS error:
failed to link (src='.../Tcl_FSGetCwd.3.gz', dst='.../Tcl_FSGetCwd.3.gz', type=1, error=CondaOSError:
OS error: win32 hard link failed
```
> Call make_hardlink_copy() on Windows too

- conda_build/build.py
- tests/test-recipes/work-deleted/bld.bat
- tests/test-recipes/work-deleted/build.py
- tests/test-recipes/work-deleted/build.sh
- tests/test-recipes/work-deleted/meta.yaml
- tests/test-recipes/work-deleted/test.py
Fixes #1580.
Let me know if you want me to add some kind of test.
> Delete the work directory before running the tests

- conda_build/build.py
- conda_build/cli/main_build.py
- conda_build/config.py
- tests/test_build.py
With Conda currently silencing conda-build's logger output, the warnings about prefix length fallback have been hidden, leading to some packages being built unintentionally with short prefixes.  This adds a flag to disable that fallback behavior.  This also adds the longstanding community request that prefix length be settable, but with the warning that they should really prefer to set croot to non-encrypted locations instead.
CC @mingwandroid @ilanschnell
> add prefix length arg.  Allow disabling of prefix length fallback

- conda_build/completers.py
- conda_build/metadata.py
Currently conda-build does not understand recipes with
```yaml
build:
skip: true  # [py36]
```
This patch should add the missing variable for the upcoming Python version.
> Support for python 3.6

- conda_build/post.py
> don't compile missing pyc when no python exists in build prefix

- conda_build/build.py
- conda_build/create_test.py
Fixes a couple of minor issues with split packages:
1. remove files in build prefix prior to next script, so that each script starts "fresh" and duplicates in packages are OK (though discouraged).
2. only make a metapackage if an output with the same name is not explicitly listed in the outputs
3. add cmd.exe execution flags
> remove packaged files from build prefix, to give next script fresh start

- appveyor.yml
- conda.recipe/meta.yaml
- conda_build/__init__.py
- conda_build/build.py
- conda_build/cli/main_build.py
- conda_build/cli/main_render.py
- conda_build/conda_interface.py
- conda_build/config.py
- conda_build/create_test.py
- conda_build/index.py
- conda_build/license_family.py
- conda_build/metadata.py
- conda_build/noarch_python.py
- conda_build/post.py
- conda_build/source.py
- conda_build/utils.py
- tests/test_api_build.py
- tests/test_cli.py
- tests/utils.py
There's a potential race condition when working with multiple locks, as we do with locking multiple folders at once.  If one set of locks is partially done, and another set is acquired, we can deadlock.
This PR implements a scheme where we try to acquire locks one-by-one, and if any fail (quickly), let go of all currently held locks in that group.  The overall timeout still applies, but it applies to the whole group, not each individual lock.
Derived from http://stackoverflow.com/questions/9814008/multiple-mutex-locking-strategies-and-why-libraries-dont-use-address-comparison
This also refactors build.py to use the utils module, rather than its small pieces.
> lock rework: try to acquire, let go if any locks fail; retry

- conda_build/build.py
- tests/test-recipes/metadata/no_link/meta.yaml
- tests/test-recipes/metadata/no_link/run_test.py
> fix no_link variable clobber.  Add test.

- conda_build/convert.py
- tests/test-recipes/metadata/entry_points/meta.yaml
- tests/test_api_convert.py
- tests/utils.py
This is really a bugfix for issue #712. 
The actual fix is in commit 
https://github.com/gomyhr/conda-build/commit/23230c65c0bfad50f4bca755603514ed56bfbe51. It is a bit more elaborate than the simplest solution in the issue, in that info/files is read as a list instead of a string straight away. This should tie better in with the change when info/paths.json will be used instead of info/files later.
The first two commits (
https://github.com/gomyhr/conda-build/commit/8f5b3d19e2e6a168baf060e08b7af9a5deb8f393 and 
https://github.com/gomyhr/conda-build/commit/eb459b13243714e66caf5178fe14f598e0e84c02) add a package consistency check to the convert test with entry points.  I wasn't quite sure tests/utils.py was the right place to add a function for checking package consistency, but I could not …
> Package consistency

- conda_build/build.py
There was an inconsistency between where the conda versions came from for the about_json test.  This makes them both come from ```conda.__version__```
> fix about.json test with conda/conda_build dev versions

- conda_build/metadata.py
closes #1634
In feature validation, if features was None, the code barfed.  This ensures that None gets translated into a list - the value should always be a list.
CC @jakirham
> fix features being None -> list

- conda_build/metadata.py
- tests/test-recipes/metadata/_git_describe_number_branch/meta.yaml
- tests/test_api_build.py
fixes #1640 - the exception should only be there if the recipe is fully rendered and yet still has periods at the start of version
> fix not-yet-rendered version raising validation error

- conda_build/build.py
- conda_build/develop.py
- conda_build/skeletons/cpan.py
- conda_build/skeletons/pypi.py
- conda_build/utils.py
- conda_build/windows.py
- tests/test_api_build.py
- tests/test_api_convert.py
- tests/test_cli.py
- tests/test_published_examples.py
- tests/utils.py
This was some crufty code duplication, anyway.
Also, Python 2.7 using check_output has a trailing newline that python 3.x does not have.  This was causing an invalid rendered recipe to be written to packages.  This newline is rstripped by this commit.
Fixes #1642 
Fixes #1618
> use only check_call_env.  Fix coercion of args to string therein

- .travis.yml
- appveyor.yml
- conda.recipe/meta.yaml
- conda_build/windows.py
fixes #1632 
Chardet enhances bs4.  It is not directly imported.
Not sure if there's anywhere else that also needs this encoding guessing.  @jakirkham if you are aware of other recipes that are broken with encoding errors, please let me know.
@tarcisiofischer this works, sort of.  I can build the package, but the tests fail with some weird characters:
```(C:\MC2x64\conda-bld\recipe_1484008724922\_t_env) C:\MC2x64\conda-bld\recipe_1484008724922\test_tmp>waf --help
[91mError: run waf-light from a folder containing waflib[0m
```
Not sure if that's related, or just an artifact.  Sometimes that stuff shows up with bash involved.
> utilize chardet and bs4 to guess file encoding

- .travis.yml
- appveyor.yml
Conda 4.3 is currently about 3x slower than conda 4.2.  Now that conda 4.3 is the default conda, our tests got slower.  This makes conda 4.2.x the used version instead.
> force conda 4.2.x for 2.7 and 3.5 builds (for speed)

- conda_build/build.py
The tar ended up with info files with full-paths because the replace did not happen
due to using the wrong slash.
I have no time to write a test for this. It seems like something that should fail an existing one though?
> build: Fix info file prefix replacement on Windows

- conda_build/conda_interface.py
- conda_build/source.py
@msarahan, @kalefranz, please review. I'm not sure I need the old:
```
except RuntimeError as e:
print("Error: %s" % str(e).strip(), file=sys.stderr)
```
.. still, but I kept it anyway.
This is needed for R packages where each meta.yaml lists two URLs:
```
url:
- http://cran.r-project.org/src/contrib/backports_1.0.4.tar.gz
- http://cran.r-project.org/src/contrib/Archive/backports/backports_1.0.4.tar.gz
```
> source: Catch CondaHTTPError so mutliple urls get checked

- conda_build/build.py
- conda_build/metadata.py
- conda_build/post.py
- tests/test-recipes/metadata/_nexpy/bld.bat
- tests/test-recipes/metadata/_nexpy/build.sh
- tests/test-recipes/metadata/_nexpy/meta.yaml
- tests/test_api_build.py
fixes #7 
fixes #1664
Would be nice to replace the _nexpy recipe with a simpler recipe that just has a known GUI entry point.  As it is, this test wastes some time downloading scipy.
> add pythonw on osx for tests when osx_is_app is defined

- conda_build/windows.py
The previous method of setting the `%MSYS2_ARG_CONV_EXCL%` environment variable tried to preserve any preexisting value of the variable. Not only does this make the build process depend on the initial environment more, it generally leads to a trailing semicolon in the variable value. This seems to cause MSYS2 to parse the variable as having an empty value that prevents *all* argument conversions, as investigated in the conda-forge `cairo` package: [see here](https://github.com/conda-forge/cairo-feedstock/pull/18).
I do not know what fallout this change will have for existing build scripts, but the current behavior cannot be what was intended.
> conda_build/windows.py: avoid trailing semicolon in %MSYS2_ARG_CONV_EXCL%

- .travis.yml
- appveyor.yml
- setup.cfg
- tests/test_api_build.py
- tests/test_build.py
I noticed that the current pytest configuration is emitting some warnings which are easily fixable:
```
WC1 None [pytest] section in setup.cfg files is deprecated, use [tool:pytest] instead.
WI1 /home/travis/miniconda/lib/python3.5/site-packages/pytest_capturelog.py:171 'pytest_runtest_makereport' hook uses deprecated __multicall__ argument
WC1 None pytest_funcarg__caplog: declaring fixtures using "pytest_funcarg__" prefix is deprecated and scheduled to be removed in pytest 4.0.  Please remove the prefix and use the @pytest.fixture decorator instead.
WC1 None pytest_funcarg__capturelog: declaring fixtures using "pytest_funcarg__" prefix is deprecated and scheduled to be removed in pytest 4.0.  Please remove the prefix and use the @pytest.fixture decorator instead.
```
* `[pytest]` should …
> Fix some small issues with pytest configuration

- tests/test_api_build.py
- tests/test_patch.py
- tests/utils.py
The [monkeypatch](http://doc.pytest.org/en/latest/monkeypatch.html) fixture automatically reverts environment variables and cwd to their previous values.
I did not run the tests locally and the changes should be harmless, but if something fails I will take a look later. 😁
> Use monkeypatch fixture in a few places of the test suite

- conda_build/windows.py
- tests/test-recipes/metadata/_script_win_creates_exe_garbled/meta.yaml
- tests/test-recipes/metadata/_script_win_creates_exe_garbled/setup.py
- tests/test-recipes/metadata/_script_win_creates_exe_garbled/test-script
- tests/test_api_build.py
As [commented](https://github.com/conda/conda-build/issues/1632#issuecomment-273949364) in #1632, the `waf` build still fails in the latest version.
I tried the PR locally on my machine and I can confirm that the recipe for `waf` now builds correctly.
For the record, here's a snipped of the bottom of the `waf-script.py` file which causes the problem:
```
wafdir = find_lib()
sys.path.insert(0, wafdir)
if __name__ == '__main__':
from waflib import Scripting
Scripting.waf_entry_point(cwd, VERSION, wafdir)
#==>
#BZh91AY&SYî?llvþÿ°#.Óÿÿÿÿÿÿÿÿÿÿÿ??Y@Â?%H4à?b<g^è?#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.#.ù??d\?mÏ??[*DUï?]??Ü2\??uöº??#1µ?vÝå?{µuÛí??R{?#/?ìb?ïG??íÕ??9M=p?#.4ò{?ÐkAìôz?m?nwzmïzô?µÓ]mô{Á??]îìç?ÝÛÞìåºÜzë?4?ûîç{yöàú#.?<mî?îí;Ý??{íßo?wÝ7=Û?µï?#.#.Ð?qtÐÁÈû?#.FT??À{çË? …
```
> Fix encoding error while creating executables on Windows

- conda_build/api.py
- tests/test-recipes/split-packages/_rm_rf_stays_within_prefix/bin/lsfm
- tests/test-recipes/split-packages/_rm_rf_stays_within_prefix/conda/meta.yaml
- tests/test-recipes/split-packages/_rm_rf_stays_within_prefix/conda/run_test.py
- tests/test-recipes/split-packages/_rm_rf_stays_within_prefix/setup.py
- tests/test_subpackages.py
closes #1661 
@patricksnape this test is meant to diagnose your reported rm_rf issue.  I did duplicate the behavior once, but in the process of shooting myself in the foot with wrong config arguments (config not passed as a keyword, which is why I added https://github.com/conda/conda-build/compare/master...msarahan:test_rm_rf?expand=1#diff-e2183a8fc8686417bd5c8f72d886e4ffR65), I can no longer repeat the behavior.  Would you please look over this test and ensure that it is repeating enough of the lsfm behavior to be an adequate test?
> add test for rm_rf invasively removing relative paths

- tests/test_api_build.py
The test depends on being in the toplevel folder when the build occurs.  The monkeypatch was resetting the folder before that happened, and thus the source download failed.
> fix git_relative_url test

- conda_build/source.py
- unzip wheel to enable including files in the wheel, such as `about.license_file`
- copy untouched wheel to allow `pip install --no-deps {{ fn }}` as install command
> allow wheels as source format

- conda_build/metadata.py
I ran into this because there was no svn available to build svn with.
If we ever were to fetch svn from svn this would break, but it gets
us out of one hole at least.
Also, it is really hard to write a test for this, sorry.
> metadata: Add a package/name = vcs exclusion to uses_vcs_in_{meta,build}

- conda_build/api.py
- conda_build/cli/main_skeleton.py
- conda_build/conda_interface.py
- conda_build/skeletons/cpan.py
@msarahan, here is my PR for https://github.com/conda/conda-build/issues/1675.
Mostly, the metacpan api url needed to be updated, but there were a few other fixes.
> adding some fixes to cpan skeleton

- conda_build/convert.py
- tests/test_api_convert.py
This file is now used in Conda 4.3 to identify files to be hardlinked.
Fixes #1678
> Conda Convert - Update the info/paths.json file

- conda_build/build.py
> fix #1708 attribute error

- conda_build/build.py
- tests/test_subpackages.py
Do not delete project files - which was possible if file paths were relative
paths.  Whoops.
Closes #1661 #1693 
CC @hainm @patricksnape @jabooth
> ensure bundle_conda cleanup is acting on absolute paths

- conda_build/build.py
- tests/test_api_build.py
Pretty simple change in response to https://github.com/conda/conda/issues/4481.  The associated https://github.com/conda/conda/pull/4482 is already in conda 4.3.9.
> rename package_metadata.json to link.json

- conda_build/build.py
- tests/test_api_build.py
fixes #1742 
On Windows, test script execution paths were not correctly quoted to allow spaces.
On linux and mac, spaces in paths still don't work, but it's because conda and openssl's custom prefix replacement don't work.
> fix quoting for test paths.  test croot with spaces.

- conda_build/metadata.py
- tests/test-recipes/metadata/unknown_selector/meta.yaml
- tests/test_api_build.py
Solution: evaluate them to false...
this is related to #1723 
It allows code like this, even if `linux-aarch64` is not known at the time of writing
```
build:
skip: True #[linux-aarch64]
```
> Problem: Unknown selectors crash conda-build

- conda.recipe/meta.yaml
- conda_build/build.py
- conda_build/cli/main_build.py
- conda_build/config.py
- conda_build/metadata.py
also, Allow default conda package by making name match pkg_name (uses default packaging logic, but allows both conda package output and wheel output without specifying files or script for main output).
> set default repo for twine to pypitest.  

- conda_build/license_family.py
The `ensure_valid_license_family` function in `license_family.py` calls `normalize()` before comparing to the list of `allowed_license_families`, which converts the license family to all-caps before comparing to the list. However, `allowed_license_families` contains some elements that are not upper-cased. This PR corrects `allowed_license_families` to only contain upper-case elements.
This bug can be reproduced with a `meta.yaml` file that has an `about` section which looks like this:
```
about:
license_family: Proprietary
```
> Fix mixed-case license family names

- conda_build/metadata.py
- tests/test-recipes/metadata/_preferred_env/run_test.py
The `preferred_env` field needs to be part of index.json for conda to properly plan installations.  That it hasn't been was an oversight that I just discovered as I'm now going back and writing extra integration tests for this feature.
> add preferred_env to index.json

- ci/travis/run.sh
- conda_build/api.py
- conda_build/build.py
- conda_build/config.py
- conda_build/index.py
- conda_build/metadata.py
- conda_build/render.py
- conda_build/variants.py
- tests/test-recipes/metadata/_post_link_exits_after_retry/meta.yaml
- tests/test_cli.py
- tests/test_variants.py
This is especially necessary for concourse's test modules, where they are just never meant to actually install/build packages.  The net result of this PR is that with api.render, you can now allow it to return un-finalized metadata.  For building, metadata will still be finalized, or will raise errors when it is not able to be finalized.
> allow un-finalizable recipes (things that are not installable)

- conda_build/utils.py
- tests/test-recipes/metadata/_unicode_in_tarball/meta.yaml
- tests/test_api_build.py
The problem may occur only on windows and only with py2.
> fix error unpacking tarball containing unicode filenames

- conda_build/build.py
- conda_build/convert.py
- conda_build/metadata.py
Replaces #1788 - meant to do this against 2.1.x.
fixes #1784
@H0R5E please test. I could not reproduce your error locally on a Win-64 system, converting a win-32 package to win-64. I used a package for wheel that I had lying around. It may be something particular about your package - especially if your default system encoding is affecting things. If this PR doesn't fix things for you, I need to ask for more info about your system, and possibly a dummy package, if you don't mind creating one (just build some arbitrary publicly available recipe and post your package somewhere).
> try to encode/decode delimiter for py_file_map

- conda_build/source.py
The _guess_patch_strip_level() function autodetects a value for the `-p` option to `patch` based on the file names present in the patch file. It had a bug, though, when the ideal strip level was zero: the code that found the value of `maxlevel` (a bit confusingly named) found its minimum value over each filename but checked for the initialization case with `if not maxlevel`. This condition holds if `maxlevel` is equal to its initial value, `None`, but also if `maxlevel` is zero. In that case, `maxlevel` could have been erroneously set to be too large, leading to patch failure, depending on the ordering of iteration through the `files` set.
This was observed in the wild:
https://circleci.com/gh/conda-forge/gobject-introspection-feedstock/2 .
> Fix detection of patch strip level when maxlevel = 0.

- conda_build/_link.py
- conda_build/build.py
- conda_build/conda_interface.py
- conda_build/utils.py
fixes #1812 
conda only recently added this attribute.  This falls back to a safe default for older conda versions.
> fix context conda_build attribute error with older conda

- conda_build/utils.py
- tests/test_jinja_context.py
If one wants to leave a lower or upper bound pinned with jinja2 pinning expressions, this provides a way to do so.  Just pass None as the value to either min_pin or max_pin.
> allow None to min_pin and max_pin to not pin those bounds

- conda_build/config.py
- conda_build/jinja_context.py
- conda_build/variants.py
This is so that we don't need to provide aliases to our cross-compiler packages.  Instead, we keep the default names of compilers the same, but append a default target_platform value.
> WIP: provide default platform

- conda_build/environ.py
This issue was encountered when building a recipe for cx_Oracle. It was failing on the test stage because `import cx_Oracle` results in setuptools `pkg_resources.resource_filename` being called, which in turn has a call to `os.environ['windir']` on Windows.
I guess that the `WINDIR` environment variable is widely assumed to always be set on Windows, like `SYSTEMROOT`.
> Pass WINDIR env var through on win

- conda_build/build.py
- conda_build/cli/main_build.py
- conda_build/config.py
- conda_build/environ.py
- conda_build/post.py
- tests/test-recipes/metadata/_test_long_test_prefix/meta.yaml
- tests/test-recipes/metadata/_test_long_test_prefix/run_test.py
- tests/test_api_build.py
- tests/test_cli.py
- tests/test_config.py
Fixes #1824 #1816 
Note that long-test prefix will be disabled by default in conda-build 2.1.7 and any future 2.1.x releases, but enabled in 3.0+.
> Add long test prefix option

- conda_build/build.py
- tests/test_cli.py
Fixes an issue reported on the conda mailing list, where specifying two or more recipes on the CLI would fail to create independent build folders.
> reset build folder for each built package

- conda_build/create_test.py
CC @stuartarchibald
I don't think this is a proper fix, but absent a reproducer, this should at least be a good enough band-aid to make conda-build get out of your way.
> wrap copy of test/source_files so that errors don't prevent a build

- conda_build/conda_interface.py
The current release doesn't work on Python 2.7 with conda >= 4.2 without this unfortunately:
```TypeError: environment can only contain strings```
> Python 2 os.environ Windows compat. fix

- conda_build/source.py
I wondered why using file sources, no symlinks were used. Seems to be forgotten.
I tried running the very long running mentioned tests, but they fail before and after my change :-( 
Running my local build worked fine for me with this change.
> Use symlinks while copying from file sources to improve perf.

- conda_build/create_test.py
Hi,
2 bugs I encountered while writing recipes for perl packages:
- conda was writing python tests everytime, even when it's a perl package (not sure it's the best way to fix it though)
- an indentation problem made the `fo` variable unavailable when writing the perl test
> Fix 2 errors when testing perl packages

- conda_build/jinja_context.py
- tests/test_jinja_context.py
`setuptools 30.3.0` added the ability to read metadata / options, i.e. keyword arguments for `setuptools.setup`, from configuration files. See https://setuptools.readthedocs.io/en/latest/setuptools.html#configuring-setup-using-setup-cfg-files.
This PR makes this functionality available in `conda_build.jinja_context.load_setup_py_data`.
I assumed that _setup.cfg_ resides next to _setup.py_ in the same directory. According to the doc-string of `distutils.dist.Distribution.find_config_files` (which is the function that provides the configuration filenames for `setup`) _setup.cfg_ is to be found "in the current directory". Thus maybe L142 should simply be `setup_cfg = 'setup.cfg'`. I am not sure whether the current working directory in `load_setup_py_data` would be the one `setuptools` / …
> read metadata / options from setup.cfg in load_setup_py_data

- tests/test_utils.py
test_unzip should only be run on Unix system where os.chmod works on all file permissions.
> TST: Add skip to test_unzip unit test

- conda_build/inspect.py
The conda inspect linkages command now logs as a warning when multiple
packages contain a library.
closes #1882
> Inspect linkages logs when mult pkgs provide lib

- conda_build/source.py
Small restructuring of a loop to avoid a potentially costly second call to hashsum_file.
@msarahan, is there a better error to be raising here than RuntimeError?  What is exceptions.VerifyError intended for?
> avoid un-necessary rehashing in some cases

- conda_build/create_test.py
Treat entries in the test/imports section as Python imports unless the package
name begins with one of the other known languages (r, lua, perl) or the test
language is explicitly included in the test block.
closes #1892
> BUG: Treat test/imports as Python import

- conda_build/utils.py
When creating entry_points for entries in the build/entry_points section use
the same template as pip uses when creating entry points for wheels.
> Create entry points scripts using pip template

- conda_build/os_utils/external.py
- tests/test_os_utils_external.py
`conda build` got hung up on a file called `git` in my `$PATH` that was not executable (by me).  This fixes it.
> check that files are executable in finding executables.

- conda_build/build.py
- conda_build/post.py
In one case, we can open the file as read-only before mmapping it to
prevent OSError 22.
When that fallback fails, set mm to the file contents not the file
handle when mmap fails to prevent:
m = SHEBANG_PAT.match(mm)
TypeError: expected string or bytes-like object
In the other case, the file is written to via the memory mapping so
there use flags=mmap.MAP_PRIVATE instead.
> Fix mmap/file problems on VirtualBox shared folders

- conda_build/build.py
a valid conda environment, at a minimum, contains a conda-meta
directory and conda-meta/history file
> fix empty create_env

- conda_build/metadata.py
This fixes a changed exception type associated with conda/conda#4158
> fix for conda's new MatchSpec implementation

- conda_build/build.py
- conda_build/metadata.py
- conda_build/render.py
- conda_build/variants.py
- tests/test-recipes/metadata/_pin_downstream/meta.yaml
- tests/test-recipes/metadata/_pin_subpackage_exact/meta.yaml
- tests/test-recipes/metadata/_run_exports/meta.yaml
- tests/test-recipes/variants/03_numpy_matrix/conda_build_config.yaml
- tests/test-recipes/variants/10_runtimes/pins_downstream/meta.yaml
- tests/test_api_build.py
- tests/test_subpackages.py
- tests/test_variants.py
after internal discussion, we decided that pin_downstream just isn't clear wording for what this feature is doing.  We believe "run_exports" is more intuitive - package requirements that are exported as runtime requirements to downstream packages.
CC @pzwang
> rename pin_downstream to run_exports

- conda_build/build.py
- conda_build/environ.py
- conda_build/utils.py
- tests/test-recipes/metadata/symlinks/run_test.sh
- tests/test_api_build.py
- tests/utils.py
This should hopefully restore --dirty to working.  It was broken with multiple outputs.
> use rm_rf to remove envs.  Fix symlinks

- conda_build/index.py
- tests/test_api_build.py
This is a partial fix for #1883 
It at least fixes errors associated with --no-locking.  The other errors are going to take more work, and unfortunately there's quite a lot ahead of them.
> fix unbound local variables when --no-locking used.  Add test.

- conda_build/config.py
Delimit package_name to prevent list from being loaded with other build folder names that contain the package name as a substring.
This allows recipes that call for the population of git-related environment variables to be rendered correctly when the `--dirty` flag is used.
> Correct rendering with --dirty flag if recipe name appears as a substring of another's name

- conda_build/variants.py
- tests/test-recipes/variants/selector_conda_build_config.yaml
- tests/test_variants.py
example:
```
python:
- 2.7
- 3.5  # [unix]
```
> add support for selectors in conda_build_config.yaml files

- conda_build/metadata.py
This patch is in conda-build 3, but I guess it didn't make it into the 2.1.x branch.
I'm running into some problems right now building conda with conda-build 3, so really need this in conda-build 2 to get the alpha release out today.  (Also looking into why conda won't build with conda-build 3.)
> fix preferred_env in index.json in 2.1.x

- appveyor.yml
- conda_build/config.py
- conda_build/environ.py
- tests/test-recipes/metadata/_perl_env_defined/run_test.py
- tests/test_metadata.py
This fixes several failing windows tests, because windows is case insensitive.
> don't expose language versions from variant as env vars

- .travis.yml
- conda_build/api.py
- conda_build/build.py
- conda_build/conda_interface.py
- conda_build/environ.py
- conda_build/index.py
- conda_build/jinja_context.py
- conda_build/metadata.py
- conda_build/render.py
- tests/conftest.py
- tests/test_api_render.py
- tests/test_build.py
This looks to me like about a 10-20% speed increase.  Further speed increases might require digging into conda (minimizing the number of re-creations of Resolve objects)
> simplify build index as global. remove duplicate creations.

- conda_build/build.py
> fix --skip-existing when multiple outputs emitted from single recipe

- conda_build/metadata.py
- tests/test-recipes/split-packages/_output_specific_subdir/meta.yaml
- tests/test_subpackages.py
This is essential for packages that create both cross-compilers and their runtime libraries.  The compilers themselves have the native platform as the host, but the runtime libraries need the target platform as their host.
cc @mingwandroid
> allow per-output specification of host subdir (target)

- conda_build/skeletons/cran.py
This PR adds libgcc to the runtime dependencies when the recipe needs compilation.
> Add libgcc to run dependencies.

- conda_build/post.py
Literal RPATHs of '$ORIGIN' were falling through to the fixup code
when they should have been passed unmodified. A trailing slash was
the cause and this broke openjdk.
> post: Fix $ORIGIN replacement

- conda_build/create_test.py
- tests/test_create_test.py
This PR has 4 commits:
1. create a test to demonstrate what I ran into in #1967 
1. fix the test from 1
1. create another test for a case that I'm not sure conda-build will allow.  If test/imports takes a list of dicts, does anything prevent two of the dicts in the list from having `lang` python?
1. fix the test from 3.
> fix perl only creating run test py #1967

- conda_build/skeletons/pypi.py
- tests/test_api_skeleton.py
Looks for simple environment markers of the form `^:python_version(<|<=|!=|==|>=|>)(.+)$` and adds in their requirements if the current Python version matches the specification. Resolves #1974.
> Add basic environment marker support to conda skeleton pypi

- conda_build/metadata.py
- tests/test-recipes/metadata/_run_constrained/meta.yaml
- tests/test_api_build.py
> support optional dependencies spec from conda 4.4

- conda_build/index.py
Instead, just omit _license from being indexed
fixes #348 
fixes #1976
> squelch failure to index folders containing _license package

- conda_build/utils.py
Although no new tests added, this PR should be pretty safe.  The function `hashsum_file` being imported from conda_interface is used by `md5_file` one level down.  So there really shouldn't be any new code paths or a net negative to test coverage.
> add sha256 value to repodata.json produced by 'conda index'

- conda_build/source.py
- tests/test_patch.py
- tests/test_source.py
When a patch contains non-utf8 or when the system encoding doesn't match the file encoding the line endings processing fails because it attempts to decode the content.
Fixes #2032
> [WIP] Avoid encoding/decoding on line-endings processing on patch files

- conda_build/render.py
[docs](https://github.com/conda/conda-docs/pull/414/files#diff-d1a5dbb2f223de4935d93990676c7074) suggest that pinning should be specified as
```yaml
pin_run_as_build:
pkg: x.x
```
but the code required a dict:
```yaml
pin_run_as_build
pkg:
min_pin: x.x
max_pin: x.x
```
This transforms `'x.x'` string from the docs example into the same value for min/max kwargs. I'm not sure if this is the right place to do the transform, or if it should be done when the config file is loaded.
> allow pin_run_as_build to be a single 'x.x' string

- conda.recipe/meta.yaml
In the master branch this has been fixed in https://github.com/conda/conda-build/commit/a31774d8b9c8d9954dc2b14be6e955ef8ec70d1b, but 2.1.15 also uses six, e.g. it is imported in [conda_build/metadata.py](https://github.com/conda/conda-build/blob/2.1.x/conda_build/metadata.py).
> Add missing six dependency

- conda_build/cli/main_build.py
- conda_build/cli/main_render.py
- conda_build/source.py
- tests/test_source.py
fixes #1512 
New things:
* filename_hashing: defaults to True.  If False, disables new conda-build 3 hashes in filenames.
* no_verify: defaults to False.  If True, does not run conda-verify checks on recipe or packages.
* set_build_id: defaults to True.  If False, does not create separate build folders for each build.
* activate: defaults to True.  If False, environments are added to PATH, but activate scripts are not run.  Not recommended.
* pypi_repository: unset by default.  PyPI repository to upload wheels to.
* pypirc: unset by default.  Path to pypirc file to be used for uploading wheels to pypi
* user: unset by default.  Username to use for uploading packages to anaconda.org or wheels to PyPI.
* anaconda_token: unset by default.  Token used to authenticate with anaconda.org for …
> add several variables that can be set in condarc

- ci/travis/run.sh
- conda_build/__init__.py
- conda_build/build.py
- conda_build/environ.py
- conda_build/index.py
- conda_build/metadata.py
- conda_build/utils.py
- tests/test-recipes/metadata/_checkout_tool_as_dependency/meta.yaml
- tests/test_api_build.py
- tests/test_utils.py
fixes #1827 
This also adds configurability to conda-build's logger usage.  Users may configure the logging using the YAML syntax presented at the bottom of the section at https://docs.python.org/3.6/howto/logging.html#configuring-logging
and by putting an entry into their .condarc files:
```
conda-build:
log_config_file: (path to config file)
```
> log info/debug to stdout.  Log warn/error to stderr.  dedupe better.

- conda_build/metadata.py
- conda_build/render.py
- tests/test_api_render.py
Previously this would be a timestamp, which looked confusing and made reproducibility poor.
> show no hash in filename unless rendering is final

- conda_build/create_test.py
Added semicolons to the printed print statement for the test to prevent syntax errors in Perl (Python and Lua accept semicolons at statement ends).
> Backport of #2012 to 2.1.x branch

- conda_build/build.py
v3.0.0
avoid failing test when using filename_hashing=False (reading non-existent .json file)
> test failure using filename_hashing=False

- conda_build/create_test.py
- tests/test_create_test.py
Backport of #1968 to fix https://github.com/conda/conda-build/issues/1967 on conda-build 2.1.x.
> Backport #1968

- conda_build/environ.py
This is needed when testing some packages involving GUI.
> Expose DISPLAY variable on Linux (2.1.x)

- conda_build/environ.py
This is needed when testing some packages involving GUI.
> Expose DISPLAY variable on Linux

- conda_build/config.py
The variable `cc.subdir` was renamed to the property `subdir` in a previous commit (referenced below). However the comment above was not. This corrects the comment to clarify what this now represents.
ref: https://github.com/conda/conda-build/commit/f99776f9a0f25e6cd2aa363ef036b8b7bbece7a6
> Fix variable name in `bldpkgs_dirs` comment

- conda_build/build.py
Build work directory is deleted in test phase and it tries to
delete the work dir with id. As a consequence, the test phase
keeps the real work dir and then the next package build breaks
because it tries to apply a patch it was already applied.
cc @gqmelo 
xref: https://github.com/conda-forge/conda-smithy/pull/526#issuecomment-309106967
> Don't set build_id in test phase if --no-build-id is given

- tests/test_api_build.py
This test make sure the work dir is removed regardless of the --no-build-id option
I made it sure the test fails before #2100
> Add test case for  #2100 and #2101 (2.1.x)

- tests/test_api_build.py
This test make sure the work dir is removed regardless of the --no-build-id option
This was ported from #2111. Apparently this issue was already fixed on master, but it's good to have a regression test anyway.
> Add test case for  #2100 and #2101

- conda_build/skeletons/pypi.py
- tests/test_api_skeleton.py
fixes #2103 
Test requirements are now parsed as a list when given a string literal. This fix includes a test using a package that uses a string in setup.py's test_requires.
> Added ensure_list to line 803 in order to parse string literal test requirements

- conda_build/convert.py
- tests/test_api_convert.py
- tests/test_cli.py
Currently, conda convert will convert a package even if both platforms and architectures are the same.  This PR includes a check that will skip conversion if the source platform and architecture equals the target platform and architecture. 
Also included is a test to make sure that these packages are not built. 
Because this feature broke the current convert test suite, the test suite has been refactored to omit conversions between the same platform and architecture.
> Added a check to skip conversion if source platform equals target platform

- conda_build/cli/main_build.py
- conda_build/config.py
- conda_build/environ.py
The --keep-old-work flag was deprecated and ended up having the same functionality as the --dirty flag. However, there are times when a developer would want to have the work directory remain intact even after a successful build/test. Rather than create a new flag, the --keep-work-dir flag will be used for this particular case.
@msarahan
> Add new functionality to --keep-work-dir flag

- conda_build/skeletons/luarocks.py
- conda_build/skeletons/pypi.py
`noarch_python` is legacy syntax
This patch modifies the skeleton generation for pypi and luarocks pkgs.
> skeleton generation: replace legacy syntax for noarch pkgs

- conda_build/build.py
- conda_build/metadata.py
- conda_build/variants.py
- tests/test_metadata.py
- show more output from source activate (especially important for seeing variables changed by activate.d scripts)
- fix cleanup not knowing about build id and doing a bad job (fixes #2104)
- Change default platform to not include things like cos5 or 109 - let the user define those.
> 3.0.0 fixes

- conda_build/build.py
- conda_build/cli/main_convert.py
- conda_build/convert.py
- conda_build/utils.py
- tests/test_api_convert.py
- tests/test_cli.py
@mandeep this almost works.  Locally, I have one test failing in the serial section (which is what most of this code is):
```
________________________________ test_convert_from_unix_to_win_creates_entry_points ________________________________
File "/Users/msarahan/code/conda-build/tests/test_api_convert.py", line 196, in test_convert_from_unix_to_win_creates_entry_points
assert files == paths_list
AssertionError: assert {'Lib/site-pa...ntry.py', ...} == {'Lib/site-pac...ntry.py', ...}
Extra items in the left set:
'Scripts/__pycache__/test-script-setup.cpython-36.pyc'
Extra items in the right set:
'Scripts/__pycache__/test-script-setup.cpython-36-script.py'
Full diff:
{'Lib/site-packages/conda_build_test/__init__.py', …
```
> Conda convert rewrite

- conda_build/metadata.py
- conda_build/render.py
- tests/test_render.py
prior to this, python was special-cased, and you could write
```
requirements:
build:
- python
```
and expect conda-build to loop over all python versions defined in conda_build_config.yaml.  For anything else, you'd need to define Jinja2 placeholders:
```
requirements:
build:
- python
- numpy   {{ numpy }}
```
where the ``{{ numpy }}`` will use the numpy value from the variant.
This PR matches package names up with variant keys, and obviates the need for the explicit syntax.  The explicit syntax still works, though.
> remove strict need to always use jinja2 for variants

- conda_build/build.py
- conda_build/exceptions.py
- conda_build/metadata.py
- tests/test-recipes/fail/check_runtime_dependencies/meta.yaml
- tests/test-recipes/fail/check_test_dependencies/meta.yaml
- tests/test_api_build.py
fixes #671
Used get_install_actions from environ.py to check if the test dependencies listed in meta.yaml could be found. This fix also includes a test to make sure that a DependencyNeedsBuildingError is raised when a test dependency can't be found.
> Added test actions so that conda build errors out earlier if test dependencies not found

- conda_build/api.py
- conda_build/environ.py
- conda_build/jinja_context.py
- conda_build/license_family.py
- conda_build/skeletons/rpm.py
- tests/test_api_skeleton.py
From my perspective this is ready for review now.
A commandline you could use to try this out is:
`conda skeleton rpm --recursive --distro centos6 --output-dir=~/conda/conda-recipes/cdts/centos6-x86_64 --architecture x86_64 libselinux-devel libX11-devel libselinux-devel java-1.7.0-openjdk java-1.7.0-openjdk-devel libgcj mesa-libGL-devel alsa-lib-devel alsa-lib alsa-utils gtk2-devel gtk+-devel libXrandr-devel ruby gperf xorg-x11-proto-devel`
Points for discussion:
What extra metadata do we want to include with these packages?
Should I allow passing `--architecture` multiple times?
> skeleton: Add rpm

- conda_build/jinja_context.py
- tests/test-recipes/variants/06_compatible_custom/compatible/meta.yaml
- tests/test-recipes/variants/07_compatible_custom_lower_upper/compatible/meta.yaml
- tests/test-recipes/variants/07_compatible_custom_lower_upper/meta.yaml
- tests/test-recipes/variants/10_runtimes/uses_run_exports/meta.yaml
- tests/test-recipes/variants/conda-build-demo.ipynb
Update links to point to real docs now (they're live), fix one bounds issue in pin_compatible, and shorten it a bit.
> update variants notebook for cb3 blog post

- conda_build/environ.py
Just like the HTTP proxies, these are part of the system configuration that the build might rely on if it uses requests to fetch an HTTPS resource. An example would be building sphinx-based documentation with the intersphinx extension enabled attempting to download the inventory from `docs.python.org`.
> Add SSL_CERT_FILE and REQUESTS_CA_BUNDLE to build environment

- conda_build/build.py
- conda_build/convert.py
In reference sorted files in issue #2140 
For build.py I merely added a sorted() call around the files argument. Even though the if statements are not calling paths in alphabetical order, the sorted files argument seems to be enough.
For convert.py I decided to append all filepaths to a list then write that sorted list into the files file.
> Sort files before they're written to the files file

- conda_build/build.py
In relation to #2140:
The field values in the metadata are sorted alphabetically prior to outputting the meta.yaml file in the info/recipe directory. The build/script and test/commands values are omitted.
> Sort output metadata prior to writing to meta.yaml

- conda_build/skeletons/cran.py
The 'Writing R Extensions' manual doesn't mandate that if there are no
suggestions for a package, then the field should not be present. It can
still be present, with a blank value, for example:
https://cran.r-project.org/web/packages/corpcor/DESCRIPTION
This patch adds the functionality to not throw an error during parsing
if the value of certain fields is empty. It should just ignore that
field and continue.
Fixes https://github.com/conda/conda/issues/5624
> cran-skeleton: allow certain blank keys

- conda_build/os_utils/ldd.py
The call to `conda_build.os_utils.pyldd.inspect_linkages` in `conda_build.os_utils.ldd.get_linkages` passes `sysroot` as a second positional argument, but the second positional argument to that function [is actually `resolve_filenames`](https://github.com/conda/conda-build/blob/667ef45bfd9e77d365403279f416eb5eb0c7fad5/conda_build/os_utils/pyldd.py#L842).
> fix inspect_linkages call in os_utils.ldd.get_linkages

- conda_build/build.py
- conda_build/utils.py
@mingwandroid brought up the issue that PR #2149 may result in an AttributeError traceback when a section contains a list as its value instead of a dictionary. This PR will fix that issue.
> Moved try block in copy_recipe further up in order to catch values that are lists

- .travis.yml
- appveyor.yml
- ci/travis/run.sh
- conda.recipe/meta.yaml
- conda_build/build.py
- conda_build/utils.py
- setup.py
- tests/test_utils.py
This adds glob2 as a dependency to the project to support patterns such as:
```
**/my_project/**/.txt
```
in all entries using expand_globs. 
Furthermore the output of expand_globs is modified to replace os.path.sep by / as conda manipulate paths containing only / (this is for example the case for ignore_prefix_files, with the modification the filtering fails on Windows). I am not sure this is the proper fix.
If you are favorable to such changes, I will add tests and update the docs on conda-docs. One open question is that glob2 is not available on conda and so it needs to be added as otherwise the conda recipe will not valid.
> Use glob2 to resolve recursive pattern /**/

- conda_build/os_utils/pyldd.py
Also use os.path.realpath instead of os.readlink so that we follow
links to links.
> pyldd: Directories are not codefiles.

- conda_build/noarch_python.py
Preserve the mode setting of files in the binary directory of noarch python
packages when rewriting the file in the python-scripts directory.
closes #2155
> Preserve mode bit on noarch python bin files

- conda_build/build.py
This cleanup happens elsewhere.  This was removing test env too aggressively (--dirty was not keeping it around)
Fixes #2166
> don't always remove test folder at end of test

- conda_build/environ.py
- conda_build/utils.py
- tests/test_api_render.py
- tests/test_jinja_context.py
When pre-release versions of things were present, conda-build's upper bounds didn't work very well.  ```python >=3.5,<3.6``` would allow python 3.6.0rc4, for example.
Here we add .0a0 to semver-style constraints, and for openssl and jpeg style, we go to the next major version, plus 'a' (presumably the first version for the next major series.)
fixes #2181 #2169
> fix upper bound increment to account for prerelease versions

- conda_build/environ.py
- conda_build/render.py
- tests/test_environ.py
As reported by @nehaljwani on flowdock, ``numpy x.x`` specs were leading to this traceback:
```
(root) root@bff79ce8ddcb:~/astropy-feedstock/recipe# conda build . --numpy 1.12
Leaving build/test directories:
Work:     ../../../conda/conda-bld/work 
Test:     ../../../conda/conda-bld/test_tmp 
Leaving build/test environments:
Test:    source activate  ../../../conda/conda-bld/_test_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehol 
Build:    source activate  ../../../conda/conda-bld/_h_env_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_placehold_pla …
```
> fix numpy x.x getting .* added to it

- conda_build/utils.py
For conda especially, what was happening was that writing the new entry points was following the symlink through to the root environment, causing the root env conda to break.
> remove existing entry points (esp. links) before writing new ones

- conda_build/build.py
- tests/test_cli.py
fixes #2212
basically, config is passed in, but doesn't have the specific build id that the test env is created with.  We need to be sure to keep that association.
> fix package testing using wrong metadata

- conda_build/metadata.py
- conda_build/render.py
- conda_build/skeletons/pypi.py
- tests/test_api_skeleton.py
- tests/test_cli.py
- tests/test_published_examples.py
This replaces the string template with what is essentially a nested ordered dict (`ruamel_yaml.comments.CommentedMap`) and writes the recipe out in conda-forge order. 
This needs a bit of cleanup still (feel free to do that, I won't be able to come back around to it until later on Sunday).
A few thoughts that I won't remember in the morning:
+ It would be nice to put the "standard order" variables (`EXPECTED_SECTION_ORDER`, `REQUIREMENTS_ORDER`, maybe `ABOUT_ORDER`) some place "standard" and have `conda skeleton` and `conda-smithy` import from that place rather than trying to keep the values synced across packages.
+ With a little refactoring I think the recipe generation conda build pulled out into a function that can take in either the dictionary `d` generated in `skeletonize` or …
> Rewrite skeleton template and match conda-forge standard

- conda.recipe/meta.yaml
- conda_build/utils.py
Our internal recipe is a development recipe.  Doing the Jinja2 this way will allow us to more easily upload testing versions to internal channels and use them with c3i.
> tweak conda.recipe to include git rev; fix regex

- conda_build/skeletons/pypi.py
Use the namespaced ruamel.yaml import in conda skeleton pypi if
importing ruamel_yaml fails.  If both fail to import raise a helpful
error message.
Import logic adapted from common/serialize.py file in conda source code.
> Fallback to using ruamel.yaml in conda skeleton

- conda_build/environ.py
- conda_build/metadata.py
- conda_build/source.py
- tests/test-recipes/metadata/source_multiple/bld.bat
- tests/test-recipes/metadata/source_multiple/build.sh
- tests/test-recipes/metadata/source_multiple/meta.yaml
After #1929, a single recipe may specify multiple source repos (fixing #1466).  In that case, the metadata `source` section is written as a **list** of source dicts instead of a single dict:
```yaml
source:
- git_url: https://github.com/foo/foo
git_tag: 1.0
- git_url: https://github.com/foo/bar
git_tag: 1.1
folder: bar
```
But that breaks an assumption in the convenience function `MetaData.get_value()` -- that every section is a `dict`.  Calls like `meta.get_value('source/git_url')` result in errors.  For example:
```pytb
File "/miniforge/lib/python3.6/site-packages/conda_build/metadata.py", line 888, in get_value
value = self.get_section(section).get(key, default)
AttributeError: 'list' object has no attribute 'get'
```
~~This PR "fixes" the problem by merely assuming the caller is …
> Fix bugs related to multiple sources

- conda_build/cli/main_build.py
- conda_build/config.py
- conda_build/source.py
- tests/test_api_build.py
Add src_cache_root to Config objects and allow setting via --cache command line flag.
> Add source cache to config and remove conda legacy imports

- conda_build/build.py
fixes #2231
If a build.sh exists and a script value exists in meta.yaml's build field, conda build will build with the script found in meta.yaml. Also a warning will be raised to let the user know that two scripts exist.
I tried adding a test for the warning that used capfd to capture stderr, but there's too much output from the build process for capfd to capture.
> Only write one build script to build file and warn when multiple scripts found

- conda_build/inspect.py
This problem surfaced via https://github.com/conda/conda/pull/5645.  Conda has always added "virtual" feature records to the `index`.  It was never a problem here because there were so few of them in the past.  Now there are a few more, and specifically feature records for python, which is the source of the particular collision here.
The way feature records for the solver are identified in `index` is that the name field ends with an `@` character.
> ignore feature records in index for 'conda inspect'

- conda_build/api.py
- conda_build/build.py
- conda_build/environ.py
- conda_build/metadata.py
- conda_build/render.py
- tests/test-recipes/metadata/source_git_jinja2/meta.yaml
- tests/test_api_build.py
- tests/test_api_render.py
- tests/test_cli.py
- tests/test_metadata.py
fixes #2245 
This also makes the hash available as the PKG_HASH env var, usable in build scripts and in meta.yaml, should the user want to put it in themselves.  It does not include the leading h.
> do not modify user-specified build/string with hash

- conda_build/create_test.py
Prevents issues when merging meta test commands and test scripts in run_test.{sh,bat}
I've seen some test failures on recipes when newlines are missing.
> Add newlines

- conda_build/metadata.py
- tests/test_source.py
Well, this is embarrassing.  Last week I submitted a PR (#2247) which had a small bug in it.  If someone uses the new "index" syntax for `get_value()` with a non-zero index (e.g. `meta.get_value('source/2/git_url')`), it won't work.  Oops.
This isn't affecting anyone right now, because at the moment no part of conda-build calls `get_value()` with a non-zero index.  But here's a fix nonetheless.  (With a test case!)
> metadata: Fix mistake in get_value() (bug from #2247)

- conda_build/tarcheck.py
Resolves #2264 
setting target in the outputs section would go through the whole build process and fail at the end with an error like this:
```
Inconsistent subdir in package - index.json expecting linux-64 got win-64
```
Add target_subdir to the assert statements allowed values in tarcheck.py. This allows the value in the outputs section's target to be valid during this check. This also doesn't interfere with the other allowed values and shouldn't have any side effects.
I have tested building a package on windows with the target hard coded to linux-64, it worked as expected. I also tested building a package which utilizes the ```conda_build_config.yaml``` for cross compiling and a normal package built and hosted on the same config. All worked as expected.
> WIP fixes setting target in outputs section

- conda_build/skeletons/pypi.py
`skeleton pypi` currently adds `setuptools` to both `build` and `run` dependencies if it is not already present in the dependencies extracted from `setup.py`. My understanding is that `setuptools` should not be needed at run time, only at build time. 
This PR drops the addition of `setuptools` to the `run` requirements; if the package explicitly lists `setuptools` as a requirement in `setup.py` then it remains in the list of dependencies.
> Do not add setuptools to runtime dependencies

- conda_build/cli/main_render.py
- conda_build/skeletons/pypi.py
- tests/test_api_skeleton.py
This pull request fixes #2244 by ensuring that all components of the recipe are (effectively) ordered dicts. Turns out that #2205 worked because I was testing it on python 3.6, which (as an implementation detail) preserves order of insertion of dictionary keys.
> Fix recipe field order in pypi skeleton

- conda_build/skeletons/cran.py
When using `conda skeleton cran` to create recipes for R packages, I noticed that the URL for the home field was always truncated. By testing this on previous versions of conda-build, I determined this bug was introduced in PR https://github.com/conda/conda-build/pull/2153 to fix https://github.com/conda/conda/issues/5624 and released in version [3.0.2](https://github.com/conda/conda-build/tree/3.0.2).
This is how the home and summary fields look in the recipe for r-corpcor created by the most recent release of conda-build (3.0.9):
```
$ conda install conda-build=3.0.9
$ conda skeleton cran corpcor
$ grep home r-corpcor/meta.yaml 
home: http
$ grep -A 3 summary r-corpcor/meta.yaml 
summary: Implements a James-Stein-type shrinkage estimator for  the covariance matrix, with
separate …
```
> Fix cran skeleton so that fields are not truncated by a semicolon.

- conda_build/api.py
- conda_build/build.py
- conda_build/metadata.py
- conda_build/render.py
- conda_build/variants.py
- conda_build/windows.py
Also collapses zipped fields better, so there aren't any duplicate garbage entries in the output conda_build_config.yml when saving out recipes.
fixes #2276
> fix double activation on windows for cross-compiling

- conda_build/build.py
This should fix the one remaining failure with conda 4.4 on Travis.
> move rm_rf test env before get_install_actions

- conda_build/metadata.py
mostly just a beautifier - make sure that you don't loop over things that are only loops on other platforms.
> run selectors before returning meta.yaml extractions

- conda_build/build.py
- conda_build/environ.py
- conda_build/metadata.py
- conda_build/render.py
- conda_build/variants.py
- tests/test_api_build.py
- tests/test_api_render.py
- tests/test_cli.py
- tests/test_subpackages.py
This fixes the problem where indirect dependencies would impose run dependencies.  For example, python uses xz.  Packages depending on python should not necessarily have a dependency on xz imposed.
> fix run_exports getting picked up transitively

- conda_build/variants.py
- tests/test-recipes/metadata/python_env_defined/run_test.py
fixes #2302 
@dhirschfeld CONDA_PY will remain the same.  PY_VER will have the period.  It doesn't make sense to have them both be the same value, IMHO.  I'll try to update the docs if I get a minute.
> fix CONDA_PY env format (no period)

- conda_build/jinja_context.py
Fixes a regression where the native compiler packages (clang, specifically) on mac was never adding _osx-64, and so was the generic clang, which doesn't set any variables.
> fix default compiler not having platform

- conda_build/build.py
- conda_build/environ.py
- conda_build/source.py
- conda_build/variants.py
- tests/test_source.py
- tests/test_subpackages.py
We archive all sources at continuum.  Doing so requires that filenames never collide.  We've found at least two common instances where they do collide:
1. Repackaging of conda packages that come from different platforms, but have the same filename
2. Downloads from github that contain only the release version (e.g. v3.0.0) rather than the project name
Adding hashes to the filename avoids these collisions.  As long as the hash (md5, sha1, sha256) is part of the recipe, we'll still be able to refer to our cache.  If they're not provided, we won't ever hit the right entry in the cache, but we'll add the discovered sha256 after the download completes, so at least we'll avoid clobbering.
> add file hash to source cache filenames to avoid collisions

- conda_build/build.py
- conda_build/render.py
- conda_build/skeletons/pypi.py
- conda_build/utils.py
- tests/test-recipes/metadata/_osx_is_app_missing_python_app/meta.yaml
- tests/test-recipes/metadata/_run_exports/meta.yaml
- tests/test-recipes/metadata/_run_exports_implicit_weak/meta.yaml
- tests/test-recipes/metadata/entry_points/meta.yaml
- tests/test-recipes/metadata/extra_freeform_metadata/run_test.py
- tests/test-recipes/metadata/jinja_load_setuptools/meta.yaml
- tests/test-recipes/metadata/osx_is_app/meta.yaml
- tests/test-recipes/metadata/preserve_egg_dir/meta.yaml
- tests/test_api_build.py
- tests/test_api_skeleton.py
- tests/test_cli.py
- tests/test_subpackages.py
There are some run_exports that should cross the build/host boundary.  For example, the runtime deps imposed by compilers specified in build should affect the end run dependencies.  However, for other build-time dependencies that exist only for utility (such as xz for unarchiving), things in build should be ignored.
This PR creates the "strong" or "weak" distinction.  It is completely optional.  Everything is "weak" by default, and the old syntax works.  The new syntax for strong run_exports is:
```
build:
run_exports:
strong:
- some_dep
weak:
- something_else
```
When run_exports has a value that is a list, all of the list items are "weak".
> create strong run_exports delineation.  Default weak

- conda_build/build.py
- conda_build/environ.py
fixes #2318 
@gabm, I am able to build conda perfectly fine with conda-build master and this recipe: https://github.com/AnacondaRecipes/conda-feedstock/blob/master/recipe/meta.yaml
I have inspected the built package, and it contains proper activate/deactivate/conda scripts, so I think the symlinking stuff (or rather, not symlinking, so that these files are real) is working OK.  We had an issue a little while ago where the symlinks were not being broken, and so we ended up writing through from the build env into the user's root env.  That should be fixed as of https://github.com/conda/conda-build/pull/2209
The error messages you posted in #2318 were annoying, but seemed ultimately harmless.  Just messy code from too many changes.  This PR cleans it up.  always_include_files when creating …
> remove meaningless error with glob_files during env creation

- conda_build/os_utils/pyldd.py
Without this, we cannot build gettext on macOS (otool returns an error). It's not a fantastic way to fix this problem, sorry.
> pyldd: Disambiguate java .class files from Mach-O fat files

- conda_build/config.py
- tests/test-recipes/metadata/empty_with_build_script/meta.yaml
- tests/test_cli.py
This PR is the result of #2329 
It adds 3 new testcases:
1. `test_relative_path_croot` which covers:  `conda-build --croot ./relative/path {recipe-folder}`
2. `test_relative_path_test_artifact` which covers: `conda-build --test ./relative/path/to/artifact.tar.bz2`
3. `test_relative_path_test_recipe` which covers `conda-build --test {recipe-folder} --croot ./relative/path/to/croot`
While test 2 and 3 worked out of the box, test 1 fails on linux and most-likely on windows as well. The fix for test 1 is included in this PR in 6720ae1, but I'm not 100% sure, so please @msarahan, review it carefully. 
I intented to use croot as an absolute path internally by parsing the commandline parameter. It was added back then by #1736. The code to make croot absolute is aparently still there, but it gets …
> Problem: relative paths in croot don't work anymore

- conda_build/build.py
This fixes #2301 
@msarahan Please review the fix carefully. There is more logic involved to index the right channels.. Maybe at some point we could teach update_index to do globbing...
There is one point where I'm not sure, and its where I throw the error... I'll mark it in the code
> Problem: When packages reside in un-indexed channels, the test command fails

- conda_build/render.py
- conda_build/utils.py
- tests/test-recipes/variants/14_variant_in_run_and_test/conda_build_config.yaml
- tests/test-recipes/variants/14_variant_in_run_and_test/meta.yaml
- tests/test_api_build.py
- tests/test_source.py
- tests/test_subpackages.py
- tests/test_variants.py
> add .* to specs that are underspecified (variants in run/test esp)

- conda_build/metadata.py
without this, running builds targeting win-32 on win-64 build workers will not evaluate x86_64 in selectors correctly.
> use host_subdir instead of build_subdir when setting selectors

- conda_build/jinja_context.py
This looks for fields named compiler_key + _version, such as ``fortran_compiler_version``.  when found, it uses this information to add a version pin to the compiler that gets specified.
This should be used with zip_keys - I haven't gotten the looping to work right with this thing on its own yet.
> allow versions to be provided for compilers with compiler jinja2

- conda_build/metadata.py
discovered this while trying to consolidate vs2008, vs2008_runtime, and vc 9 recipes into one recipe with split packages.  Split packages need to be able to set track_features independently of one another.
> add track_features and features to output options

- conda_build/build.py
- conda_build/environ.py
This has been tackled before, but is seemingly still a problem.  conda's symlink happens in cb at env creation time, but it's also happening when conda activates an env.  We need to disable both when building conda.
> avoid ever symlinking conda when building conda

- conda_build/windows.py
With this change and our previous one I can now build win-32 python.
> fix_staged_scripts needs to use host_prefix

- conda_build/post.py
- conda_build/tarcheck.py
Fixes cross-compiling errors with python packages like:
```
File "C:\ProgramData\Miniconda3\Scripts\conda-build-script.py", line 10, in <module>
sys.exit(main())
File "C:\ProgramData\Miniconda3\lib\site-packages\conda_build\cli\main_build.py", line 388, in main
execute(sys.argv[1:])
File "C:\ProgramData\Miniconda3\lib\site-packages\conda_build\cli\main_build.py", line 379, in execute
noverify=args.no_verify)
File "C:\ProgramData\Miniconda3\lib\site-packages\conda_build\api.py", line 185, in build
need_source_download=need_source_download, config=config, variants=variants)
File "C:\ProgramData\Miniconda3\lib\site-packages\conda_build\build.py", line 1773, in build_tree
notest=notest,
File "C:\ProgramData\Miniconda3\lib\site-packages\conda_build\build.py", …
```
> build_prefix->host_prefix in write_pth

- .travis.yml
- conda_build/render.py
- tests/test_api_build.py
The problem that highlighted the need for this was libtiff:
```
requirements:
build:
- {{ compiler('c') }}
- {{ compiler('cxx') }}
- cmake   # [win]
host:
- zlib
- jpeg
- xz    # [not win]
```
On Windows, the C and CXX compilers will activate the correct feature, but that's only for build section.  It left the host section ambiguous, and so we ended up with conflicts when creating the host env.
This PR addresses the issue by applying the strong run_exports from the build section to the host section.  Strong run_exports are ones that cross from build to run, as opposed to weak run_exports which pass only from host to run.  Generally, strong run_exports should only be part of (cross) compiler packages, which can target a platform other than their native one.
> make strong run_exports apply to host section as well as run section

- conda_build/windows.py
This avoids creation of the conda.bat redirect being packaged with conda.
> don't activate build or host env on win when building conda

- conda_build/render.py
- tests/test-recipes/metadata/_run_exports/meta.yaml
- tests/test-recipes/metadata/_run_exports_implicit_weak/meta.yaml
- tests/test_api_build.py
This was allowing incorrect things to happen because the actual pin was applied after we may have already obtained pins.  The end result was conflicting specs.
> fix strong run_export from build to host being applied too late

- conda_build/build.py
There is no reason on earth for this exclusion.
> Remove .a from files not considered for prefix replacement

- conda_build/config.py
Errors happen when recipe is on different drive than workdir (for example, recipe on shared drive mapped in, workdir on C:)
```
builder@DESKTOP-CB8H04D  /z/msarahan/code/aggregate
$ conda build curl-feedstock/
Attempting to finalize metadata for curl
INFO:conda_build.metadata:Attempting to finalize metadata for curl
File "C:\Users\builder\Miniconda2\Scripts\conda-build-script.py", line 11, in <module>
load_entry_point('conda-build', 'console_scripts', 'conda-build')()
File "z:\msarahan\code\conda-build\conda_build\cli\main_build.py", line 388, in main
execute(sys.argv[1:])
File "z:\msarahan\code\conda-build\conda_build\cli\main_build.py", line 379, in execute
noverify=args.no_verify)
File "z:\msarahan\code\conda-build\conda_build\api.py", line 185, in …
```
> remove several relpath uses due to Windows drive mixing errors

- conda_build/build.py
This was causing unsatisfiable issues with win-32 building on win-64
> check for run/test deps needs to use host subdir, not build

- conda_build/render.py
- conda_build/variants.py
This loads conda_build_config.yaml from the package's info/recipe dir if available.  This facilitates testing, when testing depends on variables that may have been present at build time, are present in the variant, but otherwise not present in the test scripts.
> load conda_build_config.yaml for test packages to set variables

- conda_build/skeletons/cran.py
This PR re-implements a past solution for `conda skeleton cran` that handles blank entries for any field in CRAN metadata.
Sometimes R packages on CRAN have blank metadata fields (e.g. Suggests is blank for [corpcor](https://cran.r-project.org/web/packages/corpcor/DESCRIPTION) and Enhances is blank for [data.tree](https://cran.r-project.org/web/packages/data.tree/DESCRIPTION)). In the past this caused problems when running `conda skeleton cran`, e.g.:
* Issue #1787 from March 2017 for data.tree using conda-build 2.1.5
* Issue https://github.com/conda/conda/issues/5624 from July 2017 for corpcor using conda-build 2.1.16
One solution to this problem was provided on July 5th by @nehaljwani in commit https://github.com/conda/conda-build/pull/2153/commits/4d90305bf675a6ebe49b3ead162820338f74413 …
> Simplify handling of blank fields in CRAN metadata.

- tests/test-recipes/metadata/_legacy_noarch_python/run_test.py
- tests/test-recipes/metadata/_noarch_python_with_tests/run_test.py
- tests/test-recipes/metadata/ignore_prefix_files/run_test.py
- tests/test-recipes/metadata/ignore_some_prefix_files/run_test.py
Some minimal changes to tests to prepare them for compatibility with the enhanced package cache structure that might make it into conda 4.4.  Changes are only to tests that verify files in specific locations in the package cache.  No changes needed to main code.
This PR would be needed for test compatibility with https://github.com/conda/conda/pull/5937
> prepare 2.1.x tests for enhanced package cache structure

- conda_build/config.py
- conda_build/render.py
- tests/test-recipes/metadata/_cross_prefix_elision/conda_build_config.yaml
- tests/test-recipes/metadata/_cross_prefix_elision/meta.yaml
- tests/test-recipes/metadata/_cross_prefix_elision_compiler_used/conda_build_config.yaml
- tests/test-recipes/metadata/_cross_prefix_elision_compiler_used/meta.yaml
- tests/test-recipes/metadata/_python_xx/run_test.py
- tests/test_api_render.py
fixes #2392 
The use case here is that there are a lot of recipes (especially pure python) that exist with:
```
requirements:
build:
- python
```
In cross-compiling situations, such as making win-32 packages from a win-64 conda-build install, CB3 has been dutifully separating the build and host prefixes.  Unfortunately, this is leading to packages that fail, because python will be in the build prefix, while packaging happens on what is in the host prefix (nothing).
This is probably only a fix for cross-compiling situations where the cross target runs on the host platform.  I don't think it'll work for more exotic cross-compiles, such as linux-64 -> linux-ppc64le.
> make build reqs equivalent to host when cross-compiling and no host

- conda_build/noarch_python.py
This appears to have been simpler than I thought. Stripping unrecognized files prevents `noarch: python` packages from including data_files, such as those in `$PREFIX/share`. Simply removing the stripping appears to cause the correct behavior of including these files relative to $PREFIX as in a non-noarch package.
closes #2419
> Don’t strip generic files in noarch: python

- conda_build/skeletons/pypi.py
The source archive to the pypi projects can end in more than just .tar.gz
extension. This patch allows the skeleton to support other file extensions.
Fixes #2411
> PyPI skeleton: allow multiple file extensions

- conda_build/skeletons/pypi.py
If a package is not available on PyPI the skeleton command fails with
the traceback:
```
File "/spare/scratch/1507796551/conda-build/conda_build/skeletons/pypi.py", line 220, in skeletonize
pypi_data = pypi_data.json()
File "/spare/scratch/1507796551/m3/lib/python3.6/site-packages/requests/models.py", line 850, in json
return complexjson.loads(self.text, **kwargs)
File "/spare/scratch/1507796551/m3/lib/python3.6/json/__init__.py", line 354, in loads
return _default_decoder.decode(s)
File "/spare/scratch/1507796551/m3/lib/python3.6/json/decoder.py", line 339, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
File "/spare/scratch/1507796551/m3/lib/python3.6/json/decoder.py", line 357, in raw_decode
raise JSONDecodeError("Expecting value", s, err.value) from None …
```
> Check HTTP status code of pkg manifest before decoding it

- conda_build/skeletons/pypi.py
I am trying to build a package for tensorboardX on pypi, but it fails to skeletonize. I'm still working my way through the process, but the problem I get with the existing conda-build is that when I run `conda skeleton pypi tensorboardX` it fails with the following error:
```
Error: Could not build recipe for tensorboardX. Could not find any valid urls.
```
The issue is that for this package `download_url` is defined, but is the empty string:
```
(Pdb) p data['download_url']
''
```
With this change, the branch will skip to the case when `download_url` is not defined, and print a message like:
```
Error: No source urls found for tensorboardX
```
I think this error message is much more informative in this case.
> fix misleading error when download_url is present but empty

- conda_build/skeletons/pypi.py
There is already a space after `python setup.py install`
> Drop extra space in build:script

- conda_build/environ.py
The `specs` parameter is passed as a tuple to `environ.get_install_actions`
in various places, which makes appending due to FEATURE_* environment
variables (e.g. FEATURE_NOMKL=1) fail. Therefore, explicitly convert
`specs` to a list.
> Fix FEATURE_* environment variables

- conda_build/metadata.py
- tests/test-recipes/split-packages/_per_output_tests/meta.yaml
- tests/test_subpackages.py
outputs can now be like this:
```
outputs:
- name: steve
build:
features:
- vc9
number: 4
test:
commands:
- echo "yes this works"
```
This is important for 2 reasons: it allows more of the build section to pass-through than before; and it allows per-output tests to be defined.
> pass tests and build section through wholesale from any output

- conda_build/post.py
Windows consoles by default generally start in C:\. It is common to not have write permission in the root C:\ without escalating privilege. It's better to use a proper temp directory, as the current approach fails in this case unless running as administrator, whereas with these changes it runs fine without running as administrator.
> Use proper temp directory

- conda_build/config.py
* Corrects behavior in dirty environments where a package name already encountered in a build session may appear as a prefix or suffix, with our without '_' characters, of other package names.
* Meant to be the final incarnation of the previous fixes here #1931, #1953, which were both insufficiently general to cover all combinations of cases.
> Exactly match package name in build_folder selection

- conda_build/build.py
Hi,
Temporaries accumulate in `/tmp` and are never cleared up.
The directory is created upon call to `utils.py->get_recipe_abspath()`: `need_cleanup` is set but never used in `build.py`.
On my system, `/tmp` is a tmpfs, and this leads to a fill up of my RAM, when building a lot of recipes.
Ran the tests: some issues, but unrelated to this PR.
If someone could confirm that this PR doesn't break anything, it'll be great.
> remove leftovers created by utils.get_recipe_abspath

- conda_build/utils.py
- tests/test-recipes/metadata/nested_prefix/bld.bat
- tests/test-recipes/metadata/nested_prefix/build.sh
- tests/test-recipes/metadata/nested_prefix/meta.yaml
This was especially showing up as failures to copy files when those files lived in paths mimicking the  prefix, like $PREFIX/shared/gdb/$SHARED/something
> fix path globbing and filtering replacing prefix not at start of path

- conda_build/index.py
- tests/test_index.py
This PR creates the equivalent of the current channel-level metadata.json.  The format is new, agreed to after discussion in https://github.com/conda/conda/issues/5340, and hence the new name.  In this case, there is a `channeldata_version` key, which we'll use if/when we need to change format in the future.
This PR also contains the foundation of a test framework for `conda index`.
The `conda index` command has used a caching strategy of keeping an `.index.json` file, so that rebuilding repodata is quicker on an incremental basis.  This PR adds *four* other caching files, that are in line with the typical conda package structure.  Those files are `.about.json`, `.paths.json`, and `.recipe.json`.  Actually, that's three.  The fourth is a directory `.icons/`, which holds extracted icon …
> create channel-level channeldata.json

- conda_build/api.py
- conda_build/build.py
- conda_build/utils.py
- tests/test_cli.py
also make skipped package output more informative (show used variables and their values)
>  fix duplicate env creation with no explicit outputs section

- conda_build/config.py
- conda_build/environ.py
- conda_build/jinja_context.py
- conda_build/metadata.py
- conda_build/render.py
- conda_build/skeletons/cpan.py
- conda_build/variants.py
- conda_build/windows.py
- tests/conftest.py
- tests/test-recipes/variants/18_subspace_selection/conda_build_config.yaml
- tests/test-recipes/variants/18_subspace_selection/meta.yaml
- tests/test-recipes/variants/20_subspace_selection_cli/conda_build_config.yaml
- tests/test-recipes/variants/20_subspace_selection_cli/meta.yaml
- tests/test_cli.py
- tests/test_metadata.py
- tests/test_variants.py
With zip_keys, it was very frustrating to have a central config file that
specified several zip_keys (python, vc, c_compiler, etc.), but to not allow
easy reduction of that build matrix by other config files.  One variable would
get trimmed to the shorter set of values, but then conda-build would fail with
errors about mismatching zip_keys dimensions.
This commit filters out mismatching entries, but does so in a way that allows
the dimensionality of the composite configuration to be maintained.  This also
allows things like
``conda build somerecipe --python=2.7`` to work when larger python build
matrices are defined in conda_build_config.yaml
> implement subspace selection

- conda_build/config.py
- conda_build/exceptions.py
- conda_build/index.py
- conda_build/metadata.py
- tests/test_variants.py
also adds **kw to a couple of functions that I'd consider private, but c-b-a uses.  That's OK.  We ignore c-b-a's arguments to kw.
> provide CONDA_* config attributes that c-b-a expects

- conda_build/cli/main_convert.py
- conda_build/convert.py
fixes #2471 
fixes #834
This PR adds the ``linux-ppc64le``, ``linux-armv6l``, ``linux-armv7l``, and ``linux-aarch64`` platforms to conda convert.
> Add arm and ppc architectures to convert

- conda_build/build.py
- conda_build/convert.py
When dumping to a json file if the dump contains only a dictionary or nested dictionary, the dictionary is written to the output file on a single line. This causes readability issues when the dictionary is long.
By adding the indent keyword to json.dump(), newlines are added after each key and the keys are spaced at the given indent level. I chose to indent 2 spaces as that is how ``conda`` indents its dumps.
Here is the relevant excerpt from the json module's documentation:
```
If indent is a non-negative integer or string, then JSON array elements and
object members will be pretty-printed with that indent level. An indent level of
0, negative, or "" will only insert newlines. None (the default) selects the most
compact representation. Using a positive integer indent indents that many …
```
> Format json files to include newlines and indentation

- conda_build/build.py
- conda_build/metadata.py
- conda_build/render.py
- conda_build/utils.py
- tests/test-recipes/variants/20_reprovision_source/bld.bat
- tests/test-recipes/variants/20_reprovision_source/build.sh
- tests/test-recipes/variants/20_reprovision_source/conda_build_config.yaml
- tests/test-recipes/variants/20_reprovision_source/install-output.bat
- tests/test-recipes/variants/20_reprovision_source/install-output.sh
- tests/test-recipes/variants/20_reprovision_source/meta.yaml
- tests/test-recipes/variants/20_reprovision_source/run_test.bat
- tests/test-recipes/variants/20_reprovision_source/run_test.sh
- tests/test_utils.py
- tests/test_variants.py
before this, error messages like:
```
conda_build.exceptions.RecipeError: Mismatching hashes in recipe. Exact pins in dependencies that contribute to the hash often cause this. Can you change one or more exact pins to version bound constraints?
Involved packages were:
Mismatching package: py-boost; consumer package: boost
```
showed up with non-top-level variants (such as a top-level shared lib with subpackages that consume it)
This PR also fixes some instances where the pins from the variant weren't being inserted early enough into outputs, which led to them not being differentiated well enough, which led to some of them (again, non-top-level ones) being ignored.
This PR needs tests before merging.
> fix implict pinning in outputs; fix incorrect matching of subpkgs

- conda_build/skeletons/pypi.py
- tests/test_pypi_skeleton.py
fixes #2351 
This PR adds pin compatible versioning functionality to the PyPI skeleton. For example, a version listed as ``package ~= 1.4.3`` will be converted to ``package >=1.4.3,<2``.
The error stems from https://github.com/conda/conda/blob/master/conda/cli/common.py#L106 so I'll be submitting a PR there as well. 
Tests look fine locally.
> Fix pin compatible dependencies by removing tilde from dependency

- conda_build/environ.py
**tl;dr**: This little PR fixes `GIT_DESCRIBE_TAG`, etc. in the case when `meta.yaml` specifies a custom `source: folder:`.
**Details:**
As described in the [docs](https://conda.io/docs/user-guide/tasks/build-packages/define-metadata.html#destination-path), the `source` section can optionally specify a nested `folder` within the `work` directory for the source to be cloned into.  For example:
```yaml
source:
git_url: http://github.com/foo/bar
folder: foo-sources/bar
```
...but the code that sets jinja variables such as `GIT_DESCRIBE_TAG` had assumed that the recipe did not specify a custom `folder`.  This PR fixes that.
PS -- I didn't augment the test suite, partly because this is a tiny change and partly because a number of tests were already failing in my machine.  (I think there may be …
> Support GIT_* vars even when a source folder was specified
